### ISSUE TITLE
Fetch Doesn't Respect MemoryPolicy

### ISSUE THREAD

**Issue by amlewis** [square/picasso#1001]
I'm trying to use fetch to forcibly update an item in the cache as follows:

`request.networkPolicy(NetworkPolicy.NO_CACHE).memoryPolicy(MemoryPolicy.NO_CACHE).fetch()`

I have only skimmed the top of the source code looking into this issue, but I imagine fetch() should call
`shouldReadFromMemoryCache(memoryPolicy)`
before retrieving a bitmap from the cache.

**Comment by dnkoutso** [comment]
Please provide a fix with a test.

**Comment by amlewis** [comment]
https://github.com/square/picasso/pull/1003
