### ISSUE TITLE
Memory caching in picasso 2.5.2

### ISSUE THREAD

**Issue by amodkanthe** [square/picasso#1002]
how to implement cache in picasso

In old version I use to do following

Cache cache = new LruCache( 1024*1024*1 );
Picasso.with( this ).load( file ).withCache( myCache ).into( imageView );

but withCache is no longer there what to do.

Also what is networkPolicy and memorypolicy

and what is difference between MemoryPolicy.NO_CACHE and MemoryPolicy.NO_STORE

**Comment by JakeWharton** [comment]
`withCache` has never existed.

The [`MemoryPolicy`][1] enum controls how interactions happens with the memory cache and [`NetworkPolicy`][2] enum controls how interactions happen with the disk cache. These allow you to do things like skip the memory cache when requesting an image or only request an image if it's available in the local disk cache (not the network).

Please direct questions to StackOverflow with the 'picasso' tag.

 [1]: http://square.github.io/picasso/javadoc/com/squareup/picasso/MemoryPolicy.html
 [2]: http://square.github.io/picasso/javadoc/com/squareup/picasso/NetworkPolicy.html
