### ISSUE TITLE
Not displaying place holder if image is in cache

### ISSUE THREAD

**Issue by stephanenicolas** [square/picasso#1005]
Would it be possible not to display the placeholder at all in the case images are in cache ?

It can look a bit strange but actually loading and displaying the placeholder takes time and the same zone is gonna be redrawn a few milliseconds after to display the image in cache. Would it be possible no to use the placeholder at all in such a case ?

Maybe our usage is a bit special as in our app we use only a few large images, this may not apply to a list with lots of small images.

**Comment by JakeWharton** [comment]
Picasso does not use the placeholder if the image is in the memory cache, it immediately sets the cached image. If a cached image is not in the memory cache, we set the placeholder (if given) or null out the image (to prevent recycling bugs).

If you are referring to the disk cache: Picasso knows nothing about the disk cache and cannot talk to it. Even if it did, that would require file I/O which cannot be done synchronously on the main thread.

**Comment by stephanenicolas** [comment]
Hi Jake,

thx for the answer. However, for the last sentence, I believe something is
strange as Picasso does access the disk cache on the main thread already.
Or am I wrong ?



2015-05-01 17:52 GMT+02:00 Jake Wharton <notifications@github.com>:

**Comment by dnkoutso** [comment]
No, disk cache is never accessed from the main thread. If it does its a big bug. There are ton of apps using StrictMode that would have crashed and it would have been reported to us.

**Comment by JakeWharton** [comment]
There is no disk cache. There is only an HTTP client which is only accessed on a background thread. Whether or not a disk cache exists inside of the HTTP client is completely transparent to Picasso.
