### ISSUE TITLE
How to get Image path from disk ? Why most  image downloading and caching library does not privide method getFilePath(url) ?

### ISSUE THREAD

**Issue by leelei** [square/picasso#1006]

**Comment by leelei** [comment]
when user click thumb image(have resized), it will show large Image, can pan and zoom gestures for displaying huge images, because image is too large, so i need getFilePath use SubsamplingScaleImageView

**Comment by artem-zinnatullin** [comment]
> Why most image downloading and caching library does not privide method getFilePath(url)?

Because Image Loading Library can delete cached images at any time. You can download and store image with [OkHttp](http://square.github.io/okhttp/) + [Okio](https://github.com/square/okio) or other libraries/APIs.

**Comment by JakeWharton** [comment]
Picasso has no interaction with the disk. We don't know where the image is stored. It might not even be on disk.
