### ISSUE TITLE
Unable to load streamed images 

### ISSUE THREAD

**Issue by gangji91** [square/picasso#1008]
Hi, 

I am trying to load the image from https://absoc.co.uk/assets/photos/160/poster.png using picasso. My code is as follows:
    picasso.load("https://absoc.co.uk/assets/photos/160/poster.png").into(imgPoster);

The logcat produces:
    05-05 00:23:33.911: D/skia(11102): --- SkImageDecoder::Factory returned null
    05-05 00:23:33.915: D/skia(11102): --- SkImageDecoder::Factory returned null
    05-05 00:23:33.927: D/skia(11102): --- SkImageDecoder::Factory returned null

I have tried loading images from other https sites, and it has worked fine.

Many thanks for your help.

**Comment by dnkoutso** [comment]
Most likely a bug in Android decode code. Please try another lib to see if ti works (then its a Picasso bug) and re-open the issue.

Otherwise, closing.
