### ISSUE TITLE
Implement resumeTag on ScrollView

### ISSUE THREAD

**Issue by doctorjr46** [square/picasso#1010]
hello all, thanks for this feature
 final Picasso picasso = Picasso.with(context);
            if (scrollState == SCROLL_STATE_IDLE || scrollState == SCROLL_STATE_TOUCH_SCROLL) {
                picasso.resumeTag(context);
            } else {
                picasso.pauseTag(context);
            }

how to implement that feature on ScrollView?

thanks before

**Comment by JakeWharton** [comment]
There is a sample for this:

* https://github.com/square/picasso/blob/10bac5ba59c7379eb4be4a2e7af074edc4bd9200/picasso-sample/src/main/java/com/example/picasso/SampleScrollListener.java
* https://github.com/square/picasso/blob/10bac5ba59c7379eb4be4a2e7af074edc4bd9200/picasso-sample/src/main/java/com/example/picasso/SampleGridViewActivity.java#L13
