### ISSUE TITLE
version 2.4.0, same pictures can't display properly

### ISSUE THREAD

**Issue by wdf5080309489** [square/picasso#1012]
com.squareup.picasso.Downloader$ResponseException: 504 Gateway Timeout
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:67)
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:49)
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-07 16:20:57.007  15366-15366/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-07 16:20:57.008  15366-15366/com.zivoo.life.app W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
05-07 16:20:57.008  15366-15366/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)

**Comment by wenxiang20130910** [comment]
I have a problem the same with you !

**Comment by JakeWharton** [comment]
This means that the image failed to load from the network 3 times and we finally looked for an expired version in the cache which was not found. This can be ignored, and I think we specifically don't even report it as an error in the latest version.
