### ISSUE TITLE
Picasso can not load some images with fit() and centerCrop()

### ISSUE THREAD

**Issue by start141** [square/picasso#1013]
Picasso can not load some images with fit() and centerCrop()!
if without fit() and centerCrop() picasso can load normal.

like this images:

https://cloud.githubusercontent.com/assets/6055764/7513033/ad06f6e6-f4e3-11e4-95bf-9daf5ac711d4.jpeg
https://cloud.githubusercontent.com/assets/6055764/7513035/af841ab6-f4e3-11e4-93e8-29048cc8b733.jpeg
https://cloud.githubusercontent.com/assets/6055764/7513037/b1bad946-f4e3-11e4-9b5c-a40f4e166dee.jpeg
https://cloud.githubusercontent.com/assets/6055764/7512762/ba133db0-f4e1-11e4-8b77-dad549b665f6.jpg
https://cloud.githubusercontent.com/assets/6055764/7512763/bc13ae24-f4e1-11e4-8891-8a22fba710b7.jpg

you must test with fit() and centerCrop() first time, because if load without fit() and centerCrop(), 
it will load success, next time to load with fit() and centerCrop() would also success.

ps: picasso can load this images normal from sdcard.

**Comment by start141** [comment]
I use Picasso 2.5.2

**Comment by dnkoutso** [comment]
Attach a global error listener and print the stacktrace. Use `picasso.setListener`

**Comment by dnkoutso** [comment]
Yet another dup of #907 
```
W/System.err( 1797): java.io.IOException: Cannot reset
W/System.err( 1797): 	at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err( 1797): 	at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err( 1797): 	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err( 1797): 	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err( 1797): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err( 1797): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err( 1797): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 1797): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 1797): 	at java.lang.Thread.run(Thread.java:818)
```
