### ISSUE TITLE
FileRequestHandler.getFileExifRotation is incomplete

### ISSUE THREAD

**Issue by trolik** [square/picasso#1014]
It handles only 3 cases (ORIENTATION_ROTATE_90/180/270) 

Can you please support all other cases?

----- some code from current project -----

case ExifInterface.ORIENTATION_FLIP_HORIZONTAL:
                    matrix.setScale(-1, 1);
                    break;
                /*case ExifInterface.ORIENTATION_ROTATE_180:
                    matrix.setRotate(180);
                    break;*/
                case ExifInterface.ORIENTATION_FLIP_VERTICAL:
                    matrix.setRotate(180);
                    matrix.postScale(-1, 1);
                    break;
                case ExifInterface.ORIENTATION_TRANSPOSE:
                    matrix.setRotate(90);
                    matrix.postScale(-1, 1);
                    break;
                /*case ExifInterface.ORIENTATION_ROTATE_90:
                    matrix.setRotate(90);
                    break;*/
                case ExifInterface.ORIENTATION_TRANSVERSE:
                    matrix.setRotate(-90);
                    matrix.postScale(-1, 1);
                    break;
                /*case ExifInterface.ORIENTATION_ROTATE_270:
                    matrix.setRotate(-90);
                    break;*/

**Comment by dnkoutso** [comment]
You could further expand this with a custom transformation or provide a PR that adds the remaining functionality.
