### ISSUE TITLE
#bug# When listview  scroll  picasso pause tag and then resume tag action is cancelled

### ISSUE THREAD

**Issue by cainli** [square/picasso#1016]
Piscasso.java

.......
  void enqueueAndSubmit(Action action) {
		Object target = action.getTarget();
		if (target != null && targetToAction.get(target)!= action) {
			// This will also check we are on the main thread.
			cancelExistingRequest(target);
			targetToAction.put(target, action);
		}
		submit(action);
 }

.......

When action is new object  " targetToAction.get(target)! = action"   is true ,

so I think  shoud use targetToAction.get(target).equals(action)(override action equals method )

**Comment by dnkoutso** [comment]
Your description is not clear. Please provide a PR depicting the bug and a test for it. This is too vague.
