### ISSUE TITLE
can't load with chinese character path

### ISSUE THREAD

**Issue by duduzai** [square/picasso#1017]
Any help.I use picasso load image,it's all fine like this path "/public/images/brand/a1487c29323fa9b920a79259b2fc5c07.png".But i can't get the image like this path "uploads/brand/万宝龙.png"

**Comment by dnkoutso** [comment]
Use:

```java
         Picasso = new Picasso.Builder(context).listener(new Listener() {
            @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
              exception.printStackTrace();
            }
          }).indicatorsEnabled(true).build();
```

And see the stacktrace. Provide a better URL for me that doesn't work and re-open.

**Comment by duduzai** [comment]
Hello @dnkoutso ,This is the whole url "http://www.gogoeu.cn/web/uploads/brand/佛兰克穆勒.png".And now the problem happen when i use in SAMSUNG GT-N7100(4.4.2),it can't show the path,but in my 5.0.0 device work fine.i don't why.And exception.printStackTrace() not going.thanks
