### ISSUE TITLE
Picasso not showing image,  java.io.IOException: Cannot reset

### ISSUE THREAD

**Issue by GuilhE** [square/picasso#1018]
http://stackoverflow.com/questions/30192650/picasso-not-showing-image

I'm having a problem loading images with Picasso (*'com.squareup.picasso:picasso:2.5.2'*) in Moto G (2nd gen 5.0.2).
Here's the code:
		

    Transformation transformation = new RoundedTransformationBuilder()
    		  .cornerRadiusDp(cornerRadiusDp)
    		  .oval(false)
    		  .build();
    		
    		Picasso.with(MAPetApplication.getContext())
    		  .load(uri)
    		  .centerCrop()
    		  .resize(targetWidth, targeHeight)
    		  .transform(transformation)
    		  .into(imageView, new Callback() {
                  @Override
                  public void onSuccess() {
    
                  }
    
                  @Override
                  public void onError() {
    
                  }
              });

While debugging I was able to notice that `void complete(BitmapHunter hunter)` method inside `Picasso.class` was returning a `null` result:

    void complete(BitmapHunter hunter) {
    ...
     if(shouldDeliver) {
                Uri uri = hunter.getData().uri;
                Exception exception = hunter.getException();
                Bitmap result = hunter.getResult();
                Picasso.LoadedFrom from = hunter.getLoadedFrom();
                if(single != null) {
                    this.deliverAction(result, from, single);
                }
    ...
    }

***exception = java.io.IOException: Cannot reset***

Delivering:  
result = null  
from = "DISK"  
single = com.square.picasso.ImageViewAction  
   

     private void deliverAction(Bitmap result, Picasso.LoadedFrom from, Action action) {}

Instead of delivering:  
result = android.graphic.Bitmap  
from = "DISK"  
single = com.square.picasso.ImageViewAction  

resulting in a `action.error();`

What could it be?  
Thanks.

ps: tested in Moto RAZRi 4.1.2, Nexus S 4.4.1, GT-I9505 4.4.2, Nexus 5 5.0.0/5.1.0, One Plus One 5.0.2, and it works fine.

**Comment by dnkoutso** [comment]
We are working on this for 2.5.3. Its a known issue. Dup #907

**Comment by AndroidSuperMan** [comment]
When would Picasso 2.5.3 be complete?  I am having the same issues.  Picasso 2.5.3 has been at 69% forever.....
