### ISSUE TITLE
Picasso Exif Handling is incomplete

### ISSUE THREAD

**Issue by JohnWowUs** [square/picasso#1020]
Picasso only handles the rotation and normal EXIF orientation settings correctly i.e.

ORIENTATION_NORMAL=1
ORIENTATION_ROTATE_180=3
ORIENTATION_ROTATE_270=8
ORIENTATION_ROTATE_90=6

It fails to handle 

ORIENTATION_FLIP_HORIZONTAL=2
ORIENTATION_FLIP_VERTICAL=4
ORIENTATION_TRANSPOSE=5
ORIENTATION_TRANSVERSE=7

Examples of all of these can be found at 

https://github.com/recurser/exif-orientation-examples

The fix is fairly straightforward but I can send in a pull request from a forked repository if preferred.

**Comment by dnkoutso** [comment]
Please do and include tests.
