### ISSUE TITLE
Image is not displayed in imageview

### ISSUE THREAD

**Issue by stoefln** [square/picasso#1022]
Some images do, but this one doesnt:

<pre>05-15 10:57:17.557  12120-12120/com.myapp.android D/Picasso﹕ Main        created      [R0] Request{https://apistage.myapp.com/images/gate.png}
05-15 10:57:17.567  12120-12339/com.myapp.android D/Picasso﹕ Dispatcher  enqueued     [R0]+13ms
05-15 10:57:17.577  12120-12344/com.myapp.android D/Picasso﹕ Hunter      executing    [R0]+17ms
05-15 10:57:18.447  12120-12339/com.myapp.android D/Picasso﹕ Dispatcher  retrying     [R0]+891ms
05-15 10:57:18.457  12120-12425/com.myapp.android D/Picasso﹕ Hunter      executing    [R0]+902ms
05-15 10:57:19.097  12120-12339/com.myapp.android D/Picasso﹕ Dispatcher  retrying     [R0]+1537ms
05-15 10:57:19.097  12120-12454/com.myapp.android D/Picasso﹕ Hunter      executing    [R0]+1538ms
05-15 10:57:19.107  12120-12339/com.myapp.android D/Picasso﹕ Dispatcher  batched      [R0]+1548ms for error
05-15 10:57:19.307  12120-12120/com.myapp.android D/Picasso﹕ Main        errored      [R0]+1749ms
05-15 10:57:19.307  12120-12339/com.myapp.android D/Picasso﹕ Dispatcher  delivered    [R0]+1749ms

</pre>

My code:

<pre>
    @Override
    public void onResume() {
        super.onResume();
        Picasso.with(getActivity()).setLoggingEnabled(true);
        Picasso.with(getActivity())
                .load(getAppDataSet().getLinkGateImage())
                .into(mImageView);
    }
</pre>

**Comment by dnkoutso** [comment]
Add an error listener to your picasso instance to see the stacktrace:

```
          singleton = new Builder(context).listener(new Listener() {
            @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
              exception.printStackTrace();
            }
          }).build();
```

For me it came up

```
W/System.err( 1689): java.net.UnknownHostException: Unable to resolve host "apistage.myapp.com": No address associated with hostname
W/System.err( 1689): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
W/System.err( 1689): 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
W/System.err( 1689): 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
W/System.err( 1689): 	at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
W/System.err( 1689): 	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:266)
W/System.err( 1689): 	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:240)
W/System.err( 1689): 	at com.squareup.okhttp.internal.http.RouteSelector.nextUnconnected(RouteSelector.java:156)
W/System.err( 1689): 	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:130)
```
but this could be a different error than yours.

**Comment by stoefln** [comment]
Sorry, replaced the URL. Found out the reason by myself meanwhile: The server certificate is not valid. Is there some well known workaround for accepting invalid certificates?

**Comment by dnkoutso** [comment]
Cool

**Comment by stoefln** [comment]
I don't think its cool. Picasso didnt tell me anything and it took me around 3 hours to find that out. I am not complaining, I am just pointing out what would be really cool:
Picasso telling me why it doesnt show the images and some documentation which covers how to display images from https servers with invalid certificate (quite common on staging-servers)

**Comment by dnkoutso** [comment]
Did you attach the listener as I mentioned above? That would have saved you the 3 hours. If it didnt print out the stack trace then re-open and thats a bug.

Remember to attach the listener and print the stacktrace on debug builds.

No need to be rude about what the library offers. Its open source and can be improved. I understand though the frustration of spending 3 hours for a problem.

**Comment by stoefln** [comment]
Thanks for pointing out the trick with the listener, did not know that!

**Comment by vishal901** [comment]
W/System.err( 1689): java.net.UnknownHostException: Unable to resolve host : No address associated with hostname

this is not issue for picasso lib.

actual issue are in image url like...

http:www.ancd.com/abc.png (server url not coming //   please check )

replace
http://www.ancd.com/abc.png

i solve this issue.
