### ISSUE TITLE
No feedback If Internet Permission Not Used

### ISSUE THREAD

**Issue by jlmalone** [square/picasso#1027]
This is a simple one but I just wasted time on it. 

I have a new project and forgot to add

```<uses-permission android:name="android.permission.INTERNET"/>```

It would have saved me time if there had at least been some sort of debug check for this. There was no indication and nothing available in the error callbacks to show why it was not working.

**Comment by JakeWharton** [comment]
Internet permission is only required for loading remote images. Picasso can be used on many local image sources without it. We actually used to have a check but it caused crashes on some devices. This comes up so infrequently that the feature isn't worth inclusion. If you attache a failure listener to the Picasso instance you would have seen the IO errors.
