### ISSUE TITLE
Q: How do I know if an image url is already cached?

### ISSUE THREAD

**Issue by GavinChengGitHub** [square/picasso#1029]
Basically I don't want to load the placeholder when an image is already cached. Thanks!

**Comment by dnkoutso** [comment]
`Target` provides a loadedFrom field in the callback. Use that. to determine if its coming from `MEMORY` or not. It will be invoked synchronously for you.

**Comment by dnkoutso** [comment]
You could also keep an instance of the `Cache` passed in Picasso then query the cache directly.

**Comment by JakeWharton** [comment]
The placeholder not loaded when the image is already cached.

**Comment by ericntd** [comment]
I'd like to collect the cache hit statistics
Since 90% of the time our app uses ImageView instead Target
> The placeholder not loaded when the image is already cached.
can we determine this programmatically? @JakeWharton @dnkoutso 🙏
