### ISSUE TITLE
Custom cache key

### ISSUE THREAD

**Issue by Robertoq7** [square/picasso#1030]
Hi,

My problem is that from the API I can get same images from the different url, but with same id:
{id:'ABC123', url:'http://myurl.com/image1'}
....
{id:'ABC123', url:'http://myurl.com/image2'}

But the Picasso will be download both images, that is why I would like to add a custom cache key value:

Picasso.from(context).load("http://myurl.com/image1").cacheKey("ABC123").into(imageView);
...
Picasso.from(context).load("http://myurl.com/image2").cacheKey("ABC123").into(imageView);

Is it possible? 

Thank you,
Robert

**Comment by meisterfuu** [comment]
.stableKey()

**Comment by Robertoq7** [comment]
It's working, thank you!
