### ISSUE TITLE
Missing callback events when using tags

### ISSUE THREAD

**Issue by oliverhausler** [square/picasso#1033]
Now, as we have tags to pause and resume loading (https://github.com/square/picasso/commit/15820945a0dd1f4ca7a76356fb7ad5ff82f8fe80, great improvement, thanks!), I miss additional callbacks when these events occur:

For example, I am using callbacks to set colors until the image is being loaded:

        Picasso.with(getContext()).load(url).resize(width, height).centerCrop()
                .placeholder(imagePreview.getDrawable()).error(R.drawable.testpattern)
                .tag(getContext()).into(imagePreview, new Callback() { 
            @Override public void onSuccess() {
                imagePreview.setBackgroundColor(getResources().getColor(R.color.videobackground));
            }
            @Override public void onError() {
                imagePreview.setBackgroundColor(getResources().getColor(R.color.videobackground));
            }
        });

Without tags, this was working fine. But now, the image view turns black while it is paused. Sure I could play with this and I might be able to find a solution, but I would suggest adding the following callbacks so we can control paused and resumed state as it happens:

```java
@Override public void onSuccess() {}
@Override public void onError() {}
@Override public void onPause() {} // new
@Override public void onResume() {} // new
```

**Comment by dnkoutso** [comment]
Marking for Picasso Next. This enhancement will cause an API change. We are currently getting ready for a small minor release (2.5.3). Should be in 2.6.

**Comment by oliverhausler** [comment]
If you wanted to implement it without having to change the API, you could also add a second signature of .tag() with the pause/resume callbacks as a second parameter:

    .tag(getContext(), new Callback() {})

**Comment by JakeWharton** [comment]
I don't see why tagging would effect anything here. It's meant to be a transparent operation to the load sites (and their callbacks). Why would the background tasks being paused cause you placeholder not to be displayed or go black?

**Comment by oliverhausler** [comment]
I haven't investigated into this any further yet. But I noticed it happens. Could be my logic as well. But I wanted to note there might be use cases where we want to change things while images are "on hold", so I believe the two additional events in the image lifecycle definitely make sense.

**Comment by JakeWharton** [comment]
I would be interested in code or a sample that reproduces the problem you are seeing. I am also very skeptical about the utility of these callbacks without a concrete use case which means we will almost always err on the side of not including them.

**Comment by oliverhausler** [comment]
I agree to keeping it simple.

Let me debug this and I'll get back to you with more info or sample code in case the error wasn't in my code.




-------- Original message --------
From: Jake Wharton
Date:2015/05/20 12:56 (GMT-08:00)
To: square/picasso
Cc: Oliver Hausler
Subject: Re: [picasso] Missing callback events when using tags (#1033)


I would be interested in code or a sample that reproduces the problem you are seeing. I am also very skeptical about the utility of these callbacks without a concrete use case which means we will almost always err on the side of not including them.

-

**Comment by oliverhausler** [comment]
My bad, sorry Jake, I still had the line in my code where I switched the background to black to hide #769, I just didn't see it until I set onPaused(). So no issue with black background while being paused.

**Comment by JakeWharton** [comment]
Unless there's an actual concrete use-case for callbacks around pause/resume events, I'm against their inclusion. If someone comes up with one, feel free to comment or create a new issue. Closing this guy though.

And glad you got your problem worked out!
