### ISSUE TITLE
Default LRU cache size?

### ISSUE THREAD

**Issue by agustinsivoplas** [square/picasso#1036]
Hi all, sorry for ask here but I could find a official answer about default cache size of Picasso.

I saw this post and says: Picasso uses 1/7th of the available heap for it's LRU, but is not official.

http://stackoverflow.com/questions/26663767/android-imge-picasso-square-cache-size

By default uses LRU cache?

If I want to change this size, I have to change in each instance o I could change one time in a global parameter?

 Picasso picasso = new Picasso.Builder(context).memoryCache( new LruCache(cacheSize)).build();

Thanks in advanced

All the best

Agustin

**Comment by JakeWharton** [comment]
> Picasso uses 1/7th

Yes.

> I have to change in each instance o I could change one time in a global parameter?

Create the custom `Picasso` instance and then call
```java
Picasso.setSingletonInstance(picasso);
```

Now all calls to `Picasso.with` will return you custom instance.
