### ISSUE TITLE
java.lang.NoClassDefFoundError: android.support.v7.appcompat.R$layout

### ISSUE THREAD

**Issue by vastril4o** [square/picasso#1039]
Android Studio 1.2

Adding picasso-2.5.2.jar to my project lead to this exception
removing the lib, and project is running fine again, I`have try to remove licenses file but whit no luck.

packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/MANIFEST.MF'
    }

**Comment by JakeWharton** [comment]
Picasso is not the cause of the error even if adding and removing it changes the behavior. Aapt generates that file from resources and Picasso is a jar with no resources so it cannot be the actual cause.

**Comment by vastril4o** [comment]
you are 100% right, because this is happen whit other libs, it seams to be a bug in appcompat-v21

**Comment by vastril4o** [comment]
OK finally fix it appcompat-v7:22... is buggy, i have downgrade my project to api 21 and everything is working OK now, finally can use this beautiful picasso api :)

**Comment by ramesh586** [comment]
hey @vastril4o i am still facing the same issue please provide solution
