### ISSUE TITLE
Prefetching bitmaps

### ISSUE THREAD

**Issue by tmatek** [square/picasso#1043]
I am trying to prefetch a few images in the ListView to improve user experience so that user doesn't have to wait for the image to appear while scrolling. I am using the following code in adapter's getView():

```java
for (int i = position + 1; i < this.getCount() && i < i + 3; i++) {
    Item tmp = this.getItem(i);
    Picasso.with(this.context).load(item.getMediaUrl()).resize(510, 510).fetch();
}
```

Later when displaying image I use the following:

```java
Picasso.with(this.getContext()).load(url).resize(510, 510).centerCrop().into(holder.imageView);
```

I set my memory cache size to 50 % for testing purposes. However when scrolling, the image is always loaded from disk cache (blue debug indicator) causing delay before displaying, even if it was preloaded into memory cache before (using ```fetch()```). Debug shows that memory cache is only 40 % full. What am I doing wrong?

**Comment by JakeWharton** [comment]
One has `centerCrop()` and the other does not. This affects the cache key and rendering of the image. Those effectively become two images as a result.
