### ISSUE TITLE
Picasso leaks context even though cancel is called

### ISSUE THREAD

**Issue by mblcdr** [square/picasso#1044]
I load my photo using:
```Java
Picasso.with(this).load(imageUrl)
                .tag(PhotoActivity.class)
                .resize(w, h)
                .into(photo, new Callback() {
                         @Override
                         public void onSuccess() {
                              //Some method calls here
                         }

                         @Override
                         public void onError() {}
                });
```
And I cancel this request in ```onStop()``` method using this line of code:
```Java
Picasso.with(this).cancelTag(PhotoActivity.class);
```

Yet I get this log from leak canary:

    * com.example.app.activity.PhotoActivity has leaked:
    * GC ROOT thread com.squareup.picasso.Utils$PicassoThread.<Java Local> (named 'Picasso-Idle')
    * references java.util.concurrent.PriorityBlockingQueue.queue
    * references array java.lang.Object[].[0]
    * references com.squareup.picasso.PicassoExecutorService$PicassoFutureTask.hunter
    * references com.squareup.picasso.BitmapHunter.action
    * references com.squareup.picasso.ImageViewAction.callback
    * references com.example.app.activity.PhotoActivity$1.this$0 (anonymous class implements com.squareup.picasso.Callback)
    * leaks com.example.app.activity.PhotoActivity instance
    * Reference Key: 0a9592c7-a4b5-4ff0-adf9-d3fa9984a71a
    * Device: Sony Sony C2105 C2105_1271-3303
    * Android Version: 4.2.2 API: 17
    * Durations: watch=5006ms, gc=181ms, heap dump=808ms, analysis=24507ms

**Comment by mblcdr** [comment]
I guess there was a problem with my setup, using Picasso multiple times. After I make sure every request has the same tag the leak was gone.
Sorry for the spam.

**Comment by mblcdr** [comment]
The leak happened again. All of my Picasso calls that have callbacks use PhotoActivity.class as tag, but the leak is happening again.

**Comment by dnkoutso** [comment]
Found one. And I am testing yours now. PR coming up.

**Comment by dnkoutso** [comment]
I cant seem to repro your exact case. I did find another potential leak with `fit()` though and I fixed that.

**Comment by dnkoutso** [comment]
```java    // Trigger the download of the URL asynchronously into the image view.
    Picasso.with(context) //
        .load(url) //
        .placeholder(R.drawable.placeholder) //
        .error(R.drawable.error) //
        .tag(SampleGridViewActivity.class) //
        .into(view, new Callback() {
          @Override public void onSuccess() {

          }

          @Override public void onError() {

          }
        });
```

My `onStop`

```java
    Picasso.with(context).cancelTag(SampleGridViewActivity.class);
```

**Comment by dnkoutso** [comment]
Ensure the `ImageViewAction#cancel` gets invoked.

**Comment by dnkoutso** [comment]
Provide potential sample please?

**Comment by mblcdr** [comment]
I will prepare a sample as soon as possible.

**Comment by dnkoutso** [comment]
Thanks it will greatly help.

**Comment by mblcdr** [comment]
There you go, a sample project:
https://github.com/mblcdr/PicassoLeak

**Comment by dnkoutso** [comment]
Thanks taking a look now.

**Comment by dnkoutso** [comment]
So do you have a similar case in your app? If you call `finish()` in `onCreate()` none of the lifecycle methods except `onDestroy()` will be invoked. 

So in your sample, you are not actually invoking canceling. I moved it to `onDestroy()` and it does cancel the request, however, I still see a leak warning...except the output cannot be parsed...

**Comment by dnkoutso** [comment]
Even without invoking picasso related code at all I still see a memory leak warning in the sample app....

**Comment by dnkoutso** [comment]
It seems like invoking `finish()` from `onCreate()` causes an unparseable leak warning in the sample app at least....Cancel works properly with `onDestroy()`

Can you update the sample app and try again? Something else is wrong here.

**Comment by mblcdr** [comment]
In my app, there's no calling finish() in onCreate(). But the suspicion concerning the onStop() method not being called is valid. I will try to move the cancel() call to onDestroy() method and see if the leak is gone in my app.

And about that unparseable leak warning, maybe we should file an issue at leak canary issue tracker, so they may take a look at it. The sample project I set up is pretty much the default template of a sample project.

I will update this with new info ASAP.

**Comment by dnkoutso** [comment]
OK. Having said that, removing `finish()` and pressing the back key instead creates no warnings/issues in terms of leaks at all (parseable or not parseable).

There could be something else in your app that might be specific. We can dig more.

**Comment by mblcdr** [comment]
In my app the leak warning appears when I press back button. Yet seems like I can't replicate the issue in the sample project.

I will evaluate the situation a bit more, and will update you with the results.
Thanks for the time.

**Comment by dnkoutso** [comment]
@mblcdr keep in mind a few things

1) The request is "temporarily" leaked when you use a `Callback`. It doesn't mean it will keep piling on you constantly as when the request is completed then everything will be valid for garbage collection. (Unless something else outside Picasso prevents it from getting gc'ed)

2) There is a clean up thread in Picasso that protects from forgetting to call `cancel` because most people dont do it. If a target is gc'ed picasso will invoke cancel for you cleaning up the strong `callback` reference

3) For your app. Start removing layers, picasso calls and see when the leak goes away/comes back.

**Comment by mblcdr** [comment]
Unfortunately moving the `cancel()` call to `onDestroy()` didn't do the trick. As I observed both `onStop()` and `onDestroy()` get called in my app, so no success there.

Through further more observation I found out that removing the Picasso call, gets rid of the leak.

I am sorry, but I am not allowed to provide the actual code, I will try to update the sample so that it can replicate the issue.

**Comment by mblcdr** [comment]
I updated the sample project, making the situation more similar to my app.
After a few attempts I got this:

```Java
    * com.samsaz.picassoleak.PhotoActivity has leaked:
    * GC ROOT thread com.squareup.picasso.Utils$PicassoThread.<Java Local> (named 'Picasso-Idle')
    * references java.util.concurrent.PriorityBlockingQueue.queue
    * references array java.lang.Object[].[0]
    * references com.squareup.picasso.PicassoExecutorService$PicassoFutureTask.hunter
    * references com.squareup.picasso.BitmapHunter.action
    * references com.squareup.picasso.ImageViewAction.callback
    * references com.samsaz.picassoleak.PhotoActivity$1.this$0 (anonymous class implements com.squareup.picasso.Callback)
    * leaks com.samsaz.picassoleak.PhotoActivity instance
    * Reference Key: 775ad772-1798-48a3-a2a1-2e09a34a08a1
    * Device: Sony Sony C2105 C2105_1271-3303
    * Android Version: 4.2.2 API: 17
    * Durations: watch=5010ms, gc=132ms, heap dump=447ms, analysis=15836ms
```

**Comment by mblcdr** [comment]
After more testing, it seems like that the reference will eventually be cleared by clean up thread. So this is a temp leak. I am going to close this as there is nothing more to investigate.
