### ISSUE TITLE
do i need to do some release work when the activity is destroyed?

### ISSUE THREAD

**Issue by macarthor** [square/picasso#1045]
hi all,

i'd like to state my hierarchy: a blank activty, a ViewPager fragment, some (5 - 30) ImageView nested fragments.

in every nested fragment onCreateView, i call "Picasso.with(getActivity()).load("network.image.url").into(imageView);"

when i press back to close the activity, leakcanary reports there's memory leak. so i use dump and MAT to analysis the leak:
## Class Name                                                                            | Shallow Heap | Retained Heap

com.squareup.picasso.LruCache @ 0x64e7e6a0                                            |           40 |    8,516,744
|- cache com.squareup.picasso.Picasso @ 0x64e88be0                                    |           64 |           528
|  '- singleton class com.squareup.picasso.Picasso @ 0x64e755c8 Unknown               |           16 |           584
|- cache com.squareup.picasso.Dispatcher @ 0x64e85de8                                 |           72 |           712
|  '- dispatcher com.squareup.picasso.Dispatcher$NetworkBroadcastReceiver @ 0x64e88478|           24 |            24
## '- Total: 2 entries                                                                   |              |              

any idea to fix this?

**Comment by macarthor** [comment]
Picasso.with(Context) method returns a singleton instance that is related to the context, often the activity. when the activity is going to be destroyed by GC, there's a static Picasso instance that holds the activity instance. this will cause the activity not being GCed? am i right? or i did not use Picasso correctly and missed something?

**Comment by macarthor** [comment]
i tried both Picasso.with(getActivity()), and Picasso.with(getActivity().getApplicationContext()), and both gave the same heap dump result...

**Comment by dnkoutso** [comment]
When you create a picasso instance we are explicitly invoking `context.getApplicationContext()` exactly for the reason to avoid holding on to an activity context.

Something else is going wrong here.

**Comment by dnkoutso** [comment]
```java
    /** Start building a new {@link Picasso} instance. */
    public Builder(Context context) {
      if (context == null) {
        throw new IllegalArgumentException("Context must not be null.");
      }
      this.context = context.getApplicationContext();
    }
```

**Comment by dnkoutso** [comment]
Can you provide a sample app? I cant seem to repro any of your case...

**Comment by martijndebruijn** [comment]
See http://stackoverflow.com/questions/32616944/custom-picasso-with-builder-leaks-networkbroadcastreceiver

**Comment by SagarPanwala** [comment]
Is this fixed or not? If fixed please provide solution.

**Comment by ShivaSmith** [comment]
Any updates on this?  I use Picasso to load several ImageViews inside a ViewPager... it looks like the associated containing Activity is not getting fully gc'ed.  Thanks.

**Comment by JakeWharton** [comment]
Without a full sample to reproduce the issue we have no way of verifying this is an actual problem let alone figuring out how to fix it.
