### ISSUE TITLE
Need a way to specify max dimensions for an image without scaling up

### ISSUE THREAD

**Issue by arashpayan** [square/picasso#105]
I display a list of contacts in my app, and the photos get displayed in 64x64 (dp) `ImageView`s. I'd like to switch to Picasso for the image loading, but when I call

``` java
Picasso.with(aContext)
.load(aUri)
.resize(sixtyFourDipsInPixels, sixtyFourDipsInPixels)
.placeholder(R.drawable.placeholder)
.into(myImageView);
```

contact images smaller than 64x64 dp become distorted when displayed. Click the image below to see the issue:

![screenshot_2013-06-28-01-44-14](https://f.cloud.github.com/assets/46624/721553/2e878ce0-dfe6-11e2-8972-3aaed94ca83d.png)

If I load the images using my old method which simply makes sure images larger than 64x64 dp are subsampled at load time, small images remain clearer. Click the image below to see the better quality contact photos:

![screenshot_2013-06-28-01-45-50](https://f.cloud.github.com/assets/46624/721566/67f24024-dfe6-11e2-9498-b509e0ca28c6.png)

I know the problem is being caused by the matrix multiplcation around line [538 in Picasso.java](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/Picasso.java#L538)

Unless there is something that I've overlooked in the API, I recommend adding a `maxSize(int, int)` method in the `RequestBuilder` that performs this simpler load of the image. I'd be happy to implement it and send a pull request if you'd be interested in such a contribution.

Thanks for sharing such a great project with the developer community!

**Comment by JakeWharton** [comment]
We shipped `onlyScaleDown()` at some point!
