### ISSUE TITLE
Can add an method to allow load empty path?

### ISSUE THREAD

**Issue by start141** [square/picasso#1051]
See the Picasso source, it can't load empty path.
if the path is empty, Picasso will throw IllegalArgumentException, the App will `FC`!

Can add an method to allow load empty path?

```
public RequestCreator load(String path) {
    if (path == null) {
      return new RequestCreator(this, null, 0);
    }
    if (path.trim().length() == 0) {
      throw new IllegalArgumentException("Path must not be empty.");
    }
    return load(Uri.parse(path));
  }
```

**Comment by JakeWharton** [comment]
An empty path is a data error. Either coerce it to null or fix your data.
