### ISSUE TITLE
No disk cache after using custom okHttpDownloader

### ISSUE THREAD

**Issue by yorkwang** [square/picasso#1053]
Disk cache doesn't work after using custom okHttpDownloader.                
                 @Override
	   	  public View getView(int position, View convertView, ViewGroup parent) {

                       .....
                       picasso.load(pageJson.coverUrlByIndex(position)).into(holder.coverImageView);
			return convertView;
		}

**Comment by JakeWharton** [comment]
There is not enough information here. You didn't show your custom downloaded, how you were creating it, or how you were creating your Picasso instance.

**Comment by yorkwang** [comment]
Here is my custom okdownloader code:
        OkHttpClient picassoClient = new OkHttpClient();
        picassoClient.interceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request newRequest = chain.request().newBuilder()
                            .addHeader("User-Agent", userAgent)
                            .addHeader("Referer", ref)
                            .build();
                return chain.proceed(newRequest);
            }
        });
        new OkHttpDownloader(picassoClient);

**Comment by JakeWharton** [comment]
Passing your own `OkHttpClient` instance will [not install a cache][1] per the docs.

 [1]: http://square.github.io/picasso/javadoc/com/squareup/picasso/OkHttpDownloader.html#OkHttpDownloader-com.squareup.okhttp.OkHttpClient-

**Comment by yorkwang** [comment]
Thank you!  I figured it out.
Is there any chance to change the headers dynamically after Picasso instance has been initialized? I have used UIL in my app, it can configure ever request with custom header. But UIL is slow, so I want to replace it with picasso.

**Comment by JakeWharton** [comment]
The easiest way is to use an [OkHttp interceptor][1] on which you can change the header at any time.

 [1]: https://github.com/square/okhttp/wiki/Interceptors
