### ISSUE TITLE
Images are not loading in android 5.0 using picasso library

### ISSUE THREAD

**Issue by williams-sgvu** [square/picasso#1054]
Hi I am working on demo application in which I am using picasso library v2.5.2. It is working fine on all android operating system version but not in lollipop 5.0.

Here is the link of image http://barcode.passbeemedia.com/pdf417/7/6/?text=EXPIRES07/15/2015

Here is my code for downloading bitmap and set on imageview.

```
Picasso.Builder builder = new Picasso.Builder(this);
builder.listener(new Picasso.Listener()
{
    @Override
    public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception)
    {
        exception.printStackTrace();
    }
});

builder.build().load("http://barcode.passbeemedia.com/pdf417/7/6/?text=EXPIRES07/15/2015").into(imageView, new com.squareup.picasso.Callback()
{
    @Override
    public void onSuccess()
    {
        Log.d("TAG", "onsuccess");
        progressBar.setVisibility(View.GONE);
        imageView.setVisibility(View.VISIBLE);
    }

    @Override
    public void onError()
    {
        Log.d("TAG", "onerror");
    }
});
```

layout.xml

```
<FrameLayout
android:layout_width="match_parent"
android:layout_height="wrap_content" >

    <ImageView
    android:id="@+id/qrCode"
    android:visibility="gone"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:scaleType="centerInside" />

    <ProgressBar
    android:id="@+id/ProgressBar"
    style="@android:style/Widget.ProgressBar.Small"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"/>
</FrameLayout>
```

Error logs : 

06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ java.io.IOException: Failed to decode stream.
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
06-03 14:56:23.112 12115-12115/nl.kevinvanmierlo.testproject W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

 Please help. Thanks in advance.

**Comment by JohnWowUs** [comment]
I had a look. There's something wrong with image. Even though it can be decoded libpng raises a number of warnings when you try and open it with GIMP for example. It seems as if the version of BitmapFactory in Lollipop and above (perhapseven  KitKat) is a lot less tolerant of non-standard encodings than previous versions.

**Comment by williams-sgvu** [comment]
What is wrong with the image. I am not sure. Please let me know what changes I need to do to get this worked correctly on Lollipop.

**Comment by oysteinmyrmo** [comment]
I have almost the exact same stack trace as @williams-sgvu, but for another image: http://www.miasmat.no/wp-content/uploads/2015/05/OvnsbaktKveite9.jpg

W/System.err(1467): java.io.IOException: Failed to decode stream.
W/System.err(1467):     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
W/System.err(1467):     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err(1467):     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err(1467):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
W/System.err(1467):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/System.err(1467):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/System.err(1467):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
W/System.err(1467):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
W/System.err(1467):     at java.lang.Thread.run(Thread.java:1096)
W/System.err(1467):     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

The strange thing is that image @williams-sgvu posted works fine for me, but the image(s) I need to use doesn't. I am targeting Android API 8 with support libraries. I think @JohnWowUs is correct in that there is something with the image that does it, but I cannot really figure out what it may be.

For more info, see here: http://stackoverflow.com/questions/30952980/picasso-fails-to-decode-some-images-skia-decode-returned-false

**Comment by JohnWowUs** [comment]
@williams-sgvu I'm not sure what's wrong with your image. When I export and save with GIMP the new image works. It's also a lot smaller at 1.75k compared with the original image which is 134k,

@oysteinmyrmo 
Your image works fine for me on a Nexus 7 running Lollipop. I am, however, running the fork that contains the markablestream fix (see PR #1035).

**Comment by oysteinmyrmo** [comment]
@JohnWowUs
It seems that it is the Android version that does something. Running API 10 and up it seems to work ok. Do you by chance know what causes this? As mentioned I am targeting API 8, but this is an arbitrary choice just to cover more devices, so it is not a big deal to switch to target API 10. If this is an unknown issue I can open a new issue with more details and testing.

**Comment by JakeWharton** [comment]
No action to take. If Android can't decode the image, then the library can't do anything to help.
