### ISSUE TITLE
Large lag when scrolling listview

### ISSUE THREAD

**Issue by lokewate** [square/picasso#1055]
There are many issues over the years that have complained about lags in scrolling and seems like there have been multiple solutions that have been worked on and suggested. However, I still find that there is no definitive solution for this issue. If this problem has been solved, can you please list the methods users are expected to use. If not, can you give an idea when this issue might get fixed.

My particular use case has a list view with 3 thumbnails (~40KB each) per row and about 100 rows. As soon as I scroll beyond 15-20 rows using a quick swipe, the UI almost comes to a standstill. Based on all the other issues that have been raised, this seems to be due to a large number of images getting loaded all at once. For me, creating the Picasso object with a single thread executor doesn't seem to help at all. The tag based system didn't work either. I was setting the tag using the image id during load time and then in my ViewHolder based view recycling, I cancelled the old image id when a new image was going to get assigned.

**Comment by dnkoutso** [comment]
Do you use the pause/resume with tags functionality?

**Comment by JakeWharton** [comment]
This is not an actionable issue description.

**Comment by lokewate** [comment]
@dnkoutso: Yes, I am using pause/resume.
@JakeWharton: Is there any documentation on best practices if the lag during scrolling issue has been solved?

**Comment by JakeWharton** [comment]
"Lag during scrolling" as an issue is extremely abstract. You need to figure out what is actually causing the frames to be dropped before we even identify that there is in fact an issue with Picasso. Then we can start figuring out what your code looks like, the patterns you are using, and whether both of those things are correct.

**Comment by lokewate** [comment]
Please let me know if this is not the best place to continue this discussion.

If I give the same image for Picasso to load, the lag is gone. Therefore I am assuming that this has nothing to do with any expensive layout calculations. Given this is happening when I am loading a list view with many rows and when I scroll fast (after reading all the other issues raised by others related to lags #507, #376 etc), I am assuming this is related to Picasso loading a lot of images at the same time. Having used pause/resume with tags and also tried single executor, without any luck, I was wondering if this generic issue of scrolling lag is something you expect at all. If not, maybe I can provide you with the data you need to debug why this is happening.

**Comment by JakeWharton** [comment]
One of the best ways for us to diagnose a problem is for you to modify the sample app (or create a new sample app) that we can install and instrument on our phones. This lets us be 100% sure we're seeing the same thing you are, and it works great. I realize it's a bit of work on your part, but the library is far too complex for us to make speculative suggestions and changes when we don't really understand what you are seeing.

**Comment by JakeWharton** [comment]
And the reason we're hesitant is that we've spent a lot of time making sure that the sample scrolls smoothly so it's usually ridiculously large bitmaps being resized by the system instead of Picasso or causing measure/layout passes when the bitmap is set which causes the problem.

**Comment by lokewate** [comment]
Thanks, will try to recreate the issue on the sample app and get back.

**Comment by Moudi2020** [comment]
am having same problem posted initially.. i have a pager viewer and a listview in each tab .. i have multiple rows and in each row there is an image... switching fragments from pager is laggy because of picasso.. 
Picasso.with(context).load(link).into(Image);

**Comment by vikas17** [comment]
I am having the same issue  . I am using recycler view of 6 rows and each row contain  horizantal recycler view and because of picasso its laggy while scrolling on some devices like moto x play
