### ISSUE TITLE
Reload and cache an image again, If resource has changed in server.

### ISSUE THREAD

**Issue by omid-nazifi** [square/picasso#1068]
Hi, I wanna cache images in memory by Picasso but I have a problem for reloading. Is it possible changing an image when its resource has changed in server. In other words, when network is off, used from cached image in memory and when network is On check the URL, If resource has changed then reload image. if not use a previous image.
Please let me know it is possible or not? And How can I do it?

Thanks

**Comment by JakeWharton** [comment]
You cannot both cache an image and memory and also check if it changed on the server. The `MemoryPolicy` and `NetworkPolicy` enums and associate APIs let you skip the cache and force reload an image from the network. A better approach is the just change URLs when the resource changes.

Please ask usage questions on StackOverflow with the 'picasso' tag.

**Comment by omid-nazifi** [comment]
@JakeWharton 
Thank you so much. I will ask it again in stackoverflow, and have a other question that related it
