### ISSUE TITLE
Reconfigured Bitmaps will cause inconsistent reporting in LruCache

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#1072]
On >= 19, Bitmaps can be reconfigured, and getByteCount will return the configured byte count.  The following code will crash the LruCache:

        Cache cache = new LruCache(context);
        String key = "key";
        Bitmap original = Bitmap.createBitmap(5, 5, Bitmap.Config.ALPHA_8);
        cache.set(key, original);
        original.reconfigure(1, 1, original.getConfig());
        cache.clear(); // kaboom

This can be easily fixed in Utils.getBitmapBytes by adding getAllocationByteCount for >= 19, but Maven doesn't support building against 19, so we are waiting for https://github.com/square/picasso/pull/876

I'll add a test and a fix when ready; this is just a reminder.

**Comment by NightlyNexus** [comment]
Milestone should be "Picasso Next," I think.

**Comment by JakeWharton** [comment]
This can be worked on now if you're interested.

**Comment by NightlyNexus** [comment]
Yep, I think it'll need Robolectric 3.1. I'll update that this weekend if no one beats me to it. :)

**Comment by hzsweers** [comment]
Just did it, but robolectric 3.1 still barfs :(

**Comment by JakeWharton** [comment]
Robolectric: Barfing all over your tests since 1.0.
