### ISSUE TITLE
why bitmap load crash only above Lollipop

### ISSUE THREAD

**Issue by loody** [square/picasso#1073]
it's only crash above Lollipop

A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10c in tid 11622 
06-26 13:04:55.627     954-1190/? E/NativeCrashListener﹕ Exception dealing with report
    android.system.ErrnoException: read failed: EAGAIN (Try again)
            at libcore.io.Posix.readBytes(Native Method)
            at libcore.io.Posix.read(Posix.java:147)
            at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
            at android.system.Os.read(Os.java:364)
            at com.android.server.am.NativeCrashListener.consumeNativeCrashData
(NativeCrashListener.java:240)
            at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

---

```
   Picasso.with(mContext).load(url).transform(mCircleTransform).resize(imgRadius * 2, imgRadius * 2).into(this);
```

target:

---

```
   @Override
   public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
        canvas.drawBitmap(bitmap, x, y, paint); 
   }

   @Override
   public void onBitmapFailed(Drawable errorDrawable) {

   }

   @Override
   public void onPrepareLoad(Drawable placeHolderDrawable) {

   }
```

**Comment by QDPeng** [comment]
me too,did you solve it?

**Comment by JakeWharton** [comment]
That stack trace doesn't indicate Picasso is to blame. If you can reproduce with the sample, we'd love to take a look.
