### ISSUE TITLE
How to unit test against Picasso?

### ISSUE THREAD

**Issue by mag** [square/picasso#1075]
Or: I didn't google hard enough to figure out how to unit test my code that uses Picasso.

If the latter is the case, maybe there should be something in the README?

Here's the code I'm trying to test: 

```
Picasso.with(getContext())
                .load(imageUrl)
                .resize(getWidth(), getHeight())
                .centerCrop()
                .transform(new CircularTransformation())
                .into(this);
```

From what I can tell, there's no easy way to test that I passed the right information to Picasso. And it appears that Picasso fires off a thread in Dispatcher and that the processing of requests happens there. I don't want to deal with threads, as I'm using JUnit/Robolectric.

Suggestions? At this point I feel I have to hide Picasso behind an interface, which is fine, but I wanted to check to see if I'm missing something.

**Comment by JakeWharton** [comment]
There is no need to unit test image loading.

Unit testing is for things like business logic and it should be going nowhere near the UI. Even if you do (ab)use things like Robolectric to run things like views or godforbid and entire activity (which I would highly discourage), doing some sort of assertion based on image loading will be massively challenging and likely devolve into scripting behavior against Picasso's API which will not only tie you to our API, but also require test changes anytime you change your interaction with Picasso.

Testing image loading is for an integration of functional test run through instrumentation which can be done in black box or grey box style. The nuance of our threading model, interacting with the HTTP client, and the ridiculous amount of code both in Java and native land that the platform uses for handling image decoding cannot be accurately mocked or stubbed or faked in any reasonable way.

**Comment by mag** [comment]
One other salient detail: My current situation makes it difficult to inject a mock Picasso object into the site of the above code. If that wasn't the case I could use Mockito and create a mock based on the class.  

I could use a global Service Factory type thing to give me a Picasso instance, and I could mock that out in tests, but because load() return a RequestCreator, I'd have to *also* make the RequestCreator global/static...which starts to really get weird.

And finally I tried to subclass Picasso but to no avail. There's a guy on the web who did that, but he had to put it in com.square.picasso, which I also found a bit gross.

**Comment by mag** [comment]
@JakeWharton Harrumph! I unit test all over the place. View logic, business logic, whatever logic. Because the code I'm trying to test is "near the UI", it does not mean I shouldn't be able to test it under isolated conditions.  

But I don't want this to become a debate about proper unit testing, or Robolectric, so let me reframe my problem. 

I'm not trying to test that images are *really* loading. Rather, I have some code that invokes Picasso, and it needs to invoke Picasso only at the certain times, and under certain conditions. And it needs to invoke Picasso correctly. It's irrelevant where this code lives or whether it's UI code...I want to get this code under test so I can refactor it, as it has some duplication and the logic of exactly when to invoke Picasso is subtle and interesting.  

Is that so wrong :angel:?

I'm pretty new to Picasso, so thanks for pointing out that it is a complex, multi-threaded library with lots of dependencies. I am sure it is well tested, so I am cool with mocking the whole thing out in my test. But that's not as easy as I'd like, and I was hoping to find out differently.

(I'd also be cool if Picasso was designed in such a way that its more dangerous / multi-threaded / platform-specific dependencies could be injected so I can use alternate implementations in test situations). 

In the meantime, I will wrap Picasso in a mockable object. Feel free to close this issue (unless somebody else out there feels there's something to this). The only reason I posted this as an issue was that I thought i might have missed something and that this issue would be a guidepost for future devs trying to solve this same problem.

**Comment by mag** [comment]
FWIW my problem was more about my code than Picasso. Once I was able to find a better means of injection, I was able to mock out Picasso and the associated RequestCreator, and verify they were both used appropriately.

That being said, there are a few changes I'd suggest to make it even easier to test against. One would be allowing client code to create a RequestCreator themselves, and hand it to Picasso; the other would be extracting the "Picasso" class into an interface so it's easier to create test doubles (rather than having to use mocks).

If I were to try a PR for any of this, would you guys consider it?

**Comment by JakeWharton** [comment]
That would be a backwards incompatible change and require a major version bump. I'm not opposed to making the change, but we're unlikely to release a major version without correcting some actual problems with the implementation of the library. Unfortunately, no one is really working on Picasso at this time beyond minor fixes that come in.

**Comment by mag** [comment]
Cool, thanks. If I get a chance I'll put in a PR for the website to make a note of how to test against the library.
