### ISSUE TITLE
picasso 2.5.2 unable display Lance blur image from some file

### ISSUE THREAD

**Issue by Miroslav10** [square/picasso#1076]
When i show grid images from device, Image  Lance blur image don't showing.
 
File file = new File(imagePath);
        if (file.exists()) {
            porgress.setVisibility(View.VISIBLE);
            Picasso picasso =new Picasso.Builder(context).listener(new Picasso.Listener() {
                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                    LOGE("picasso_test", exception.toString());
                    exception.printStackTrace();
                    ;
                }
            }).build();
            picasso.load(file)
                    .fit()
                    .centerCrop()
                    .into(imageView);
        } else imageView.setImageDrawable(null);

logs:
07-06 18:44:40.732  15847-15847/com.inkly.android E/picasso_test﹕ java.io.IOException: Cannot reset
07-06 18:44:40.732  15847-15847/com.inkly.android W/System.err﹕ java.io.IOException: Cannot reset
07-06 18:44:40.732  15847-15847/com.inkly.android W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
07-06 18:44:40.732  15847-15847/com.inkly.android W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
07-06 18:44:40.732  15847-15847/com.inkly.android W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
07-06 18:44:40.732  15847-15847/com.inkly.android W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
07-06 18:44:40.732  15847-15847/com.inkly.android W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-06 18:44:40.733  15847-15847/com.inkly.android W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-06 18:44:40.733  15847-15847/com.inkly.android W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-06 18:44:40.733  15847-15847/com.inkly.android W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-06 18:44:40.733  15847-15847/com.inkly.android W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
07-06 18:44:40.733  15847-15847/com.inkly.android W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by JakeWharton** [comment]
This issue is known, and there's already a few other issues tracking it. #364
