### ISSUE TITLE
Keep-Alive connection

### ISSUE THREAD

**Issue by khafan** [square/picasso#1079]
Does Picasso support the HTTP Keep-Alive by default? If not how can I enable this option? 
(Our app is mainly based on images and 0I've read that it has a huge impact on performance)
example link: https://www.nginx.com/blog/http-keepalives-and-web-performance/

**Comment by JakeWharton** [comment]
Picasso is not an HTTP client but rather uses either HttpURLConnection from
Java or OkHttp if it's available for downloading images. The HTTP client is
responsible for implementing and supporting keep alive. And both of these
two do support it.
