### ISSUE TITLE
resize() not correctly applied to error image?

### ISSUE THREAD

**Issue by oliverhausler** [square/picasso#1086]
In Picasso 2.5.2, I have the following code:

                final int height = videoPreview.getHeight();
                final int width = (int) (videoPreview.getHeight() * 1.8); // TODO we may want to set width to 0 so Picasso auto-scale, but this doesn't work in Picasso 2.5.2 https://github.com/square/picasso/issues/994

                Picasso.with(getContext())
                        .load(url).config(Constants.IMAGE_QUALITY_HIGH).resize(width, height).centerCrop().noFade()
                        .error(R.drawable.testpattern)
                        .into(videoPreview);

My ImageView has a fixed height, and width is set to wrap content.

Not sure if this is a bug in Picasso, but when I run above code my images are correctly scaled, except when loading a local error image: In this case the image height is correctly scaled, but the width adheres to the original error image's width, not the relative height used in Picasso, e.g. the one set in resize(). In other words: height of the error image is correctly set, but width is not.

I understand that wrap content means the image view is allowed to scale, but shouldn't Picasso adhere to the same scaling rules for error images as it does for correctly loaded images?

**Comment by JakeWharton** [comment]
Placeholder and error images are never transformed, they must be sized for the target view or use the target's built-in scaling mechanisms (like ImageView's scaleType) for size adjustments. For placeholders we obviously can't transform them, but we apply the same logic to error images. Transforming them might cause additional problems (decoding, OOM, etc.) which then put us in a place where we can't do anything.
