### ISSUE TITLE
Support to load into TextView CompoundDrawable

### ISSUE THREAD

**Issue by JSafaiyeh** [square/picasso#1091]

**Comment by JakeWharton** [comment]
This has been requested before, and we are unlikely to add it for a few reasons:
 * It requires at least four new APIs for determining the target of load.
 * Compound drawables have no intrinsic size so `fit()` can't work.
 * There's potential for ambiguity in behavior: when the same TextView is seen twice but different compound drawable locations are requested is that simply two images on one view or a view recycling and the business logic choosing to change the icon location.

This can already be accomplished in a straightforward way using a `Target` instance for the view which passes the `Bitmap` to the appropriate position in a call to `setCompoundDrawables`.

**Comment by prashand** [comment]
There's a solution for this [here](https://stackoverflow.com/a/53131079/1800515)
