### ISSUE TITLE
Picasso not loading images in android v5.1.1

### ISSUE THREAD

**Issue by thaKombo** [square/picasso#1094]
I recently noticed that Picasso failed to load images on devices that run android version 5.1.1. On testing the same app on version 5.0 and earlier, Picasso works fine. Is there a bug or something that changed in this new android version that prevents the library from loading images?

**Comment by JakeWharton** [comment]
There is nothing actionable in this issue as its written. If you have a test app we can run to demonstrate the problem, or a stack trace of the failure and example images URLs that exhibit the problem then we can look at it, but we aren't able to guess as to what's happening here.

I will say that we have Picasso on many tens of thousands of devices with Android 5.1 and are not seeing any problems.
