### ISSUE TITLE
Failed to load a local image, but can load same image from network.

### ISSUE THREAD

**Issue by wbo4958** [square/picasso#1095]
Hello dev,

I have a local pic in the internal storage, but picasso can't load it.
I put the same pic in the server, and then picasso can load it successful.

Could I get your help?

![2](https://cloud.githubusercontent.com/assets/1320706/8980733/74d14aa8-36e5-11e5-9b70-5d20d3e4f1ec.png)

**Comment by RenatoKiss** [comment]
I noticed the same issue. If I am right, there is a problem with into(ImageView, Callback) method when it tries to get the width and the height of the target. Both of them get 0 value, so the next if statement (which decides to load placeholder image or not) returns true.

**Comment by JakeWharton** [comment]
With what exception does it fail to load?

**Comment by SureshCS-50** [comment]
Just by passing your resourceId, This will work..

    Picasso.with(context)
                                .load(R.drawable.ic_file)
                                .into(img);
