### ISSUE TITLE
OException: Failed to decode stream

### ISSUE THREAD

**Issue by HellAvalor** [square/picasso#1096]
What could it be?

Not loading
![Not loading](http://jadmin.jeunesseglobaldev.com/imgdb/videos/SECRET-OF-JEUNESSE.jpg)
Loading normal
![Loading normal](https://jadmin.jeunesseglobal.com/imgdb/videos/SERUM_SAMPLING.jpg)

Both load normal with lazyLoader and other images from htt/https loading normal

Error Trace
```
 java.io.IOException: Failed to decode stream.
at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```
Picasso: 2.5.2
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp:2.2.0'

compileSdkVersion 22
targetSdkVersion 20

Builder config
```
picasso = new Picasso.Builder(application).listener(new Picasso.Listener() {
                    @Override
                    public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                        exception.printStackTrace();
                    }
                }).build();
```

**Comment by adrian-linca** [comment]
The image that is not loading is jpeg CMYK format, which is not supported on android 4.2.2 or lower.

**Comment by JakeWharton** [comment]
@adrian-linca Interesting! I wasn't aware of this.

To the larger error, this is thrown when Android's `BitmapFactory` returns null which means that Android was unable to decode the image into a `Bitmap`. There's not a whole lot Picasso can do in this situation aside from display the error image. In this case it looks like part of the image format was unsupported on particular versions of Android.

**Comment by adrian-linca** [comment]
@JakeWharton I got to this bug while searching for solution to my own issue.
The image below is not loaded by picasso. The same issue with stream decoding as for isWebPFile in BitmapHunter, but this case is not covered by picasso (opened an issue #1284).
http://static.cinemagia.ro/img/resize/db/movie/01/76/03/medium-464288l-120x170-b-b11b0234.bmp

**Comment by AxiomAim** [comment]
I experienced this exact same error using and Imgut.com link. This could be helpful: when using "Image Link" http://imgur.com/BlXRuOf it will create this exact error. You should use the "Direct Link" http://i.imgur.com/BlXRuOf.png provided. This solved the problem. Perhaps your situation is similar.
