### ISSUE TITLE
Picasso doesnt load from disk if downloader is defined

### ISSUE THREAD

**Issue by GPack1** [square/picasso#1097]
I defined a downloader for my Picasso instance:

    OkHttpClient myOkHttpClient = new OkHttpClient();
    myPicassoInstance = new Picasso.Builder(context).downloader(new OkHttpDownloader(myOkHttpClient)).build();
    Picasso.setSingletonInstance(myPicassoInstance);

fetch() - or into() - loads images from network, writes in cache, then at next request loads from memory only until process dies: when process dies and is restarted, fetch() restarts to load from network ignoring the cache entries.
I tried without downloader and now fetch() loads right from disk.

    myPicassoInstance = new Picasso.Builder(context).build();
    Picasso.setSingletonInstance(myPicassoInstance);

my question's detail on stackoverflow: 
http://stackoverflow.com/questions/31709763/picasso-fetch-and-get-with-okhttpdownloader

**Comment by meisterfuu** [comment]
Picasso leaves the disc(!) caching up to okhttp and you never called "setCache" on your OkHttpClient. Default implementation does that.

**Comment by GPack1** [comment]
I didnt know. Can I use this as default implementation does?
    myOkHttpClient.setCache(new com.squareup.okhttp.Cache(cacheDir, maxSize));

**Comment by ChristianLJ** [comment]
I have the same problem.
What was your solution?

**Comment by GPack1** [comment]
I solved adding setCache as above: `myOkHttpClient.setCache(new com.squareup.okhttp.Cache(cacheDir, maxSize));`
