### ISSUE TITLE
How to properly implement disk cache

### ISSUE THREAD

**Issue by leapfrog-santosh** [square/picasso#1098]
I am using `Picasso 2.5.2` in following manner
```java
public class PicassoLoader {

    private static Picasso picasso;
    private static final long DISK_CACHE_SIZE = 120000000;

    private static Picasso getPicasso() {
        if (picasso == null)
            picasso = new Picasso.Builder(MainApplication.getContext())
                    .downloader(new OkHttpDownloader(getCacheDir(), DISK_CACHE_SIZE)).indicatorsEnabled(true).build();
        return picasso;
    }

    private static File getCacheDir() {
        File file = MainApplication.getContext().getExternalFilesDir(null);
        return new File(file, "picasso/cache");
    }

    public static RequestCreator load(String url) {
        return getPicasso().load(url);
    }
    
}
```
And my `Gradle` build script
```java
  //and my Gradle Script (BTW I am also using Retrofit)
  // square library
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
    compile 'com.squareup.okio:okio:1.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
```
   I have to show list of images. All of the images comes when there is internet access. But, when there is no internet access, only some of the images are shown. Meaning when the images are all downloaded, the next time when there is no internet access, shouldn't it load from disk? Further, there are files present on `/mnt/sdcard/Android/packagname/files/picasso/cache`, which indicates that the disk cache is working . Or is there a better way to implement `disk cache` on `Picasso`.
Thanks

**Comment by JakeWharton** [comment]
You have done this correctly. What is likely happening, is that when you are connected to the internet OkHttp has to do a conditional cache check with the server to see if the local images are up-to-date. When disconnected it cannot do that check so it has to assume that they're up-to-date. The behavior of disk caching is controlled entirely by the server and the cache headers it sets. Picasso knows nor controls anything about the behavior.

Also use version 2.4.0 for the OkHttp dependency and delete the Okio dependency (it comes transitively) and delete the 'okhttp-urlconnection' dependency (it's not needed anymore).
