### ISSUE TITLE
Not working with OkHttp

### ISSUE THREAD

**Issue by MyHeartsECO** [square/picasso#1099]
So if I don't use OkHttp there is no problem. Problem is, when I add OkHttp to my Gradle libs, image doesn't load.

There is my Picasso code:

``` java
Picasso.with(((NotHeaderViewHolder) holder).sahip.getContext())
                    .load(current.imageLink)
                    .placeholder(R.drawable.arrow_right)
                    .error(R.drawable.error_notlar_avatar)
                    .transform(new CircleTransform())
                    .into(((NotHeaderViewHolder) holder).sahip);

//And there is my dependencies

compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp:okhttp:2.4.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'
compile 'com.squareup.okio:okio:1.4.0'

//I've even used
new Picasso.Builder(context).downloader(new OkHttpDownloader(picassoClient)).build();
//for OkHttp builds, that didn't work either. Images always load on error drawable.

//Thanks for any help.
```

**Comment by JakeWharton** [comment]
You can remove the dependency on 'okhttp-urlconnection' completely and you should not be explicitly depending on 'okio', it will automatically come transitively.

Without more information as to what the exception is, what the url is, etc. there's no way we can know what's happening here.

**Comment by MyHeartsECO** [comment]
Okay i've removed 'okio' and 'okhttp-urlconnection' from dependency, problem is still there. I can't post image link here, so I mailed the link to your gmail.

About the exception, I've been trying to catch it but it's not on popping up on any logs. I've been using this to catch it.

```java
 Picasso picasso = new Picasso.Builder(context)
                    .downloader(new OkHttpDownloader(new OkHttpClient()))
                    .listener(new Picasso.Listener() {
                        @Override
                        public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                            Log.i(TAG, "Picasso exception= " + exception.toString());
                            exception.printStackTrace(); //or this one

                        }
                    })
                    .build();

// all i have as exception which is not coming from these logs are:

I/dalvikvm﹕ Could not find method java.nio.file.Files.newOutputStream, referenced from method okio.Okio.sink

 W/dalvikvm﹕ VFY: unable to resolve static method 21878: Ljava/nio/file/Files;.newInputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/InputStream;

```

**Comment by MyHeartsECO** [comment]
Okay so I've just tested code on API 21 and it is working but it's not working(image isn't loaded) on KitKat. Things are getting weird. 

If anybody is interested, I've tested for picasso 2.4.0 and 2.5.2, results are the same.

**Comment by MyHeartsECO** [comment]
I think that image url has got problems. I've tried with different image url and it worked magically. Very interesting.

**Comment by JakeWharton** [comment]
Those log messages are warnings, not errors, and neither Picasso nor OkHttp use those code paths.  It sounds like you determined the image was the problem.
