### ISSUE TITLE
Too may open files error when loading 50+ images

### ISSUE THREAD

**Issue by timkoers** [square/picasso#1100]
Sorry for creating a new ticket that is exactly the same as the previous.
Jake told me to create a single Picasso instance and use it everywhere. The problem wasn't solved with this. It still shows me the that Too many files are open, with errorno=24

This only happens when flinging the listview. I am pausing and resuming the Tag at the OnScrollListener. Or should I cancel the tag?

My small logcat:

E/NativeCrypto﹕ AppData::create pipe(2) failed: Too many open files
art/runtime/indirect_reference_table.cc:77] Check failed: table_mem_map_.get() != nullptr ashmem_create_region failed for 'indirect ref table': Too many open files

I'm hoping that we get to a solution this time, since I'm out of knowhow about solving this issue.

Thanks!
Tim

**Comment by JakeWharton** [comment]
Show us as much code as possible or create a sample project which demonstrates the problem. Otherwise there's no action we can take here.

**Comment by timkoers** [comment]
Here is the code i use (part of the total code)
http://pastebin.com/W2A8u7Ex
What might be the issue, is that there are 2 ListViews loading side by side, due to the Tabs (Android loads the tab next to the current tab, and that is also a tab with heavy image loading)

**Comment by JakeWharton** [comment]
Line 34, line 64, line 68, and line 84 are creating new Picasso instances. Call `.build()` _once_ and re-use the same instance everywhere. You can also call `Picasso.setSingletonInstance()` with that instance which will make `Picasso.with()` return your custom instance so that you don't have to pass it around manually.

**Comment by polenoso** [comment]
Thanks JakeWharton! that solved my issue. The singleton instance of Picasson is really the key. thanks.

**Comment by esses77** [comment]
I have to say thanks JakeWharton too. "Call .build() once and re-use the same instance everywhere." suggestion worked well :)

**Comment by s1mar** [comment]
@JakeWharton What is or are the downsides of creating a new instance every time ?, is this a bad practice ?. I know you are a busy man, but I'd like to know this for knowledge purposes, so whenever you've the time, I'd appreciate if you can shed some light on this.

**Comment by JakeWharton** [comment]
It creates about 5 threads for each request which don't go away until they
time out after a minute. You'll very quickly exhaust available memory or
file handles or both.

**Comment by s1mar** [comment]
@JakeWharton  Thank you sensei !
