### ISSUE TITLE
Cache does not work properly

### ISSUE THREAD

**Issue by AlexeyTvorogov** [square/picasso#1101]
Problem 1:
I try to load image without Network Connection into ImageView by this code:

 Picasso.with(this)
                .load(avatarUrl)
                .placeholder(R.drawable.gray_image)
                .memoryPolicy(MemoryPolicy.NO_CACHE)
                .error(R.drawable.gray_image)
                .fit()
                .centerInside()
                .into(avatarImageView);

I expect, then image will not be  loaded without Network. But Picasso load image without problems.
I think, that MemoryPolicy.NO_CACHE disable image loading  from disk or memory. Is it true? Or how can I prevent loading images without Network connection(But not disable saving).

Problem 2:
I try to load image with Network connection. I execute next actions: 
1.loading image with Picasso into ImageView
2.Update image on server
3. Call Picasso.with(this).invalidate(avatarUrl);
4. Reload image into ImageView
I expect, I'll get new image from server, but sometimes I get oldImage. Seems, like image still in cache. How can I clear image from memory and disk cache?
Best regards, Alexey.

**Comment by JakeWharton** [comment]
> Or how can I prevent loading images without Network connection(But not disable saving).

You can do this by disabling the disk cache or using `NetworkPolicy.NO_CACHE`, though I cannot fathom why you would want to do such a thing as this is extremely wasteful. You could just check if the network was connected before loading an image which would still allow caching to work in your favor.

> How can I clear image from memory and disk cache?

Same as above. Either fix your server to send proper headers, use different URLs, or disable the use of the disk cache. There's no way for the client to know that the remove image has changed.

**Comment by Fyb3roptik** [comment]
This is why we would have to do it:

https://github.com/hdodenhof/CircleImageView/issues/282
