### ISSUE TITLE
Get full image from url

### ISSUE THREAD

**Issue by martipello** [square/picasso#1107]
Hi I know this isn't the right place for this but I've checked everywhere and cannot find a definite answer how do I get a full image from a URL using your library, I've tried many things the images are below the 2000x2000 but only just, closest I get Picasso downloads half the size at something like 1080 x 910 any suggestions? And again I'm sorry to ask this here but I've tried everywhere else

**Comment by JakeWharton** [comment]
> 've tried many things the images are below the 2000x2000 but only just, closest I get Picasso downloads half the size at something like 1080 x 910 any suggestions? And again I'm sorry to ask this here but I've tried everywhere else

Without more information it's impossilble to know how you are using the library. Picasso will downscale automaticalyl when using APIs like `fit()`. It will use the original unless otherwise instructed.
