### ISSUE TITLE
Images do not load on first start.

### ISSUE THREAD

**Issue by TheAndroidMaster** [square/picasso#1108]
I am trying to make my app create views from a string-array of urls. When I had the target set as the imageView, it loaded fine. But if I create a custom target in order to also get the average color of the image, the images don't load (the views load fine) Loading them again causes some of the images to display, though. Here is my code:
 
        isOdd=true;

        while(count<name.length){
            final CardView cardView = new CardView(Flat.this);
            String mName = name[count];
            mName = mName.replace("*", "");
            cardView.setClickable(true);
            cardView.setUseCompatPadding(true);
            cardView.setId(count);
            cardView.setLayoutParams(new CardView.LayoutParams(CardView.LayoutParams.MATCH_PARENT, CardView.LayoutParams.WRAP_CONTENT, 1));
            cardView.setForeground(getSelectedItemDrawable());
            LinearLayout vertical = new LinearLayout(Flat.this);
            vertical.setOrientation(LinearLayout.VERTICAL);
            final ImageView image = new ImageView(Flat.this);
            image.setBackgroundColor(getResources().getColor(R.color.oranged));
            image.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
            LinearLayout horizontal = new LinearLayout(Flat.this);
            horizontal.setOrientation(LinearLayout.HORIZONTAL);
            horizontal.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
            horizontal.setId(count);
            final TextView title = new TextView(Flat.this);
            title.setBackgroundColor(getResources().getColor(R.color.orange));
            title.setTextColor(getResources().getColor(R.color.white));
            title.setPadding(50, 40, 50, 40);
            title.setText(mName);
            Picasso.with(this)
                    .load(url[count])
                    .resize(100, 100)
                    .centerInside()
                    .into(new Target() {
                        @Override
                        public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                            image.setBackgroundColor(getDominantColor(bitmap));
                            title.setBackgroundColor(getDominantColor(bitmap));
                            image.setImageBitmap(bitmap);
                        }

                        @Override
                        public void onBitmapFailed(Drawable errorDrawable) {

                        }

                        @Override
                        public void onPrepareLoad(Drawable placeHolderDrawable) {

                        }
                    });
            cardView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(Flat.this, WallpaperView.class);
                    intent.putExtra("num", v.getId());
                    intent.putExtra("array", R.array.name_james);
                    intent.putExtra("arrays", R.array.url_james);
                    intent.putExtra("up", "Flat");
                    Flat.this.startActivity(intent);
                }
            });
            if(isOdd){
                root.addView(cardView);
                cardView.addView(vertical);
                vertical.addView(image);
                vertical.addView(title);
                isOdd=false;
            }else{
                rootView.addView(cardView);
                cardView.addView(vertical);
                vertical.addView(image);
                vertical.addView(title);
                isOdd=true;
            }
            count=count+1;
        }

    public static int getDominantColor(Bitmap bitmap) {
        if (null == bitmap) return Color.TRANSPARENT;

        int redBucket = 0;
        int greenBucket = 0;
        int blueBucket = 0;
        int alphaBucket = 0;

        boolean hasAlpha = bitmap.hasAlpha();
        int pixelCount = bitmap.getWidth() * bitmap.getHeight();
        int[] pixels = new int[pixelCount];
        bitmap.getPixels(pixels, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());

        for (int y = 0, h = bitmap.getHeight(); y < h; y++) {
            for (int x = 0, w = bitmap.getWidth(); x < w; x++) {
                int color = pixels[x + y * w]; // x + y * width
                redBucket += (color >> 16) & 0xFF; // Color.red
                greenBucket += (color >> 8) & 0xFF; // Color.green
                blueBucket += (color & 0xFF); // Color.blue
                if (hasAlpha) alphaBucket += (color >>> 24); // Color.alpha
            }
        }

        return Color.argb(
                (hasAlpha) ? (alphaBucket / pixelCount) : 255,
                redBucket / pixelCount,
                greenBucket / pixelCount,
                blueBucket / pixelCount);
    }

**Comment by TheAndroidMaster** [comment]
I have come up with a theory as to why it doesn't work properly: I haven't looked through Picasso's code, but can it access a final ImageView? I think it can only change the image of a final ImageView if it has the image readily available. In this occasion though, I need it to be final or I can't access it from the Target... Help please?

**Comment by jaydeep17** [comment]
Your custom Target might be getting garbage collected. Try holding a strong reference to it.

**Comment by TheAndroidMaster** [comment]
@jaydeep17 What do you mean by a strong reference? Sorry, I am still a beginner...

**Comment by TheAndroidMaster** [comment]
@jaydeep17 I looked it up, that fixes the issue (maybe my previous theory was wrong), but I cannot do that in this situation - I still need a way to access the imageview. I will keep trying other ways to do it.

**Comment by JakeWharton** [comment]
Code that contains:
```java
.into(new Target() {
```
is **always** wrong because Picasso stores a weak reference to the target. This means that nothing is keeping a strong reference and it will be garbage collected.

An easy way around this is to call `setTag` on some view with the `Target` instance to ensure a string reference is kept.

**Comment by TheAndroidMaster** [comment]
@JakeWharton Thanks for your help. I have found a somewhat easier (for me, at least) to understand way to avoid this, which is to create the views in the target. I should have thought of this earlier... :smile:

**Comment by TheAndroidMaster** [comment]
@JakeWharton is there a way to put extra details (like an int) when you start loading the image and retrieve it from the target? I have tried lots of things, including this:

            final SquareImageView image = new SquareImageView(Flat.this);
            image.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
            image.setBackgroundColor(getResources().getColor(R.color.oranged));
            LinearLayout horizontal = new LinearLayout(Flat.this);
            horizontal.setOrientation(LinearLayout.HORIZONTAL);
            horizontal.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
            final TextView title = new TextView(Flat.this);
            title.setBackgroundColor(getResources().getColor(R.color.orange));
            title.setTextColor(getResources().getColor(R.color.white));
            title.setPadding(50, 40, 50, 40);
            title.setText(mName);
            title.setId(Integer.valueOf(url[count]));
            Picasso.with(this)
                    .load(url[count])
                    .resize(300, 300)
                    .centerCrop()
                    .placeholder(R.mipmap.downloading)
                    .error(R.mipmap.wifioff)
                    .into(image);
            Picasso.with(this)
                    .load(url[count])
                    .resize(20, 20)
                    .into(target);
        }

I tried to use `from` to get the url of an image, then convert it to an integer which *should* be the same value as the id of the TextView created at the same time. It crashes whenever I start the activity, but doesn't say what the error is in the logcat...

    Target target = new Target() {
        @Override
        public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
            View tv = findViewById(Integer.valueOf(from.toString()) );
            int color = getDominantColor(bitmap);
            tv.setBackgroundColor(color);
        }

        @Override
        public void onBitmapFailed(Drawable errorDrawable) {

        }

        @Override
        public void onPrepareLoad(Drawable placeHolderDrawable) {

        }
    };

**Comment by TheAndroidMaster** [comment]
I changed from.toString() to from.name() and that fixed the issue but now it's saying the integer isn't valid. I'm not sure if it's possible to fix this, I will post it here if I do though.
