### ISSUE TITLE
The same image, Picasso doesn't load it on some android devices.

### ISSUE THREAD

**Issue by zzMOM** [square/picasso#1110]
Phones I used, not work: SAMSUNG OS4.1.2, NEXUS 5 OS5.1
Phones I used, do work: HTC one OS5.0.2, NeEXUS 9 OS5.0

Loding this image from url: https://btr01-dev.s3.amazonaws.com/mi/37d99c44-1675-4e67-9f25-98b539d54c18 

I debug and find the problem is 
Picasso.with(getContext())
                .load(url)
                .resize(width, height)
                .centerCrop()
                .into(imageView);

Caused by:  RequestCreator.java
Line 649:  Bitmap bitmap = picasso.quickMemoryCacheCheck(requestKey);      ///Return NULL

Caused by:  Picasso.java
Line 484:   Bitmap cached = cache.get(key);            /// Return NULL

Caused by: LruCache.java
Line 58 :    mapValue = map.get(key);       ///Return NULL
Key has correct value: 
          https://btr01-dev.s3.amazonaws.com/mi/37d99c44-1675-4e67-9f25-98b539d54c18
          resize:360x360
          centerCrop
But map not contains the key, so return null.

So, can anyone help me to fix this issue. Thanks very very much.

**Comment by marconealberto** [comment]
how did you solve it? I'm facing a similar issue

**Comment by harshals25** [comment]
android:usesCleartextTraffic="true"

Putting this in the manifest file solved the issue for me. Basically it has to deal with the API level, this will resolve the issue even if you have a target level of 21 or less
