### ISSUE TITLE
Load array of image url with completion event  

### ISSUE THREAD

**Issue by ronjumola** [square/picasso#1112]
Hi! First of all I thank you for this very wonderful library.

I noticed that the library functions to load one image per line of code. I have surfed the issue list but I can't seem to find one for my concern. 

I'm trying to load an array of image URL with a progress event and a completion event . Can you help me? Thanks!

**Comment by JakeWharton** [comment]
Since you know the array length, use the callback parameter on `into` or `fetch` to increment (or decrement) a counter which will give you overall progress. Once the counter reaches the same value as the array size (or reaches 0 if you count down) then it has completed.
