### ISSUE TITLE
Picasso download and cache problem!

### ISSUE THREAD

**Issue by THEONE10211024** [square/picasso#1115]
Can I download images in one Activity from web and cache it in the phone, not show it here .And when I jump to another Activity I just load the image from cache and put it into the ImageView?

**Comment by master-wang** [comment]
Try pass context which instanceof Application ?

**Comment by JakeWharton** [comment]
Call fetch() on the image which will cache it for future loads.

**Comment by THEONE10211024** [comment]
Thanks！
