### ISSUE TITLE
Change interface of CallBack

### ISSUE THREAD

**Issue by CaoManhDat** [square/picasso#1116]
Sometime, we wanna do some caching in CallBack (like save file to the disk). 
```java
      requestCreator.into(view, new Callback() {
        @Override
        public void onSuccess() {
          Bitmap bitmap = ((BitmapDrawable)view.getDrawable()).getBitmap();
          CacheUtils.saveBitmap(mContext,url,bitmap);
        }

        @Override
        public void onError() {

        }
      });
```
But because onSuccess not pass ImageView object so we always have to create a new instance of CallBack everytime (which costly). I suggest we should change the interface of CallBack to
```java
public interface Callback {
  void onSuccess(ImageView view);
  ...
}
```

**Comment by JakeWharton** [comment]
Callbacks are run on the main thread so if you are writing to disk you will be dropping frames and blocking the UI. As to the callback change, it would be backwards incompatible and can only be done in a Picasso v3.0 which is tracked by #581.
