### ISSUE TITLE
Custom cache policy with OKHttp

### ISSUE THREAD

**Issue by paatz04** [square/picasso#1121]
Hey - awesome library!

I've got a question. I'm wondering if it is possible to force some images to be cached locally until I manually release them (or to be released only if needed and only after all the other images are released). I would like to have a overall memory cache + a local disk cache, but I also have to ensure that some images are downloaded and locally cached for sure (with higher priority).
Is that possible somehow ? Or how can I set the CachControl or the OkHttpClient to be used with my Picasso instance. I couldn't find answers in the API / forums.

Thanks a lot!
Cheers

**Comment by JakeWharton** [comment]
> force some images to be cached locally

Picasso has no cache that can be controlled in this manner. 

By default images are cached using HTTP caching semantics using the HTTP headers which participate in caching in accordance to the RFC.
