### ISSUE TITLE
Picasso keeps allocate more and more memory

### ISSUE THREAD

**Issue by koptus** [square/picasso#1124]
I'm using picasso to load images from server in my list adapter. When I'm scrolling list up and down Picasso keeps allocate more and more memory, screen here: http://i.stack.imgur.com/bBpnm.png

    @Override
    public View getView(final int position, View convertView, ViewGroup viewGroup) {
        ViewHolder viewHolder;

        if (convertView == null || convertView.getTag() == null) {
            //init list item
            viewHolder = new ViewHolder();

            LayoutInflater inflater = (LayoutInflater) mContext
                    .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            convertView = inflater.inflate(R.layout.subfood_item, viewGroup,
                    false);

            viewHolder.mImgvPicture = (ImageView) convertView.findViewById(R.id.imgvPicture);
            viewHolder.mTvHeader = (TextView) convertView.findViewById(R.id.tvHeader);
            viewHolder.mTvDescription = (TextView) convertView.findViewById(R.id.tvDescription);

            convertView.setTag(viewHolder);
        } else {
            //list item is used again - get all references for view
            viewHolder = (ViewHolder) convertView.getTag();
        }
        Product product = mItems.get(position);

        viewHolder.mTvHeader.setText(product.getName());
        viewHolder.mTvDescription.setText(product.getDescription());

        if (product.isAsset()) {
            String folderPath = "file:///android_asset/product/";
            Picasso.with(mContext).load(folderPath + product.getPath()).fit().centerCrop().
                    into(viewHolder.mImgvPicture);
        } else {
            RestUtils.loadImageWithPicasso(RestUtils.URL_IMAGE_FROM_PRODUCT + product.getNetId(), viewHolder.mImgvPicture);
        }

        return convertView;
    }

First part - loading from assets is fine. Problem is with:

    RestUtils.loadImageWithPicasso(RestUtils.URL_IMAGE_FROM_PRODUCT + product.getNetId(), viewHolder.mImgvPicture);
I've wrapped this with additional method because of server authentication and offline caching. Below is code of RestUtils.loadImageWithPicasso
        
     public static void loadImageWithPicasso(String url, ImageView imageView) {
                float dp = App.getContext().getResources().getDisplayMetrics().density;
                if(dp<=4.0f){
                    url = url+"?size="+(int)Math.floor(dp);
                }  else {
                    url = url+"?size=4";
                }

        String requestUrl = RestUtils.getUrl(url);

        OkHttpClient picassoClient = new OkHttpClient();

        final String finalUrl = url;
        String hash = RestUtils.getHashed(finalUrl);
        Interceptor interceptor = new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request newRequest = chain.request().newBuilder()
                        .addHeader(RestUtils.HEADER, RestUtils.getHashed(finalUrl))
                        .build();
                return chain.proceed(newRequest);
            }
        };

        picassoClient.interceptors().add(interceptor);

        File httpCacheDir = new File(App.getContext().getExternalCacheDir(), RestUtils.IMAGE_CACHE);
        long httpCacheSize = 40 * 1024 * 1024;
        Cache cache = new Cache(httpCacheDir, httpCacheSize);
        picassoClient.setCache(cache);

        Picasso picasso = new Picasso.Builder(App.getContext()).downloader(new OkHttpDownloader(picassoClient)).build();

        picasso.load(requestUrl)
                .into(imageView);
    }

Even if I quit from fragment, memory is still allocated.

**Comment by koptus** [comment]
I was thinking that this is because of OkHttpClient, so I've tried regular use of picasso with random cat image:
            Picasso picasso = new Picasso.Builder(App.getContext()).build();

            picasso.load("http://blog.karmako.pl/wp-content/uploads/2013/09/tapetki_koty_0721.jpg")
                    .into(viewHolder.mImgvPicture);

But result is the same.

**Comment by mattprecious** [comment]
You're creating a new `OkHttpClient`, `Cache`, `OkHttpDownloader`, and `Picasso` every single time you call `loadImageWithPicasso()`. This is using all your memory. You should only be creating these once and re-using them for every call.

The `Picasso` instance used in that method must also be the same one you use when `isAsset()` is true or you're going to have problems with view recycling.
