### ISSUE TITLE
Picasso gives error after loading the image for sometime

### ISSUE THREAD

**Issue by timkoers** [square/picasso#1126]
The strange thing is, that picasso is working, but then another image url is being loaded, and Picasso stops working and throws an error.

Setup of the app:

Picasso picasso = new Picasso.Builder(this).downloader(new OkHttpDownloader(new OkHttpClient())).build();
        Picasso.setSingletonInstance(picasso);

Then for each image in the list (download and display it):

Picasso.with(context)
                .load(url)
                .priority(Picasso.Priority.HIGH).tag(context)
                .error(R.mipmap.ic_error)
                .resize(image.getPreview_width(), image.getPreview_height())
                .into(holder.image);

Nothing fancy at all. In fact in that same activity as the code above (well the code above is in an adapter fired from the same activity) 
This:
Picasso.with(this)
                .load(userAvatarURL)
                .transform(new CircleTransform())
                .into(targetsList.get(0));

Works flawlessly.

And the first loading code produces this logcat error:

http://pastebin.com/HuB3ptCH
Is it possible that this is caused by Android Sdk 23?

Thanks,

Tim

**Comment by iman2420** [comment]
There is a [jar version ](http://central.maven.org/maven2/com/jakewharton/picasso/picasso2-okhttp3-downloader/1.0.1/picasso2-okhttp3-downloader-1.0.1.jar) for this artifact

**Comment by JakeWharton** [comment]
We can no longer see that pastebin. Feel free to post the exception again and we can take a look.
