### ISSUE TITLE
White flash when loading already fetched images.

### ISSUE THREAD

**Issue by Ph1b** [square/picasso#1127]
I'm using a view holder where I call [notifyItemChanged](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemChanged(int)) every time an item changed. (I.e some textView). But the item also contains an ImageView for which I use Picasso to load the image. 

But the problem is that then [onBindViewHolder](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onBindViewHolder(VH, int)) which also calls Picasso to load the image from disk. 
Even tough the image is already in the cache at that time, there is a white flash even tough the image is the same.

See [this screencast](https://www.dropbox.com/s/beoonjkg9t8wh2g/device-2015-08-31-132502.mp4?dl=0)

**Comment by SimonVT** [comment]
It's the entire row that's flashing because of the default ItemAnimator on RecyclerView. You can disable this: https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html#setSupportsChangeAnimations(boolean)

**Comment by Ph1b** [comment]
Ah okay, then it's no bug. Thanks!
