### ISSUE TITLE
Picasso fails when loading large images (clicked from camera, sample included)

### ISSUE THREAD

**Issue by Dexteroo7** [square/picasso#1128]
In my application the user has the option of choosing an image as profile picture. Initially I was uploading the complete thing to the cloud but then decided to do some compression. When I tried with some bigger images I noticed that picasso simply failed when I gave it the "uri".

I then performed custom resize and quality reduction and then gave the file to picasso and it was successful.

Here is the link for the sample code. I uploaded an image for which it was failing to dropbox and the link is present in the code.

Sample code : https://www.dropbox.com/s/9y3qmxg9x4syjbs/MyApplication.zip?dl=0

**Comment by lovetuzitong** [comment]
same issue when load high-resolution(4480x2688) image
```java
W/System.err﹕ java.io.IOException: Cannot reset
W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by eygraber** [comment]
Dupe? https://github.com/square/picasso/issues/364

**Comment by JakeWharton** [comment]
Yep.
