### ISSUE TITLE
EMFILE (Too many open files)

### ISSUE THREAD

**Issue by alireza-87** [square/picasso#1129]
hi
I have a Listview In my Application , in ListView Adapter i used picasso for download and show image.
My Request send to a webserive with an authorization Header.I Added an OkHttpDownloader and picasso work veryfine but after a while application Crash and give me this error:
/*************************
09-01 02:23:20.087: A/art(12135): art/runtime/indirect_reference_table.cc:77] Check failed: table_mem_map_.get() != nullptr ashmem_create_region failed for 'indirect ref table': Too many open files
09-01 02:23:20.088: W/libbacktrace(12135): bool UnwindCurrent::UnwindFromContext(size_t, bool): unw_init_local failed -1
09-01 02:23:20.089: W/libbacktrace(12135): bool UnwindCurrent::UnwindFromContext(size_t, bool): unw_init_local failed -1
09-01 02:23:20.090: I/System.out(12135): DiskLruCache /storage/emulated/0/ichat/userimage is corrupt: /storage/emulated/0/ichat/userimage/journal: open failed: EMFILE (Too many open files), removing
/*************************
I got research and I understood must use .with(context) method for SingletonInstance. but the problem is when use .with() method picasso do not download image becuase my custom downloader Not added  to picasso object.

now there is my code in adapter:

		com.squareup.picasso.Cache cachm = new com.squareup.picasso.Cache() {

			@Override
			public int size() {
				// TODO Auto-generated method stub
				return 2000000000;
			}

			@Override
			public void set(String arg0, Bitmap arg1) {
				// TODO Auto-generated method stub
				String filePath = ClassesConst.DIR_STORAGE
						+ ClassesConst.DIR_ROOT_DIR
						+ ClassesConst.DIR_USER_IMAGE_DIR + "thmb_"
						+ fileName;
				File avatar = new File(filePath);
				if (!avatar.exists()) {
					Uri fileAddress = Uri.fromFile(new File(filePath));
					MyImage a1 = new MyImage(arg1);
					a1.saveImage(filePath);

				}

			}

			@Override
			public int maxSize() {
				// TODO Auto-generated method stub
				return 0;
			}

			@Override
			public Bitmap get(String arg0) {
				// TODO Auto-generated method stub
				String filePath = ClassesConst.DIR_STORAGE
						+ ClassesConst.DIR_ROOT_DIR
						+ ClassesConst.DIR_USER_IMAGE_DIR + "thmb_"
						+ fileName;
				File avatar = new File(filePath);
				if (avatar.exists()) {
					Uri fileAddress = Uri.fromFile(new File(filePath));
					MyImage a1 = new MyImage(fileAddress);
					return a1.getImageBitmap();

				}
				return null;
			}

			@Override
			public void clearKeyUri(String arg0) {
				// TODO Auto-generated method stub

			}

			@Override
			public void clear() {
				// TODO Auto-generated method stub
			}
		};

		OkHttpClient picassoClient = new OkHttpClient();
		long maxSize = 200000000L;
		File fileCache = new File(ClassesConst.DIR_STORAGE
				+ ClassesConst.DIR_ROOT_DIR + ClassesConst.DIR_USER_IMAGE_DIR);
		picassoClient.setCache(new Cache(fileCache, maxSize));
		final String credential = Credentials.basic(ClassesConfig.getUsername,
				ClassesConfig.getPass());
		final int x = arg0;
		picassoClient.interceptors().add(new Interceptor() {
			@Override
			public Response intercept(Chain chain) throws IOException {
				Request newRequest = new Request.Builder()
						.url(ClassesConfig.getWebServiceAddress()
								+ ClassesConfig.getWebServiceMethodAvatar()
								+ listPerson.get(x).getUsername())
						.addHeader("authorization", credential).build();
				return chain.proceed(newRequest);
			}
		});

		OkHttpDownloader objDownloader = new OkHttpDownloader(picassoClient);
		
		Picasso objPicasso = new Picasso.Builder(ClassesConfig.getAppContext()).downloader(objDownloader)
				.memoryCache(cachm).build();
		
		objPicasso.setDebugging(true);
		objPicasso.setLoggingEnabled(true);
		objPicasso.setIndicatorsEnabled(true);
		
		objPicasso.load(
				ClassesConfig.getWebServiceAddress()
						+ ClassesConfig.getWebServiceMethodAvatar()
						+ listPerson.get(x).getUsername())
				.error(R.drawable.ic_placeholder_userimage)
				.networkPolicy(NetworkPolicy.OFFLINE)
				.placeholder(R.drawable.ic_placeholder_userimage).tag(_context)
				.fit().into(viewHolder.imgUserImage);

what should i do?
Thanks

**Comment by JakeWharton** [comment]
First of all, doing I/O in a `Cache` is going to destroy your app performance. The `Cache` instance is interacted with on the main thread, and you are doing blocking I/O now in that pathway.

You also seem to be creating a new `Picasso` instance each time you call `load`. This is massively wasteful and the source of your problem as file descriptors are being left open. Create one instance and re-use it.
