### ISSUE TITLE
How should I run picasso-sample in android studio?

### ISSUE THREAD

**Issue by and1990** [square/picasso#1135]
Picasso-sample is an android application. How should I run picasso-sample in android studio?
And an error occurs, it echos "Androidmanifest xml does not exist or has incorrect root tag".
So what show I do ? Please help me.

**Comment by JakeWharton** [comment]
Picasso is currently built with Maven. You can import the project with IntelliJ IDEA, not Android Studio. Eventually we might switch, but no one is really working on Picasso at the moment.

**Comment by and1990** [comment]
I got it. thanks.
