### ISSUE TITLE
Load Dropbox Photos With Picasso

### ISSUE THREAD

**Issue by ribbon-xx** [square/picasso#1138]
Hi everyone,

I have a problem when wanna get my photos from dropbox and load it into GridView and i wanna use Picasso in adapter too. But i cannot or understand how can i do that @@.

PS: i'm using Dropbox Android SDK 1.6.3

Please help me, thanks so much!

**Comment by JakeWharton** [comment]
GitHub issues are not a good place for discussion and investigation around usage of the library. We'd prefer if you would ask the question on StackOverflow with the 'picasso' tag. There is a much larger community there with a much better system of searching and archiving of existing questions for future travelers to find.
