### ISSUE TITLE
CallBack.onSuccess() never called when image loaded from cache

### ISSUE THREAD

**Issue by garlix** [square/picasso#1140]
Hi, as the title states neither `CallBack.onSuccess()` nor `CallBack.onError()` are called when Picasso load an image from the cache. So how it is possible to know when the image is loaded?

Thanks in advance

**Comment by JakeWharton** [comment]
Show code.

**Comment by garlix** [comment]
Sorry
```java
String url = "some_url";
ImageView imgView = ....;
Picasso.with(getActivity()).load(url).placeholder(R.drawable.court).into(imgView, new Callback() {
			@Override
			public void onSuccess() {
				Log.e(TAG, "onSuccess()");
			}
			
			@Override
			public void onError() {
				Log.e(TAG, "Picasso error!!");
			}
		});
```
`onSuccess()` is called only when the image is downloaded from the network.

**Comment by garlix** [comment]
I've figured it out. I'm very sorry the `onSuccess` is called correctly each time. The difference is that, when the image is already in the memory, the call is synchronous and this behavior messed up some of my app logic.
I'm orry for wasting your time.
Closing...

**Comment by CreaRo** [comment]
Thanks a lot for this! I didn't realise this was called synchronously if cached - messed up my app logic too :D

**Comment by slott** [comment]
How to see if image is in the cache? I'm loading the image and need to callback to trigger a transition - that never happens when image is loaded from cache.
