### ISSUE TITLE
Image visibility gone while loading

### ISSUE THREAD

**Issue by cuartas15** [square/picasso#1142]
It's a matter of milliseconds, but when picasso loads a local image the space filled with the imageview gets like visibility gone, the layout try to fit that space, so generally I get a weird layout with the other components bigger or off of position, etc.
Again, it just happens in milliseconds before the image is loaded, but it's enough noticeable and I don't want to show that to potential customers, especially when I'm using images as buttons that change their states when clicked (switch the image), so it happens regulary.
Is there a way to load local images instantaneously just like the default setImageResource?

PS: prefetching images doesn't work in all cases, and I generally get outofmemory error if I use app a long time and keep switching activities

**Comment by JakeWharton** [comment]
No. If you use Picasso it will always move to the background thread to do loading as image manipulation cannot happen on the main thread. Only if the image was already loaded and thus cached in memory will it be available instantly. You should either use a placeholder or correctly size your resources and use the normal loading mechanisms for them.
