### ISSUE TITLE
OutOfMemoryException issue

### ISSUE THREAD

**Issue by manishgithub1173** [square/picasso#1144]
Our application is image resource heavy. Currently we don't have provision of sending images depending on device resolution from the server. The images sent from the server are generally of high resolution (around 900 X 900). I have few queries :
1) Will the image downloaded and stored in file disk cache will be of same size as the original size in server.

2) Once the image is saved in file disk cache, how is the image processed to bring it in the in-memory cache. Are the bitmap image stored in in-memory cache will be transformed to lower resolution depending on device resolution?

3) If the target image height and width is not known then how can we scale down the bitmap image as per device resolution? As per our requirement, it is not possible to give fixed width and height to imageview. There is resize(int, int) method but the problem is, we can't change the image height and width in some cases. Ideally, there should be some solution to downscale the image size by % (lets say 20%).

**Comment by manishgithub1173** [comment]
By the way, the crash is not happening on all devices as it depends on memory.

**Comment by jjhesk** [comment]
I used this setup to making store requests.

loading a large image from the network and making sure it will reload it again
```
  getPicClient()
                .load(mBind.image)
                .memoryPolicy(MemoryPolicy.NO_STORE,MemoryPolicy.NO_CACHE)
```

also please make a builder on the application level and initiate it at the beginnning

```java
 private void buildPicasso() {
        Picasso.Builder builder = new Picasso.Builder(this);
        builder.downloader(new OkHttpDownloader(this, Integer.MAX_VALUE));
        Picasso built = builder.build();
        built.setIndicatorsEnabled(true);
        built.setLoggingEnabled(true);
        Picasso.setSingletonInstance(built);
    }

```

**Comment by eling13** [comment]
Yes , I have the same question about the 2) and 3). Because the target image height and width is not known when down the jpg from the server,may be it is a big resolution, may be it is a small resolution, If 
set resize , It may wil make the small pic fuzzy in a big size ImageView(base on the pre-rezie)...

**Comment by JakeWharton** [comment]
1. yes
2. yes
3. you can use `fit()` which will wait for the target `ImageView` to be measured before loading the image at the exact resolution. Beyond that, you can do things like scaling down by 20% by using a ViewTreeObserver to wait for the view to be measured, calculating the 20% shrink yourself, and passing those values to `resize(int, int)`.
