### ISSUE TITLE
onPrepareLoad callback doesn't call when image is loading from memory

### ISSUE THREAD

**Issue by VadimWelldone** [square/picasso#1151]
Hi guys,

I just realized that onPrepareLoad callback doesn't call when I load image from memory and calls each time when image loads from network or disk. Is it intentionally implemented such way? Am I misunderstanding something?

My code is following:

```java
public static void loadBigArtwork(Context context, long artworkId, Target target) {
       Picasso.with(context)
          .load(CommonsHelper.getBigArtworkUrl(artworkId))
          .placeholder(context.getResources().getDrawable(R.drawable.placeholder_300))
          .error(context.getResources().getDrawable(R.drawable.placeholder_300))
          .into(target);
    }
```

Thanks in advance.

**Comment by JakeWharton** [comment]
`onPrepareLoad` is only called for asynchronous loading to inform the `Target` that it should display some sort of placeholder or loading indicator. When the image is available instantly, this callback is skipped to avoid any work that would be done executing it since `onBitmapLoaded` is about to be called anyway.

**Comment by VadimWelldone** [comment]
I got it. Thanks Jake :+1:

**Comment by lwlittayat** [comment]
i have a ploblem when i display Picasso imageview and get bitmap is null
Picasso.with(topicass.getContext()).load(url in googleDrive).into(ImageView);
byte[] image = imageViewToByte(ImageView); // i use byte array to sqlite BLOB

//here imageViewToByte
    public static byte[] imageViewToByte(ImageView image) {
        Bitmap bitmap = ((BitmapDrawable) image.getDrawable()).getBitmap();
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.JPEG, 100, stream);
        byte[] byteArray = stream.toByteArray();
        return byteArray;
    }

please help
