### ISSUE TITLE
What is default cache policy?

### ISSUE THREAD

**Issue by luaz** [square/picasso#1154]
May I know what is the default cache policy? (I assume 2.5.2 got its own caching mechanism which doesn't rely on okhttp)
- How big is the cache size for local file and memory / how to change it?
- What is the algo to decide which cache got cleared first?
- Any API/Settings to manipulate the caching mechanism?

**Comment by JakeWharton** [comment]
> How big is the cache size for local file and memory / how to change it?

Disk cache is 50MB I think. Memory is 1/7th heap size.

You can chance it by calling `setCache` on the builder for memory cache or by installing your own disk cache on the HTTP client.

> What is the algo to decide which cache got cleared first?

Memory is LRU. Disk cache is up to whatever HTTP client you are using, presumably it follows RFC 7234 rules (or the like).

> Any API/Settings to manipulate the caching mechanism?

See first answer.

**Comment by JakeWharton** [comment]
>  assume 2.5.2 got its own caching mechanism which doesn't rely on okhttp

No. Nothing changed.

**Comment by luaz** [comment]
Thanks. I assume the following is the correct code to increase disk cache size to 250MB

        Picasso picasso =  new Picasso.Builder(this).downloader(new OkHttpDownloader(getCacheDir(), 250000000)).build();
        Picasso.setSingletonInstance(picasso);

**Comment by JakeWharton** [comment]
Yep!

**Comment by ralphevmanzano** [comment]
@JakeWharton may I ask where should I put this code?

**Comment by PavanBilagi** [comment]
How to change the default disk cache policy? I have tried to use cache-control headers for the image, `<cache-control: public, max-age=60>`  but it is not working. Is there a way to set an expiry time for images while storing in the disk?

**Comment by JakeWharton** [comment]
Picasso doesn't have a disk cache. OkHttp maintains an HTTP cache which is
controlled by HTTP cache headers (which Picasso has no control over).

**Comment by PavanBilagi** [comment]
Thanks @JakeWharton will raise it in https://github.com/square/okhttp/issues
