### ISSUE TITLE
Picasso doesnt show images on Android 4.4.4 (MotoX smartphone) from Camera

### ISSUE THREAD

**Issue by deadean** [square/picasso#1156]
Picasso doesnt show images on Android 4.4.4 (MotoX smartphone) from Camera and it shows images from another albums correctly. Picasso version 2.5.2.2

**Comment by JakeWharton** [comment]
There is far too little information here to be actionable. Without debug logs, exceptions, example images that fail, etc. we have no way of knowing what's happening. If you can supply enough information we can re-open the bug.

**Comment by deadean** [comment]
I have uploaded the image that Picasso doesn't show here : http://rghost.net/private/8ySdnWjM5/33f8364b8c875c007932c52c9f1388ab
