### ISSUE TITLE
ERROR D/skia: --- SkImageDecoder::Factory returned null

### ISSUE THREAD

**Issue by semiromid** [square/picasso#1163]
I try load image from server  but not work - http://worldfilmpeople.bombinfo.ru/1/DvpvklR.png --- NOT GOOD

IF i try load image from http://i.imgur.com/DvpvklR.png   --- GOOD

10-14 15:07:58.300 2099-2099/? D/dalvikvm: Late-enabling CheckJNI
10-14 15:07:58.420 2099-2099/? E/dalvikvm: Could not find class 'android.transition.Slide', referenced from method ru.noticeword_send.com.sendpm.MainActivity.initActivityTransitions
10-14 15:07:58.420 2099-2099/? W/dalvikvm: VFY: unable to resolve new-instance 1940 (Landroid/transition/Slide;) in Lru/noticeword_send/com/sendpm/MainActivity;
10-14 15:07:58.420 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x22 at 0x0006
10-14 15:07:58.420 2099-2099/? D/dalvikvm: DexOpt: unable to opt direct call 0x421f at 0x08 in Lru/noticeword_send/com/sendpm/MainActivity;.initActivityTransitions
10-14 15:07:58.440 2099-2099/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
10-14 15:07:58.444 2099-2099/? I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onSearchRequested
10-14 15:07:58.444 2099-2099/? W/dalvikvm: VFY: unable to resolve interface method 17569: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
10-14 15:07:58.444 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
10-14 15:07:58.444 2099-2099/? I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onWindowStartingActionMode
10-14 15:07:58.444 2099-2099/? W/dalvikvm: VFY: unable to resolve interface method 17573: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
10-14 15:07:58.444 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
10-14 15:07:58.460 2099-2099/? I/dalvikvm: Could not find method android.widget.LinearLayout$LayoutParams.<init>, referenced from method android.support.design.widget.AppBarLayout$LayoutParams.<init>
10-14 15:07:58.464 2099-2099/? W/dalvikvm: VFY: unable to resolve direct method 18072: Landroid/widget/LinearLayout$LayoutParams;.<init> (Landroid/widget/LinearLayout$LayoutParams;)V
10-14 15:07:58.464 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x70 at 0x0000
10-14 15:07:58.464 2099-2099/? I/dalvikvm: Could not find method android.widget.LinearLayout$LayoutParams.<init>, referenced from method android.support.design.widget.AppBarLayout$LayoutParams.<init>
10-14 15:07:58.464 2099-2099/? W/dalvikvm: VFY: unable to resolve direct method 18072: Landroid/widget/LinearLayout$LayoutParams;.<init> (Landroid/widget/LinearLayout$LayoutParams;)V
10-14 15:07:58.464 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x70 at 0x0000
10-14 15:07:58.464 2099-2099/? I/dalvikvm: Could not find method android.widget.FrameLayout$LayoutParams.<init>, referenced from method android.support.design.widget.CollapsingToolbarLayout$LayoutParams.<init>
10-14 15:07:58.464 2099-2099/? W/dalvikvm: VFY: unable to resolve direct method 17970: Landroid/widget/FrameLayout$LayoutParams;.<init> (Landroid/widget/FrameLayout$LayoutParams;)V
10-14 15:07:58.464 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x70 at 0x0000
10-14 15:07:58.468 2099-2099/? I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
10-14 15:07:58.468 2099-2099/? W/dalvikvm: VFY: unable to resolve virtual method 428: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
10-14 15:07:58.468 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
10-14 15:07:58.468 2099-2099/? I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
10-14 15:07:58.468 2099-2099/? W/dalvikvm: VFY: unable to resolve virtual method 450: Landroid/content/res/TypedArray;.getType (I)I
10-14 15:07:58.468 2099-2099/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
10-14 15:07:58.480 2099-2099/? D/dalvikvm: GC_FOR_ALLOC freed 159K, 14% free 4160K/4836K, paused 3ms, total 3ms
10-14 15:07:58.504 2099-2099/? W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-14 15:07:58.596 2099-2103/? D/dalvikvm: GC_CONCURRENT freed 77K, 13% free 4477K/5088K, paused 27ms+1ms, total 31ms
10-14 15:07:58.612 2099-2099/? D/libEGL: loaded /system/lib/egl/libEGL_genymotion.so
10-14 15:07:58.612 2099-2099/? D/: HostConnection::get() New Host Connection established 0xb7f28728, tid 2099
10-14 15:07:58.628 2099-2099/? D/libEGL: loaded /system/lib/egl/libGLESv1_CM_genymotion.so
10-14 15:07:58.628 2099-2099/? D/libEGL: loaded /system/lib/egl/libGLESv2_genymotion.so
10-14 15:07:58.688 2099-2099/? W/EGL_genymotion: eglSurfaceAttrib not implemented
10-14 15:07:58.752 2099-2099/ru.noticeword_send.com.sendpm D/OpenGLRenderer: Enabling debug mode 0
10-14 15:07:59.068 2099-2127/ru.noticeword_send.com.sendpm D/skia: --- SkImageDecoder::Factory returned null
10-14 15:07:59.236 2099-2103/ru.noticeword_send.com.sendpm D/dalvikvm: GC_CONCURRENT freed 351K, 17% free 4548K/5416K, paused 6ms+0ms, total 17ms
10-14 15:07:59.716 2099-2152/ru.noticeword_send.com.sendpm D/skia: --- SkImageDecoder::Factory returned null
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err: java.io.IOException: Failed to decode stream.
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at java.lang.Thread.run(Thread.java:856)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
10-14 15:08:00.420 2099-2099/ru.noticeword_send.com.sendpm I/111:  зпгрузка - java.io.IOException: Failed to decode stream.

**Comment by Hofferic** [comment]
Looking at the trace it seems the bitmap you are trying to load is invalid in some shape or form. 

Picasso uses the android platform capabilities for all image decoding. The "failed to decode stream" message means that the most probable cause is a bitmap android cannot decode or a ressource that is NOT a bitmap being passed to picasso and therefore the android framework methods (for example picasso is served a server error page with HTTP 200 and tries to decode the error page as a bitmap). Either way the problem is most probably in the ressource you are trying to load, not in picasso.

**Comment by JakeWharton** [comment]
> The "failed to decode stream" message means that the most probable cause is a bitmap android cannot decode or a resource.

Demonstrating a failure other than this will result in re-opening the issue.

**Comment by jaydeepDobariya** [comment]
02-17 15:02:56.310: D/skia(4320): --- SkImageDecoder::Factory returned null
02-17 15:02:56.310: D/skia(4320): --- SkImageDecoder::Factory returned null
02-17 15:02:57.220: D/skia(4320): --- SkImageDecoder::Factory returned null
02-17 15:02:57.220: D/skia(4320): --- SkImageDecoder::Factory returned null


i have also face this problem.
please give me proper solution..

**Comment by maniaZTD** [comment]
In my case I solved this error with encode the url 
Because image url that i wanted to download has the Persian letters(or other Unicode character) in it 
So I replaced all Persian characters with encoded UTF-8 letters

**Comment by hamidsn** [comment]
I ended up with encoding characters of my uri, it is working. Basically issue was with a wrong character in the image uri
