### ISSUE TITLE
Picasso doesnt show images on Android 4.4.4 (MotoX smartphone) from Camera

### ISSUE THREAD

**Issue by deadean** [square/picasso#1164]
Picasso doesnt show images on Android 4.4.4 (MotoX smartphone) from Camera. Here this image:
http://rghost.net/private/8ySdnWjM5/33f8364b8c875c007932c52c9f1388ab

**Comment by JakeWharton** [comment]
What's the error? stacktrace? How are you calling Picasso? Without the details it's impossible to diagnose what's happening.
