### ISSUE TITLE
Extra data for Downloader

### ISSUE THREAD

**Issue by sierbrat** [square/picasso#1165]
What do you think about adding extra data for Downloader?
Something like this: https://github.com/nostra13/Android-Universal-Image-Loader/blob/master/library/src/main/java/com/nostra13/universalimageloader/core/download/ImageDownloader.java

It's a very useful feature for implementation custom logic in downloader.

**Comment by JakeWharton** [comment]
You can just put the extra data in the Uri and pull it out in the downloader. We use fake Uris with fake schemes to do all kinds of clever things.

**Comment by sierbrat** [comment]
Ok, Thanks you
