### ISSUE TITLE
Picasso not load image into item of GridView or RecyclerView

### ISSUE THREAD

**Issue by phamxuanlu** [square/picasso#1169]
I used Picasso like bellow code in my custom adapter extends from BaseAdapter (for GridView) or RecyclerView.Adapter (for RecyclerView)

entry.getUrlImage() return value  like this : "/storage/sdcard0/DCIM/100LGDSC/CAM00046.jpg"

```Java
Picasso.with(mContext)
                .load(entry.getUrlImage())
                .resize(150,150)
                .into(holder.iIvImage);
```
But my grid show blank items, Another info like name ... still show at there.

**Comment by wuyexiong** [comment]
replace your code like that

Picasso.with(mContext)
                .load(new File(entry.getUrlImage()))
                .resize(150,150)
                .into(holder.iIvImage);
