### ISSUE TITLE
In any adapterview Picasso not loading image!

### ISSUE THREAD

**Issue by wal-kumail** [square/picasso#1171]
I have use the different approaches so far using target, but haven't succeed till yet. 

Dont know why in adapterview (listview or gridview) Picasso fails to load large images.

**Comment by JakeWharton** [comment]
You have provided no information so no one would be able to help you anyway. Please consider posting to StackOverflow with the 'picasso' tag and include information about how you're using Picasso, the behavior you're seeing, device info, and any other info that might be relevant.
