### ISSUE TITLE
How to calculate width and height used in `fit()` ?

### ISSUE THREAD

**Issue by marioosh-net** [square/picasso#1174]
I'm using `.fit()` on images in `ViewPager`. All images have the same dimensions. Is a simple way to calculate width and height values used by `.fit()` ? For better performance, I think about calculate this one time for first image and use `.resize()` (instead of `fit()`) with calculated values for all next images. I'm using Picasso 2.4.0.

**Comment by JakeWharton** [comment]
It just uses the raw width and height of the target `ImageView`. So if you can figure out what the size will be in pixels based on dp calculation or whatever layout constraints you are using to size the ImageView, those values can be passed to `resize`.

> For better performance

Are you seeing a performance problem? I'm not sure I would go through any trouble unless you have measured actual problems in using `.fit()`, and in that case, we'd like to know what they are.

**Comment by marioosh-net** [comment]
I thought that width and height are in some way calculated when using `fit()`, so to better performance i just need to calculate it only once. If it is raw width and height of `ImageView` there is no problem at all. Thank You.

**Comment by JakeWharton** [comment]
Nope. It's entirely the dimensions of the target view.
