### ISSUE TITLE
image loading response 404 cached

### ISSUE THREAD

**Issue by machinezhou** [square/picasso#1176]
hi sir, 
My question is like this:
The first time I load an image "http://xxx.xxx.a.jpg" from server which cannot find this picture and response 404 correctly.  Then I put a picture on the server as "http://xxx.xxx.a.jpg",  refresh loading with picasso and oddly 404 again. So I assume there's some sort of cache effect here in Okhttp or Picasso. Any idea?

**Comment by JakeWharton** [comment]
If the server returns 404 Picasso itself will not cache anything about the request. For every request for that URL, it will call down into the HTTP client for the resource. What the HTTP client does, however, is not up to Picasso. That said, no HTTP client that I know of caches 404 responses.

I tested this and saw it call the HTTP client each time for a 404. Unless you can demonstrate that it's Picasso causing this behavior (which I can't imagine how it would be) I'm going to close for now.

**Comment by machinezhou** [comment]
Thanks a lot sir，I'll check it out with our server mate.
