### ISSUE TITLE
set and fetch identifier for cached image

### ISSUE THREAD

**Issue by AniketBhadane** [square/picasso#1180]
How can I set and fetch an identifier for the cached image in picasso?

Specifically, I want to set unix timestamp along with a cached image (which I'm calling as modified time).

Using picasso, I'm fetching some images from network and caching them. These images are profile images of users.

Picasso.with(context)
        .load(url)
        .placeholder(R.drawable.ic_contact_picture)
        .error(R.drawable.ic_contact_picture)
        .into(imageView);

On my server database, I maintain images' last modified time. So whenever I request a image, I want to first send the image modified time that I have locally, so that I can check whether modified time of the image at server has changed and then refetch image only if it has changed.

Algorithm:

1. Fetch picasso cached image modified time

2. Send this time to server

3. Server checks whether modified time for the image has changed.

4. If server replies yes, refetch the new image and set new modified time received from server in picasso. Else, do nothing.

I can do steps 2,3,4. But I'm not sure how step 1 can be done?

How can I set and fetch modified time for the cached image in picasso?

**Comment by JakeWharton** [comment]
Picasso's cache does not honor any time-based system. It uses a
non-persistant LRU based on size.

Picasso relies on the HTTP client for disk caching, and HTTP caching
already does exactly what you described automatically when using the proper
cache headers. You can set a length of time the image is valid, and when it
expires a check will be performed where the server can return a 304
indicating the image doesn't need downloaded again. There are tons of
resources and documents describing HTTP caching and the headers required.

As to Picasso's memory csche, we have no plans to expose any APIs to
control it in this way or support time-based invalidation. In practice the
process only lives for a few minutes anyway which is why the disk cache is
where this belongs.

**Comment by AniketBhadane** [comment]
Does Picasso also maintain ETag and send it to server while fetching?

**Comment by JakeWharton** [comment]
No. That would be the HTTP client's responsibility.

**Comment by AniketBhadane** [comment]
If I just Okhttp dependencies in gradle, does Picasso use it automatically then? Or do I have to explicitly create OkHttpClient object and send it to downloader tag?

**Comment by JakeWharton** [comment]
Picasso will use OkHttp automatically if it is in your app!

**Comment by AniketBhadane** [comment]
Alright, so I have to send headers from server side script and for next subsequent calls from app to server, picasso will internally use okhttp to send back those headers without any okhttp configuration?

**Comment by JakeWharton** [comment]
Yep!

**Comment by AniketBhadane** [comment]
I'm using php as backend script and apache server, now since the url in load tag is path to the image .../.../...jpg, how can I set the headers in a php script?

**Comment by JakeWharton** [comment]
I don't know. A PHP forum or StackOverflow would be the right place to find
that information.

**Comment by AniketBhadane** [comment]
http://stackoverflow.com/questions/33393085/php-set-headers-for-requested-image I've posted this question

**Comment by AniketBhadane** [comment]
Also, I think that this would be a general issue, since the load tag will always have an image path, how can headers be set using any server and scripting language?

**Comment by JakeWharton** [comment]
That question is far beyond the scope of anything that needs documented on
this library. How many languages, server softwares, and caching strategies
are there. You could write a book on that subject!

**Comment by AniketBhadane** [comment]
For using OkHttp properly, do I have create OkHttpClient object? Like:
```
OkHttpClient client = new OkHttpClient(); client.setProtocols(Arrays.asList(Protocol.HTTP_1_1));
final Picasso picasso = new Picasso.Builder(context) .downloader(new OkHttpDownloader(client)) .build();
```

**Comment by jonan** [comment]
As @JakeWharton said here https://github.com/square/picasso/issues/1180#issuecomment-151836185, Picasso will use OkHttp if available. So if you add OkHttp as a dependecy, Picasso will use it.
