### ISSUE TITLE
Picasso Flowchart

### ISSUE THREAD

**Issue by AniketBhadane** [square/picasso#1181]
Is there any flowchart or documentation available that describes process flow of how picasso fetches images?

Like whether it first checks for memory cache, then disk cache or http client cache control, when does it handle networkpolicy, memorypolicy parameters etc.

**Comment by JakeWharton** [comment]
There is no such chart. Would make a good contribution

**Comment by AniketBhadane** [comment]
If I have simply
Picasso.with(context)
                    .load(url)
                    .placeholder(R.drawable.ic_contact_picture)
                    .error(R.drawable.ic_contact_picture)
                    .into(imageView);

how would I know whether image would be loaded from cache or would it be refetched?

**Comment by JakeWharton** [comment]
You can't. That depends on the memory cache state and the disk cache state,
neither of which you can know statically.

**Comment by AniketBhadane** [comment]
I meant to say, in what order does it check the caches and okhttp?

**Comment by AniketBhadane** [comment]
This seems to be issue still in thread #438 Also https://github.com/square/picasso/issues/438#issuecomment-50907839 mentions the same problem that I have. Also there are many people further below in that thread having the same problem

**Comment by JakeWharton** [comment]
Picasso has only one cache, a memory one. It checks it and then calls the
HTTP client if there was a cache miss.

**Comment by AniketBhadane** [comment]
So if there is a cache-control header set in http client, and it expires, still the cached image will be fetched. Am I right?

**Comment by JakeWharton** [comment]
That is entirely up to the HTTP client. If it honors csje headers, then
yes, that is what will happen.

**Comment by AniketBhadane** [comment]
That was not my point. Like you said, memory cache is first checked and http client is called ONLY IF CACHE MISS. Then till the cache exists, suppose 10 hours, it will not call http client at all ! And if cache-control has max-age of suppose 1 hour, then irrespective of whether the http client honors the headers or not, picasso will not call it since cache exits

**Comment by JakeWharton** [comment]
That is correct, and is the behavior we chose because in practice no one
uses expiration times that short.

**Comment by AniketBhadane** [comment]
Considering an example of WhatsApp, where such thing is used to show images in listview in chats list and contacts list. When we scroll through its listview, images in its cache are first loaded and in the background it checks whether the image has changed as we scroll. We can actually see old image fading into new one, if there's a change. Does it mean it is always referring to its http client, irrespective of memory cache miss?

**Comment by JakeWharton** [comment]
You would have to consult their developers. I have no idea.

**Comment by AniketBhadane** [comment]
Sorry for that question.

Regarding picasso, if 
Picasso.with(context)
.load(url)
.networkPolicy(NetworkPolicy.NO_CACHE) /*******/
.placeholder(R.drawable.ic_contact_picture)
.error(R.drawable.ic_contact_picture)
.into(imageView);

with networkpolicy set, even then picasso will first look for memory cache? Is networkpolicy for the http client and not for picasso?

**Comment by JakeWharton** [comment]
Yes

**Comment by JakeWharton** [comment]
Closing as there's no action to take.
