### ISSUE TITLE
picasso not working with okhttp

### ISSUE THREAD

**Issue by AniketBhadane** [square/picasso#1183]
I've added following gradle dependencies:
```
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp:okhttp:2.5.0'
```
Using picasso simply like this:
```
        Picasso.with(context)
                .load(url)
                .placeholder(R.drawable.ic_contact_picture)
                .error(R.drawable.ic_contact_picture)
                .into(imageView);
```
Here url is something like:
```
myserverpath/getImage.php?param=abc
```
In this getImage.php file, I'm setting header
```
header('Cache-Control: max-age=60');
```
And sending image like this:
```
echo file_get_contents("$imagepath");
```
Once picasso has fetched the image, it caches the image and never refetches the image again. It always shows the cached image without refetching it. It should fetch the image again if 60 seconds have passed as defined in Cache-Control header. This means Picasso is NOT CONSIDERING okhttp or okhttp is not working properly? What's the problem here?

**Comment by JakeWharton** [comment]
Picasso's memory cache does not honor caching headers. It is assumed that
the LRU and short process lifetime will be enough to ensure images are
refreshed from the HTTP client which, in most cases, will end up using the
disk cached version anyway. It would require a great deal of logic and
extra infrastructure to honor these headers for little benefit so the
choice was made to ignore them at the memory level.
