### ISSUE TITLE
How to set maximum caching time?

### ISSUE THREAD

**Issue by HemaJha** [square/picasso#1184]
Hi,
Presently i am using UIL(universal image loader) but as picasso providing more feature compare to UIL so i am planning to upgrade from UIL to picasso but the only problem is that i am unable to find any property for setting caching Age.

**Comment by JakeWharton** [comment]
Picasso's memory cache does not use time to evict items from the cache. You can create your own `Cache` implementation that honors time, but by default Picasso only uses an LRU at a fixed size (1/7th of the heap). Images will stay in the memory cache as long as the process is alive or until they are evicted by other images being loaded.
