### ISSUE TITLE
picasso loading old images from cache after images being updated on server

### ISSUE THREAD

**Issue by jawadturk** [square/picasso#1186]
hey , I'm new to picasso . Its amazing library with great capabilities . Im using it to load images from url . in my code i might update the image on the server keeping the same URL . my problem is that after updating the image picasso is still displaying the old image from cache and not from URL . I already know why because the URL is the same . so please i need help in case there is a way to let picasso know that image should be loaded again from server instead cache . Ive tried to invalidate URL after updating certain image but when i went offline images failed to load from cache although they were loaded again !

**Comment by ChristianLJ** [comment]
This might be because of the Expires or Cache Policy headers.

Can you please provide your headers?

**Comment by JakeWharton** [comment]
You can use `.memoryPolicy(MemoryPolicy.NO_CACHE)` on the next request which will skip Picasso's cache. There's also `.networkPolicy(NetworkPolicy.NO_CACHE)` if you need to bust the HTTP cache.

**Comment by RohitJPatil** [comment]
Excellent answer  .memoryPolicy(MemoryPolicy.NO_CACHE)
Thaks alot

**Comment by gitchrisadams** [comment]
After using .memoryPolicy, the image was still not changing. After using .networkPolicy(NetworkPolicy.NO_CACHE)
It worked perfectly. Thank you!

**Comment by JerabekJakub** [comment]
Hi, how about the use case when image is changed for example once a year. I don't wanna set policy to NO_CACHE, because i want caching enabled. URL is still the same after update, how long will it take to load new version?

**Comment by JakeWharton** [comment]
It will be loaded once per application launch or when evicted from the
cache by loading a bunch of other images.

**Comment by CoolMind** [comment]
Why is this issue closed? I bumped into this problem. Is it a way to force Picasso update it's cached image?

**Comment by JakeWharton** [comment]
You can use the memory and disk cache APIs on RequestBuilder to control
that.

**Comment by CoolMind** [comment]
Thank you, Jake! It's the first time when such a famous person replyes me. I looked for "Request.Builder" and understand that it was better to make Picasso as a Singleton in Application class. In my case user receives an image from gallery or camera and save in temporary file. If then the user gets a new photo it should be replaced into a file and shown again. So now I use different file names, but probably it will be better to use the same.

**Comment by blackhawk389** [comment]
In my case picasso loading image again, seems like it didnt cached image

**Comment by sivarajesh** [comment]
Try this @CoolMind  @blackhawk389 

Picasso.get().invalidate("THAT URL")
