### ISSUE TITLE
Catch "" when load image

### ISSUE THREAD

**Issue by lijianhy** [square/picasso#1187]
The first,I add this "compile 'com.squareup.picasso:picasso:2.5.2'" only in my app
than catch the exception "java.net.UnknownHostException" for this url "http:\/\/file_azf.1sapp.com\/upload\/sp\/2015\/11\/03\/1446515773922.jpeg".
At last,i add this to the build.gradle "compile 'com.squareup.okhttp:okhttp:2.5.0'"
the image show in the view

**Comment by JakeWharton** [comment]
UnknownHostException comes from the networking stack which does DNS resolution. Both OkHttp and HttpURLConnection will likely use the same platform APIs for this, but it is possible that some configuration might prevent the host from being resolved in one but not the other.

In any case, this isn't a problem with Picasso itself, but some configuration elsewhere, or perhaps even just a transient network problem. There's no action to take on our side.
