### ISSUE TITLE
getExifOrientation open to SQL Injection?

### ISSUE THREAD

**Issue by KyleJahnke** [square/picasso#1188]
According to static code analysis tools, the below method in MediaStoreRequestHandler is susceptible to SQL injection on the call to query(). Should there be some sort of sanitation performed on the uri field to prevent any chances of this?

 static int getExifOrientation(ContentResolver contentResolver, Uri uri) {
    Cursor cursor = null;
    try {
      cursor = contentResolver.query(uri, CONTENT_ORIENTATION, null, null, null);
      ...

**Comment by JakeWharton** [comment]
> Should there be some sort of sanitation

Like what? We have no context on the content of the `Uri`, so I don't really know what Picasso would do.

That `Uri` instance is passed into Picasso as part of an image request. If there's any risk associated with querying a content resolver with the Uri then I think it should be the application's problem to sanitize, not Picasso.
