### ISSUE TITLE
Allow editing singleton

### ISSUE THREAD

**Issue by dadino** [square/picasso#1195]
I'm using Picasso to load images, using an authentication header. This header changes during the Application lifecycle, so I tried creating a new Picasso instance and setting it with setSingletonInstance. Turns out I can't. 
This seems like a pretty normal use case, so I think I'm missing something.

Here is what I do now:

    public static void setPicasso(final Context context) {
		OkHttpClient client = getOkHttpClient();

	    client.interceptors()
		      .add(new Interceptor() {
			      @Override
			      public Response intercept(Chain chain) throws
					      IOException {
				      final String token = PrefsUtils.loadLoginToken(context);
				      Request newRequest = chain.request()
				                                .newBuilder()
				                                .addHeader(Api.TOKEN,
						                                token != null ? token : "")
				                                .build();
				      return chain.proceed(newRequest);
			      }
		      });

		Picasso picasso = new Picasso.Builder(context).downloader(new OkHttpDownloader(client))
		                                              .defaultBitmapConfig(Bitmap.Config.RGB_565)
		                                              .build();
		Picasso.setSingletonInstance(picasso);
	}

**Comment by JakeWharton** [comment]
Retain the interceptor and change the value it sets. There's no need to
recreate the whole Picasso instance.

**Comment by kSriramji** [comment]
@JakeWharton Please add code snippet to retain the interceptor
