### ISSUE TITLE
inPurgeable vs inBitmap option

### ISSUE THREAD

**Issue by lzyzsd** [square/picasso#1198]
Since inPurgeable is not encouraged by Google according to api doc
>While inPurgeable can help avoid big Dalvik heap allocations (from API level 11 onward), it sacrifices performance predictability since any image that the view system tries to draw may incur a decode delay which can lead to dropped frames. Therefore, most apps should avoid using inPurgeable to allow for a fast and fluid UI. To minimize Dalvik heap allocations use the inBitmap flag instead.

so, why picasso not use inBitmap option?

**Comment by JakeWharton** [comment]
Dupe of #672. See my responses there.

**Comment by lzyzsd** [comment]
Sorry for not notice that, thanks a lot!

**Comment by JakeWharton** [comment]
Yeah it's a complicated topic, unfortunately.
