### ISSUE TITLE
OutOfMemory Exception handled?

### ISSUE THREAD

**Issue by fmeneuhe** [square/picasso#1199]
Hi,
Does the Picasso lib handle large images that can cause a OutOfMemoryException? Does the the lib compress or any other method to avoid out of memory problems?
Thanks

**Comment by JakeWharton** [comment]
No. If you ask for a ridiculously large image then Picasso will try to load it and it will crash your app. There are APIs that you should be using which can help to prevent this (like `fit()`), but ultimately Picasso will do what you tell it and if you tell it to load too much the app will eventually OOM.
