### ISSUE TITLE
Layout of GridView with ImageViews can be ruined with fast scrolling through items if one of them has invalid url to load image

### ISSUE THREAD

**Issue by karmazinkd** [square/picasso#1201]
The issue is recorded and uploaded here: https://drive.google.com/file/d/0B5Y65du7slVnaE5KbnpzLThDaU0/view?usp=sharing 
and described below:

I have a simple GridView of ImageViews. ImageViews are being populated with images via Picasso in my CustomAdapter getView() method:
```
   @Override
    public View getView(int position, View convertView, ViewGroup parent) {

        ViewHolder viewHolder;

        if (convertView == null) {
            convertView = mLInflater.inflate(R.layout.poster_layout, parent, false);
            viewHolder = new ViewHolder();
            viewHolder.imageViewPoster = (ImageView) convertView.findViewById(R.id.ivPoster);
            convertView.setTag(viewHolder);
        } else {
            viewHolder = (ViewHolder) convertView.getTag();
        }


        Picasso.with(mContext)
                .load(mMovieList.get(position).getPosterUrl())
                .placeholder(R.drawable.ic_hourglass_empty_white_24dp)
                .error(R.drawable.ic_highlight_off_white_24dp)
                .into(viewHolder.imageViewPoster);

        return convertView;
    }
```

I have a list of 20 Url's of movie posters and everything works fine. 
Until one of the poster's Url I receive is invalid. As a result ImageView shows a placeholder and after couple of retries it display an error picture, which was provided in `.error()` method. This works as expected. 
If you scroll smoothly (not skipping items) everything works fine. (you can see it in the video)

But if you scroll down *through* that item, which has no image, very fast and you stop in a position where your empty ImageView is on top (so that only part of empty ImageView is visible on the top of screen) and then you scroll up fast - strange things happen: layout is seems to be melted and shifted. And when you scroll up to the start of the grid you will see that you can scroll even higher than the first ImageView. How could that be even possible? Then you just scroll up until all ImageViews disappear.

I have a suspicion that when Picasso is trying to get the image by invalid url it goes through some transient states and when you scroll in that moment up - getView() method takes this View to reuse and something goes wrong because of that.

I can say that in my app if all 20 ImageViews have valid Url for images - everything works fine, no matter how hard I try to scroll up & down.

Here is a layout with  GridView: 
`fragment_posters.xml`
```
<GridView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/gvPosters"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#000"
    android:columnWidth="150dp"
    android:gravity="center"
    android:horizontalSpacing="0dp"
    android:numColumns="auto_fit"
    android:stretchMode="columnWidth"
    android:verticalSpacing="0dp" />
```

here is the a poster layout:
`poster_layoout.xml`
```
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/ivPoster"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:padding="0dp"
    android:minHeight="15dp"
    android:minWidth="15dp"
    android:background="#875457"/>
```

is it a bug or I'm missing something?

**Comment by karmazinkd** [comment]
UPD:
even when I don't reuse convertView's in getView() method: I still get the same issue:
```
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {

        View view = mLInflater.inflate(R.layout.poster_layout, parent, false);
        ImageView imageViewPoster = (ImageView) view.findViewById(R.id.ivPoster);

        Picasso.with(mContext).load(mMovieList.get(position).getPosterUrl())
                    .placeholder(R.drawable.ic_hourglass_empty_white_24dp)
                    .error(R.drawable.ic_highlight_off_white_24dp)
                    .into(imageViewPoster);

        return view;
    }
```

**Comment by karmazinkd** [comment]
Issue was because of android:adjustViewBounds="true" in ImageView. 

This attribute adjusts size of ImageView in order to fit actual content image, it does not respect layout_width and layout_height of ImageView. So when there was an error while loading image - the error placeholder was displayed, which has different sizes than the rest of ImageViews in the GridView. 
Thus it was breaking the whole layout.

I removed that attribute and edited error placeholder image so it's size now equals the size of the rest of ImageViews and everything works fine.

Hope this will be useful for someone ;)

**Comment by berkantkz** [comment]
Thanks so much @karmazinkd . Removing android:adjustViewBounds="true" fixed my issue!
