### ISSUE TITLE
how can i change memory cash for images loaded from disk ?

### ISSUE THREAD

**Issue by mohabinventor** [square/picasso#1203]
i'am using picasso to load images from disk as follow picasso.with(context).load(file).into(imageview);  how can i set memory cash this way? thanx in advance

**Comment by JakeWharton** [comment]
Images are automatically cached in memory. You do not have to do anything.

**Comment by mohabinventor** [comment]
hay jakeWharton if i  scroll gridview down then back up to images already loaded i take a lot of time to appear and sometime i get plank activity and then app crashs

**Comment by JakeWharton** [comment]
Then other images are evicting the older ones from the cache due to their
size.

**Comment by mohabinventor** [comment]
so how can i solve this problem ?

**Comment by mohabinventor** [comment]
those images are thumbnails

**Comment by JakeWharton** [comment]
Load smaller versions or increase the size of the memory cache.

**Comment by mohabinventor** [comment]
i am actually asking about that .. plz read the question again .

**Comment by JakeWharton** [comment]
Call `new LruCache` with the size you want and pass that to `setCache` on `Picasso.Builder`.
