### ISSUE TITLE
Picasso how to deal with both small pic and big pic in the list

### ISSUE THREAD

**Issue by eling13** [square/picasso#1207]
I get the path from the list, If this path is a big resolution pic , pre-set resize api can avoid the OOM,but 
if I get the path that It is a small pic, the pre-set resize make the  the small pic become fuzzy...
How to deal with the big pic and small pic in the same ImageView, using 
                                                    Picasso.with(mContext)
			   .load(pathStr[position])
			   .centerCrop()
			   .resize(xx, xx)
			   .into(viewHolder.mImageView);

**Comment by eling13** [comment]
I have another question:
If a jpeg pic resolution is:1280*1440 ,decode it to Bitmap, the bitmap will hold the almost 5M, the picasso
can scale it base on the device screen resolution?? If not ,that is will be very horrible...

**Comment by JakeWharton** [comment]
> How to deal with the big pic and small pic in the same ImageView

We don't control the images, you do. I'm not sure what you would expect here, Picasso is just doing what you tell it. If the images are smaller you could use smaller ImageViews I suppose.

> can scale it base on the device screen resolution

`.fit()` will scale to the target `ImageView`s measured size.
