### ISSUE TITLE
Using Picasso with HttpUrlConnection and Osmdroid caches tiles as images

### ISSUE THREAD

**Issue by InI4** [square/picasso#1210]
I wonder if it'd be possible for Picasso not to make all HttpUrlConnections on the device use the Picasso cache? No, I haven't found an corresponding HttpUrlConnection API. I just wanted to keep my APK as lean as possible and now it seems like I need OkHttp also?!

**Comment by JakeWharton** [comment]
You can use the [`NetworkPolicy`][1] which can be specified by calling `networkPolicy` in the request chain. If you don't want to use cache for a request specify both `NO_CACHE` and `NO_STORE`.

 [1]: https://square.github.io/picasso/2.x/picasso/com/squareup/picasso/NetworkPolicy.html

**Comment by InI4** [comment]
Well, of course I want to use Picassos cool caching! 

Problem is, that I use HttpUrlConnections for other stuff, like osmdroid and rest services. Getting the latter stuff in the "picasso-cache" folder both, wastes storage and interferes with Picassos cache performance.

**Comment by JakeWharton** [comment]
Unfortunately the response cache is global for the process when using HttpURLConnection. If you use OkHttp just for Picasso (or for both, really), then they will not share a response cache unless you explicitly use the same OkHttpClient instance (which is not the default behavior).
