### ISSUE TITLE
CollapsingToolbarLayout setBackground

### ISSUE THREAD

**Issue by laurent512** [square/picasso#1213]
Hi !

First I would like to thank you cause your library save me a lot of time.

But i'm confronted to a problem now, I would like to change the background of my collapsingtoolbarLayout.

The problem is I have to use this : collapsingToolbarLayout.setBackground(Drawable drawable);

Sadly I have no idea how to do that since previously I have always used it like that : Picasso.with(mContext).load(subCategoryItem.getThumbnail())
                .error(R.drawable.placeholder)
                .placeholder(R.drawable.placeholder)
                .into(viewHolder.thumbnail);

Thanks for your help :)

**Comment by JakeWharton** [comment]
Create a Target that sets it and pass that to .into()

**Comment by laurent512** [comment]
I saw that kind of answer of I have no idea how to create that target :/

Sorry, i'm a newbie in the android world :'(

**Comment by JakeWharton** [comment]
Please ask on StackOverflow with the 'picasso' tag then. This tracker is
for bugs and feature requests, and is far from ideal as a support forum.
