### ISSUE TITLE
about premultiplied (API<=17) canvas.drawBitmap() Err

### ISSUE THREAD

**Issue by xperad** [square/picasso#1214]
target = new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom loadedFrom) {
                  canvas.drawBitmap(bitmap, a, b, null);  // NullPointerException!

●Conditions
 : tested on Android API 17 Device.
 : compileSdkVersion 23
 : minSdkVersion 17
 : targetSdkVersion 21

Becuz, in android.graphic.Bitmap Source, there is 「premultiplied」boolean field in KitKat version.
but API17 has no the field. how can I solve this problem?

**Comment by JakeWharton** [comment]
From your description of the problem, this has nothing to do with Picasso but your use of the Canvas API. Please direct questions about the Android APIs and their usage to StackOverflow or the Android developers Google Group.
