### ISSUE TITLE
Listview doesn't show images or crashes on high quality images

### ISSUE THREAD

**Issue by AndroidSuperMan** [square/picasso#1215]
It's used to work before 4.44+.  Now the Listview either doesn't show any items or crashes on high quality images.  I've been waiting for the fix for like age, but the milestone has been stuck at 69% for a year!   I very like your library, so please help you and help us.  If you are planning to abandon your library, please say so.  Thank you!

**Comment by JakeWharton** [comment]
This issue does not describe the underlying problem or a way to reproduce it and even alludes to the fact that there might be an existing issue for it already. Closing as not actionable.

**Comment by AndroidSuperMan** [comment]
Well. it does if you try to load the high quality images with your library on android 4.44 yourself.
