### ISSUE TITLE
Picasso fit() does not work in ImageSwitcher

### ISSUE THREAD

**Issue by PatrickMA** [square/picasso#1217]
If I want to `.fit()` a image in an ImageView in my custom ViewSwitcher but it will not get displayed. If I remove it, it works perfectly.

My ImageSwitcher:

    public class ImageSwitcher extends ViewSwitcher {
        public ImageSwitcher(Context context) {
            super(context);
        }
    
        public ImageSwitcher(Context context, AttributeSet attrs) {
            super(context, attrs);
        }
    
        public void setImageSource(String url) {
            ImageView image = (ImageView) this.getNextView();
            PicassoUtils.getPicassoWithBasicAuthorizationFrom(user, getContext())
                    .load(url)
                    .noFade()
                    .fit()
                    .into(image, new Callback() {
                        @Override
                        public void onSuccess() {
                            showNext();
                        }
    
                        @Override
                        public void onError() {
    
                        }
                    });
        }
    }

This is my ViewSwitcher factory:

    imageSwitcher.setFactory(new ViewSwitcher.ViewFactory() {
            public View makeView() {
                ImageView imageView = new ImageView(mActivity);
                imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
                imageView.setLayoutParams(
                        new FrameLayout.LayoutParams(
                                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
                        )
                );
                return imageView;
            }
        });

This is my PicassoUtils method:

    public static Picasso getPicassoWithBasicAuthorizationFrom(final User user, Context context) {
        OkHttpClient picassoClient = new OkHttpClient();
    
        picassoClient.interceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request newRequest = chain.request().newBuilder()
                        .addHeader("Authorization", "Basic " + user.getBasicAuthString())
                        .build();
                return chain.proceed(newRequest);
            }
        });
    
        picassoClient.setCache(new Cache(context.getCacheDir(), Integer.MAX_VALUE));
        return new Picasso.Builder(context).downloader(new OkHttpDownloader(picassoClient)).build();
    }

**Comment by PatrickMA** [comment]
I've found out that the ImageView's height and width in my ImageSwitcher equals 0. Maybe the ImageView has not been measured at this point?

Another Info: I prepare the ImageSwitcher first and add it to a FrameLayout with `addView()`. 
This is because I have another views (e.g. a ViewSwitcher with a TextView) which must be over the ImageSwitcher. When everything is prepared the FrameLayout will be added to the View.

**Comment by PatrickMA** [comment]
> Maybe the ImageView has not been measured at this point?

Yeah that was the cause. Now I'm waiting until the first ImageView has been measured:

    imageSwitcher.getChildAt(0).getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                // set first image
                imageSwitcher.setImageSource(slideshow.getSlides().get(0).getImageUri());
            }
        });

If I set a breakpoint in `onGlobalLayout()` I can see that the first ImageView in ViewSwitcher has been measured. 

But if i make the same (`addOnGlobalLayoutListener(...)`) on the 2nd ImageView the view doesn't get measured even the breakpoint gets hit in `onGlobalLayout()`.

I think because the 2nd ImageView is `GONE` in the ImageSwitcher..
But how to solve that the 2nd ImaveView gets also measured?

**Comment by PatrickMA** [comment]
Okay .... I've found out why. The ImageView is `GONE`. And then ... of course ... 
Picasso's waiting time until it's measured is infinity ....

I could solve it by adding `image.setVisibility(View.VISIBLE)`

**Comment by JakeWharton** [comment]
Glad you solved it!
