### ISSUE TITLE
Can't load images from Instagram media url

### ISSUE THREAD

**Issue by nima-ahmadi** [square/picasso#1220]
I want to load images from Instagram media url like :
`https://instagram.com/p/7-6FIJjMym/media/`

The url returns a `HTTP/1.1 302 FOUND` and a location header for redirection like:
`https://scontent.cdninstagram.com/hphotos-xpt1/t51.2885-15/s320x320/e35/1530612_903806373047604_222778181_n.jpg`

Here is my code:
`Picasso.with(MainActivity.this).load(url).into((ImageView)findViewById(R.id.imageView));`

Here is my log:
`12-01 10:40:33.134 18439-18439/ D/Picasso: Main        created      [R0] Request{https://instagram.com/p/7-6FIJjMym/media/}`
`12-01 10:40:33.139 18439-18542/ D/Picasso: Dispatcher  enqueued     [R0]+5ms `
`12-01 10:40:33.142 18439-18544/ D/Picasso: Hunter      executing    [R0]+8ms `

It won't load the image.

**Comment by JakeWharton** [comment]
Android's built-in `HttpURLConnection` does not follow 302 redirects. There's already an issue tracking that #1191. You can also add OkHttp to your project which will automatically follow redirects, though.

(This was also posted to SO: http://stackoverflow.com/q/34015000/132047)

**Comment by nima-ahmadi** [comment]
I forgot to mention that I've already added OkHttp to my dependency :
    `    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp:2.6.0'`
Still the image won't show up. There is a potential solution here:
http://stackoverflow.com/questions/23562794/doesnt-picasso-support-to-download-images-which-uses-https-protocol/26398617#26398617
