### ISSUE TITLE
In the millet mobile phone I have a local image is in the sd card in the dark path, but Picasso can't load it

### ISSUE THREAD

**Issue by pxfile** [square/picasso#1222]

**Comment by JakeWharton** [comment]
There is not enough information here to make this report actionable. Do you have permission? How are you loading the image? Example image? What is logged when debug logs are turned on? If you attach an error handler is an exception passed to it from loading the image?

But beyond this, your are asking a usage question which is more appropriate for StackOverflow. If there's a concrete bug here that can be demonstrated we can re-open the issue.
