### ISSUE TITLE
Picasso doesn't load never invoke callback

### ISSUE THREAD

**Issue by 278956952** [square/picasso#1226]
Hi 
Picasso doesn't load images and never invoke callback no matter onSuccess or onError? The code like this:

  Picasso.with(context).load(TextUtils.isEmpty(couponInfo.getImage()) ? null : couponInfo.getImage())
                        .config(WQCMApplication.getBitmapConfig())
                        .into(imgCoupon, new Callback() {
                            @Override
                            public void onSuccess() {
                                imgCoupon.setDrawingCacheEnabled(true);
                                Bitmap downBitmap = imgCoupon.getDrawingCache();
                                Bitmap bitmap = ImageTools.grey(downBitmap);
                                imgCoupon.setImageBitmap(bitmap);
                                imgCoupon.destroyDrawingCache();
                                Log.e("img", "imgloadScuesss");
                            }

                            @Override
                            public void onError() {
                                Picasso.with(context).load(R.drawable.ic_img_load_defult).into(imgCoupon);
                                Log.e("img","imgload");
                            }
                        });

Thank you very much!

**Comment by JakeWharton** [comment]
What URL are you loading? Is an error passed to the error handler on the `Picasso.Builder`?

**Comment by 278956952** [comment]
Hi,the image url is null.

**Comment by JakeWharton** [comment]
This is expected behavior. There was no image to load so it can neither be a success nor failure. If you need to run code in this case you should add your own `null` check and either call the callback yourself or just run whatever code directly.

**Comment by 278956952** [comment]
Thank you very much! get it!

**Comment by 278956952** [comment]
Hi，Is the callback  meaning that the picture has download ok and put into the imageview?

**Comment by JakeWharton** [comment]
Yes
