### ISSUE TITLE
Fails to download url

### ISSUE THREAD

**Issue by j-garin** [square/picasso#1229]
Hi.

I'm trying to make Picasso library work and it doesn't seem to load any images I've been trying to feed it.
I have only One view in my layout - that is ImageView. Here's my activity code:

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ImageView iv = (ImageView) findViewById(R.id.iv);

        Picasso.with(this).load("http://www.ufunk.net/wp-content/uploads/2014/10/sacha-kalis-bahamas-girl-14.jpg")
                .into(iv, new Callback() {
                    @Override
                    public void onSuccess() {
                        Log.d("picasso", "success!");
                    }

                    @Override
                    public void onError() {
                        Log.d("picasso", "error!");
                    }
                });
    }
}

Logs show "error!" message all the time. The image didn't load even once.
Picasso library 2.5.2. Android studio version 1.5.
Am I missing something?

**Comment by jeprojects** [comment]
Same problem here.
