### ISSUE TITLE
Picasso load big image bug

### ISSUE THREAD

**Issue by caixuejian** [square/picasso#1236]
Picasso.with(this).load(mMediaTransmission.getPictureFilePath()).resize(0, 400).into(new Target() {
                @Override
                public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                    mCropView.setBackgroundBitmap(bitmap);
                }

                @Override
                public void onBitmapFailed(Drawable errorDrawable) {
                }

                @Override
                public void onPrepareLoad(Drawable placeHolderDrawable) {

                }
            });
if the pictureFile is large image, picasso will never load success

**Comment by caixuejian** [comment]
I think the reason may be that I found in the source the function resize don't work when the Target is not ImageView, how can I fix it ?

**Comment by JakeWharton** [comment]
> the function resize don't work when the Target is not ImageView

This is false.

What exception is passed to the exception handler on `Picasso.Builder` when the image is loaded?

**Comment by caixuejian** [comment]
@JakeWharton  no exception !  maybe the time of the Picasso load picture file is too long ！ Glide work well!

**Comment by JakeWharton** [comment]
Either the `onBitmapLoaded` is called or an exception is passed to the exception listener when `onBitmapFailed` is called.

**Comment by caixuejian** [comment]
I wait two minutes !  either the onBitmapLoaded is called or an exception is passed to the exception listener when onBitmapFailed is called. but when the picture file is small size , It will load quickly!

**Comment by caixuejian** [comment]
now six minutes ! the Picasso is still loading

**Comment by caixuejian** [comment]
Image size 4128*2322=9.6MP  file size 3.28MB

**Comment by JakeWharton** [comment]
The image is too large to be loaded into an OpenGL texture. If you look in the logs you'll see that Skia logs this fact.

Dupe #754.
