### ISSUE TITLE
Is picasso automatically removes unused images from picasso-cache directory or we have to manually call Picasso.with(getActivity()).invalidate(file);  to remove unused cached image from cache directory?

### ISSUE THREAD

**Issue by kiranboghra** [square/picasso#1239]

**Comment by JakeWharton** [comment]
Picasso does not write images to disk, that is the HTTP client it uses. But yes, the HTTP client uses an LRU to clean out old images that are not used. 

And calling `invalidate` does not actually interact with images stored in the HTTP client's disk cache, only Picasso's memory cache.
