### ISSUE TITLE
Picasso not delete cache images

### ISSUE THREAD

**Issue by jitendraramoliya** [square/picasso#1241]
Picasso Doesn't cache image from folder 'picasso-cache'. I have checked in data/data/packagename/cache/picasso-cache folder. I think Invalidate(url) only change in journal key file but dont delete image from cache folder. Can I get Cache path from image url? So I can delete cache file manually.  Looking forward to your answer.................

**Comment by jonan** [comment]
This has been recently answered here: https://github.com/square/picasso/issues/1239#issuecomment-166936878

**Comment by JakeWharton** [comment]
See the linked comment.
