### ISSUE TITLE
picasso loading altered image

### ISSUE THREAD

**Issue by jam0cam** [square/picasso#1243]
The easiest way to explain this is to look at the screenshot attached:
![shoe](https://cloud.githubusercontent.com/assets/869467/12004334/cc0ba46e-ab05-11e5-915a-b215a5acdb97.png)

Compare that image with the image at this URL:
http://www.6pm.com/images/z/3/4/8/8/1/4/3488140-p-MULTIVIEW.jpg

Notice that the image Picasso loads has a bunch of black lines in the upper right corner. Do you know why this is the case? 

The image is being loaded as so:

```
        Picasso.with(this)
                .load(mUrl)
                .into(mImageView1);
```

**Comment by JakeWharton** [comment]
Picasso doesn't scale things, it just asks Android to do it for us. What
you are seeing is the result of Androids Bitmap scaling and filtering
pipeline. There isn't a lot of control over it.

**Comment by jam0cam** [comment]
thank you
