### ISSUE TITLE
Memory leak in picasso 2.5.2?

### ISSUE THREAD

**Issue by Kyba1985** [square/picasso#1247]
Hi,
I'm using Picasso in a project for my company. I load images of many articles in differents recyclerview. Every recyclerview is inside a fragment in viewpager. I had an out of memory error when scroll down many recyclerview. I use gradle memory tool for investigation. In the snapshot of memory heap i see a lot of finalizerreference. The memory heap grows and after load about 100 / 150 images the app crash. I think that the leak is not in my code, because if i switch to volley library the out of memory error disappears. The GC with volley can free the space in heap, with Gradle can't. In my code i use these line of code to load the images: 

double wD = holder.rlNewsRowContainer.getWidth() * 0.8;
int w = (int) wD;
int h = CodeUtils.convertDp2px(180, mContext);
instance.load(CodeUtils.createUrlImage(Constants.VIGNETTA, item.getId()) + item.getUrlImage()).resize(w, h).networkPolicy(NetworkPolicy.NO_CACHE).into(holder.newsImage);
                        

With this line the out of memory doesn't appear:
VolleyUtils.loadNetworkImage(CodeUtils.createUrlImage(Constants.VIGNETTA, item.getId()) + item.getUrlImage(), holder.newsImage);

Any idea for this behaviour? Do i need some particular settings to do in the builder of picasso?
Thanks for support.

**Comment by JakeWharton** [comment]
Please provide a sample that demonstrates the problem.

**Comment by Kyba1985** [comment]
Hi, after further investigation and read another thread on picasso issue, i found that the problem is not caused from picasso, but it's caused by the viewpager. After changed the fragment adapter with another implementation that removes the fragment with a transaction, the issue is disappeared. Thanks anyway.

**Comment by SagarPanwala** [comment]
@Kyba1985 : Can you please provide me the solution? I'm also facing the same issue and stuck on it and also is there any way to free up space in listview when user scrolls down like 100 images free up first 50 images. Currently, I'm not sure about behaviour, but when I scroll downs it increases heap size.

**Comment by yuruxuan** [comment]
@Kyba1985 I also meet same issue when I use viewpager + Fragement + recyclerview. It look like more image data which in memory not relase, I don' t know the right use. Can you provide a simple demo?
My E-mail is 544324974@qq.com  .Thanks a lot
