### ISSUE TITLE
When will new picasso version release? Since okhttp has release 3.0 version which has a lot changes

### ISSUE THREAD

**Issue by vforandroid** [square/picasso#1254]
My project has retrofit and picasso, and I update retrofit to the latest version which include okhttp 3, but picasso still is using 2.  So I get some trouble about package name.
Is there some schedule to release new version? I like official version :)

**Comment by JakeWharton** [comment]
You can use https://github.com/JakeWharton/picasso2-okhttp3-downloader for now. We don't have any idea when a next release will be.

**Comment by UglyTroLL** [comment]
@JakeWharton Is there any plans for merging the fix for the 'MarkableInputStream cannot reset' issue? I saw there are few PRs there but never got merged back.
