### ISSUE TITLE
After Updating okhttp to okhttp3 the OkHttpDownloader wont work for Picasso

### ISSUE THREAD

**Issue by ArslanAli7** [square/picasso#1256]
Hello @JakeWharton  i have upgraded my project to okhttp3 using     
compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'
,now for image downloading i am using picasso 2.5.2, but for all of the sudden okhttp Downloader is not recognizable by picasso any more, do i need to upgrade picasso library as well in order for it to work with okhttp3,currently i am using gradle build system and do not know much about how to add snapshot to your project,maybe you can help me out here,this is the exception i am getting :
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/OkHttpClient;
                                                                      at com.squareup.picasso.OkHttpDownloader.defaultOkHttpClient(OkHttpDownloader.java:31)
                                                                      at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:76)
                                                                      at utils.Global.onCreate(Global.java:33)

**Comment by JakeWharton** [comment]
You can either use https://github.com/JakeWharton/picasso2-okhttp3-downloader, the latest SNAPSHOT built from `master`, or just wait until the next release. I would recommend using my standalone `Downloader` for now, though.

**Comment by JakeWharton** [comment]
The Picasso upgrade to OkHttp 3 was #1251.

**Comment by ArslanAli7** [comment]
thanks a lot mate,for now, i have integrated the latest snapshot and will update the code with the next release.

**Comment by iman2420** [comment]
There is a [jar version ](http://central.maven.org/maven2/com/jakewharton/picasso/picasso2-okhttp3-downloader/1.0.1/picasso2-okhttp3-downloader-1.0.1.jar) for this artifact

**Comment by zenith22** [comment]
I am facing this issue on Android 4.4 only, others Android 5+ are working fine.
My server has disabled the support for TLS 1.1 and below, it only supports TLS 1.2 now.
For Android 4.4 i have made the fix as given [here](https://stackoverflow.com/a/42181470).

@JakeWharton 
Is the issue related to this? 
Could you please confirm.

**Comment by pavithra19** [comment]
@zenith22 I tried the solution using the link in your comment. but we are not able to add headers in that solution. Is there any alternative way?
