### ISSUE TITLE
how to add cookie header with picasso?

### ISSUE THREAD

**Issue by kkwsl** [square/picasso#1259]
OkHttpClient tmp = client.clone();
tmp.networkInterceptors().add(new Interceptor() {
			@Override
			public Response intercept(Chain chain) throws IOException {
				Request request = chain.request().newBuilder().addHeader("Cookie", mCookieStr).build();
				return chain.proceed(request);
			}
		});
mPicasso = new Picasso.Builder(mContext).downloader(new OkHttpDownloader(tmp)).build();

i use these code,but not work

**Comment by guowang1102** [comment]
I also encountered this problem, is looking for solutions

**Comment by kkwsl** [comment]
finally i find maybe sth wrong with my url,  but the url can display on the web

**Comment by guowang1102** [comment]
this is my blog http://blog.csdn.net/guowang_wei/article/details/50536987 .
Code is very simple














At 2016-01-21 09:06:29, "kkwsl" <notifications@github.com> wrote:


finally i find maybe sth wrong with my url, but the url can display on the web

**Comment by JakeWharton** [comment]
For `UrlConnectionDownloader` you can override `load(Uri)`, call `super`, and add a header to the returned `HttpURLConnection`.

For `OkHttpDownloader` and `OkHttp3Downloader` you need can add an interceptor to add the header or configure the `OkHttpClient` to use cookies. See OkHttp's wiki and javadoc for instructions on how to do that.
