### ISSUE TITLE
java.lang.NoClassDefFoundError: com.squareup.picasso.Picasso

### ISSUE THREAD

**Issue by parcool** [square/picasso#1264]
IDE:android studio 2.0 preview。gradle plugin：2.0.0-alpha3
I import a library named 'android image slider' and it compile 'picasso',but it get a runtime error,i asked at that library issues,at now,no response for that issue,so i paste here!

I use the code like example： 
SliderLayout sliderShow = (SliderLayout) mainActivity.findViewById(R.id.slider);
TextSliderView textSliderView = new TextSliderView(mainActivity);
textSliderView
.description("Game of Thrones")
.image("http://images.boomsbeat.com/data/images/full/19640/game-of-thrones-season-4-jpg.jpg");

    sliderShow.addSlider(textSliderView);

this runtime error caused:
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: java.lang.NoClassDefFoundError: com.squareup.picasso.Picasso
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.SliderTypes.BaseSliderView.bindEventAndShow(BaseSliderView.java:210)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.SliderTypes.TextSliderView.getView(TextSliderView.java:25)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:81)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:998)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:930)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.daimajia.slider.library.Tricks.ViewPagerEx.onMeasure(ViewPagerEx.java:1453)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.View.measure(View.java:16529)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1973)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1170)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1352)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1057)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5666)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.Choreographer.doCallbacks(Choreographer.java:574)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.Choreographer.doFrame(Choreographer.java:544)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.os.Handler.handleCallback(Handler.java:733)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.os.Handler.dispatchMessage(Handler.java:95)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.os.Looper.loop(Looper.java:136)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at android.app.ActivityThread.main(ActivityThread.java:5072)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at java.lang.reflect.Method.invokeNative(Native Method)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at java.lang.reflect.Method.invoke(Method.java:515)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
01-13 18:41:51.947 31958-31958/com.gc.parcool W/System.err: at dalvik.system.NativeStart.main(Native Method)

I searched in google,but i do not the resolve my error by this 3 solutions:
1、 clean and rebulid
2、-keep class com.squareup.picasso.** { *; }
3、change the gradle plugin version to 1.5.0

**Comment by JakeWharton** [comment]
This is a local configuration problem and not something wrong with Picasso. Your best bet would be to ask on a community like StackOverflow with the 'picasso' tag and any other information you can provide. Since it's not a feature request or bug report there's no action to take on our part, and there's simply not enough information to know what's failing.

**Comment by parcool** [comment]
thanks,but i don't fix my project yet.thanks a lot for your replay!

**Comment by omidraha** [comment]
@parcool I have the same issue, do you find a solution for it?
