### ISSUE TITLE
Compatibility issues with picasso 2.5.2 and okhttp 3 

### ISSUE THREAD

**Issue by AndFChat-Pandora** [square/picasso#1265]
Using OkHttpDownloader does not work when okhttp3 is being used. OkHttp3Downloader does not exist in picasso 2.5.2, so the two will not work together by default.

**Comment by JakeWharton** [comment]
Correct. This is already fixed on master. See #1256.

**Comment by brsengar** [comment]
I couldn't see OkHttp3Downloader in the release 2.5.2. Is there any Picasso release after this?

**Comment by JakeWharton** [comment]
No
