### ISSUE TITLE
java.lang.NoClassDefFoundError: com.squareup.picasso.Utils when loading image

### ISSUE THREAD

**Issue by noxevolution** [square/picasso#1271]
Hi, I am using Picasso for quite a while now, I had encountered a weird problem today..
I simply load an image url to an imageview with this code,

Picasso.with(_context)
                .load(groupDeatils.getThumbnail()).transform(new CircleTransform())
                .into(group_pic);

after building the project when i run and go to the page i am getting this error,

java.lang.NoClassDefFoundError: com.squareup.picasso.Utils

please any help would be appreciated!!!!

**Comment by noxevolution** [comment]
Sorry, It was not the problem of picasso, seems like it was a multidex error. solved it by adding these 2 lines,
dexOptions {
        javaMaxHeapSize "4g" 
        preDexLibraries = false
}

Thanks for this awesome library!!!!!

**Comment by Reponic** [comment]
Heet, where did you add those lines?

**Comment by noxevolution** [comment]
You have to add it it on app gradle file.....
