### ISSUE TITLE
Cache original image after transformation

### ISSUE THREAD

**Issue by kuno** [square/picasso#1272]
In our app, one image that download from a url might  be using in different places. In some places, it required to do some transformation to the image before showing to the user, others don't.

The problem is that once a transformation been done, everywhere else only can see the transformed  image, no the original one.

I knew one solution is disable cache totally for this image. But what if I still like to have caching for this image.

Is this possible with picasso ?

**Comment by JakeWharton** [comment]
> The problem is that once a transformation been done, everywhere else only can see the transformed image, no the original one.

This is not true.

The transformed image is cached, yes, but that image is only served from the cache to requests which have the same transformations. If you request an image with different transformations the original will be loaded from the disk cache.
