### ISSUE TITLE
How to clear Particular Picasso Image cache in android

### ISSUE THREAD

**Issue by fusionraja** [square/picasso#1273]
I am loading image using picasso. In this image, i drawing the paint, after i paint and save the image, but cache image not displayed that drawing line but full image display with drawing lines. But i close the app and again open the app, it cache image display with draw line.

Note: I Load image from sdcard, not download from server
While i clear your cache folder picasso-cache, it not working. Please suggest me the solution

**Comment by JakeWharton** [comment]
You need to call `invalidate` when you save with the image and pass the same path that you use to `load`.

**Comment by fusionraja** [comment]
@JakeWharton thanks. But everytime it get refresh if i click image in recycle adapter. What i do??

**Comment by parthanjaria** [comment]
@JakeWharton , it is not working, i tried it.

**Comment by parthanjaria** [comment]
Not working for me either
