### ISSUE TITLE
Problem showing drawable shapes

### ISSUE THREAD

**Issue by ch4vi** [square/picasso#1276]
Hi, 

I'm trying to load a drawable like this: 

```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@color/white_alpha"/>
    <size
        android:width="20dp"
        android:height="20dp"/>
</shape>
```

into an ImageView:

```xml
<ImageView
        android:id="@+id/dot_second"
        android:layout_height="10dp"
        android:layout_width="10dp"/>
```

and my Picasso call:

```java
Picasso.with(getContext())
             .load(R.drawable.dot_unselected)
              .into(secondDot);
```

But the shape is never showed and I'm getting this in my LogCat:

```
D/skia: --- SkImageDecoder::Factory returned null
```

I can't find any problem like this, I'm not loading an url and when I put a ```mipmap``` with a .png the image is showed correctly.

I don't know what's happening.

**Comment by JakeWharton** [comment]
Why not just call `secondDot.setImageResource(R.drawable.dot_unselected)`?

**Comment by ch4vi** [comment]
But what about the caching? the shape is being rendered every time that is used

**Comment by Hofferic** [comment]
I'm not sure about shapes, but most drawables are cached by the system when
you first use them. You will have to verify if that applies to shapes as
well but as long as you are just swapping drawables and not manipulating
them you should not need to cache them manually or via picasso.

Try making a button listener that swaps this shape a couple hundred times
or so. Then start the app, wait until everything is loaded, force a  GC,
start allocation tracking and use that button. Then you can easily see if
the system caches shape resources. (Or you could Google it..)

**Comment by ch4vi** [comment]
It's okay then. I just thought that Picasso could work with shapes.
