### ISSUE TITLE
Picasso Load Image Fail with fit()

### ISSUE THREAD

**Issue by evilandeath** [square/picasso#1278]
Using the Picasso fit() to lower image size. 
In sometimes this function will also cause the image not display normally

What I found it that when process image decode, the check out function when processing to reset() step,
the decode byte array large than the default setting "65536", the reset() function went to the exception state, I/O exception, then showing no image.

Is anyone meet this situation before ?

Note : Same image, when I take the fit() setting out, the image display normally.

**Comment by JakeWharton** [comment]
This is being tracked as #364.
