### ISSUE TITLE
Picasso loads image only the first time

### ISSUE THREAD

**Issue by sshanbhag7** [square/picasso#1279]
I have implemented Picasso as follows on onCreate.

Picasso.with(context)
                .load("url")
                        .placeholder(R.drawable.default_propic)
                .fit()
                  .into(profilePic);

The image just gets downloaded the first time u enter the activity and is set in the imageview.
Once you press back and finish the activity and on return even though there is a change of the image on that url the previous image is seen and not the new image. What can be the issue? Please help.

**Comment by JakeWharton** [comment]
Picasso caches images in memory to avoid reloading them. To force it to load every time use `.memoryPolicy(NO_STORE)`.

**Comment by sshanbhag7** [comment]
Thank you so much for the answer. But it worked when I added both
 .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
                .networkPolicy(NetworkPolicy.NO_CACHE)
