### ISSUE TITLE
video thumbnail can not be load by picasso 

### ISSUE THREAD

**Issue by guider** [square/picasso#1281]
video thumbnail can not be load by picasso    but ImageLoader.getInstance().displayImage(uri.toString(),holder.image);

**Comment by JakeWharton** [comment]
Elaborate? What's the code that's loading the image? What behavior do you
see? Are any errors logged?

**Comment by roomtek** [comment]
I use this for video thumbnails with Picasso:
where videoId is a valid "Video.Media._ID"

    picasso.load(ContentUris.withAppendedId(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, videoId)).resize(px, px).centerCrop().into(imageview);

**Comment by technicalbird** [comment]
Its working @roomtek

**Comment by JakeWharton** [comment]
Not enough information to be actionable.
