### ISSUE TITLE
Picasso doesnt load image into ViewPager imageView.

### ISSUE THREAD

**Issue by summers314** [square/picasso#1283]
While using the following code the images are being loaded properly: 
Picasso.with(getActivity().getApplicationContext())
        .load("file:///android_asset/"+filePath)
        .into(mainImage);

But when fit or resize is used, some of the images load and some dont
Picasso.with(getActivity().getApplicationContext())
        .load("file:///android_asset/"+filePath)
        .resize(width, height)    ~or~    fit()
        .centerCrop()
        .into(mainImage);

Its hard to point out the bug, since some images are being loaded and some arn't. Also the error is not consistent with the orientation and is random. (meaning image not being loaded may be Portrait or Landscape).

**Comment by summers314** [comment]
Also, hardcoding the width & height doesnt help either; ie, 

Picasso.with(getActivity().getApplicationContext())
.load("file:///android_asset/"+filePath)
.resize(720, 1180)
.centerCrop()
.into(mainImage);

**Comment by JakeWharton** [comment]
If you enable debug logging and attach an error listener Picasso will tell you what is causing the failure. Closing due to age, but feel free to comment if you find the underlying cause and want us to help investigate.
