### ISSUE TITLE
License odd wording

### ISSUE THREAD

**Issue by digitalbuddha** [square/picasso#1285]
Was looking at the license for Picasso and noticed 
```Copyright [yyyy] [name of copyright owner]```
https://github.com/square/picasso/blob/master/LICENSE.txt#L190

Seems to be that way for Dagger as well.  Is this something that is in repo due to error?  Legal is checking licenses within our app and I wanted to make sure this is the correct one we should eb including.

**Comment by JakeWharton** [comment]
That is the section of the license which tells you how to apply it. Look in the readme for the applied version.
