### ISSUE TITLE
Is it possible to add duration for the Cross Fading between images?

### ISSUE THREAD

**Issue by dterrier** [square/picasso#1286]
I understand that by default there is a cross fading when you want a reload an image, and even is it possible to set 'noFade()' so makes sense to set some duration to the fading in the case that you want to use it.

Actually I not sure if Picasso is only using fade in for incoming images but not fade out for the images to be replaced, so in that case I'm extending my question to if it is possible to enable cross fading (and also set a duration).

Thanks in advance,

Daniel

**Comment by NightlyNexus** [comment]
It is not currently possible to set the duration of the fade in the API.
The fade duration is 200 milliseconds. To get a better understanding, check out [`PicassoDrawable`](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/PicassoDrawable.java). The fade occurs whenever the load is not directly from the Picasso object's Bitmap memory cache (and you don't specify `noFade()` in the `RequestCreator`).

Currently, you would need to use a `Target` and implement your own logic for your case.

**Comment by dterrier** [comment]
Hi @NightlyNexus thanks for replaying. 

I'll check PicassoDrawable, I need to change that because 200 ms is too fast. The only problem that I can see is that Picasso knows when an image is replaced and not refresh it but if I do that manually the image is gonna be refreshed every time also when the image in the server hasn't changed... that makes sense?

**Comment by NightlyNexus** [comment]
No, I don't think I understand what you mean. Picasso's Downloader and Cache don't know about your Target...

**Comment by JakeWharton** [comment]
```java
final AtomicBoolean playTransition = new AtomicBoolean();
Picasso.with(context).load(url).noFade().into(imageView, new Callback() {
  @Override public void onSuccess() {
    if (playTransition.get()) {
      // Fade in imageView.getDrawable();
    }
  }
});
playTransition.set(true);
```

**Comment by NightlyNexus** [comment]
^ Ah, much more clever than using a `Target`. +1.

**Comment by dterrier** [comment]
Yeah that's the problem, if I'm pooling ( every x seconds calling Picasso to update the image ) and I need to change the image only when it's changed, this solution will refresh the image always, and I only need to refresh (and do the animation) when actually the image has changed.

Eg

Pooling (every x seconds) {

Picasso.with(mContext).load(imageUrl).placeholder(R.drawable.image).into(rootView.findViewById(R.id.imgProfile),
                        new Callback()
                        {
                            @Override
                            public void onSuccess()
                            {
                            }

                            @Override
                            public void onError()
                            {
                            }
                        });
}

So this every x seconds change the image unless the image is the same, when the image is changed I need to set the fading a bit longer. 

I think if I do the animation 'manually' doesn't matter if the image has changed... the animation will be executed every time ??

**Comment by dterrier** [comment]
Thanks @JakeWharton 

In that case I can't fade out the exiting image right???

**Comment by NightlyNexus** [comment]
If you are building the `RequestCreator` the same way every time without any invalidation, the Cache hit is going to prevent any network call from executing. You'll just get an immediate call to the Callback.

You can fade out the current image if you wanted to, but this is more of an explanation for StackOverflow.

**Comment by dterrier** [comment]
OK I think I got it, thanks again.
