### ISSUE TITLE
Callback with fit() is not invoked

### ISSUE THREAD

**Issue by MisterRager** [square/picasso#1287]
When `fit` is invoked, the specified `Callback` item is not called on success. Unfortunately, the fix from last time is still in place. I'm still investigating the "why", though.

**Comment by JakeWharton** [comment]
Need heaps of more information here to try and offer any kind of help or insight.

> the fix from last time

Last time?

**Comment by MisterRager** [comment]
[last time](https://github.com/square/picasso/issues/229)

Sorry about the sparse details. I'm hammering it with a debugger right now. Are there special requirements to make `fit` work?

Also, here's the offending code:

```
            File file = attachment.getThumbnailFile(mContext);
            Picasso.with(mContext)
                    .load(file)
                    .fit()
                    .centerCrop()
                    .error(R.drawable.annotation_x)
                    .into(holder.mImageView, new Callback(){
                        @Override
                        public void onSuccess(){
                            holder.mImageView.setVisibility(View.VISIBLE);
                            holder.mProgressBar.setVisibility(View.GONE);
                        }

                        @Override
                        public void onError(){
                            holder.mImageView.setVisibility(View.VISIBLE);
                            holder.mProgressBar.setVisibility(View.GONE);
                        }
                    });
```

**Comment by MisterRager** [comment]
Actually, this looks to be my fault - I think I hid the view before I asked for the image to get fit into it. After I confirm, I'll close the ticket.

**Comment by MisterRager** [comment]
Thanks for the super-fast response, Mr Wharton!

**Comment by MisterRager** [comment]
In case anybody finds it, my workaround was to just grab the size of the element from its LayoutParams:

```
 ViewGroup.LayoutParams imageLayoutParams = holder.mImageView.getLayoutParams();
 Picasso.with(mContext)
                    .load(file)
                    .resize(imageLayoutParams.width, imageLayoutParams.height)
...
```

**Comment by JakeWharton** [comment]
:+1:
