### ISSUE TITLE
I m facing this while loading an image from camera

### ISSUE THREAD

**Issue by antoniomerlin** [square/picasso#1288]
`W/System.err: java.io.IOException: Cannot reset
W/System.err:     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)`

While loading image from gallery working fine but loading image after camera capture causing this exception.

**Comment by JakeWharton** [comment]
This is fixed on master. Please try 2.6.0-SNAPSHOT and report any issues with it.
