### ISSUE TITLE
Too many open files when adding a custom header

### ISSUE THREAD

**Issue by LeeWoo337** [square/picasso#1294]
I've seen the solutions where `Too many open files` is caused by having more than one instance of Picasso, so I've implemented the single instance in my Application class.

`Picasso picasso = Picasso.with(this);`
`Picasso.setSingletonInstance(picasso);`

Now, within my ImageHelper class, there are images that require a custom header.  My problem is I can't create an instance of Picasso with a custom header and avoid the `Too many open files` error.  

Here is some of the code from my ImageHelper.  `Picasso.with(mContext)` is using the singleton instance from the Application class, obviously.

```
if (mContentToken == null || mContentToken.isEmpty()) {
    Picasso.with(mContext)
        .load(imageUrl)
        .error(defaultImageResource)
        .into(imageView);
} else {
    OkHttpClient picassoClient = new OkHttpClient.Builder()
        .addInterceptor(new Interceptor() {
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {
                Request newRequest = chain.request().newBuilder()
                    .addHeader("Authorization", "Bearer " + mContentToken)
                    .build();
                return chain.proceed(newRequest);
            }
    }).build();

    Picasso picasso = new Picasso.Builder(mContext).downloader(new OkHttp3Downloader(picassoClient)).build();
    picasso.load(imageUrl)
        .error(defaultImageResource)
        .into(imageView);
}
```

**Comment by NightlyNexus** [comment]
You can use a mutable OkHttp `Interceptor`. Put the Interceptor into the client.
Then, if some condition is met, add the header to the request in the Interceptor.

**Comment by LeeWoo337** [comment]
Thanks for the response @NightlyNexus. I've attempted to implement this and it doesn't seem to be successful at adding the header.  

This is called within the Application class when it is created.  I understand that mContentTokenInterceptor is null here to begin with and will not work with standard images, but will fix that once I get custom images working.
```
private void initializePicasso() {
		OkHttpClient picassoClient = new OkHttpClient.Builder()
				.addInterceptor(mContentTokenInterceptor).build();
		Picasso picasso = new Picasso.Builder(this).downloader(new OkHttp3Downloader(picassoClient)).build();
		Picasso.setSingletonInstance(picasso);
}
```
Also in my Application class I've added a call to add the custom header:
```
public void addImageContentToken(final String contentToken) {
        mContentTokenInterceptor = new Interceptor() {
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {
                Request newRequest = chain.request().newBuilder()
                        .addHeader("Authorization", "Bearer " + contentToken)
                        .build();
                return chain.proceed(newRequest);
            }
        };
}
```

Then from my ImageHelper class
```
application.addImageContentToken(mContentToken);
Picasso.with(mContext)
                        .load(imageUrl)
                        .error(defaultImageResource)
                        .into(imageView);
```

Is there something I have wrong here or a call I'm forgetting to make?

**Comment by NightlyNexus** [comment]
Uuuuuum, it looks like you are just passing a null Interceptor into the OkHttpClient.

I was saying something like:
```
final class ContentTokenInterceptor implements Interceptor {
  volatile String contentToken = null;

  void setContentToken(String contentToken) {
    this.contentToken = contentToken;
  }

  @Override public okhttp3.Response intercept(Interceptor.Chain chain) throws IOException {
    Request newRequest = chain.request().newBuilder()
        .addHeader("Authorization", "Bearer " + contentToken)
        .build();
    return chain.proceed(newRequest);
  }
}
```
Then, you could update the `contentToken` when you get it by holding the reference to your Interceptor.

Btw, this is probably a discussion better suited for SO. I'd continue over there if you post the question.

**Comment by LeeWoo337** [comment]
Agreed.  Thank you for the help thus far.
