### ISSUE TITLE
Again resize, again:  Cannot reset

### ISSUE THREAD

**Issue by Daard** [square/picasso#1295]
02-12 14:59:21.531 32172-32172/com.company W/System.err: java.io.IOException: Cannot reset
02-12 14:59:21.535 32172-32172/com.company W/System.err:     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
02-12 14:59:21.535 32172-32172/com.company W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
02-12 14:59:21.535 32172-32172/com.company W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
02-12 14:59:21.535 32172-32172/com.company W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
02-12 14:59:21.535 32172-32172/com.company W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
02-12 14:59:21.535 32172-32172/com.company W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-12 14:59:21.535 32172-32172/com.company W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-12 14:59:21.536 32172-32172/com.company W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-12 14:59:21.536 32172-32172/com.company W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-12 14:59:21.536 32172-32172/com.company
 W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

![preview_1000_photo](https://cloud.githubusercontent.com/assets/4972277/13007591/14bee788-d19a-11e5-88b0-ab31912c425b.jpg)

**Comment by JakeWharton** [comment]
Does it happen with 2.6.0-SNAPSHOT?

**Comment by Daard** [comment]
Nope. I have forked 2.6. Works fine. Only in 2.5.2.
12 февр. 2016 г. 19:17 пользователь "Jake Wharton" <notifications@github.com>
написал:
>
> Does it happen with 2.6.0-SNAPSHOT?
>
> On Fri, Feb 12, 2016, 8:06 AM Larion Babych <notifications@github.com>
> wrote:
>
> > 02-12 14:59:21.531 32172-32172/com.company W/System.err:
> > java.io.IOException: Cannot reset
> > 02-12 14:59:21.535 32172-32172/com.company W/System.err: at
> >
com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
> > 02-12 14:59:21.535 32172-32172/com.company W/System.err: at
> > com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
> > 02-12 14:59:21.535 32172-32172/com.company W/System.err: at
> > com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
> > 02-12 14:59:21.535 32172-32172/com.company W/System.err: at
> > com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
> > 02-12 14:59:21.535 32172-32172/com.company W/System.err: at
> > java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
> > 02-12 14:59:21.535 32172-32172/com.company W/System.err: at
> > java.util.concurrent.FutureTask.run(FutureTask.java:237)
> > 02-12 14:59:21.535 32172-32172/com.company W/System.err: at
> >
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> > 02-12 14:59:21.536 32172-32172/com.company W/System.err: at
> >
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> > 02-12 14:59:21.536 32172-32172/com.company W/System.err: at
> > java.lang.Thread.run(Thread.java:818)
> > 02-12 14:59:21.536 32172-32172/com.company
> > W/System.err: at
> > com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
> >
> > [image: preview_1000_photo]
> > <
https://cloud.githubusercontent.com/assets/4972277/13007591/14bee788-d19a-11e5-88b0-ab31912c425b.jpg

**Comment by JakeWharton** [comment]
Great. So it'll be in the next release which we hope to be relatively soon.
