### ISSUE TITLE
Slow loading from disk cache

### ISSUE THREAD

**Issue by hoshi-takanori** [square/picasso#1300]
Hello,
I noticed that loading images from disk cache is slow, because of 200ms BATCH_DELAY in Dispatcher.java.
Can it be removed or decreased, or at least made configurable?

**Comment by Janneman84** [comment]
I agree, loading from disk is often even slower than loading from the network. That can't be right.

Often you can work around it by using fetch() to preload it into memory, but it depends on the situation of course.

**Comment by MazizEsa** [comment]
@JakeWharton, does this issue requires help / contributor?

**Comment by stleusc** [comment]
I implemented a 5 line fix that makes it configurable. Played with number in the range of 20-50 and it is butter smooth.... The developer should be allowed to pick the trade off between perceived speed and overhead.

**Comment by franciscojunior** [comment]
I'm also facing this issue when using Picasso in my application. When loading from the disk, I notice a delay. I know that there may be a reason for the delay, but I think it would help if we could configure it.

@stleusc , would you mind sharing your fix so we can have a look at it? Thanks in advance.

**Comment by stleusc** [comment]
The fix was rather easy. I simply changed the delay from 200 to 50. Since I
was fine with that delay I did not even bother to make this option A
configuration, even though free public release it should be configurable.
Does that help?

**Comment by franciscojunior** [comment]
Yes, it does. Thank you very much for your reply. I also agree it would
help if the official release supported some kind of configuration for this.

I'll create a custom build with this parameter changed and give it a try.

Thank you, Stephan.

Em 09/09/2016 08:31, "Stephan Leuschner" <notifications@github.com>
escreveu:

**Comment by ianmartorell** [comment]
I'm facing this issue as well, but I'm not sure where exactly the delay should be changed. Any pointers highly appreciated!

**Comment by stleusc** [comment]
Dispatcher.java...
search for BATCH_DELAY and change it to 50. Works perfectly for me.

**Comment by ianmartorell** [comment]
Okay, but that file is part of Picasso's source, are you loading the library from source instead of using Gradle?

**Comment by stleusc** [comment]
Yes

**Comment by ianmartorell** [comment]
Alright, thanks!

**Comment by parkgrrr** [comment]
Are there any additional workarounds other than editing the batch delay? I am experiencing this and it is frustrating. It's actually slower loading from the disk than it is from the network on a solid connection.

**Comment by LukeLinXu** [comment]
OMG, almost 3 years, it is not solved with nice api?

**Comment by JakeWharton** [comment]
Batching was removed

**Comment by jlubeck** [comment]
I'm still experiencing a delay when loading from disk. Why could that be if Batching was removed?
