### ISSUE TITLE
picasso how much support  okttp version ?

### ISSUE THREAD

**Issue by dengluoy** [square/picasso#1301]
`    static Downloader createDefaultDownloader(Context context) {
       
        if (SDK_INT >= GINGERBREAD) {
            try {
                Class.forName("com.squareup.okhttp.OkHttpClient");
                return OkHttpLoaderCreator.create(context);
            } catch (ClassNotFoundException ignored) {
            }
        }
        return new UrlConnectionDownloader(context);
    }`

**Comment by JakeWharton** [comment]
All 2.x versions are supported, 3.x support will be in the next version. You can use https://github.com/JakeWharton/picasso2-okhttp3-downloader for now if you need 3.x support.

**Comment by dengluoy** [comment]
Thank you very much !
