### ISSUE TITLE
Placeholder Url

### ISSUE THREAD

**Issue by AlokBansal8** [square/picasso#1304]
In my app, I first load the small versions of pics in some sort of feed. When user clicks on a pic a more detailed version of the pic is loaded in a bigger image view.
As the first version is already downloaded, I want to set the url of small version as placeHolder when loading from the url of bigger version, such that the new bigger image view should show at least the already downloaded version.

**Comment by JakeWharton** [comment]
We have no plans on doing this. You can create concurrent Picasso requests and then use a listener to cancel the first request if the second one finishes first.
