### ISSUE TITLE
fit() is not working in recyclerView with gridLayoutManager

### ISSUE THREAD

**Issue by dannybabbev** [square/picasso#1312]
I have a recyclerView with gridLayoutManager set to 2 spans. 
`mGallery.setLayoutManager(new GridLayoutManager(this, 2));
 mGallery.addItemDecoration(new GridSpacingItemDecoration(2, 20, false));
 mGallery.setAdapter(new GalleryAdapter(this, data));`

I load my images from drawable folder in the Adapter.

`Picasso.with(mContext).load(mDataset.get(position)).fit().into(holder.vImage);`

 Problem is that when I set the image with Picasso and use the _fit()_ method I get no images in my View, whereas if I use _resize()_ everything works fine.
![screenshot_2016-03-09-22-52-35](https://cloud.githubusercontent.com/assets/11413212/13650120/be3c6b1e-e649-11e5-972f-f725ee772519.png)

As strange, as it seems there is a scrollbar, which cannot be scrolled and there are no images.

**Comment by JakeWharton** [comment]
Can you try the 2.6.0-SNAPSHOT?

**Comment by dannybabbev** [comment]
The latest version is 2.5.2

**Comment by dannybabbev** [comment]
I successfully added the 2.6.0-SNAPSHOT version of Picasso. Anyways, the problem still persists.

**Comment by JohnWowUs** [comment]
This might be the same as issue #1291
