### ISSUE TITLE
Path Picasso save image

### ISSUE THREAD

**Issue by alexxsera** [square/picasso#1317]
Hello

I have the need to move in an intent of the photo uri
You can be derived in some way this information in Picasso?

thank you

**Comment by JakeWharton** [comment]
I don't understand the question. You want to read a photo URI from an intent or send an intent with a photo URI?

**Comment by alexxsera** [comment]
Yes, sorry for my bad English!!! I would like to start an intent passing a picasso's photo URI in it... this intent is to an external application (instagram).

Thanks,
Alessandro

**Comment by bo-bda** [comment]
I think you want to get a cached image which you wants to open in new activity, isn't it? If it's true you need any cache photo client.

**Comment by alexxsera** [comment]
Ok, I will make it simpler.... it is possible to get a cached photo local URI? :)

Thanks,
Alessandro

**Comment by alexxsera** [comment]
example instagram intent

String type = "image/*";
String filename = "/myPhoto.jpg";
String mediaPath = Environment.getExternalStorageDirectory() + filename;

createInstagramIntent(type, mediaPath);

private void createInstagramIntent(String type, String mediaPath){

    // Create the new Intent using the 'Send' action.
    Intent share = new Intent(Intent.ACTION_SEND);

    // Set the MIME type
    share.setType(type);

    // Create the URI from the media
    File media = new File(mediaPath);
    Uri uri = Uri.fromFile(media);

    // Add the URI to the Intent.
    share.putExtra(Intent.EXTRA_STREAM, uri);

    // Broadcast the Intent.
    startActivity(Intent.createChooser(share, "Share to"));
}

**Comment by bo-bda** [comment]
save file to disk and then share it any way wherever you want.

**Comment by JakeWharton** [comment]
Unfortunately we don't have any easy way to save an image to disk. You'll have to load and save the `Bitmap` yourself by passing a `Target` instance to `into()` which then compresses it to a file. There's a feature request (#506) for being able to save an image to a file, but there's some limitations in the internal pipeline which prevent it from being added easily.
