### ISSUE TITLE
How can I prefetch a number of images in the starting of the application showing progress?

### ISSUE THREAD

**Issue by burakkilic** [square/picasso#1318]
Hello;

I want to prefetch and cache the files in the starting of my application. I wrote the code in this gist:

[https://gist.github.com/burakkilic/b205ab57ef611c768280](https://gist.github.com/burakkilic/b205ab57ef611c768280)
But images seems not to be cached on the disk. Because if I turn off internet connection, images are not loaded in the views.

How can I solve that?

**Comment by JakeWharton** [comment]
Picasso does not have a disk cache. The HTTP client does disk caching. If the images you are loading do not have the proper HTTP headers to enable caching then they won't be retained by the HTTP client for loading offline. Picasso plays no part in this and has no control over it.
