### ISSUE TITLE
get cached bitmap immediately?

### ISSUE THREAD

**Issue by stefi92** [square/picasso#1320]
Hello, can you please help me with my actual problem? I load images into scrollView and after click, i want to animate fade in and fade out clicked image, but I can't load the image in method onCreate in new Activity immediately, so there's some delay and animation doesn't display correctly.

**Comment by geeksammao** [comment]
@stefi92 Picasso displays images until their size finishes calculating(which is not finished in onCreate),so I think you can delay your animation using view.post(runnable).

**Comment by JakeWharton** [comment]
You can use a callback in your load to trigger the animation when it's loaded. This will happen immediately when the image is cached. There is no way to force an image to load synchronously on the main thread. You'll drop frames and lock up the application.
