### ISSUE TITLE
ViewTreeObserver API is mis-used

### ISSUE THREAD

**Issue by yigit** [square/picasso#1321]
We've received the following bug about RecyclerView and Picasso:
https://code.google.com/p/android/issues/detail?id=191824

After investigation, it turns out that it is an issue related to how ViewTreeObservers work. Basically, two  `view#getViewTreeObserver` calls wont necessarily return the same observer if the View's attach/detach state changes in between. 

When you add an observer to a View while it is detached, you actually add it to an internal tree and the list gets merged into the main ViewTree once the view is attached. Unfortunately, they are NOT detached when the view is detached. 
So there is a chance that the observer will never be removed because you'll keep removing it from the fake one here:
https://github.com/square/picasso/blob/bc6af7a755a30e98be4cf57cb77f36809ddb92ba/picasso/src/main/java/com/squareup/picasso/DeferredRequestCreator.java#L40

Although the behavior in the Framework is not intuitive, there is not much we can do at this point since changing it will mean behavior change and we cannot change existing devices. 

You can work around this issue by adding an attach state listener to the View.

**Comment by JakeWharton** [comment]
Thanks. Does that mean there's no pre-API 12 solution? Or should we recommend users on pre-API 12 use a different pattern for loading images inside a RV?

**Comment by yigit** [comment]
actually pre-12 you'll be (sort of) fine because RV's default item animator does not animate anything (this issue happens due to animations). But there is no guarantee for that. 
RecyclerView provides child attach-detach callbacks for the items, you can advice people to clear state using those callbacks. 
Btw, to be clear the issue is not specific to the RecyclerView.  
Below is a code that reproduces the ViewTreeObserver issue:

        final ViewGroup vg = (ViewGroup) findViewById(R.id.container);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                final View item = getLayoutInflater().inflate(R.layout.item, vg, false);
                item.getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
                    @Override
                    public boolean onPreDraw() {
                        Log.d(TAG, "on pre draw " + System.nanoTime());
                        // this will still be called each time screen draws
                        item.getViewTreeObserver().removeOnPreDrawListener(this);
                        return true;
                    }
                });
                vg.addView(item);
                vg.removeViewAt(0);
            }
        }, 1000);

        return true;
