### ISSUE TITLE
Latest 2.6.0 SNAPSHOT Broken

### ISSUE THREAD

**Issue by eygraber** [square/picasso#1324]
Having a dependency on the latest snapshot of 2.6.0 results in there not being a `com.squareup` package. I created a test project just to make sure. Here's the `build.gradle`:

``` groovy
repositories {
  jcenter()
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

apply plugin: 'com.android.application'

android {
  compileSdkVersion 23
  buildToolsVersion "24.0.0 rc2"

  defaultConfig {
    applicationId "com.test"
    minSdkVersion 15
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
}

dependencies {
  compile 'com.squareup.picasso:picasso:2.6.0-SNAPSHOT'
}
```

**Comment by JakeWharton** [comment]
What's the error?

**Comment by eygraber** [comment]
My bad. It's not a gradle error. If I have this line in my project:

`import com.squareup.picasso.Picasso;`

I get a compiler error saying "Cannot resolve symbol 'squareup'"

I manually downloaded the latest jar from sonatype, and the package structure is correct, with all the class files under `com/squareup/picasso`. I decompiled the class files, and the package statements are all correct.

To be sure I ran `gradlew --refresh-dependencies` and the error still occurred.

**Comment by eygraber** [comment]
Looking at the External Libraries branch under Project view in AS doesn't show Picasso as being part of the project.
![capture](https://cloud.githubusercontent.com/assets/1100381/13968777/f918aa6c-f054-11e5-909a-6602e264da5f.PNG)

**Comment by eygraber** [comment]
Explicitly requesting the SNAPSHOT version from 2/19/2016 works:

`compile 'com.squareup.picasso:picasso:2.6.0-20160219.155404-2'`

**Comment by eygraber** [comment]
@JakeWharton The latest working snapshot has been flushed from Sonatype, and so this issue now has no workaround. I've tested snapshots from multiple libraries and they all work. OkHttp3's snapshot (3.3.0) also no longer works, so I'm assuming something went wrong with your CI. I'll open an issue on OkHttp as well (seems to have more eyeballs ATM).

**Comment by JakeWharton** [comment]
The snapshots for both projects look fine.

**Comment by eygraber** [comment]
They literally both just started working as soon as you commented that.

**Comment by JakeWharton** [comment]
Do you have a proxy or something between you an Sonatype? Seems like
something is causing problems between the two of you.

**Comment by eygraber** [comment]
Not that I know of. I've also tried it on different machines that have no relation logically or geographically. Also [other users seem to have the same issue](https://github.com/square/picasso/issues/1314#issuecomment-200875165)

**Comment by eygraber** [comment]
@JakeWharton After the latest commits were made, snapshot builds are broken again.

**Comment by AllenVork** [comment]
I got the error too:
Error:(44, 13) Failed to resolve: com.squareup.picasso:picasso:2.6.0-20160219.155404-2

**Comment by irfanayaz** [comment]
Any update on the broken snapshot?
