### ISSUE TITLE
download image slow(6M size in 19s)

### ISSUE THREAD

**Issue by chengsheng03061** [square/picasso#1330]
How can I make the download faster? the picasso log is below,

Line 64: 03-25 21:21:38.805: D/Picasso(16494): Main        created      [R24] Request{http://192.168.0.101:9500/download_usbAudioCover?%2Fmnt%2Fsda1%2F%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9+%282%29%2F2.1.14+%E9%9F%B3%E4%B9%90%E6%96%87%E4%BB%B6%E4%B8%AD%E6%9C%89%E5%A4%9A%E4%B8%AA%E4%B8%8D%E5%90%8C%E5%B0%81%E5%A5%97%E5%9B%BE%E7%89%87%2F%E5%87%A4%E8%88%9E%E4%B9%9D%E5%A4%A9%E5%BC%80%E5%9C%BA%E6%9B%B2dj.mp3 resize(144,144) centerInside}
	Line 66: 03-25 21:21:38.806: D/Picasso(16494): Dispatcher  enqueued     [R24]+0ms 
	Line 67: 03-25 21:21:38.806: D/Picasso(16494): Hunter      executing    [R24]+1ms 
	Line 72: 03-25 21:21:41.709: D/Picasso(16494): Hunter      decoded      [R8]+23s 
	Line 73: 03-25 21:21:41.710: D/Picasso(16494): Dispatcher  batched       for completion
	Line 94: 03-25 21:21:57.942: D/Picasso(16494): Hunter      decoded      [R24]+19s 
	Line 95: 03-25 21:21:57.943: D/Picasso(16494): Hunter      transformed  [R24]+19s 
	Line 96: 03-25 21:21:57.944: D/Picasso(16494): Dispatcher  batched      [R24]+19s for completion
	Line 97: 03-25 21:21:58.177: D/Picasso(16494): Main        completed    [R24]+19s from NETWORK
	Line 98: 03-25 21:21:58.178: D/Picasso(16494): Dispatcher  delivered    [R24]+19s 

Thanks for any help!

**Comment by chengsheng03061** [comment]
As a comparison, from disk the log is below,
	Line 110: 03-25 21:29:49.825: D/Picasso(2266): Main        created      [R25] Request{http://192.168.0.101:9500/download_usbAudioCover?%2Fmnt%2Fsda1%2F%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9+%282%29%2F2.1.14+%E9%9F%B3%E4%B9%90%E6%96%87%E4%BB%B6%E4%B8%AD%E6%9C%89%E5%A4%9A%E4%B8%AA%E4%B8%8D%E5%90%8C%E5%B0%81%E5%A5%97%E5%9B%BE%E7%89%87%2F%E5%87%A4%E8%88%9E%E4%B9%9D%E5%A4%A9%E5%BC%80%E5%9C%BA%E6%9B%B2dj.mp3 resize(144,144) centerInside}
	Line 112: 03-25 21:29:49.825: D/Picasso(2266): Dispatcher  enqueued     [R25]+0ms 
	Line 113: 03-25 21:29:49.826: D/Picasso(2266): Hunter      executing    [R25]+1ms 
	Line 180: 03-25 21:29:58.231: D/Picasso(2266): Hunter      decoded      [R25]+8s 
	Line 181: 03-25 21:29:58.232: D/Picasso(2266): Hunter      transformed  [R25]+8s 
	Line 182: 03-25 21:29:58.232: D/Picasso(2266): Dispatcher  batched      [R25]+8s for completion
	Line 199: 03-25 21:29:58.434: D/Picasso(2266): Dispatcher  delivered    [R25]+8s 
	Line 200: 03-25 21:29:58.435: D/Picasso(2266): Main        completed    [R25]+8s from DISK

And for the IOS device(Iphone 5) the time is about 5s/1s, Thanks for your help!

**Comment by JakeWharton** [comment]
Picasso is not responsible for the speed of the network or the speed of the local disk. All it does is ask the HTTP client to download the entire resource and waits for the data.
