### ISSUE TITLE
Image drawable is getting null when using with resize and center

### ISSUE THREAD

**Issue by ashishbhandari** [square/picasso#1333]
I am resizing and cropping by this way:

```
public static Drawable drawableCreator(Context context, Icon item) {
        ImageView imageView = new ImageView(context);
        Picasso.with(context).load("file:///android_asset/" + item.path).resize(72, 72).centerCrop().into(imageView);
        return imageView.getDrawable();
    }
```

In first attempt its giving me the null drawable but when i  passed him the same image then only i was able to get drawable.

If i am trying without resize and centerCrop then its working perfectly.

I am using `compile 'com.squareup.picasso:picasso:2.5.2'`

**Comment by JakeWharton** [comment]
Picasso is asynchronous so you either need to use `get()` or pass a callback to `into` to be notified when it's available.
