### ISSUE TITLE
image don't load from php=id

### ISSUE THREAD

**Issue by scheccia1** [square/picasso#1334]
I have images in a forum but i can't load them... it's a iusse?
the link is as 
http://www.mysite.com/download/file.php?id=19109

**Comment by slymnblgnn** [comment]
Can you give full image link? 

mysite.com isn't working.

**Comment by JakeWharton** [comment]
Please take general usage questions to StackOverflow with the 'picasso' tag. If you can demonstrate that this is a bug in Picasso and can provide reproduction steps, a stacktrace, and/or other information to let us diagnose then feel free to re-file an issue.
