### ISSUE TITLE
Picasso uses too much memory

### ISSUE THREAD

**Issue by kokeroulis** [square/picasso#1338]
Hello,

I am trying to use picasso to load 6 images from my drawable folder. The images are small. There are 6 images and the biggest one is 550x500. I have looked inside the picasso issues and i have seen people that are being able to load images which are 8MP and they only need 30MB.... My application needs 45-50mb in order to load those 6 images...

I am sure that i do something wrong but i don't know what...
Here is my exact code https://gist.github.com/kokeroulis/b0866b868561b53456a9.
And here is my images  

https://drive.google.com/folderview?id=0B2acElIBi8YXQk5XZXhvazdMMWc&usp=sharing

Thank you

**Comment by BrunoVT1992** [comment]
try using this configuration, it will remove the alpha channel of the image but will save you a lot of memory:
Picasso.With(Application.Context).Load(imageUrl).Config(Bitmap.Config.Rgb565).Into(imageView);

**Comment by kokeroulis** [comment]
Sorry for my late response. That seems to make things better. Thank you. So is there something wrong with the images?

**Comment by JakeWharton** [comment]
> from my drawable folder

From `drawable/`? Or from density-specific drawable buckets?

If they are in `drawable/` they will be resized up on higher-density screens to be very large and occupy a lot of memory.

**Comment by kokeroulis** [comment]
@JakeWharton The images where located inside the "res/drawable" folder. After i moved them inside to "res/drawable-nodpi" everything seems fine. Thank you
