### ISSUE TITLE
MediaStore thumbnail requests with resize actually requests the wrong thumbnail

### ISSUE THREAD

**Issue by sclarkson** [square/picasso#1341]
If you make a request for a Uri like `content://media/external/images/thumbnails/3`, it is handled by MediaStoreRequestHandler. If the request has specified a size, the bitmap will first try to be loaded with

`bitmap =
            Images.Thumbnails.getThumbnail(contentResolver, id, picassoKind.androidKind, options);`

where

`long id = parseId(request.uri);`

and

```
public static long parseId(Uri contentUri) {
    String last = contentUri.getLastPathSegment();
    return last == null ? -1 : Long.parseLong(last);
}
```

So, in this example, `getThumbnail` is called with an id of 3.

However, the `getThumbnail` function, the id parameter is the image ID, not the thumbnail ID. This corresponds to the column `MediaStore.Images.Thumbnails.IMAGE_ID`. In my case, the image was actually at `content://media/external/images/media/5505`. Now, on my phone, there was no overlap between the thumbnail IDs and the image IDs, so the `getThumbnail` requests all failed and fell back to just opening a stream with the ContentResolver. However, there could in principle be overlap, resulting in a request for a thumbnail of the wrong image.

I believe this to be related to #985, and possibly #872 (the author here believed their issue was with an android bug, but I think they may have been mistaken).

**Comment by JakeWharton** [comment]
I'm going to dupe this onto #872. Thanks for the investigation!
