### ISSUE TITLE
Picasso showing no data for getSnapshot().dump()

### ISSUE THREAD

**Issue by DhruvSuri** [square/picasso#1342]
Hi,
I have been trying to integrate Picasso in my project but I am not able to see the stats for cache missed and hits.
He are the logs 
===============BEGIN PICASSO STATS ===============
                                                                Memory Cache Stats
                                                                  Max Cache Size: 100
                                                                  Cache Size: 0
                                                                  Cache % Full: 0
                                                                  Cache Hits: 0
                                                                  Cache Misses: 0
                                                                Network Stats
                                                                  Download Count: 0
                                                                  Total Download Size: 0
                                                                  Average Download Size: 0
                                                                Bitmap Stats
                                                                  Total Bitmaps Decoded: 0
                                                                  Total Bitmap Size: 0
                                                                  Total Transformed Bitmaps: 0
                                                                  Total Transformed Bitmap Size: 0
                                                                  Average Bitmap Size: 0
                                                                  Average Transformed Bitmap Size: 0
                                                                ===============END PICASSO STATS ===============
04-03 08:04:12.960  I/Picasso: ===============BEGIN PICASSO STATS ===============
                                                                Memory Cache Stats
                                                                  Max Cache Size: 100
                                                                  Cache Size: 0
                                                                  Cache % Full: 0
                                                                  Cache Hits: 0
                                                                  Cache Misses: 0
                                                                Network Stats
                                                                  Download Count: 0
                                                                  Total Download Size: 0
                                                                  Average Download Size: 0
                                                                Bitmap Stats
                                                                  Total Bitmaps Decoded: 0
                                                                  Total Bitmap Size: 0
                                                                  Total Transformed Bitmaps: 0
                                                                  Total Transformed Bitmap Size: 0
                                                                  Average Bitmap Size: 0
                                                                  Average Transformed Bitmap Size: 0
                                                                ===============END PICASSO STATS ===============

These are always blank./
These are my configurations 
`Picasso picasso = new Picasso.Builder(context)
                .memoryCache(new LruCache(100))
                .build();
        picasso.setIndicatorsEnabled(true);
        picasso.setLoggingEnabled(true);

public void FunctionUsingPicasso(){
    picasso.with(context).load(newsCard.imageUrl).noFade().fit().into(imageView);
            picasso.getSnapshot().dump();
}`

Am i missing something?
Thanks in advance.

**Comment by DhruvSuri** [comment]
``

**Comment by JakeWharton** [comment]
If you made your own `Picasso` instance then you should just call `picasso.load(..)` not `picasso.with(..).load(..)`. Calling `with` looks up the singleton instance and won't actually use your instance to load.

**Comment by JakeWharton** [comment]
Conversely, calling `Picasso.with(..).getSnapshot().dump()` will work for what you are currently doing.

**Comment by DhruvSuri** [comment]
Thanks a lot.
Solved my problem.
