### ISSUE TITLE
¿How to use byte[] in picasso.load()?

### ISSUE THREAD

**Issue by Otrebornet** [square/picasso#1343]
I have a database with a Blob field that stored images and i want to load them in a ImageView but i receive the next error: "Cannot resolve method load(byte[])"
Here is my code:

`public View getView(int position, View convertView, ViewGroup parent) {
    View row = convertView;
    ViewHolder holder = null;
    if (row == null) {
        LayoutInflater inflater = LayoutInflater.from(context);
        row = inflater.inflate(R.layout.imagen_guardada, null);
        holder = new ViewHolder();
        holder.image = (ImageView) row.findViewById(R.id.imagenBase);
        holder.nombreImage = (TextView) row.findViewById(R.id.txtNombreImagen);
        row.setTag(holder);
    } else {
        holder = (ViewHolder) row.getTag();
    }
    Picasso.with(context)
            .load(c.getBlob(0)) //c is a cursor that query to database the images and column 0 is Blob field
            .into(holder.image);
    c.moveToPosition(position);
    holder.nombreImage.setText(c.getString(2));
    return row;
}`

Thanks in advance.

**Comment by JakeWharton** [comment]
This is not currently supported and is unlikely to be supported in the near term.

**Comment by JakeWharton** [comment]
Dupe #1088.
