### ISSUE TITLE
Detecting automatically if it is URL or local path

### ISSUE THREAD

**Issue by miroslavign** [square/picasso#1344]
Instead of everywhere in code where I use:

```java
 if (DateAndStringHelper.isUrl(path))  // "http(s)://"   or "content://"
                Picasso.with(this)
                        .load(path)
                        .into(imageView);
            else {
                File f = new File(path);
                Picasso.with(this)
                        .load(f)
                        .into(imageView);
            }
```
could some kind of a detection be embedded inside Picasso ?

**Comment by JakeWharton** [comment]
If you universally use `Uri` instead of `String` the type is already detected based on the protocol scheme.

**Comment by miroslavign** [comment]
Meaning, again manually serializing/de-serializing, converting back and forth from String-ed db to Uri on like a gazillion places in code...
But I see the point...

**Comment by JakeWharton** [comment]
`Uri` is lazy so it's not going to really cost anything to wrap it around a `String`. Plus it's probably the more correct type to use here. A `String` can represent anything whereas Picasso is built on `Uri` and it uses it for every internal mechanism (like decided how to load).

**Comment by miroslavign** [comment]
I understand.
Tnx Jake, and good job with those libs you guys share !
