### ISSUE TITLE
502 Bad Getway 

### ISSUE THREAD

**Issue by coulddog6** [square/picasso#1345]
Hello. I have something issue when load this image http://cifrosvit.com/images/mod_catalog_prod_11/117026/97290_small.jpg. All images located on that server can't downloaded through Picasso. Exception detailMessage : "502 Bad Gateway".
I use com.squareup.picasso:picasso:2.5.2.
My code:
Picasso.Builder builder = new Picasso.Builder(context)
                    .listener(new Picasso.Listener()
                    {
                        @Override
                        public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception)
                        {
                            exception.printStackTrace();
                        }
                    });
            builder.build().load("http://cifrosvit.com/images/mod_catalog_prod_11/117026/97290_small.jpg")
                    .error(R.drawable.ic_no_image)
                    .into(holder.image);
Please help me find the case of this issue.

**Comment by JakeWharton** [comment]
It's either an actual 502 from the server or the device is offline and the image is not cached.

**Comment by coulddog6** [comment]
JakeWharton I think you not write, because as you can see through postman image from this link loaded correctly and server return code 200. Device online because if i change server address, for example http://cifrosvit.seotm.biz/images/mod_catalog_prod_11/119886/14593343280_cmszoom_height_126.jpeg image loaded correctly. And i think this is not related with cache because both images size about 5KB.

**Comment by JakeWharton** [comment]
Well it isn't Picasso throwing this error, it's the HTTP client that Picasso is asking to load the URL. So really it's one of those two things.

**Comment by coulddog6** [comment]
I will create new project with only that code and try to load this image. And give an answer.

**Comment by coulddog6** [comment]
I deploy test project to repository https://github.com/coulddog6/PicassoTest/blob/master/app/src/main/java/com/example/seotm/picassotest/FullscreenActivity.java
Please check that, it will be very helpful for me. 
That project contains in gradle only picasso library. Exception message is the same.

**Comment by coulddog6** [comment]
JakeWharton I slove this issue. Case is the server change url to mobile version url. And therefore images download from browser correctly and do not loaded from phone. Tnx for your time.

**Comment by JakeWharton** [comment]
Glad to hear it. Thanks.
