### ISSUE TITLE
How to read and understand getSnapshot().dump() ? 

### ISSUE THREAD

**Issue by siripin701** [square/picasso#1348]
My objective is to compare result between using fit().centerCropt() and not using anything while loading imageView. I'm testing this in RecyclerView Adapter (Grid Layout)
========First Test====================
Picasso.with(context)
    .load(imgURL)
    .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
    .networkPolicy(NetworkPolicy.NO_CACHE, NetworkPolicy.NO_STORE)
    .into(holder.ivGrid);

===> First Result

Memory Cache Stats
          Max Cache Size: 57521883
          Cache Size: 12811068
          Cache % Full: 23
          Cache Hits: 101
          Cache Misses: 19
        Network Stats
          Download Count: 32
          Total Download Size: 203448
          Average Download Size: 6357
        Bitmap Stats
          Total Bitmaps Decoded: 45
          Total Bitmap Size: 24948804
          Total Transformed Bitmaps: 8
          Total Transformed Bitmap Size: 12695616
          Average Bitmap Size: 554,417
          Average Transformed Bitmap Size: 295246

========Second Test====================
Picasso.with(context)
    .load(imgURL)
    .fit()
    .centerCrop()
    .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
    .networkPolicy(NetworkPolicy.NO_CACHE, NetworkPolicy.NO_STORE)
    .into(holder.ivGrid);

===> Second Result

Memory Cache Stats
          Max Cache Size: 57521883
          Cache Size: 12811068
          Cache % Full: 23
          Cache Hits: 108
          Cache Misses: 16
        Network Stats
          Download Count: 32
          Total Download Size: 203448
          Average Download Size: 6357
        Bitmap Stats
          Total Bitmaps Decoded: 45
          Total Bitmap Size: 24948804
          Total Transformed Bitmaps: 40
          Total Transformed Bitmap Size: 37081152
          Average Bitmap Size: 554417
          Average Transformed Bitmap Size: 824025

My questions are:
1) Which numbers should I compare?

2) I want to know how much memory the second test help me save.
Which numbers can answer me that?

3) Why "Total Bitmap Size" and "Average Bitmap Size" are still the same in both tests?

4) If I want to know the current memory used by all these images, can I calculate from 
Total Transformed Bitmap Size + (remaining of non transform bitmaps) * Average Bitmap Size
For example, the current memory used in the second test will be
37081152 + (45 - 40)*554417 => 39 M ?
 
5) In conclusion, which test performs better? The first one or the second one?

6) In the second test, how can "Total Transformed Bitmap Size" be bigger than "Total Bitmap Size" ?

**Comment by JakeWharton** [comment]
1. i guess Total Decoded Size would suffice?
2. same as 1
3. because the source images are the same
4. i'm not sure how accurate this is, but it should put you in the ballpark at the very least
5. fit().centerCrop() will be slightly slower (mostly amortized since we stream the data to the decoder anyway), but ultimately you'll end up with less allocated memory.
6. I believe we report the processed bytes here, so you'll see more bytes come across the transformations required to resize the image vs. the non-fit case where the Bitmap is used as-is and not processed at all.
