### ISSUE TITLE
2.6.0 - SNAPSHOT - Failed to resolve

### ISSUE THREAD

**Issue by davidtcdeveloper** [square/picasso#1349]
Hi,

I just configured my gradle to use the snapshot version but I always get an error when I sync the gradle files:
`Failed to resolve: com.squareup.picasso:picasso:2.6.0-SNAPSHOT`

My settings:
```
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
```
```
compile 'com.squareup.picasso:picasso:2.6.0-SNAPSHOT'
```

Did I miss something? Can anybody help me?

**Comment by AllenVork** [comment]
I got the same error.Do you get any solution?

**Comment by davidtcdeveloper** [comment]
@AllenVork No, just downloaded the jar file and included into the project :/

**Comment by joebowbeer** [comment]
It should be declared as a project repository, not a buildscript repository?

```
allprojects {
    repositories {
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}
```

**Comment by rmassaroto** [comment]
joebowbeer comment resolved my issue. Just declared it as a project repository and gradle was able to resolve it. :)
