### ISSUE TITLE
Get error response body?

### ISSUE THREAD

**Issue by liutingdu** [square/picasso#1351]
I use Picasso to retrieve image from a series of web URLs, there are two types of images can be returned:
1. Return a valid image with HTTP code 200
2. Return an error image with HTTP code 404

I'd like to retrieve & show the error image in the ImageView, but couldn't find a way to get the error response body.

I've tried 

```
            new Callback() {
                @Override
                public void onSuccess() {
                }

                @Override
                public void onError() {
                }
            }
```

But there is no argument in `onError()`, then I tried:

```
new Picasso.Listener() {
                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                    exception.printStackTrace();
                }
            }
```

Then I can get the HTTP code from exception but still not able to get the response image body.

I know this can be done by using Volley:

```
            ImageRequest imageRequest = new ImageRequest(url,
                    new Response.Listener<Bitmap>() {
                        @Override
                        public void onResponse(Bitmap bitmap) {
                            imageView.setImageBitmap(bitmap);
                        }
                    }, getWidth(), getHeight(), ImageView.ScaleType.CENTER_CROP, Bitmap.Config.RGB_565,
                    new Response.ErrorListener() {
                        public void onErrorResponse(VolleyError error) {
                            int errorCode = error.networkResponse.statusCode;
                            if(errorCode == 404) {
                                byte[] data = error.networkResponse.data;
                            }
                        }
                    });
```

I wonder is there an equvalent approach in Picasso? I really want to keep using it because it's faster, more lightweighted and animated.

Thanks a lot!

**Comment by JakeWharton** [comment]
We do not provide access to the error response body anywhere. The HTTP code is available from the ErrorListener which you can register with a `Picasso.Builder` if you create your own `Picasso` instance.
