### ISSUE TITLE
https proguard obscurification issues

### ISSUE THREAD

**Issue by vauywaves** [square/picasso#1355]
Hi,
I found an interesting issue upon proguard obscurification.

images with https url doesnt load after i apply proguard obscurification.
http images loads perfectly ok.

i have used the following:
compile 'com.squareup.picasso:picasso:2.5.2'

and following proguard flags:
-keep class com.squareup.picasso.**
-dontwarn com.squareup.picasso.**

also tried explicitly using below library, but https doesnt work with this either.
compile 'com.squareup.okhttp:okhttp:2.4.0'

**Comment by JakeWharton** [comment]
Does the https URL work when you don't ProGuard?

**Comment by vauywaves** [comment]
Hi Jake,

yes https & http both work when its not obscurificated.

after obscurification http works, but https always fails.

this happens "only" when i use the combination of these two.
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp:okhttp:2.4.0'

if i remove dependency of okhttp library, https also works after obscurification.

**Comment by JakeWharton** [comment]
Picasso has no control over http or https. ProGuard is doing something to OkHttp to prevent it from working correctly and without a sample project demonstrating the issue it's going to be impossible for us to help
