### ISSUE TITLE
Set our own time for fade in animation?

### ISSUE THREAD

**Issue by MiralDesai** [square/picasso#1356]
Hey,

Love the library but wondering if this improvement was possible. Could we control the fade in time? It's a bit too abrupt for my needs, but the animation itself is fine. So just adjusting the time might be a good thing to be made available to us. 200ms is a bit too short, and the adding my own custom fade in a `Target()` callback or new `Callback(){}` doesn't solve the issue, because the animation repeats itself when scrolling up and down the list. Something Picasso's stock fade in animation does not do.

Would be nice to hear what others think as well. Personally I think it would be a good addition.

**Comment by dnkoutso** [comment]
@JakeWharton what you think for an API per request for `fadeDuration`?

**Comment by JakeWharton** [comment]
Would be nice to have a pluggable mechanism for this as it would also support #707. Duping this onto #1257.

**Comment by JakeWharton** [comment]
Sorry, duping that onto this.

**Comment by JakeWharton** [comment]
Nope duping onto #743.
