### ISSUE TITLE
the loaded image disappears after 1 sec picasso

### ISSUE THREAD

**Issue by a3adel** [square/picasso#1357]
i'm attaching a view to my screen which contains imageview and uses picasso to load the image from the server it loads fine but after one second it disappears and replaced with the place holder i debugged the code to check if it's recalled with invalid url or any problem before it disappears the function isn't called it just disappears the following is a snippet of my code

```
doSomeThing(){
Picasso.with(activity)
                .load(showImageUrl)
                .fit()
                .centerCrop()
                .placeholder(R.drawable.logo)
                .into(currentShowImage);}
```

and this is how i attach my view i send the activity object to it 
```
`  public void attachMiniPlayer(Activity activity) {
        if (activity != null) {
            updateComponentsReferences(activity);
            doSomeThing();
        }
    }

private void updateComponentsReferences(activity){
       this.activity=activity;
}
```
`

**Comment by JakeWharton** [comment]
The placeholder is only set when you call `into` on `Picasso`, so something is calling that again. Can you provide a standalone sample which demonstrates the problem?
