### ISSUE TITLE
downloaded pdf files also being cached in picasso cache folder

### ISSUE THREAD

**Issue by jaarvis-iqbal** [square/picasso#1365]
I am loading thumbnails of books using picasso library when i download a particular pdf book using ThinDownloadManager(https://github.com/smanikandan14/ThinDownloadManager) in internal storage directory then picasso library make a cache of that pdf file in picasso cache folder so if i delete that book from internal storage directory it still remains in picasso cache and if i download again it loaded from cache which i don't want

**Comment by JakeWharton** [comment]
HttpURLConnection only has a single global cache because it's a global HTTP client. If you want separate ones you'll need to use OkHttp instead.
