### ISSUE TITLE
fit and resize method can not display pictures in Android 5.1

### ISSUE THREAD

**Issue by tianshaokai** [square/picasso#1368]

**Comment by JakeWharton** [comment]
This report is not actionable as-is. In order to make this useful we need an example picture which reproduces the behavior, the exception being thrown/logged, and the device you're testing on.

**Comment by tianshaokai** [comment]
I don‘t found any error log in logcat.    Lenovo 2 A8-50LC Android 5.1 API 22 is my testing device.

**Comment by tianshaokai** [comment]
Loading sd pictures will reappear the problem.
eg:
Picasso.with(context).load("file:///storage/emulated/0/DCIM/Camera/IMG_20160421_142309.jpg").fit().into(imageview);

**Comment by JakeWharton** [comment]
You can pass an error listener by building your own `Picasso` instance using `new Picasso.Builder()`

**Comment by tianshaokai** [comment]
The problem is not a problem？？ Please list an example to solve this problem.

**Comment by tianshaokai** [comment]
I tried the way you said it was still.  Would you help me to solve this probleam.

Picasso.Builder builder = new Picasso.Builder(context);
                    builder.listener(new Picasso.Listener() {
                        @Override
                        public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                            Log.e("Picasso Error", "Errored out, hiding view");
                        }
                    });
                    Picasso pic = builder.build();
                  pic.load("file:///storage/emulated/0/DCIM/Camera/IMG_20160421_142309.jpg").fit().into(bb);

**Comment by JakeWharton** [comment]
Log the exception which is passed to that callback.

**Comment by captain-miao** [comment]
@tianshaokai 
`

        Picasso.Builder builder = new Picasso.Builder(context);
        builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
                Log.e("Picasso Error", uri.toString());
            }
        });
`

**Comment by tianshaokai** [comment]
@captain-miao  你给我的方法也是一样无法显示sd 图片，如果我不用fit 或者 resize方法 在5.1 系统里是可以显示的
Picasso.with(context).load("file:///storage/emulated/0/DCIM/Camera/IMG_20160421_142309.jpg").into(imageview);

在5.1 系统上，只要加了fit 或者 resize 方法就无法显示sd图片了，

**Comment by captain-miao** [comment]
@tianshaokai I just to say:exception.printStackTrace();
I test it:
`fit()-->android:scaleType="fitXY"
resize()-->Resize the image to the specified size`

It's wording on Android 6.0.

**Comment by tianshaokai** [comment]
@captain-miao Can you give me a example to test.

**Comment by captain-miao** [comment]
@tianshaokai 

The code is same.
```
        Picasso.Builder builder = new Picasso.Builder(imageView.getContext());
        builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
                Log.e("Picasso Error", uri.toString());
            }
        });
        Picasso pic = builder.build();
        pic.load("file:///storage/emulated/0/DCIM/Camera/IMG_20160421_142309.jpg")
            .fit()
            .into(imageView);
```

**Comment by tianshaokai** [comment]
@captain-miao  @JakeWharton  I got an error message.

java.io.IOException: Cannot reset
     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
Error: file:///storage/emulated/0/12studay/1461396168437.png exception: java.io.IOException: Cannot reset

**Comment by JakeWharton** [comment]
This is already fixed on master. You can try the 2.6.0-SNAPSHOT version for
a fix.

**Comment by tianshaokai** [comment]
@JakeWharton Thanks

**Comment by rambabupadimi** [comment]
Am getting error in Android 5.1, please help me

E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/picasso/Picasso;

**Comment by SalvatoreT** [comment]
@rambabupadimi, if this is an issue with Picasso, open a new issue and include a code snippet that demonstrates the issue. If you're having an issue using Picasso (which is my guess), I recommend [posting your question/issue to StackOverflow](https://stackoverflow.com/questions/ask?tags=picasso) which gets way more eyeballs.

Either way, this thread isn't the proper place for your question.
