### ISSUE TITLE
resize doesn't work well on some cellphone

### ISSUE THREAD

**Issue by AllenVork** [square/picasso#1372]
When loading large image, I use resize option.But it just works well on some cellphone, others are not.It will show nothing.

**Comment by JakeWharton** [comment]
This is fixed on master and will be released as 2.6.0. You can use 2.6.0-SNAPSHOT for now.

**Comment by AllenVork** [comment]
I've tried  `compile 'com.squareup.picasso:picasso:2.6.0-SNAPSHOT'`，but it's invalid

**Comment by JohnWowUs** [comment]
@AllenVork The snapshots are in the sonatype repository. You'll need to add the line 
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
to your repositories section in your build.gradle file.
