### ISSUE TITLE
compile success,run error

### ISSUE THREAD

**Issue by 908931448** [square/picasso#1373]
I want to clone project to my android studio.compile success,but occur error when running.Error is:'converting bytecode to dex:Cause Dex cannot parse version 52 byte code'

**Comment by martyglaubitz** [comment]
likely javac runs in java8 mode. ensure that the java compiler runs in java 7 mode.
```groovy
// compiler would produce dex incompatible bytecode otherwise
sourceCompatibility = 1.7
targetCompatibility = 1.7
```

**Comment by irfanirawansukirman** [comment]
the problem same with me. i only change setting for JDK version. you should open project setting
FIle_ ->ProjectStructure-> and change version JDK to 1.7. it's work fine for me

**Comment by JakeWharton** [comment]
Picasso build with Maven so it's unlikely to work in Android Studio. If you open the `pom.xml` in IntelliJ IDEA it should work.
