### ISSUE TITLE
how to load bitmap for imageview without url, uri, drawable, asset with this library?

### ISSUE THREAD

**Issue by DoaiNguyen** [square/picasso#1376]

**Comment by JakeWharton** [comment]
You cannot. Those are the only supported places to load from.

**Comment by DoaiNguyen** [comment]
Why? I hope that the new version of the picasso library will support this issue. thank you.

**Comment by JakeWharton** [comment]
Support what? You didn't ask for anything specific, just if there was a way
other than URI or drawable.

**Comment by DoaiNguyen** [comment]
i want to load a bitmap for imageview to avoid OutOfMemoryException

**Comment by JakeWharton** [comment]
If you already have a bitmap the data is already loaded, just call
setImageBitmap on the ImageView

**Comment by DoaiNguyen** [comment]
I know. i have a gridview with many item, if i call setimagebitmap on the imageview, it will be the outofmemoryexcaption.
