### ISSUE TITLE
Inconsistent color reproduction

### ISSUE THREAD

**Issue by DanielJette** [square/picasso#1377]
### Problem

We've recently observed minor variations in the colors in images loaded via Picasso.

### Example

Included below are screencaptures of an image loaded via Picasso. Both thumbnails were loaded on API 21 emulators running at 480x800@240dpi.

On separate host machines (one ubuntu (1) and another mac (2)), the same image yields very, very slight variations in color on some pixels (3):
![image](https://cloud.githubusercontent.com/assets/5921367/15001889/5bd0b26e-1169-11e6-9947-178906039f27.png)

### Source

We are using the following code to load the thumbnail:

```java
Picasso.with(getContext())
                .load(imageUrl)
                .resizeDimen(R.dimen.app_icon_size, R.dimen.app_icon_size)
                .centerCrop()
                .placeholder(res)
                .into(this);
```

The image original image being loaded can be found here: https://cdn.shopify.com/s/files/1/0829/7557/products/280526_main.jpeg?v\u003d1441312168

**Comment by DanielJette** [comment]
I'm wondering if there are any color management settings (ICC color profiles?) being applied or GPU-accelerated operations that may be impacting the determinism of the output.

**Comment by JakeWharton** [comment]
Certainly nothing set by Picasso. Are the configurations of the emulators
the same with regard to screen size and density? Same API level?

My guess would be that it's a change in Android's behavior with regard to
resizing and specifying that resizing should be filtered. All in all,
Picasso itself shouldn't vary in any way and there's no deep control over
decoding or resizing so I'm at a loss as to what is causing it.

**Comment by DanielJette** [comment]
Thanks for the prompt reply @JakeWharton. Your comments helped us focus our investigation on our CI infrastructure and we were able to identify the problem. Our local configuration was set to use x86 emulator images while the CI environment was using x86_64 images. The extra precision on the 64 bit emulator is likely the cause of the variation in color.
