### ISSUE TITLE
Use Picasso, BMP format pictures don't show?

### ISSUE THREAD

**Issue by FDoubleman** [square/picasso#1378]
Hi,
   When I use the Picasso .resize(50,50) .centerCrop() or   .fit()   ,BMP format pictures don't show in imageView. But on the other image format can normal display.  can you help me ?this why?

**Comment by tianshaokai** [comment]
The same problem.[#1371](https://github.com/square/picasso/issues/1371)

**Comment by JakeWharton** [comment]
Great. So this is fixed on `master` and you can try 2.6.0-SNAPSHOT for now until there's a new release.

**Comment by FDoubleman** [comment]
how to I get Picasso 2.6.0-SNAPSHOT.can you tell  me,that detailed steps for get Picasso 2.6.0-SNAPSHOT.  thank you Wharton.
