### ISSUE TITLE
Getting Java.io.closeable Error in Android

### ISSUE THREAD

**Issue by MicroSumari** [square/picasso#1383]
I am getting the following error. While running my program. I am unable to understand the problem. A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

Code

ArrayList<String> selection = new ArrayList<>();
TextView finaltext = null;
    @Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
        finaltext = (TextView)findViewById(R.id.final_result);
        finaltext.setEnabled(false);
}
public void selectItem(View view)
{
    boolean checked = ((CheckBox) view).isChecked();
    switch (view.getId())
    {
        case R.id.fruit_apple:if (checked){selection.add("Apple");}else {selection.remove("Apple");}
        break;
        case R.id.fruit_orange:if (checked){selection.add("Orange");}else {selection.remove("Orange");}
        break;
        case R.id.fruit_grape:if (checked){selection.add("Grapes");}else {selection.remove("Grapes");}
        break;
    }
}

**Comment by JakeWharton** [comment]
That code has no Picasso interaction.
