### ISSUE TITLE
How to load https protocol image with okhttp3?

### ISSUE THREAD

**Issue by Fover23** [square/picasso#1386]
I try to write this code , but OkHttpDownloader is error .

```kotlin

Picasso.Builder(context).downloader(OkHttpDownloader(OkHttpClient())).build()

```

How to load https protocol images ? Change okhttpClient back to 2.x?

**Comment by JakeWharton** [comment]
You can use https://github.com/JakeWharton/picasso2-okhttp3-downloader/ until the next Picasso release.
