### ISSUE TITLE
com.squareup.picasso.Downloader$ResponseException: 403 Forbidden

### ISSUE THREAD

**Issue by WTMahone** [square/picasso#1387]
hi, Jack! I have a problem when I using Picasso. The error log is : com.squareup.picasso.Downloader$ResponseException: 403 Forbidden

why ?

this is my code : 
Bitmap bitmap = Picasso.with(J2WHelper.getInstance().getApplicationContext()).load(uri).placeholder(R.mipmap.head_default).resize(50, 50).get();

com.squareup.picasso.Downloader$ResponseException: 403 Forbidden
05-19 19:08:28.063 28976-29282/? W/System.err:     at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:121)
05-19 19:08:28.063 28976-29282/? W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
05-19 19:08:28.063 28976-29282/? W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
05-19 19:08:28.063 28976-29282/? W/System.err:     at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
05-19 19:08:28.063 28976-29282/? W/System.err:     at com.kemaicrm.kemai.common.customview.combinationAvatar.CircularImageView$1.run(CircularImageView.java:84)
05-19 19:08:28.063 28976-29282/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-19 19:08:28.063 28976-29282/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-19 19:08:28.063 28976-29282/? W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by JakeWharton** [comment]
403 is a server response so you'll need to work it out with the server team or API documentation as to why you cannot access the resource. This isn't a Picasso issue.
