### ISSUE TITLE
google play store SSL warning

### ISSUE THREAD

**Issue by or-dvir** [square/picasso#1393]
hi.
i have published my app on the google play store and im getting a warning from google saying something about using an old and unsecured version of SSL.
the warning refers to this page:
https://support.google.com/faqs/answer/6376725

the thing is in my app i am not doing anything related to SSL.
i read online that it's most probably a third party library thats causing the warning, so i am writing this message to all the third party libraries i am using in my app.

are you using SSL in your library in any way? could it be that your library is the cause for this warning?
if so, when can i expect a new version which uses the latest SSL version?

this is important because as the link above mentions:
"Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL"

thanks

**Comment by JakeWharton** [comment]
No. Picasso just delegates to HttpURLConnection or OkHttp for https traffic.
