### ISSUE TITLE
what's the problem can anybody  help?

### ISSUE THREAD

**Issue by tailanx** [square/picasso#1396]
![4evey0 q p_mx44mex umkh](https://cloud.githubusercontent.com/assets/6790747/15490767/a2c400ba-219d-11e6-81a9-1842088cec2d.png)

**Comment by JakeWharton** [comment]
You used an activity as a tag which will leak it until the request completes. Did you call cancel with that activity instance?

**Comment by tailanx** [comment]
thanks you for you answer , but i load pic is in listview, every item should load  pic  ,how can i solve that?

**Comment by JakeWharton** [comment]
```java
Picasso.with(context).load(url).into(imageView);
```

**Comment by tailanx** [comment]
yes i do  that , my application use listview  ,  when scroll is fast  i set tag,like this
 public void onScrollStateChanged(AbsListView view, int scrollState) {
        Picasso picasso = Picasso.with(context);
        if (scrollState == SCROLL_STATE_IDLE || scrollState == SCROLL_STATE_FLING) {
            picasso.resumeTag(context);
        } else {
            picasso.pauseTag(context);
        }
    }
but i don't konw how to cancel

**Comment by tailanx** [comment]
every item should cancel ?

**Comment by tailanx** [comment]
![0m f2a b6 cu1 7n ra 5 l](https://cloud.githubusercontent.com/assets/6790747/15491147/5cac9ea4-21a0-11e6-8de7-184bf9611f96.png)
like that  ,include head  and item picture

**Comment by tailanx** [comment]
solve that in onDestory() , Picasso.with(this).cancelTag(this)?

**Comment by JakeWharton** [comment]
Yep. That'll do it.

**Comment by tailanx** [comment]
ok  thank you  receiving !!
