### ISSUE TITLE
Image is not loading in android 4.0.0 devices with Picasso

### ISSUE THREAD

**Issue by nageshnallapu** [square/picasso#1399]
I used #SSL certified Url's to load in the imageview.
But in below #4.1.2 versions image is not loading.

**Comment by JakeWharton** [comment]
There is far too little information here to make this an actionable report. Please provide reproduction steps and the exception that's being logged when trying to load.

**Comment by nageshnallapu** [comment]
Problem solved.Previously we used ssl certified url's,now we changed these into normal url's
