### ISSUE TITLE
Unable to load images with .jpeg/.jpg extension.

### ISSUE THREAD

**Issue by jskcse4** [square/picasso#1400]
sample url : `https://beta.receiptmatch.com/admin/webresources/images/no_company_image.jpg`

`Picasso.with(mContext).load("https://beta.receiptmatch.com/admin/webresources/images/no_company_image.jpg").into(itemViewHolder.imgLogo);`

extension with .png working normally. But .jpg not.

**Comment by dnkoutso** [comment]
Attach an error listener to see what the error is.

**Comment by jingbolee** [comment]
same error ,unable to load jpg, and png working normally. 
@jskcse4 you fixed it?

**Comment by jskcse4** [comment]
@jingbolee no... still searching...

**Comment by ugurcmk** [comment]
I'm trying to dowload image from your link and don't get error. I am using Picasso 2.5.2 and Android Studio 2.2 Beta. You can see result by the link. [http://i64.tinypic.com/1086atl.png](link)

**Comment by sp-1234** [comment]
> Attach an error listener to see what the error is.

Is it even possible?

**Comment by gvsharma** [comment]
i am using v2.5.2 and it is working fine for me..and can you be specific with your error logs?

**Comment by BukT0p** [comment]
v2.5.2 your sample jpg works for me, but I have same issue - Log:
```
D/Picasso: Main        created      [R1] Request{https://news.mayomedicallaboratories.com/files/2017/06/Platelet-Toon_1.jpeg}
 D/Picasso: Hunter      joined       [R1]+1ms to [R0]+251ms, [R1]+1ms
 D/Picasso: Dispatcher  retrying     [R0]+1145ms, [R1]+896ms 
 D/Picasso: Hunter      executing    [R0]+1147ms, [R1]+897ms 
 D/Picasso: Dispatcher  retrying     [R0]+1696ms, [R1]+1447ms 
 D/Picasso: Hunter      executing    [R0]+1697ms, [R1]+1448ms 
 D/Picasso: Dispatcher  batched      [R0]+1698ms, [R1]+1449ms for error
 D/Picasso: Dispatcher  delivered    [R0]+1901ms, [R1]+1652ms 
 D/Picasso: Main        errored      [R0]+1902ms 
 D/Picasso: Main        errored      [R1]+1652ms 
```
