### ISSUE TITLE
Load image in Custom ImageView 

### ISSUE THREAD

**Issue by GauravCreed** [square/picasso#1402]
Hi @squarefinance 

I am trying to load image in My Custom ImageView but i can't able to set 
`//Picasso.with(mContext).load(path).into(target);
Picasso.with(mContext).load(path).into(circle_avatar);`

`Target target = new Target() {
        @Override
        public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
            circle_avatar.setImageBitmap(bitmap);
        }

        @Override
        public void onBitmapFailed(Drawable errorDrawable) {
        }

        @Override
        public void onPrepareLoad(Drawable placeHolderDrawable) {
        }
    };`

And ??My Custom ImagView is [https://github.com/Pkmmte/CircularImageView](CircularImageView) 
please help me to solve this bug.

Thanks

**Comment by JakeWharton** [comment]
Your `Target` is being garbage collected because nothing references it. Place it in a field or implement it on a subclass of the view so that it can be used directly. This will ensure the callbacks are invoked.
