### ISSUE TITLE
Image is not showing [though the image url is valid]

### ISSUE THREAD

**Issue by lalaji** [square/picasso#1403]
Hi,

I have written below piece of code to get an image from a url and show in my android app.I'm using picaso version 2.5.2 [compile 'com.squareup.picasso:picasso:2.5.2'] and android android minSdkVersion is 8 and targetSdkVersion is 15.
My problem is the image url which is I used from below code block is valid and can be viewable directly through accessing browser.I checked the response headers for that browser call also and I could see content-length header is there.

private final void changeNavigationDrawer() {
        final View headerLayout = navigationView.getHeaderView(0);
        final ImageView customerProfileRoundImage = (ImageView) headerLayout.findViewById(R.id.customer_profile_round_image);
        final TextView customerName = (TextView) headerLayout.findViewById(R.id.customer_name);
        final TextView customerMobile = (TextView) headerLayout.findViewById(R.id.customer_mobile);
        Session loginSession = sessionManager.getLoginSession();
        if (!imageUrl.isEmpty()) {
            Picasso.with(headerLayout.getContext()).invalidate(**imageUrl**);
            Picasso.with(headerLayout.getContext()).load(imageUrl).into(customerProfileRoundImage);
        } else {
            customerProfileRoundImage.setImageResource(R.mipmap.anonymous_user);
        }
        customerName.setText(loginSession.getName());
        customerMobile.setText(loginSession.getMobileNumber());
    }

final ImageView customerProfileImage = (ImageView) view.findViewById(R.id.profile_image_container);
        if(**imageUrl**!=null) {
            Picasso.with(view.getContext()).invalidate(**imageUrl**);
            Picasso.with(view.getContext()).load(imageUrl).into(customerProfileImage);
        }else {
            customerProfileImage.setBackgroundResource(R.mipmap.anonymous_user);
        }

Could someone give me a clue on what is the issue on above?

**Comment by wogenhaosini** [comment]
Yes, I have appeared in this situation  

Picasso version:2.5.2

**Comment by gvsharma** [comment]
the v2.5.2 is stable and am using quite for sometime for loading remote images. Can you provide the logs that you are getting..?

**Comment by JakeWharton** [comment]
Without the image URL and a sample that reproduces it or at least the full stacktrace there's not really anything we can do here.

**Comment by ml454** [comment]
try https://jcrstatic.s3-ap-southeast-1.amazonaws.com/rRXswrOU6dGuhJrvQ5XXyA 
please
