### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ibrahim-appgodz** [square/picasso#1405]
Fatal Excception while using in in com.daimajia.slider library
android.graphics.BitmapFactory.nativeDecodeAsset (BitmapFactory.java)
android.content.res.Resources.getDrawable (Resources.java:1613)
com.squareup.picasso.RequestCreator.getPlaceholderDrawable (RequestCreator.java:676)
com.squareup.picasso.RequestCreator.into (RequestCreator.java:637)
com.daimajia.slider.library.SliderTypes.BaseSliderView.bindEventAndShow (BaseSliderView.java:246)
com.daimajia.slider.library.SliderTypes.DefaultSliderView.getView (DefaultSliderView.java:25)
com.daimajia.slider.library.SliderAdapter.instantiateItem (SliderAdapter.java:81)
com.daimajia.slider.library.Tricks.InfinitePagerAdapter.instantiateItem (InfinitePagerAdapter.java:54)
com.daimajia.slider.library.Tricks.ViewPagerEx.addNewItem (ViewPagerEx.java:848)
com.daimajia.slider.library.Tricks.ViewPagerEx.populate (ViewPagerEx.java:998)
com.daimajia.slider.library.Tricks.ViewPagerEx.populate (ViewPagerEx.java:930)
com.daimajia.slider.library.Tricks.ViewPagerEx.onMeasure (ViewPagerEx.java:1453)
android.view.View.measure (View.java:17387)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by JakeWharton** [comment]
OOMs are a result of telling Picasso to load too much. There's nothing the library can do to avoid them since it's doing exactly as you instructed it.

In this case it looks like a large resource being used as a placeholder set it over the edge.
