### ISSUE TITLE
Memory management in Picasso

### ISSUE THREAD

**Issue by rahulrj** [square/picasso#1418]
I had a few questions about Picasso.
1. I saw [here](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/LruCache.java#L30) that the memory cache used by Picasso is just a LinkedHashMap which holds a strong reference to the Bitmaps. Shouldn't it have a WeakReference or a SoftReference to the Bitmaps? If not, then how will the images get cleared from cache when memory becomes low and GC runs?

2.In a heap dump collected from an app after closing the app on back-press and running the GC, i can still see the instances of Picasso.LruCache (image attached below) with Bitmaps in it. Why is this LruCache instance retained? Because its occupying a lot of memory.

![picasso_new](https://cloud.githubusercontent.com/assets/2638816/15958873/9d1cd38c-2f15-11e6-9fc0-af76d96bda5e.png)

3.Also i can see a lot of instances of `PicassoDrawable` class. That too after GC run
![picasso_2](https://cloud.githubusercontent.com/assets/2638816/15961135/c2041830-2f20-11e6-8150-fdf0b8537db3.png)

**Comment by JakeWharton** [comment]
It's a cache so strong references are what we want. We want to retain the
recently used bitmaps for when you scroll back up in a list or press back
to the previous screen. The LRU policy manually evicts the cache contents
when they are unused and allows them to be GC'd.

**Comment by JakeWharton** [comment]
Of you want it to use less memory you can create the Cache yourself at any size.
