### ISSUE TITLE
Whether the picasso support gif image?

### ISSUE THREAD

**Issue by tianshaokai** [square/picasso#1420]

**Comment by JakeWharton** [comment]
Yes. Just not animated.

**Comment by tianshaokai** [comment]
Whether you consider adding animation？

**Comment by JakeWharton** [comment]
That would require Picasso to ship its own image decoder, and we don't want
to be in the business of shipping image decoders. Your best bet is to
solicit Android to include support for it.

**Comment by tianshaokai** [comment]
Thanks，But android does not currently support.
