### ISSUE TITLE
Picasso.Builder leakage with an error of Picasso-Dispatch

### ISSUE THREAD

**Issue by wangbourne** [square/picasso#1427]
Picasso is called in Adapter with a way of:
```
 mPicassoBuilder.build().load(finalImageURL)
                        .fit().centerCrop()
                        .placeholder(R.drawable.menu_image_placeholder).into(holder.imageView);
```

Here, mPicassoBuilder is initialised in constructor via:

`mPicassoBuilder = new Picasso.Builder(mContext).executor(Executors.newFixedThreadPool(15)).memoryCache(Cache.NONE);`

Above code could crash the app because of memory leak. If I change another way to load image: 

```
Picasso.with(mContext).load(finalImageURL)
                        .fit().centerCrop()
                        .placeholder(R.drawable.menu_image_placeholder).into(holder.imageView);
```
it will be OK.

is there anyone else once met similar problems?

**Comment by JakeWharton** [comment]
You absolutely should not create new Picasso instances each time you need one. Create a single `Picasso` instance and re-use it everywhere or use `Picasso.with` (which will also always return a single instance).
