### ISSUE TITLE
OutOfMemory on loading < 4MB on images on multiple devices

### ISSUE THREAD

**Issue by mmvicsonvictor** [square/picasso#1429]
First of all, thanks for this super useful library. I have used it on multiple projects before and this is the first time I am running into an issue(also the first project which loads tons of images).

My app downloads a bunch of images to display them on 5 pages on a PagerAdapter. I am testing it on multiple devices including the 6p. I keep getting the OOM issue consistently. I tried a custom transformation to scale down the image, but looks the server is returning the correct sizes images and the inSampleSize on the BitmapFactory.options turns out to 1, so that did not help. I also have to mention that for a good user experience, we are loading the first 3 images on all the 5 pages. So approx 15 image requests and requested to be loaded by picasso pretty quickly, could even be requested simultaneously at the same time. I am using the default BitmapConfig.

And I use Dagger to inject a singleton instance of picasso.

```
@Provides
@Singleton
public Picasso providePicasso(OkHttpClient client) {
    return new Picasso.Builder(context)
            .loggingEnabled(true)
            .indicatorsEnabled(true)
            .downloader(new OkHttp3Downloader(client))
            .listener(new Picasso.Listener() {
                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                    Timber.e(exception, "Failed to load image: %s", uri);
                }
            })
            .build();
}
```

And the okHttpClient used is:

```
private static OkHttpClient.Builder createOkHttpClient(Context context) {
    // Install an HTTP cache in the application cache directory.
    File cacheDir = new File(context.getCacheDir(), ShopConstants.HTTP);
    Cache cache = new Cache(cacheDir, ShopConstants.IMAGE_DISK_CACHE_SIZE);

    return new OkHttpClient.Builder()
            .cache(cache)
            .connectTimeout(ShopConstants.HTTP_TIMEOUT_VALUE, SECONDS)
            .readTimeout(ShopConstants.HTTP_TIMEOUT_VALUE, SECONDS)
            .writeTimeout(ShopConstants.HTTP_TIMEOUT_VALUE, SECONDS);
}
```

If you see in the stats dumped below, there is only a total of 4MB of images that are downloaded from the server. However the cache size grows to 24MB and total bitmap size comes out to approx 123 MB. I do not understand why the total bitmap size is much larger than the total size of the images downloaded.

===============BEGIN PICASSO STATS ===============
Memory Cache Stats
  Max Cache Size: 28760941
  Cache Size: 24174420
  Cache % Full: 85
  Cache Hits: 0
  Cache Misses: 24
Network Stats
  Download Count: 24
  Total Download Size: 4163837
  Average Download Size: 173493
Bitmap Stats
  Total Bitmaps Decoded: 19
  Total Bitmap Size: 122061516
  Total Transformed Bitmaps: 3
  Total Transformed Bitmap Size: 3202668
  Average Bitmap Size: 6424290
  Average Transformed Bitmap Size: 177926
===============END PICASSO STATS ===============

Can someone please tell me if I am doing something wrong. The only way I am able to avoid the OOM now is turning on 'largeHeap' on the manifest. 

Thanks a lot in advance.

**Comment by eriuzo** [comment]
actual memory used to display images is not determined by its file size, but by its resolution.

for example: a PNG image at 800x600  with transparency (32-bit) will require 800x600x(32/8) bytes = 1920000 bytes = 1.83 MB, whatever the original file size is.

**Comment by JakeWharton** [comment]
OOMs are not caused by this library. Usually the leading cause is heap fragmentation or small memory leaks that add up over time.
