### ISSUE TITLE
What's holding back the release of v2.6.0?

### ISSUE THREAD

**Issue by cbruegg** [square/picasso#1435]
While Square's work on this library is truly appreciated, I don't understand what's causing the last release to be from March 2015, while many bugs have been fixed since then thanks to various contributions.

Could you please give an outline of what's still to be done in order to release v2.6.0, so community members can help? The [milestones page](https://github.com/square/picasso/milestones) shows that all goals are completed. I understand that you have [more important things](https://www.reddit.com/r/androiddev/comments/4bgaci/autovalue_extensions_jake_wharton/d195t4r) to do, but with 69 contributors in this repo, that shouldn't be a big problem.

**Comment by JakeWharton** [comment]
We'll try to release soon, but there remains to be no timeline.

**Comment by PaulWoitaschek** [comment]
Any news on this?

**Comment by AlmogBaku** [comment]
2017, any news?

**Comment by JakeWharton** [comment]
Jodie Whittaker is the new Doctor Who

**Comment by cbruegg** [comment]
Not to offend anyone, but I've given up on Picasso and switched to Glide. It looks like no maintainer here has the time to make a release, which is fine, but maybe this library should then be deprecated or another maintainer should be found?

**Comment by JakeWharton** [comment]
Making a release is the easiest part, and has nothing to do with it.

**Comment by cbruegg** [comment]
By "releasing" , I also meant testing, sorry if that was unclear. I don't
think anyone is complaining about a lack of new features, but 2.5.2 simply
contains some bugs that make it unusable in production for some use cases
IMO. An intermediate release would be really helpful, but if nobody has
time for that soon, or this is not something you'd like to do, that's fine
- a notice would be appreciated though.

**Comment by JakeWharton** [comment]
The code has deviated far beyond what could be made as an intermediate
release.

**Comment by cbruegg** [comment]
That's good to know. Thanks for clarifying!
