### ISSUE TITLE
didn't cache the picture in just same url

### ISSUE THREAD

**Issue by davodm** [square/picasso#1436]
Hi, i have a weird problem in using this library on my android project.
pictures will be open in this url but won't cache.

http://beporsim.com/assets/avatars/31ed28a42015721ad2212010e9fea2a1.jpg
http://beporsim.com/assets/avatars/9727a88996661f3ffae98042ed166a96.jpg

but if i open it with this url everything is ok!
http://beporsim.com/api/v2/avatar/31ed28a42015721ad2212010e9fea2a1
http://beporsim.com/api/v2/avatar/9727a88996661f3ffae98042ed166a96

Thanks

**Comment by NightlyNexus** [comment]
Does the picture not cache in the memory cache? Are you using anything else (like a resize or Transformation) that might change the memory cache's key? Should this be moved to StackOverflow?

**Comment by JakeWharton** [comment]
The cache control headers are very different between these two URLs which will change the caching behavior. Picasso has no control over whether or not images are cached, this all is handled by the HTTP client and controlled by the cache headers from the server.

**Comment by pipigithub** [comment]
@NightlyNexus You'r right.didn't cache the picture in just same url,because use resize.
