### ISSUE TITLE
OkHttp3 interceptor not working

### ISSUE THREAD

**Issue by Rashwan** [square/picasso#1438]
I'm using a custom Okhttp3 Client to intercept Picasso calls and modify the url to add an API key : 
```java
OkHttpClient picassoClient =  new OkHttpClient.Builder().addInterceptor(new Interceptor() {          
 @Override      
    public Response intercept(Chain chain) throws IOException {
               Request originalRequest = chain.request();
                HttpUrl fullPath = originalRequest.url().newBuilder()
                        .addQueryParameter("api_key", application.getString(R.string.movies_api_key))
                        .build();
                Request.Builder newRequestBuilder = originalRequest.newBuilder().url(fullPath);
                Request newRequest = newRequestBuilder.build();
                return chain.proceed(newRequest);
            }
        }).build();
```
Then constructing the Picasso instance : 

```java
Picasso picasso = new Picasso.Builder(this).downloader(new OkHttp3Downloader(picassoClient)).build();

picasso.setLoggingEnabled(true);
Picasso.setSingletonInstance(picasso); 
```

Then loading the image : 

```java
Picasso.with(this).load("http://image.tmdb.org/t/p/w300/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg").fetch();
```
When Observing the Picasso logger i see that the API key is never added and also when using the debugger i see that the intercept method is never called .

Right now i'm using the latest Picasso snapshot along with Okhttp 3.3.1 , I also used picasso 2.5.2 with [OkHttp3Downloader](https://github.com/JakeWharton/picasso2-okhttp3-downloader) but with the same results.

**Comment by JakeWharton** [comment]
Picasso's logger isn't going to show the api key because it's added by the HTTP client. I just tried your exact code and I see the interceptor being called for every request.

**Comment by Rashwan** [comment]
How would i see the interceptor being called ? Using the debugger ?

**Comment by JakeWharton** [comment]
Yeah. Or just put in a log statement.

**Comment by Rashwan** [comment]
Did both , the debugger dosen't stop at the break point inside the interceptor nor the log statement is shown . maybe using retrofit with another custom OkHttpClient is causing some interference ? will try with a fresh project.

**Comment by Rashwan** [comment]
It turns out that the problem was that i was using the Interceptor to also add a base url (ex: "http://image.tmdb.org/t/p/w300/") for the image to be loaded as the api would just give me a relative one (ex: "/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg") and because i would call picasso.load() on the relative path it wouldn't find the "http" portion so it wouldn't even call the interceptor and add the base url. don't know it this is expected behavior or not

**Comment by JakeWharton** [comment]
It tries to load that as a local file because it looks like an absolute file path. You need to use 'http' or 'https' scheme in what you pass to Picasso for it to use the downloader. You can still replace the host in the interceptor, just use a dummy one when calling load.
