### ISSUE TITLE
Problem with fit() and resize() for images that are too big

### ISSUE THREAD

**Issue by thomashorta** [square/picasso#1440]
Hi, I'm using Picasso 2.5.2 and I'm having the problem that the image that I'm trying to load is too big (exceeding the maximum texture size), to avoid this issue (that is not actually a picasso issue) I'm trying to use resize() or fit(), but then Picasso gives this error:
`java.io.IOException: Cannot reset`

I am aware that this is a known problem and I just cloned the library and found that it was actually corrected by commit **b61c5d42da7243eab27b16a3396f8be4aff00084**.

    commit b61c5d42da7243eab27b16a3396f8be4aff00084
    Author: JohnWowUs <thenegus@gmail.com>
    Date:   Thu May 21 09:03:17 2015 +0100
    
        Added dynamic limit option to MarkableInputStream

So my question is: **what is the release date of a new picasso version that will incorporate this change?** I really need this change ASAP and didn't want to compile a local jar just for this change.

**Comment by JakeWharton** [comment]
We don't have release dates planned nor do we ever give estimates. You can use 2.6.0-SNAPSHOT from Sonatype's snapshots repo or download the latest aar from their repo as a local file and include it in your build for now. The link is in the README.
