### ISSUE TITLE
Cannot resolve method 'load(java.langObject' on picasso

### ISSUE THREAD

**Issue by hanseptiawan** [square/picasso#1442]
sorry for my bad english, i'm new in android developer. I'm trying to call some user data from server using retrofit and then there are image data too. So i used picasso as a image loader and place the result from picasso to my recycler view. I placed picasso in my adapter but there is an error from the load method, i'm confused which the right way should be. Please help me out, here my adapter : 

package com.lakonlawas.cloudwaroeng2.adapter;

import android.content.Context;
import android.content.Intent;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import com.lakonlawas.cloudwaroeng2.R;
import com.lakonlawas.cloudwaroeng2.activity.DetailActivity;
import com.lakonlawas.cloudwaroeng2.model.Restaurant;
import com.squareup.picasso.Picasso;

import java.util.List;

public class RestaurantAdapter extends RecyclerView.Adapter<RestaurantAdapter.RestaurantViewHolder>{

    private List<Restaurant> restaurants;
    Context context;

    public class RestaurantViewHolder extends RecyclerView.ViewHolder{
        TextView NAMA_RES, DESKRIPSI;
        ImageView SAMPUL_RES;

        public RestaurantViewHolder(View v){
            super(v);
            NAMA_RES = (TextView) v.findViewById(R.id.card_title);
            DESKRIPSI = (TextView) v.findViewById(R.id.card_text);
            SAMPUL_RES = (ImageView) v.findViewById(R.id.card_image);
            v.setOnClickListener(new View.OnClickListener(){
                @Override
                public void onClick(View v){
                    int position = getAdapterPosition();
                    Context context = v.getContext();
                    Intent intent = new Intent(context, DetailActivity.class);
                    intent.putExtra("NAMA_RES",restaurants.get(position).getNAMARES());
                    intent.putExtra("DESKRIPSI",restaurants.get(position).getDESKRIPSI());
                    intent.putExtra(DetailActivity.EXTRA_POSITION, getAdapterPosition());
                    context.startActivity(intent);
                }
            });
        }
    }

    public RestaurantAdapter(List<Restaurant> restaurants, Context context){
        this.restaurants = restaurants;
        this.context = context;
    }

    @Override
    public RestaurantAdapter.RestaurantViewHolder onCreateViewHolder(ViewGroup parent,
                                                                     int viewType){
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.list_restaurant, parent, false);
        return new RestaurantViewHolder(view);
    }

    @Override
    public void onBindViewHolder(RestaurantViewHolder holder, int position){
        Restaurant restaurant = restaurants.get(position);

        holder.NAMA_RES.setText(restaurants.get(position).getNAMARES());
        holder.DESKRIPSI.setText(restaurants.get(position).getDESKRIPSI());
        //error line, cannot resolve method 'load(java.lang.Object'
Picasso.with(context).load(restaurants.get(position).getSAMPULRES())
                .fit()
                .centerCrop()
                .into(holder.SAMPUL_RES);
    }

    @Override
    public int getItemCount(){
        return restaurants.size();
    }
}

**Comment by xX7** [comment]
restaurants.get(position).getSAMPULRES()

Seems to return a Object type. Load () accepts a String with the URL for example. Please lern a little more before asking these kind of questions in the issue field of this library.
