### ISSUE TITLE
fit() does not defer if the ImageView already has a height and width

### ISSUE THREAD

**Issue by suau** [square/picasso#1446]
I'm using Picasso in a RecyclerView with a custom ImageView (ArImageView).
ArImageView allows setting a aspect ratio for the view (calls `requestLayout()`), which together one side of the ImageView will determine the height/width of the final view in `onMeasure`.
Picassos `fit()` will only defer loading when either the height or the width is 0, this does not work well with re-used and re-measured Views (like ArImageView).
This is not specific to my custom view and will occur with any re-used ImageView.

**Comment by NightlyNexus** [comment]
Re-open this until a fix is found?
