### ISSUE TITLE
How to use picasso with FirebaseStorage

### ISSUE THREAD

**Issue by Ashok-Varma** [square/picasso#1448]
FirbaseStorage we can host images with access writes.

- I was able to load these images using Glide using custom StreamModelLoader<>
- when i checked picasso library i was able to create a custom downloader but load method will only give me URI but i need to send Firebase StorageReference object.

one possible solution i can send the firebase url and convert to StorageReference inside load method. which i wouldn't prefer because i will be duplicating the logic. I need all the Firebase converters at single place.

Is there any other solution to do this in picasso ?? if not it would have been better if picasso downloader is Generic class instead of standard Uri one.

**Comment by JakeWharton** [comment]
Downloader is for URLs only. You can register a [`RequestHandler`][1] which loads from arbitrary sources by handling a custom URI scheme.

For your example, the URIs could be like `firebase://path/to/resource`.

 [1]: http://square.github.io/picasso/2.x/picasso/com/squareup/picasso/RequestHandler.html

**Comment by premithk** [comment]
A sample request handler for picasso to work with firebase urls
https://gist.github.com/premithk/7311a47e9ee848829ad86595c39878a0
