### ISSUE TITLE
Unable to load large image from URI

### ISSUE THREAD

**Issue by hemantomnie** [square/picasso#1450]
I am trying select pictures form gallery and then using picasso to attach it on imageview.
Picasso is working fine with small image but fails with large image. Please help me.

**Comment by nitingrov86** [comment]
I am also facing the same issue mostly with Motorola Devices. Looks more like memory heap issue. More I read issues over here it looks like they are taking care of this issue in v2.6. Not sure though when is the new release.
@JakeWharton can you please calrify if possible.

**Comment by JakeWharton** [comment]
There is not enough information to make this report actionable. Please include offending images, the code used to load, logs, the exception passed to Picasso's exception handler, etc.

**Comment by MichaelGoj** [comment]
I was facing the same issue on a Moto X 2nd Gen Android 5.0 and I debugged it and I can see the following exception `java.io.IOException: Cannot reset` from the BitmapHunter object within Picasso's `complete` method which seems to be related to this issue https://github.com/square/picasso/issues/364
```
hunter = {BitmapHunter@5223} 
 action = {TargetAction@5220} 
 actions = null
 cache = {LruCache@5224} 
 data = {Request@5218} "Request{file:///data/data/com.myexample/cache/IMG_20160715_135310.969 resize(640,640) centerCrop}"
 dispatcher = {Dispatcher@5225} 
 exception = {IOException@5226} "java.io.IOException: Cannot reset"
  cause = {IOException@5226} "java.io.IOException: Cannot reset"
  detailMessage = "Cannot reset"
  stackState = {Object[11]@5236} 
  stackTrace = {StackTraceElement[0]@5237} 
  suppressedExceptions = {Collections$EmptyList@5238}  size = 0
  shadow$_klass_ = {Class@4048} "class java.io.IOException"
  shadow$_monitor_ = -1953730282
 future = {PicassoExecutorService$PicassoFutureTask@5227} 
 key = "file:///data/data/com.myexample/cache/IMG_20160715_135310.969\nresize:640x640\ncenterCrop\n"
 loadedFrom = {Picasso$LoadedFrom@5200} "DISK"
 picasso = {Picasso@5187} 
 priority = {Picasso$Priority@5228} "NORMAL"
 requestHandler = {FileRequestHandler@5229} 
 result = null
 stats = {Stats@5230} 
 exifRotation = 0
 memoryPolicy = 0
 networkPolicy = 0
 retryCount = 0
 sequence = 8
 shadow$_klass_ = {Class@1490} "class com.squareup.picasso.BitmapHunter"
 shadow$_monitor_ = -1403433541
```

**Comment by MichaelGoj** [comment]
Everything works fine with the latest snapshot of 2.6.0 👍
