### ISSUE TITLE
SocketException

### ISSUE THREAD

**Issue by Zamuzo** [square/picasso#1453]
Hello,

When I try to download image from disk with very slow connection (GPRS), it's very long (about 10min) and I get Socket exception before get image from DISK

`    compile 'com.squareup.picasso:picasso:2.5.2'
     compile 'com.squareup.okhttp:okhttp:2.4.0'`

`        OkHttpClient client = new OkHttpClient();
        client.setCache(new Cache(context.getApplicationContext().getCacheDir(), Integer.MAX_VALUE));
        client.setConnectTimeout(5, TimeUnit.SECONDS); // connect timeout
        client.setReadTimeout(15, TimeUnit.SECONDS);    // socket timeout
        Picasso.Builder builder = new Picasso.Builder(this);
        builder.downloader(new OkHttpDownloader(client));
        //builder.downloader(new UrlConnectionDownloader(this));
        Picasso built = builder.build();
        built.setIndicatorsEnabled(BuildConfig.DEBUG);
        built.setLoggingEnabled(BuildConfig.DEBUG);
        Picasso.setSingletonInstance(built);`

<img width="1340" alt="capture d ecran 2016-07-15 a 14 34 30" src="https://cloud.githubusercontent.com/assets/14942807/16874679/f0d7aaa6-4a9a-11e6-8471-2185636801c3.png">

Thanks in advance

PS : Sorry about my bad english

**Comment by JakeWharton** [comment]
This is just a connection reset. Networks are always flaky so this will happen frequently. Picasso will retry the download again shortly after this happens.
