### ISSUE TITLE
Apply the custom fade for images coming from the network

### ISSUE THREAD

**Issue by iad24** [square/picasso#1454]
Right now I used this block to have the fade in effect.

----------------------
final AtomicBoolean playAnimation = new AtomicBoolean(true);
            Picasso.with(view.getContext()).load(url).noPlaceholder().noFade().into(avatar, new Callback() {
                @Override
                public void onSuccess() {
                    if (playAnimation.get()) {
                        Animation fadeOut = new AlphaAnimation(0, 1);
                        fadeOut.setInterpolator(new AccelerateInterpolator());
                        fadeOut.setDuration(500);
                        avatar.startAnimation(fadeOut);
                    }
                }

                @Override
                public void onError() {

                }
            });
            playAnimation.set(true);

---------------------

But onSuccess is always called even though the image is from memory.
I only want to apply the fade in effect for new images coming from the network.

**Comment by JakeWharton** [comment]
You should be calling `set(false)` not `set(true)`.

**Comment by iad24** [comment]
@JakeWharton thanks

to others, also change "if (playAnimation.get())" to "if (**!**playAnimation.get())"
