### ISSUE TITLE
Handle Null Uri in custom Request Handler

### ISSUE THREAD

**Issue by mshukla19** [square/picasso#1461]
Is there any way we can handle null image url in picasso. Currently an error callback is not called when url is null. I was thinking of creating a custom Request Handler and loading a placeholder image when uri is null like this -

```
@Override
        public boolean canHandleRequest(Request data) {
            return data.uri == null || data.uri.toString().startsWith("/") ||
                    !UtilitySingleton.isValidUrl(data.uri.toString());
        }
```

But this doesn't work as `forRequest` is never called when Uri is null so request handler doesn't come into action. I want to do this because assets used in our app are not controlled by us and urls are frequently null. Trying to avoid null checking in every model/place

**Comment by JakeWharton** [comment]
We already use `null` as an explicit signal and cannot change its behavior without breaking some assumptions (potentially in custom request handlers in people's apps). Unfortunately I don't see a way to support this without a breaking change and we're not planning to do one of those any time soon.

One option would be to wrap Picasso's API into your own image loading abstraction and encode this application-specific behavior in there.
