### ISSUE TITLE
New Release for OkHttp3Downloader

### ISSUE THREAD

**Issue by jaredsburrows** [square/picasso#1472]
@JakeWharton Can we release a `2.5.3` for `OkHttp3Downloader`? This way going from `com.squareup.okhttp:okhttp` to `com.squareup.okhttp3:okhttp` is a smooth transition.

**Comment by JakeWharton** [comment]
2.6 is the next release. You can use https://github.com/JakeWharton/picasso2-okhttp3-downloader/ for now.

**Comment by jaredsburrows** [comment]
Thanks and I am using that.

Jared Burrows

*jaredsburrows@gmail.com <jaredsburrows@gmail.com>*
LinkedIn: https://www.linkedin.com/in/jaredsburrows
