### ISSUE TITLE
Refresh cache on pull to refresh on listview

### ISSUE THREAD

**Issue by parinparikh-nv** [square/picasso#1473]
My problem is like when i do pull to refresh, then at that time the profile picture of the user should be changed if any user have update it's profile picture. The image URL is not changed but the image within the URL is changed.Now my cached image is different and the original image within the URL is different.So i want to update that cached image with the original URL image when user do a "Pull To Refresh". How can i achieve this? Right now i am not able to do this kind of thing.

Or

Is there any way to create 2 different kind of caches ?
One for saving profile pictures of the user and
Second for saving normal pictures.

And clear the cache of profile pictures when do a pull to refresh?

**Comment by JakeWharton** [comment]
You can specify `NO_CACHE` for both `memoryPolicy` and `diskPolicy` to skip the cache and force refresh.

**Comment by parinparikh-nv** [comment]
Thanks for the reply..i achieved it with the help of invalidate().I have invalidate all the image path when user do a pull to refresh.

**Comment by JakeWharton** [comment]
Just note that only invalidates the memory cache, not the disk cache.
