### ISSUE TITLE
picasso with NTLM authentication

### ISSUE THREAD

**Issue by adelemam** [square/picasso#1477]
I've tried lot of solution to view images authentication with NTLM (Sharepoint server) but failed, 
I liked using picasso, any direct help for this issue?

**Comment by JakeWharton** [comment]
Authentication is a concern of the HTTP client and Picasso just delegates to whatever HTTP client you explicitly specify or is automatically available thought the `Downloader` interface. So figure out how to get NTLM authentication working with HttpURLConnection or OkHttp and then specify a configured `Downloader` to a `Picasso.Builder` for it to use.
