### ISSUE TITLE
504 Unsatisfiable Request (only-if-cached)

### ISSUE THREAD

**Issue by kishukismat** [square/picasso#1480]
System.err: com.squareup.picasso.Downloader$ResponseException: 504 Unsatisfiable Request (only-if-cached)
System.err:     at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:67)
System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:49)
System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
System.err:     at java.lang.Thread.run(Thread.java:818)
System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)

Note :  Uploaded image size is almost 3MB.

**Comment by JakeWharton** [comment]
This just indicates your device is offline and the image is not available in the disk cache.

**Comment by kishukismat** [comment]
Other images are loading in the device from the internet. And Of course it is online.

**Comment by kishukismat** [comment]
I also thought that it's failing to downloaded after 3 attempts. But can you please suggest me the solution which I should try?

**Comment by JakeWharton** [comment]
Download smaller versions of the images and/or increasing your HTTP client
timeout.
