### ISSUE TITLE
How to remove the files from cache

### ISSUE THREAD

**Issue by MuralikrishnaM** [square/picasso#1481]
I wanted to remove all the files from the Picasso cache at the time of logging out of the application. Can you please help me how to do that, i dont want to invalidate every single file separately, also where does it save all the files? Can we see them?

**Comment by JakeWharton** [comment]
Picasso doesn't have a disk cache. It relies on the HTTP client for disk caching. Picasso will ask the HTTP client to create a cache in the `getCacheDir()` of your application, but the name of the folder is an implementation detail. If you want strong control over the disk cache, your best bet is to choose the folder name yourself inside of `getCacheDir()`, configure the cache on the HTTP client directly (preferably OkHttp!), and pass that HTTP client instance to your own `Picasso.Builder`. This ensures that your code is always in control of the location and can do things like clear out its files.
