### ISSUE TITLE
Loading Image Into Layout Background Does Not Load Placeholder

### ISSUE THREAD

**Issue by chickendiver** [square/picasso#1483]
I'm using a custom layout, into which I am using Picasso to load a background image.

    public class LinearLayoutCustom extends LinearLayout implements Target {

    private Context context;
    private BitmapDrawable bitmapDrawable = null;
    private Bitmap globalBitmap;
    private String globalContextIdentifier;

    public LinearLayoutCustom(Context context) {
        super(context);
    }

    public LinearLayoutCustom(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public LinearLayoutCustom(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {

        globalBitmap = bitmap;

        updateLayoutBackground();

        Log.d("PicassoTest", "Finished onbitmaploaded");
    }

    private void updateLayoutBackground(){

        final LinearLayout innerLayout = (LinearLayout) findViewById(R.id.inner_description_layout);
        int newHeight = innerLayout.getHeight();

        if (((newHeight > 0) && (getWidth() >0 )) && isShown()){

            Log.d("PicassoTest", "width and height are greater than 0");

            final Bitmap backgroundBitmap = globalBitmap;

            Bitmap tempBitmap = backgroundBitmap.createScaledBitmap(backgroundBitmap, getWidth(), newHeight, false);
            bitmapDrawable = new BitmapDrawable(tempBitmap);
            if((globalContextIdentifier != null) && (globalContextIdentifier.equals("WELCOME"))){
                //Do nothing
                //bitmapDrawable.setColorFilter(0x80B8775D, PorterDuff.Mode.MULTIPLY);
            }
            else{
                bitmapDrawable.setColorFilter(0xD9B8775D, PorterDuff.Mode.MULTIPLY);
            }

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                setBackground(bitmapDrawable);
            } else {
                setBackgroundDrawable(bitmapDrawable);
            }

        }
        else{
            Handler handler = new Handler();
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    updateLayoutBackground();
                }
            }, 1);
        }
    }

    @Override
    public void onBitmapFailed(Drawable errorDrawable) {
        //Set your error drawable
    }

    @Override
    public void onPrepareLoad(Drawable placeHolderDrawable) {
        setBackgroundColor(0xB8775D);
        setVisibility(View.VISIBLE);
    }

    public void setContext(Context givenContext){
       context = givenContext;
    }

    public void setGlobalContextIdentifier(String globalContextIdentifier) {
        this.globalContextIdentifier = globalContextIdentifier;
    }
    }

My Picasso call is simply:

    final LinearLayoutCustom strongRefLayout = layout;
    Picasso.with(c).load(
                    locationPictureURL)
                    //This doesn't actually seem to be adding a placeholder...
                    .placeholder(R.drawable.default_picture_pre_load)
                    .into(strongRefLayout);

However, when I do this, Picasso clears the background until loading the image, thereby leaving it white until the image is loaded.

I have tried setting "noPlaceholder()" with to no avail as well.

Is there something that I'm missing here?

P.S.: I looked into #469, #670, and #696, but the solutions presented did not work in this case.

**Comment by JakeWharton** [comment]
Picasso knows nothing about your view or its background as evidenced by the fact that you never pass the view directly to Picasso. Instead, it only has access to your `Target` instance and can only call the methods on `Target`. `noPlaceholder()` (and `placeholder()`) has no effect when using a `Target` so something else has to cause this problem. I would suggest starting with a more simple test case and slowly adding back in all your logic to identify the problem.
