### ISSUE TITLE
remove failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by woodcockjosh** [square/picasso#1486]
I keep getting these in the logs. Doesn't make any sense. 

09-11 19:24:48.479 11611-11831/com.opentimeapp.opentime W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.opentimeapp.opentime/cache/picasso-cache/4eb1529381b98174dd855af56ef69cd7.0
09-11 19:24:48.479 11611-11831/com.opentimeapp.opentime W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.opentimeapp.opentime/cache/picasso-cache/4eb1529381b98174dd855af56ef69cd7.1
09-11 19:24:48.549 11611-11820/com.opentimeapp.opentime W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.opentimeapp.opentime/cache/picasso-cache/1c0de2e8986ce7aa77e7763f8d6e4404.0
09-11 19:24:48.549 11611-11820/com.opentimeapp.opentime W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.opentimeapp.opentime/cache/picasso-cache/1c0de2e8986ce7aa77e7763f8d6e4404.1

I have write permissions and it still does it. Idk why. I'm on an Samsung S5 Running API 24

**Comment by JakeWharton** [comment]
Despite Picasso's name being included in the path, Picasso has nothing to do with this. These are coming from the underlying HTTP client which is managing the disk cache and Picasso has no control over it. It looks like the cache dir might have been cleared out from underneath the HTTP client which won't hurt anything.

**Comment by woodcockjosh** [comment]
Sure it doesn't crash the app but if it also doesn't allow picasso to cache images then it's a problem because it's the main benefit of picasso. Where do you suggest opening a ticket?
