### ISSUE TITLE
Exception: cache is closed

### ISSUE THREAD

**Issue by rahulrj** [square/picasso#1490]
I am frequently getting the `Exception` with message "Cache is closed" in `BitmapHunter#run` function. One of the image URL with which i am getting this exception is 

`https://i.l.inmobicdn.net/ifctpads/IFC/CCN/assets/learnmoreeng1470056739.png`

Also, this is not device/OS specific and i can see this across Android 7.0,Android 6.0,Android 5.
I am using Picasso 2.5.2.

**Comment by JakeWharton** [comment]
Please provide a sample or test that can reproduce the problem. Otherwise there's nothing we can do.

Picasso only closes a non-shared disk cache when you call `.shutdown()` or it could be closed by someone else.
