### ISSUE TITLE
Exceptions not being logged

### ISSUE THREAD

**Issue by Dragas** [square/picasso#1496]
Hi!
Is there any reason behind picasso not logging exceptions to console by default?
Current behavior tends to suggest backwards debugging methods to find out why the image isn't loaded.

**Comment by JakeWharton** [comment]
Network errors aren't exceptional exceptions. They're guarantee to happen.
Logging them to the logcat by default is needless spam 99.9% of the time.
If you want them logged, you can add an error listener to Picasso.Builder
and do whatever you want with them.
