### ISSUE TITLE
can't use disk cache

### ISSUE THREAD

**Issue by jingquanxie** [square/picasso#1497]
I use the following two url
http://www.youwu.cc/uploads/allimg/160306/1-160306124603.jpg?xxxxx
and 
http://www.youwu.cc/uploads/allimg/160807/1-160PGS611.jpg

Their difference is a parameter, a no parameters

that is my code
       @Override
        public View getView(int i, View view, ViewGroup viewGroup) {
            ViewHold viewHold = null;
            if (view == null) {
                view = LayoutInflater.from(mContext).inflate(R.layout.image_item, null);
                viewHold = new ViewHold();
                viewHold.imageView = (ImageView) view.findViewById(R.id.image);

                view.setTag(viewHold);
            } else {
                viewHold = (ViewHold) view.getTag();
            }

            String url = getItem(i);
            Picasso.with(mContext).setIndicatorsEnabled(true);
            Picasso.with(mContext).setLoggingEnabled(true);
            Picasso.with(mContext).load(url).resize(500,500).centerCrop().into(viewHold.imageView);
//            Glide.with(mContext).load(url).into(viewHold.imageView);

            return view;
        }

        class ViewHold {
            ImageView imageView;
        }

When I disconnect the Internet, I open the page again, the first url  of the picture will not be able to show, and the second is able to show, and from the disk。

so  This is why?

and version picasso 2.5.2

**Comment by JakeWharton** [comment]
Picasso does not have a disk cache. It delegates to the underlying HTTP client for disk-based caching. Both return cache headers regardless of the query parameter so I'm not sure what the problem is, but it's not inside of Picasso.

**Comment by VinaChiong** [comment]
@jingquanxie 
I think that is because your parameter of url is not unique in every request, like timestamp.
And Picasso use **LruCache** as a memory cache. You can not get the same Bitmap with a different url.

**Comment by jingquanxie** [comment]
@JakeWharton 
Well, I don't know if Picasso has a disk cache. I see it in the log. 

When I have a connection to the Internet
09-22 09:20:09.793 2505-2505/com.example.cailing.mytestpicasso D/Picasso: Main        completed    [R6]+4014ms from NETWORK

When I disconnect the Internet。
09-22 09:21:57.833 4170-4170/com.example.cailing.mytestpicasso D/Picasso: Main        completed    [R6]+304ms from DISK

and I do not know why the same respose header information can have a different effect.

You can find a URL to try it.

**Comment by jingquanxie** [comment]
@VinaChiong 
No, you don't know what I mean.
I am sorry, my English is very poor, but you can use any URL to try it.

**Comment by jingquanxie** [comment]
@VinaChiong 

This is the key of my problem.

When I disconnect the Internet, I open the page again, the first url of the picture will not be able to show, and the second is able to show, and from the disk。
