### ISSUE TITLE
when load image from server happened error ,the error holder did not show, placeholder was not replaced

### ISSUE THREAD

**Issue by littleloulou** [square/picasso#1498]
I use recyclerView with picasso, my code as follow:
![image](https://cloud.githubusercontent.com/assets/15904364/18742503/3af05e1c-80e7-11e6-8a92-6ed606c5a57e.png)
the setData() is a method of my custom ViewHolder, when onBindViewHolder this method will be invoked,
but when load image from server happened error ,the error holder did not show, placeholder was not replaced,it still show. please help me . I am a developer for TV.

**Comment by sisel** [comment]
bean.url==null?

**Comment by JakeWharton** [comment]
Please add debug logs and attach an error listener to the Picasso instance and provide the stacktrace. It's impossible to know what's going on otherwise. Preemptively closing because of the age of the issue.
