### ISSUE TITLE
Why there is no new releases of Picasso?

### ISSUE THREAD

**Issue by mmarshak** [square/picasso#1499]

**Comment by JakeWharton** [comment]
Because it's not done.

**Comment by mmarshak** [comment]
So if I grab picasso via Gradle with - 
compile 'com.squareup.picasso:picasso:2.5.2'

Am I am going to get the release that is 1.5 years old or the latest Master?

When the next release is expected?

**Comment by JakeWharton** [comment]
You'll get 2.5.2. You can use 2.6.0-SNAPSHOT for master. There is no
timeline for the next release.

**Comment by mmarshak** [comment]
What most people use 2.5.2 or 2.6.0-SNAPSHOT? 
Could you suggest a guidance about which one to pick?
