### ISSUE TITLE
Static code Analysis number of PICASSO

### ISSUE THREAD

**Issue by patientrx** [square/picasso#1501]
Please share any static code analysis number you have for picasso.

**Comment by JakeWharton** [comment]
42

**Comment by patientrx** [comment]
Hi Jake thanks for quick reply.
If they are using Static Code Analysis, what is the tool. How many low, mid, high issues.
Also suggest the evidence for same.

My software security team need the same information.

**Comment by patientrx** [comment]
@JakeWharton can you elaborate what you mean by "42"
Are you using any Static code analysis tool , share the place where i can find the result.

**Comment by JakeWharton** [comment]
The only static analysis we use is checkstyle for enforcing simple style
rules.

**Comment by patientrx** [comment]
@JakeWharton Thanks. Can you share the results of checkstyle. Any Links/data

**Comment by JakeWharton** [comment]
The results are simply that all changes must pass checkstyle. It runs automatically on pull requests and will fail the build if it's violated.
