### ISSUE TITLE
blue indicator issues 

### ISSUE THREAD

**Issue by BelongsH** [square/picasso#1506]
i use picasso get image in my applications.
image show indicator is blue,but i use charles know have http connect。 so  I thinks diskcache is not working but image  indicator show blue . 

i need you help . Thanks

**Comment by JakeWharton** [comment]
This isn't enough information to diagnose what is going on. We have tests for the indicator which synthesize the headers. Can you express the problem as a failing test case? Preemptively closing based on age.
