### ISSUE TITLE
Download multiple images and store in Realm 

### ISSUE THREAD

**Issue by RameshBhupathi** [square/picasso#1508]
**NeedsInfo** 
have to download more than 30 images and save them into Realm DataBase

Downloading Bitmaps Using Picasso .get() method inside Asyntask,after downloading and saving, going for another,Any Best way to download all images Simultaneously and save them into Realm as ByteArray.

**Comment by JakeWharton** [comment]
You can use `.into(Target)` to download in parallel using Picasso own executor or I would recommend you use your own executor that has multiple threads making `get()` requests.
