### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Target callback must not recycle bitmap!

### ISSUE THREAD

**Issue by vleonovs** [square/picasso#1510]
Good Day, Picasso Developers.
I have faced with the crash.
```
Fatal Exception: java.lang.IllegalStateException Target callback must not recycle bitmap!
com.squareup.picasso.TargetAction.complete (TargetAction.java:38)
com.squareup.picasso.Picasso.deliverAction (Picasso.java:558)
com.squareup.picasso.Picasso.complete (Picasso.java:517)
com.squareup.picasso.Picasso$1.handleMessage (Picasso.java:117)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7325)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

Unfortunately, I can't find steps to reproduce, to share with the code snippet.
And I have one feedback from the user:

> stops for no reason while attempting to load images.

Seems it happens while scrolling these images..
![7d12f56d4303495796170c119abef207](https://cloud.githubusercontent.com/assets/10854965/19524940/11b820ba-9628-11e6-8a93-270a4c6e5a77.png)

What can cause this crash and how to avoid or fix him ?

Anyway, thank you!

**Comment by JakeWharton** [comment]
This checks that you do not call `recycle()` on the `Bitmap` we hand you inside of a `Target#onBitmapLoaded` callback. The exception message indicates you are doing this.

**Comment by vleonovs** [comment]
Okay, I found this code, where `onBitmapLoaded ` is called. But where and how I must call `recycle()`. I was trying different ways, but nothing helps me
```
Target target = new Target() {

			@Override
			public void onPrepareLoad(Drawable arg0) {
			}

			@Override
			public void onBitmapLoaded(Bitmap arg0, LoadedFrom arg1) {
				image.setImage(ImageSource.bitmap(arg0));
			}

			@Override
			public void onBitmapFailed(Drawable arg0) {
			}
		};
```

**Comment by JakeWharton** [comment]
Well it's either inside `ImageSource.bitmap` or `image.setImage`

**Comment by vleonovs** [comment]
Thank you for your fast answer.
I fixed this crash with this code:
```
   /**
     * Provide a loaded bitmap for display.
     * @param bitmap bitmap to be displayed.
     */
    public static ImageSource bitmap(Bitmap bitmap) {
        if (bitmap == null) {
            throw new NullPointerException("Bitmap must not be null");
        } else if (bitmap.isRecycled()) {
            bitmap = bitmap.copy(bitmap.getConfig(), true);
        }
        return new ImageSource(bitmap);
    }
```

Maybe it will help somebody.

**Comment by agentraymond232** [comment]
@vleonovs bitmap.copy fails if bitmap is recycled (`in android.graphics.Bitmap.copy(Config, boolean)`)

**Comment by wlyu2001** [comment]
Is there a reason why the bitmap here can't be recycled? What if onBitmapLoaded callback allows another thread to recycle the bitmap?

**Comment by cuichanghao** [comment]
should not check recycle(), user may be just use one-off like combine custom bitmap with other.

**Comment by cuichanghao** [comment]
What I'm trying to say is i found after one-off use this callback bitmap, and set bitmap = null, the GC cannot collect it ASAP. 
- The depth(Android studio memory profiler) is nothing.
- The bitmap cannot collection even multiple GC(android studio press GC button).
- It took five minutes before it was finally collected.
- In Android 8.0 (API level 26), and higher, the bitmap pixel data is stored in the native heap.
https://developer.android.com/topic/performance/graphics/manage-memory

In the case of heavy memory usage in the short term, we need to make it clear at the native level that the bitmap can be recycled as soon as possible. This should be left up to the person who uses Picasso.
