### ISSUE TITLE
Device reboots: RuntimeException: bad array lengths when loading image into a notifications contentview

### ISSUE THREAD

**Issue by sneps85** [square/picasso#1511]
I am using picasso to change a notification's image. The notification is there for audio streaming and changes the cover of the current playing song.

Unfortunately I am getting a RuntimeException: bad array lengths on a Samsung Ace 4 with Android 4.4 installed, which causes the device to reboot.

Here the stack trace:

> java.lang.RuntimeException: bad array lengths
> at android.os.Parcel.readIntArray(Parcel.java:827)
> at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:348)
> at android.app.NotificationManager.notify(NotificationManager.java:158)
> at android.app.NotificationManager.notify(NotificationManager.java:120)
> at com.squareup.picasso.RemoteViewsAction$NotificationAction.update(RemoteViewsAction.java:117)
> at com.squareup.picasso.RemoteViewsAction.complete(RemoteViewsAction.java:42)
> at com.squareup.picasso.RequestCreator.performRemoteViewInto(RequestCreator.java:713)
> at com.squareup.picasso.RequestCreator.into(RequestCreator.java:560)

and here the code I am using to replace the cover image:

`Picasso
                    .with(context)
                    .load(song.getCoverImage(context))
                    .into(notification.contentView, R.id.status_bar_album_art, FOREGROUND_SERVICE, notification);`

**Comment by JakeWharton** [comment]
Reboots? Or is it a sys UI and app crash simultaneously?

**Comment by jrodbx** [comment]
Closing.  Reopen if still relevant.
