### ISSUE TITLE
Picasso image loading/downloading after resizing

### ISSUE THREAD

**Issue by mwshubham** [square/picasso#1512]
We have little doubt.  Is possible to resize/transform the image without loading into the view using picasso. Loading here means without actually downloading the actual image.

Let say I have an image of 3000 x 3000 on the server and I want to load it on a view of 500x500 but I don't to download it rather than I just want to resize it and then further downloading take place.

This will save unnecessary data usage of the user.

**Comment by JakeWharton** [comment]
Picasso is a client library so no. You need server-side software like
Thumbor to do resizing on the server.
