### ISSUE TITLE
Picasso doesn't load image in ImageView - Samsung Smartphones

### ISSUE THREAD

**Issue by yeisonvargasf** [square/picasso#1513]
Hello,

I'm taking a photo (Camera Samsung) and after that I'm calling 'load' method in onActivityResult (Fragment), but Picasso doesn't load the image into ImageView on Samsung Smartphones. On the other hand when the gallery has been called, everything has been worked fine.

`Picasso.with(getContext()).load(new File(UploadImage.logoUri)).resize(240, 0).into(
                        (ImageView)getView().findViewById(R.id.image_view_profile));`

I have tested:
- Memory
- Permissions
- Using 2.5.2 version.
- Updating to 2.6.0-SNAPSHOT
- Downgrading to 2.4.0

And anything worked, so I think that the problem is because I'm calling Picasso load method in OnActivityResult?

**Comment by caseykulm** [comment]
@yeisonvargasf Do you have Picasso and Http Client logs?

**Comment by JakeWharton** [comment]
Please explain "doesn't load". Enable debug logging and paste the logs. Add an error listener to the Picasso instance and paste any exceptions.

**Comment by JakeWharton** [comment]
Preemptively closing based on time, but feel free to comment and we can take a look with said information
