### ISSUE TITLE
Some images not loading

### ISSUE THREAD

**Issue by muhammadsaqib** [square/picasso#1517]
Images for example
http://www.zameen.com/common/resize.php?img=4/9711182_3983379.jpg

loads fine on the browser but for some reason Picasso failed with following logs:

 D/Picasso: Main        created      [R10] Request{http://www.zameen.com/common/resize.php?img=4/9711182_3983379.jpg}
D/Picasso: Dispatcher  enqueued     [R10]+0ms 
D/Picasso: Hunter      executing    [R10]+1ms 
D/Picasso: Dispatcher  batched      [R10]+531ms for error (will replay)
D/Picasso: Dispatcher  delivered    [R10]+748ms 
D/Picasso: Main        errored      [R10]+749ms

**Comment by febimfelix** [comment]
The url is working with the basic Picasso functions . Below is my code.

```
Picasso picasso = Picasso.with(getActivity());
            picasso.setIndicatorsEnabled(true);
            picasso.load(image)
                    .into(imageViewPreview);
```

**Comment by muhammadsaqib** [comment]
@febimfelix 
Right! Issue was with some response headers which got fixed on server side ended up fixing the issue.
