### ISSUE TITLE
部分机型设置大小会出现问题不能显示到控件上，比如魅族部分手机

### ISSUE THREAD

**Issue by jingtonglong** [square/picasso#1518]

**Comment by bkraszewski** [comment]
Please use English when filing an issue

**Comment by opcc60** [comment]
I have the same problem.
When I called method resize, I got an error "Cannot reset".
I find some issues about this and I find in BitmapHunter, there is a TODO in line 117 at 2.5.2.

long mark = markStream.savePosition(65536); // TODO fix this crap.

Is this the reason of this problem?

**Comment by JakeWharton** [comment]
Yes. This is fixed on `master` and you can try it with the 2.6.0-SNAPSHOT.
