### ISSUE TITLE
Loading a Drawable Object with Picasso in Android

### ISSUE THREAD

**Issue by maher640** [square/picasso#1523]
Apparently, it's not possible to load a Drawable object with Picasso

`Drawable myDrawable; = packageManager.getApplicationIcon("pkg name")
 Picasso.with(context).load(myDrawable).into(myImageView); //ERROR`

In a current project I'm working on, I get a list of installed apps along with their icons. The icons are Drawable object. Is there a work around for loading the drawables with Picasso? or this feature is still under development?

**Comment by JakeWharton** [comment]
Why wouldn't you just set the `Drawable` on `myImageView`?

**Comment by maher640** [comment]
@JakeWharton I do did that, but I was thinking of taking advantage of some of Picasso's features like caching.

**Comment by JakeWharton** [comment]
You can write a RequestHandler for a Uri like package://com.whatever that
loads the Bitmaps from PackageManager and then you get all the normal
features of Picasso.

**Comment by maher640** [comment]
@JakeWharton thanks for the tip. I'll give it a shot.
