### ISSUE TITLE
This is Bug?The application may be doing too much work on its main thread

### ISSUE THREAD

**Issue by xueyaolive** [square/picasso#1528]
When sliding on recyclerview, The application may be doing too much work on its main thread

**Comment by JakeWharton** [comment]
Picasso does all its work on background threads.

**Comment by xueyaolive** [comment]
load the local image, and do not do other things!

 @Override
    public void onBindViewHolder(PhotoAdapter.ViewHolder holder, int position) {
            String path = list.get(position);
//            Picasso.with(context)
//                    .load("file://" + path)
//                    .into(holder.imgPhoto); -->It's error(The application may be doing too much work on its main thread)
            Glide.with(context)
                    .load(path)
                    .into(holder.imgPhoto); -->It's ok
    }
