### ISSUE TITLE
Load large image from local uri or camera doesn't display

### ISSUE THREAD

**Issue by jessyuan24** [square/picasso#1529]
I resize the large image from local, then it works, but resize the image from the camera it doesn't display. I call fit method also doesn't works

**Comment by vishal901** [comment]
Imagepath = "/storage/emulated/0/Pictures/Photos/IMG_20161215_121844.jpg"

after call,

// call compress method aa.txt file
 File file =  compressImage( Imagepath ,getActivity() );

 Picasso mPicasso = Picasso.with(this);
                mPicasso.setIndicatorsEnabled(true);
                mPicasso.load(file)
                        .centerCrop()
                        .resize(96,96)
                        .into(ImageView);

[aa.txt](https://github.com/square/picasso/files/653957/aa.txt)
