### ISSUE TITLE
Doesn't it cache automatically ?

### ISSUE THREAD

**Issue by nitinsurana** [square/picasso#1533]
Hi
The website nor the readme say anything about having okhttp for caching. I guess caching is default behavior (with or without okhttp) 

```
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp3:okhttp:3.4.2'

```

I'm having the above dependencies and load image using 
`Picasso.with(img.getContext()).load(R.drawable.r).resize(30, 30).into(img);`

And whenever I visit the activity again, the image takes time to load. If it had been cached, it should be instant.

There's no other picasso configuration in my code. What am I missing ?
Also, can you please add some samples in either the readme or the website to make it clear how cache works and if okhttp is a required dependency and is there any configuration required or just the single line of code.

**Comment by behzodbek** [comment]
Picasso doesn't caches images. It is job of http layer. OkHttp stores data into cache if response contains proper headers for caching http response. 
1. Content length
2. Cache life time
