### ISSUE TITLE
Using Android asset as a placeholder

### ISSUE THREAD

**Issue by blipinsk** [square/picasso#1540]
It would be nice to be able to use a path to an `asset` to load a placeholder.

I know I can load an asset into a `Drawable` manually, but I think an out of the box method that would handle loading process asynchronously would be much better.

**Comment by JakeWharton** [comment]
> an out of the box method that would handle loading process asynchronously would be much better.

Placeholders and error drawables must be able to be loaded synchronously. The resource system is optimized for loading and decoding synchronously on the main thread whereas assets are not. Why do you want to use assets over resources?

**Comment by blipinsk** [comment]
The reason is a combination of wanting to organize my data better, keeping everything in one place, wanting to have a bit more flexible setup and being lazy... with unknown proportions 😄 .

The client of mine is expecting me to ship the app with a bunch of data that will act as an initial state of the app's database. So that users who initially run the app without Internet connection get to see some version of the downloadable content. This data contains images, that normally (when the app is online) are downloaded from separate urls. The images shipped with the app would be just perfect for placeholders for the live data, due to other requirements from my client.

As this initial pack of data will, most certainly, change quite often, hardcoding everything would be just a pain in the butt, that's why I'm just keeping a version of backend responses, that are dumped in the database on its creation/upgrade. If there's any change in the expected initial data, I can just swap the file in the assets (that represents the backend response), handle that in database upgrade, and I'm done. From the organizational point of view, it was logical for me to put images in assets as well, so I can do the same thing (as I do with backend responses) if something changes. Everything is organized neatly in one place, in folders in my assets.
 
I guess I could keep those images in resources, but I believe I would lose some of the structural clarity.
