### ISSUE TITLE
Don't break in null or empty URL

### ISSUE THREAD

**Issue by josinaldobarbosa** [square/picasso#1542]
I usually get the url per request, and it may happen that it does not come.

```
// Im hate this line, I have to check every time I use, because the app BREAK!
if (url != null && !url.isEmpty()) {
    Picasso.with(context)
      .load(url)
      .into(imageView)   
}
```

**Comment by JakeWharton** [comment]
Null is allowed. It cancels the previous request to the specified target.

An empty URL is a data modeling problem. It's neither a valid URL nor the canonical representation of absent in Java. We have no plans to change this behavior for empty string.
