### ISSUE TITLE
clear cache from disk

### ISSUE THREAD

**Issue by amyliu1062** [square/picasso#1543]
the picasso don`t real clear cache , it  just set url invalid  but not  remove from disk ， so the cache require  memory.  
can  it  extend  a  method to remove cache from the disk ?

**Comment by JakeWharton** [comment]
Picasso doesn't maintain the disk cache. The HTTP client does. If you need to clear the disk cache you should install it into the HTTP client yourself so that you have full control over the folder that it's using which you can clear whenever you want.
