### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by shaileshmulange** [square/picasso#1545]
java.io.FileNotFoundException:/storage/emulated/0/Demo/IMG_20161130_201337.jpg: open failed: EACCES (Permission denied)

I tried to get the image from sdcard and show into imageview but getting the error FileNotFoundException.

I have tested my application on two devices 1:-Galaxy Nexus(4.3) 2:-MotoG2 (6.0)
with version picasso:2.5.2.

I am able to solve this issue on  MotoG2 (6.0)  with provide runtime permission i.e."android.permission.WRITE_EXTERNAL_STORAGE" and "android.permission.READ_EXTERNAL_STORAGE" but how to deal with it below 6.0?

I have used below code for it.
String filePath = Environment.getExternalStorageDirectory().getAbsolutePath() + "/Demo/IMG_20161130_201337.jpg";
        
        Log.d(TAG, "File Path :" + filePath);
        File file = new File(filePath);

        Uri uri = Uri.fromFile(file);

        Picasso.Builder builder = new Picasso.Builder(this);
        builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
            }
        });
        builder.build().load(uri).into(img);

**Comment by JakeWharton** [comment]
Add those permissions to your directly to your manifest.

**Comment by shaileshmulange** [comment]
I have added that permission in my manifest also.
