### ISSUE TITLE
NoClassDefFoundError org.springframework.web.util.UriTemplate with picasso 2.5.2

### ISSUE THREAD

**Issue by kot331107** [square/picasso#1547]
Hi, thanks for a great lib!
However I've a bit stucked in a start of developing my app... :(
An exception is thrown after I've added a "picasso 2.5.2" dependency to the build.gradle. Do you have any idea how I'd resolve it? Oh and sorry for AA in my code!

UPDATE: I found that it works on API 23 but fails on API 15 - 17, ...? Also I've tried clean & build...

Console log:

> E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                  java.lang.NoClassDefFoundError: org.springframework.web.util.UriTemplate
                      at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:498)
                      at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:472)
                      at com.clockbyte.woodpecker.web.RestClient_.getFeed(RestClient_.java:48)
                      at com.clockbyte.woodpecker.activities.MainActivity.fetchFeed(MainActivity.java:208)
                      at com.clockbyte.woodpecker.activities.MainActivity_.access$601(MainActivity_.java:41)
                      at com.clockbyte.woodpecker.activities.MainActivity_$8.execute(MainActivity_.java:204)
                      at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:403)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                      at java.lang.Thread.run(Thread.java:864)

Code which throws an exception (in MainActivity):
```java
    @Background
    void fetchFeed(){
        showIndicator(true);
        List<FeedItem> feedItems =  restClient.getFeed(); // here I got the exception
        fetchFeedUI(feedItems);
    }
```

REST client code 
```java
@Rest(rootUrl = DomainUrl + PostUrl, converters = { MappingJackson2HttpMessageConverterEx.class })
public interface RestClient extends RestClientErrorHandling {
    @Get(GetFeedUrl)
    List<FeedItem> getFeed();

    @Get(GetFeedUrl + PageParamUrl)
    List<FeedItem> getFeedByPage(@Path int page);

    @Post(NewUrl)
    @Accept(MediaType.APPLICATION_JSON)
    void sendNewPost(@Body PostItem postItem);
}
```

My build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
def AAVersion = '4.1.0'
def ParcelerVersion = '1.1.5'

apt {
    arguments {
        resourcePackageName android.defaultConfig.applicationId
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
    }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
    defaultConfig {
        applicationId "com.clockbyte.woodpecker"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions{
        pickFirst 'META-INF/LICENSE'
    }

    dexOptions {
        preDexLibraries = false
    }

    afterEvaluate {
        tasks.matching {
            it.name.startsWith('dex')
        }.each { dx ->
            if (dx.additionalParameters == null) {
                dx.additionalParameters = ['--multi-dex']
            } else {
                dx.additionalParameters += '--multi-dex'
            }
        }
    }
}

configurations.all {
    resolutionStrategy.force 'com.google.android.gms:play-services-ads:9.6.1'
}

dependencies {
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    apt "org.androidannotations:rest-spring:$AAVersion"
    compile "org.androidannotations:rest-spring-api:$AAVersion"

    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'org.apache.commons:commons-io:1.3.2'

    compile 'com.android.support:support-v4:25.0.1'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.google.firebase:firebase-core:9.6.1'
    compile 'com.google.firebase:firebase-analytics:9.6.1'
    compile 'joda-time:joda-time:2.9.3'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.8.4'
    compile 'com.fasterxml.jackson.core:jackson-core:2.8.4'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.8.4'
    compile 'com.fasterxml.jackson.datatype:jackson-datatype-joda:2.8.4'
    compile 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'
    compile 'org.springframework.android:spring-android-rest-template:2.0.0.M3'
    compile 'com.github.clockbyte:admobadapter:1.3.0'
    compile 'pub.devrel:easypermissions:0.2.0'
    compile 'com.squareup.picasso:picasso:2.5.2'

    compile 'com.android.support:multidex:1.0.1'

    apt "org.parceler:parceler:$ParcelerVersion"
    compile "org.parceler:parceler-api:$ParcelerVersion"

    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by JakeWharton** [comment]
This exception does not come from Picasso or anything related to Picasso. It is instead a problem with your local build. I'd recommend doing a clean build to reset any weird state.

**Comment by kot331107** [comment]
@JakeWharton yeah, seems you're right, today I've updated the gradle build plugin to 2.2.3 and now it works. BTW I've tried clean build before and it failed. However thanks a lot for your advice!
