### ISSUE TITLE
Network-only  and don`t want to retry with disk

### ISSUE THREAD

**Issue by mwping** [square/picasso#1550]
I use Picasso like below:

`Picasso.with(activity).load(url).error(R.mipmap.network_error).memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE).networkPolicy(NetworkPolicy.NO_CACHE, NetworkPolicy.NO_STORE).into(imageView)`

By reading the source code I found that if  load an image url from network error (for example ,I enable the airplaneMode), Picasso will retry twice with header value "no-cache,no-store" and use "only-if-cached,max-age=2147483647" to retry with disk cache for the third time.However , I don`t want to retry from disk, I want that if retry error for 3 times, then just give up so I can show the network_error drawable,  is it possible to solve my trouble with Picasso ?

**Comment by JakeWharton** [comment]
We don't support this and don't have any plans to change the behavior at this time. You could write your own `Downloader` which ignored the last attempt and immediately failed.
