### ISSUE TITLE
Can/should I use two Picasso instances in this situation?

### ISSUE THREAD

**Issue by DavidMihola** [square/picasso#1551]
Where the situation is this: In our current app we have two sets of images we are loading and displaying with Picasso.
(1) A set of TV channel logos which rarely if ever change. These are reused all over the place in the application.
(2) A set of current screenshots for each channel which change every few seconds.
All HTTP responses have the appropriate caching headers.

Now, sometimes we seem to have the situation that the screenshots push the icons out of the disk cache and must consequently be reloaded.

To avoid this I thought about constructing two Picasso instances each with their own OkHttp client and disk cache - one for the icons and one for the screenshots - and injecting/using these in the appropriate places.

I know that Picasso should generally be used as a singleton - but is this a situation where it would make sense to make an exception?

Thanks for any advice!

**Comment by JakeWharton** [comment]
Yes, this is a use case for two instances! In general the term "singleton" tends to means more make-sure-you're-re-using-the-same-instance-and-not-creating-new-ones and less make-sure-there's-only-one-instance.

**Comment by DavidMihola** [comment]
@JakeWharton Perfect! Thank you so much!
