### ISSUE TITLE
Transformation is applied before the scaling

### ISSUE THREAD

**Issue by jason-christian-92** [square/picasso#1554]
Hi,

I used the picasso library to show images retrieved from URL with rounded corner. So far, it's working perfectly.  The problem comes when I tried to scale the image to fit the width and height defined in the xml. The image dimension is bigger than the ImageView's size, so I use the scaling 'centerCrop' in the xml.

The result is that the rounded corner is nowhere to be seen (because of the scaling). I believe picasso applied the transformation first, then do the scaling so that the rounded corner is out of the view.

I have tried to re-order the image builder pattern, but the result is still the same.
Is there any way to tell Picasso to scale first, then transform?

**Comment by JakeWharton** [comment]
Transformations are always applied last: https://github.com/square/picasso/blob/289ed30e3814774a9a8b4b811dedb573056ef098/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java#L242-L248. Are you sure there isn't a scale type or a transformation on the View which is masking the corner?
