### ISSUE TITLE
transform() version that produces Drawable, not Bitmap

### ISSUE THREAD

**Issue by rongi** [square/picasso#1556]
This will be very useful with drawables that clip original bitmap. For example drawables that makes image with rounded corners or circle image from square bitmap.

Producing clipped bitmap from source bitmap directly is memory inefficient since it requires another memory allocation with size of original bitmap.

**Comment by JakeWharton** [comment]
For better or worse, Picasso is a Bitmap pipeline and we have no plans to change that.

By using `into(Target)` you're given the `Bitmap` and can apply any `Drawable` you want before setting it on the desired view.

**Comment by rongi** [comment]
@JakeWharton when using into(Target) you are forced to leave behind much more valuable feature of Picasso: proper handling of list view recycling :(

**Comment by JakeWharton** [comment]
You can call `cancel(Target)` when a view is recycled. It's the exact same mechanism.

**Comment by rongi** [comment]
@JakeWharton Ok, thank you for the hint
