### ISSUE TITLE
How to force download image from the back end for only a particular image ?

### ISSUE THREAD

**Issue by nitin070895** [square/picasso#1557]
In my Android App I have a Viewpager that shows banner images that are loaded from web URLs. The web URLs are saved in a database at back end that are sent to the app using an API call.  Suppose I have 2 images one of a cat and other of a dog, these two images are accessed from these two URLs (https://abc.com/cat.jpg and https://abc.com/dog,jpg) but now if I want to replace the image of a cat with an image of a Tiger with the same URL as that of the cat i.e https://abc.com/cat.jpg. 

The problem with Picasso is that it picks cat.jpg i.e the image of the cat from cache which has now been changed at the back end with the image of a tiger but with the same name cat.jpg.

So I want to ask if there is a way of avoiding the access of a particular image from the cache i.e disk cache and memory cache. If the image is changed but not the name of the image how can it be updated on the app.

**Comment by JakeWharton** [comment]
You can specify `memoryPolicy(NO_CACHE)` and `networkPolicy(NO_CACHE)` to skip the cache when making the request. That said, changing the image at a URL is a bad practice and you're much better off creating a new URL and sending that URL down in response to a web request.

**Comment by nitin070895** [comment]
Thankyou :)
