### ISSUE TITLE
For how long the images are kept in the cache.

### ISSUE THREAD

**Issue by nitin070895** [square/picasso#1558]
One image that is loaded via Picasso from the Internet is stored in memory cache and disk cache. I want to know for how many hours/days does the image will be kept in these caches.

**Comment by ismaellg** [comment]
@nitin070895 server's response will determinate how long an image is kept in disk cache. Please check http's cache control header.. and for both caches images may get evicted based on LRU strategy.

**Comment by JakeWharton** [comment]
Images are kept in the memory cache forever until they're pushed out by new ones or the process dies. The disk cache is maintained by the HTTP client, not Picasso, and so its retention policy is completely opaque to Picasso, although honoring the HTTP caching headers specified in the response is almost always going to be its behavior.

**Comment by nitin070895** [comment]
Thankyou .. :)
