### ISSUE TITLE
How to save loaded image ,text into internal storage for offline loading ?

### ISSUE THREAD

**Issue by joy-sec** [square/picasso#1560]
Hi,
I want to know 
How to save loaded image ,text into internal storage for offline load?

**Comment by JakeWharton** [comment]
We currently don't have an API to save to a File. Dupe of #506. If you want offline your best bet is to use a normal HTTP client to download and save images and then use Picasso to load them from disk.

**Comment by joy-sec** [comment]
then please share this method
