### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Target callback must not recycle bitmap! 

### ISSUE THREAD

**Issue by vleonovs** [square/picasso#1561]
Good Day,
I have a crash:

```
Fatal Exception: java.lang.IllegalStateException Target callback must not recycle bitmap!
com.squareup.picasso.TargetAction.complete (TargetAction.java:38)
com.squareup.picasso.Picasso.deliverAction (Picasso.java:558)
com.squareup.picasso.Picasso.complete (Picasso.java:517)
com.squareup.picasso.Picasso$1.handleMessage (Picasso.java:117)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7325)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```
The Target:
```
Target target = new Target() {

            @Override
            public void onPrepareLoad(Drawable arg0) {
            }

            @Override
            public void onBitmapLoaded(Bitmap arg0, LoadedFrom arg1) {
                if(image != null) {
                                     image.setImage(ImageSource.bitmap(arg0));
                }
            }

            @Override
            public void onBitmapFailed(Drawable arg0) {
            }
        };
```

and bitmap method:

    /**
     * Provide a loaded bitmap for display.
     * @param bitmap bitmap to be displayed.
     */
    public static ImageSource bitmap(Bitmap bitmap) {
        if (bitmap == null) {
            throw new NullPointerException("Bitmap must not be null");
        } else if (bitmap.isRecycled()) {
            bitmap = bitmap.copy(bitmap.getConfig(), true);
        }
        return new ImageSource(bitmap);
    }
what is wrong?

**Comment by caseykulm** [comment]
Same exact problem you had a couple months ago https://github.com/square/picasso/issues/1510

**Comment by JakeWharton** [comment]
Yep. And my comment on that issue still applies:

> This checks that you do not call `recycle()` on the `Bitmap` we hand you inside of a `Target#onBitmapLoaded` callback. The exception message indicates you are doing this.
