### ISSUE TITLE
Question - Is it possible to handle custom arguments in .load() method

### ISSUE THREAD

**Issue by prvnmit** [square/picasso#1562]
Is it possible to write a handler to manage custom arguments in the .load() function ?

For instance, I would pass package name and class name to the load() function

Picasso.with(context).load(packageName, className).into(imageVIew)

I would then want my custom handler to take in the packageName and className and build a resource uri for the app icon, and use the uri to fetch the image.

I also want the step that builds the resource uri from packageName and className to be executed in the background thread.

Can someone please suggest some way for this ?

Thanks.

**Comment by JakeWharton** [comment]
We have the [`RequestHandler`][1] API to support this use case.

 [1]: http://square.github.io/picasso/2.x/picasso/com/squareup/picasso/RequestHandler.html
