### ISSUE TITLE
Placeholder and error to respect rotation

### ISSUE THREAD

**Issue by ersin-ertan** [square/picasso#1571]
```java
            Picasso.with(getActivity())
                .load("bad url")
                .placeholder(R.drawable.img)
                .error(R.drawable.img)
                .rotate(rotation)
                .fit()
                .into(img);
```
Rotation occurs only if load succeeds, should/is there be a way to persist image rotation within the API for placeholder and error display.

**Comment by JakeWharton** [comment]
We have no plans to support this. Placeholder and error drawables are displayed as-is. Transformation APIs only apply to the loaded resource (URL or otherwise). Are you using rotations that are no 90 degree increments that you cannot provide placeholder or error drawables for?
