### ISSUE TITLE
NullPointerException: threadName == null

### ISSUE THREAD

**Issue by Auronake** [square/picasso#1572]
Hi Square's team!

We obtain this stack crash, from Crashlytics, with our production application : 

```
Fatal Exception: java.lang.NullPointerException: threadName == null
       at java.lang.Thread.setName(Thread.java:910)
       at com.squareup.okhttp.internal.NamedRunnable.run(SourceFile:31)
       at java.lang.Thread.run(Thread.java:818)
```

So, I look at in the buildGradle and we use only Picasso from square (which have a dependency with okhttp i guess) : com.squareup.picasso:picasso:2.5.2

This is arrived, for the moment, only on one device (so it isn't critical) : 
Samsung, SM-G901F with android 6.0.1

I don't have more informations about this crash. So, any ideas ?

Thank you!

**Comment by JakeWharton** [comment]
Picasso will use OkHttp but only if you've explicitly put a dependency on it. Perhaps it's coming transitively from some other dependency? In any case, this was likely a bug in OkHttp 2.x and not in Picasso itself. You could try explicitly using the latest version of OkHttp 2.x.

**Comment by Auronake** [comment]
Thks for the response.
We have excluded dependency in Picasso and import okhttp 3.5.0
