### ISSUE TITLE
Can't load Image from Firebase Storage

### ISSUE THREAD

**Issue by C0nstan** [square/picasso#1574]
I'm using picasso a lot in my app to load Images.
Now i want to load an Image from Firebase Storage, but Picasso doesn't load it into my ImageView.
I have tried it with an Simple Target too, but just the Prepare Function was called.
I dived in deeper to understand whats going on and i can see an
NetworkRequestHandler.ContentLengthException in the BitmapHunter.
I just don't know why this happens.

Picasso works everywhere else in my app, it just doesn't wants to load the Images from Firebase Storage.
Here is the image URL i try to load:

https://firebasestorage.googleapis.com/v0/b/findeling-dev.appspot.com/o/chats%2F704cf8be-3885-45a7-bbfe-ad1f19d86a74?alt=media&token=c5610680-afb3-4a1c-8401-d78155f1cd06

I tried it with an simple sample app, an it just works....don't know whats going on here.

Maybe i should say, that picasso loads the image the first time i've tried it.

the load function in NetworkRequestHandler gets a response with cached == true. This leads to an LoadedFrom Disk. But the length of the InputStream inside is zero.
I think this means, Picasso tries to load the Image from Disk, but can't find any data there.
There is a Comment in the NetworkRequestHandler:

    // Sometimes response content length is zero when requests are being replayed. Haven't found
    // root cause to this but retrying the request seems safe to do so.

It just retries the Request, but doesn't seem to delete the entry for the cach. So it always tries to load it from Disk.

EDIT: Maybe it tries to read from Network too. Here is an Extract of the response in OkHttpDownloader after this line of code:
`com.squareup.okhttp.Response response = client.newCall(builder.build()).execute();`

`response = {Response@7121} "Response{protocol=http/1.1, code=200, message=OK, url=https://firebasestorage.googleapis.com/v0/b/findeling-dev.appspot.com/o/chats%2F704cf8be-3885-45a7-bbfe-ad1f19d86a74?alt=media&token=c5610680-afb3-4a1c-8401-d78155f1cd06}"
 body = {Call$RealResponseBody@7126} 
  response = {Response@7140} "Response{protocol=http/1.1, code=200, message=OK, url=https://firebasestorage.googleapis.com/v0/b/findeling-dev.appspot.com/o/chats%2F704cf8be-3885-45a7-bbfe-ad1f19d86a74?alt=media&token=c5610680-afb3-4a1c-8401-d78155f1cd06}"
   body = {Cache$CacheResponseBody@7145} 
    bodySource = {RealBufferedSource@7152} "buffer((source(java.io.FileInputStream@f9b1f67)))"
    contentLength = "0"
    contentType = "image/jpeg"
    snapshot = {DiskLruCache$Snapshot@7155} 
  source = {RealBufferedSource@7141} "buffer(buffer((source(java.io.FileInputStream@f9b1f67))))"
  shadow$_monitor_ = -1927218144
 cacheControl = null
 cacheResponse = {Response@7127} "Response{protocol=http/1.1, code=200, message=OK, url=https://firebasestorage.googleapis.com/v0/b/findeling-dev.appspot.com/o/chats%2F704cf8be-3885-45a7-bbfe-ad1f19d86a74?alt=media&token=c5610680-afb3-4a1c-8401-d78155f1cd06}"
 code = 200
 headers = {Headers@7129} "ETag: "fa3bd61bd63e41162ca1481a9c562939"\nx-goog-generation: 1484134325528000\nx-goog-metageneration: 1\nx-goog-stored-content-encoding: identity\nx-goog-stored-content-length: 191365\nx-goog-meta-firebaseStorageDownloadTokens: c5610680-afb3-4a1c-8401-d78155f1cd06\nContent-Type: image/jpeg\nContent-Disposition: inline; filename*=utf-8''704cf8be-3885-45a7-bbfe-ad1f19d86a74\nx-goog-hash: crc32c=3NB61w==\nx-goog-hash: md5=+jvWG9Y+QRYsoUganFYpOQ==\nx-goog-storage-class: STANDARD\nAccept-Ranges: bytes\nX-GUploader-UploadID: AEnB2Up12U8og-A1_lSHG77qNcAdGrwIERffLjoHrbLrwuvk-zkZodcxRg-6nevYXUC09Koc5bEMibudP661jBQu4w6-JYRabQ\nExpires: Wed, 11 Jan 2017 12:23:23 GMT\nDate: Wed, 11 Jan 2017 12:23:23 GMT\nCache-Control: private, max-age=0\nLast-Modified: Wed, 11 Jan 2017 11:32:05 GMT\nContent-Length: 0\nServer: UploadServer\nAlt-Svc: quic=":443"; ma=2592000; v="35,34"\nOkHttp-Selected-Protocol: http/1.1\nOkHttp-Sent-Millis: 1484137407621\nOkHttp-Received-Millis: 1484137408345\n"
 message = "OK"
 networkResponse = {Response@7131} "Response{protocol=http/1.1, code=304, message=Not Modified, url=https://firebasestorage.googleapis.com/v0/b/findeling-dev.appspot.com/o/chats%2F704cf8be-3885-45a7-bbfe-ad1f19d86a74?alt=media&token=c5610680-afb3-4a1c-8401-d78155f1cd06}"`

**Comment by C0nstan** [comment]
It seems to be a problem with an older version of OkHttp. Updating to the newest version fixed the Issue :/

**Comment by JakeWharton** [comment]
Perfect. We updated the version on `master` and it will be required for the next release.

**Comment by dmitrikudrenko** [comment]
@C0nstan What okhttp's version do you use? I use 3.9.1 and receive 304 for some firebase storage paths

**Comment by C0nstan** [comment]
The Project i had the Error is using version 3.5.0

**Comment by anantshah93** [comment]
I am using the latest version, still not loading image...

**Comment by jeancsanchez** [comment]
The version 2.5.2 works for me.
