### ISSUE TITLE
Notification.contentview is deprecated on android 7.0+.

### ISSUE THREAD

**Issue by swy0710** [square/picasso#1575]
`Picasso.with(mContext)
.load(uri)
.into(notification.contentView, R.id.icon, MEDIA_NOTIFICATION_ID, notification);`

Because Notification.contentView is deprecated on android 7.0+ and and it can be null, My app keeps crashing.
I need your help.

**Comment by caseykulm** [comment]
Check if ```notification.contentView``` is null before trying to use it.

**Comment by JustZak** [comment]
Using deprecated fields at all seems unwise. Are there any other known workarounds to this?

**Comment by JakeWharton** [comment]
Deprecated does not mean non-functional. Workarounds are required for
things that are broken.

**Comment by rachray-rlj** [comment]
+1 on this issue

@JakeWharton There's a work around needed for Nougat as contentView returns null.

**Comment by JakeWharton** [comment]
`Notification#contentView` is not deprecated. If it's `null` then you shouldn't invoking Picasso since there's nowhere for it to load an image.
