### ISSUE TITLE
why Picasso is not loading " http://placehold.it/150/dff9f6" this url ? Can any body explain to me.

### ISSUE THREAD

**Issue by rohitbandil** [square/picasso#1577]

**Comment by JakeWharton** [comment]
What error occurs? What logs are you seeing?

**Comment by JakeWharton** [comment]
What version of the library? Are you using OkHttp? If so, OkHttp 2 or 3?

**Comment by rohitbandil** [comment]
I am using this "com.squareup.picasso:picasso:2.5.2" dependency.I am not using any library.It's just a simple hello test app.I have a problem with this url only, other API URL are easily loading.

**Comment by caseykulm** [comment]
@rohitbandil Do you have a log of the failure? That url works just fine for me.

**Comment by rohitbandil** [comment]
@caseykulm I am getting this error in the log - "301 Moved Permanently"

**Comment by tevjef** [comment]
Related to #463

**Comment by oscarg798** [comment]
@rohitbandil 301 is because http://placehold.it/150/dff9f6 redirects the request to https://placeholdit.imgix.net/~text?txtsize=14&bg=dff9f6&txt=150%C3%97150&w=150&h=150, but changing  the picasso downloader to OkHttpDownloader, worked for me. #463

**Comment by caseykulm** [comment]
@rohitbandil @oscarg798 Also the same solution that was suggested for #463 works here with/without the OkHttpDownloader,

> It is redirecting from HTTP to HTTPS and your client probably isn't
> handling that properly. Either request that URL with HTTPS so the redirect
> stays on the same protocol or drop OkHttp into your app (it will follow the
> cross-protocol redirect).

Changing http://placehold.it/150/dff9f6 to https://placehold.it/150/dff9f6 works with the default ```UrlConnectionDownloader```, and both urls work with the ```OkHttpDownloader```

**Comment by rohitbandil** [comment]
Yeah i have added https in my url and its working now.Thank you very much for you solution.

**Comment by rohitbandil** [comment]
@caseykulm solution worked for me
