### ISSUE TITLE
Images aren't loading

### ISSUE THREAD

**Issue by Brooklyn24** [square/picasso#1578]
http://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Nordpole.png/220px-Nordpole.png
http://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Map_of_the_McMurdo-South_Pole_highway.jpg/300px-Map_of_the_McMurdo-South_Pole_highway.jpg

Any other images are ok.  v2.5.2
"Nordpole.png/220px-Nordpole.png" and  does picasso cut url after first .png (two .jpg at second url)??

**Comment by caseykulm** [comment]
@Brooklyn24 Do you have a stacktrace? Those load fine for me.

**Comment by caseykulm** [comment]
@Brooklyn24 The same solution that was suggested for #1577 and #463 works here with/without the OkHttpDownloader,

> It is redirecting from HTTP to HTTPS and your client probably isn't
> handling that properly. Either request that URL with HTTPS so the redirect
> stays on the same protocol or drop OkHttp into your app (it will follow the
> cross-protocol redirect).

Changing http://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Nordpole.png/220px-Nordpole.png to https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Nordpole.png/220px-Nordpole.png and http://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Map_of_the_McMurdo-South_Pole_highway.jpg/300px-Map_of_the_McMurdo-South_Pole_highway.jpg to https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Map_of_the_McMurdo-South_Pole_highway.jpg/300px-Map_of_the_McMurdo-South_Pole_highway.jpg works with the default ```UrlConnectionDownloader```, and all urls work with the ```OkHttpDownloader```

**Comment by JakeWharton** [comment]
Supporting http to https redirects are now supported on master. The workaround for now is to use OkHttp as the HTTP client.
