### ISSUE TITLE
Memory isn't free when using multiple instance of Picasso

### ISSUE THREAD

**Issue by nvl2val** [square/picasso#1580]
I use multiple instance of Picasso in my project. Once I enter a `Fragment`, I get a new instance of Picasso to load url to my `ImageView`. But after I leave this Fragment and it's host activity, the heap memory does not decrease. The memory keeps increasing when I enter this Fragment every time. You can write two Master-Detail activities to test that: in detail activity, create a custom picasso instance to load image.

**Comment by JakeWharton** [comment]
Call `shutdown()` when you are leaving the scope of where an instance is useful. You won't be able to interact with the instance after calling this method.

**Comment by nvl2val** [comment]
Yes it works. Sorry for my ignorance.
