### ISSUE TITLE
Cannot load image to ImageView

### ISSUE THREAD

**Issue by clementf2b** [square/picasso#1581]
The picasso side           
                             

    Picasso.with(getApplicationContext()).load(product_data.getImage()).networkPolicy(NetworkPolicy.OFFLINE).into(detail_product_image, new Callback() {
                        @Override
                        public void onSuccess() {
                        }

                        @Override
                        public void onError() {
                            Picasso.with(getApplicationContext())
                                    .load(product_data.getImage())
                                    .placeholder(R.mipmap.app_icon)
                                    .error(R.mipmap.app_icon)
                                    .centerCrop()
                                    .into(detail_product_image);

                            detail_product_image.invalidate();
                        }
                    });
                }

My xml

     <?xml version="1.0" encoding="utf-8"?>
     <fyp.hkust.facet.util.VerticalScrollView
         xmlns:android="http://schemas.android.com/apk/res/android"
         xmlns:app="http://schemas.android.com/apk/res-auto"
         xmlns:emojicon="http://schemas.android.com/apk/res-auto"
         xmlns:expandableTextView="http://schemas.android.com/apk/res-auto"
         xmlns:tools="http://schemas.android.com/tools"
         android:id="@+id/activity_product_detail_scroll_layout"
         android:layout_width="match_parent"
         android:layout_height="match_parent"
         tools:context="fyp.hkust.facet.activity.ProductDetailActivity">

    <LinearLayout
        android:id="@+id/activity_product_detail_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:paddingBottom="@dimen/activity_vertical_margin"
        android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingTop="@dimen/activity_vertical_margin">

        <RelativeLayout
            android:id="@+id/detail_product_image_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.vatsal.imagezoomer.ImageZoomButton
                android:id="@+id/detail_product_image"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:src="@mipmap/ic_launcher" />

        </RelativeLayout>
       </LinearLayout>
       </fyp.hkust.facet.util.VerticalScrollView>

I cannot load the image after using the picasso. But I can see the image that I set in the layout preview but when I load the image to that imageview, it cannot show the image. I have checked that I have got a correct url for the image. Please give me some helps. Thank you.

**Comment by JakeWharton** [comment]
You specified an OFFLINE network policy which means Picasso is restricted to only the memory cache and disk cache and unable to load using the network. If the image isn't in those two caches then it won't show up.
