### ISSUE TITLE
Picasso can't load the picture when it's name contain "%".

### ISSUE THREAD

**Issue by ZhanQiangWu** [square/picasso#1582]
Picasso can't load the picture when it's name contain "%".eg,the path of the image is "/storage/emulated/0/dcim/%QPR5C8J5IS378WJK.png"
Is it a bug or my way to deal with it is wrong ?
Thank's for help!

**Comment by ZhanQiangWu** [comment]
I have resolved the problem.
just use
Picasso.load(new File("/storage/emulated/0/dcim/%QPR5C8J5IS378WJK.png"))
instead of
Picasso.load("file://"+"/storage/emulated/0/dcim/%QPR5C8J5IS378WJK.png")
when load the local picture

**Comment by JakeWharton** [comment]
Great. For what it's worth, the required prefixes are documented [on the `load(String)` method][1].

 [1]: http://square.github.io/picasso/2.x/picasso/com/squareup/picasso/Picasso.html#load-java.lang.String-
