### ISSUE TITLE
IllegalStateException in Picasso.setSingletonInstance()

### ISSUE THREAD

**Issue by sprilutsky** [square/picasso#1584]
Please add a new method for check singleton state of Picasso (may be - boolean isSingletonState()).
This is method need for check singleton state(singleton instance is exist) and after this is solution remove try -catch(IllegalStateException e)

**Comment by NightlyNexus** [comment]
What's your use case?

**Comment by sprilutsky** [comment]
we are have method which return Picasso instance
for example:
`public static final Picasso getPicasso(Context context){
Picasso.Builder builder = new Picasso.Builder(context); 
builder.downloader(new OkHttp3Downloader(Utils.generateImageCacheDir())); 
Picasso built = builder.build(); 
built.setLoggingEnabled(BuildConfig.DEBUG); 
Picasso.setSingletonInstance(built);
return built;`
And when we are use getPicasso second and another time, we have exception IllegalStateException in Picasso.setSingletonInstance(built) line;
Because we add try catch for Picasso.setSingletonInstance(build), but is bad solution.
bad solution:
try{
     Picasso.setSingletonInstance(built);
}catch(IllegalStateException e){
}

good solution(I think):
if(!Picasso.isExistSingletonStateInstance()){// may be another name for method
  Picasso.setSingletonInstance(built);
}

**Comment by NightlyNexus** [comment]
`Picasso.get(Context)` already returns the static singleton instance.
Obviously, the better solution is to cache result of your `getPicasso` method above into the appropriate scope, but I think you just want to `setSingletonInstance(built)` somewhere statically and then call `Picasso.get(Context)` to get it.

**Comment by JakeWharton** [comment]
Alternatively, don't bother with the singleton instance and just cache the instance you're creating yourself in a static field. After all, that's all `setSingletonInstance` is doing.

But I definitely recommend moving your call to `setSingletonInstance` to a place where it's guaranteed to only happen once (like in `Application.onCreate`) instead. Otherwise just keep your own static boolean that indicates whether you've called the method.

**Comment by parthanjaria** [comment]
But if we have some kind of method which will already tell us that setSingltonInstance is already called and we don't need to call again then it might not be and issue.
