### ISSUE TITLE
Failed to decode stream

### ISSUE THREAD

**Issue by masoudshahrabi** [square/picasso#1586]
I face this problem when i try to load jpeg images with 32 bit depth. I know jpeg files usually have 24 bit depth but the 32 bit ones can be loaded in regular browsers. However picasso cant handle this format.
This is the link I use:
http://arthibition.net/uploadCore/product/1395/06/thumbnail/mcmjxtlskr.jpg

**Comment by JakeWharton** [comment]
This error occurs when Android is unable to decode your image. There's nothing Picasso can do to correct this. Consider using another image format or re-encoding your image.
