### ISSUE TITLE
IOException: Failed to decode stream

### ISSUE THREAD

**Issue by mursidyazar** [square/picasso#1587]
https://s3.amazonaws.com/cactusexams/58aaf214425d7c0e5244d0ec1487598127433.jpeg

This image not load in api 23. It loads in api 21 smoothly. The logs and my codes are as follows. 

D/skia: --- decoder->decode returned false
W/System.err: java.io.IOException: Failed to decode stream.
W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

//CODES
Picasso.with(activity).setLoggingEnabled(true);
Picasso.Builder builder = new Picasso.Builder(activity);
builder.listener(new Picasso.Listener() {
       @Override
        public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception){
            exception.printStackTrace();
        }
});
builder.build().load(user.getProfileImageUrl()).into(itemIcon);

**Comment by JakeWharton** [comment]
This error occurs when Android is unable to decode your image. There's nothing Picasso can do to correct this. Consider using another image format or re-encoding your image.

**Comment by novodimaporo** [comment]
I has the same issue, its quite unpredictable, sometimes it loads and sometimes not. If its because android cant decode it, wouldn't it be always not?

**Comment by jays95jp** [comment]
I have same issue with API 26 (LGE Nexus 5X) Same log which one mention above.
Working fine with API 23
