### ISSUE TITLE
Pause/cancel tags on lifecycle events?

### ISSUE THREAD

**Issue by WildWeazel** [square/picasso#1588]
I was introduced to tag management via futurestud.io but they only give examples for view changes eg. scrolling list views. Is there any need or advantage to calling pause/cancel on a tag when a fragment or activity is paused or stopped, or is Picasso already aware of those events since it has the Context reference?

**Comment by JakeWharton** [comment]
Picasso does not monitor lifecycles automatically so using the tag with the fragment or activity instance and then batch canceling them when it leaves is definitely a wise decision.
