### ISSUE TITLE
picasso https

### ISSUE THREAD

**Issue by junyao-yu** [square/picasso#1595]
Picasso was how to support HTTPS to load the picture?

**Comment by JakeWharton** [comment]
Picasso sends all HTTP and HTTPS uris to an HTTP client. The default is HttpURLConnection which supports HTTPS but you can also provide your own `Downloader` such as for OkHttp or other HTTP clients.

**Comment by junyao-yu** [comment]
But why are some pictures of the HTTPS address, Picasso was loading images show out?
