### ISSUE TITLE
LruCache Fatal Exception: java.lang.IllegalArgumentException Max size must be positive.

### ISSUE THREAD

**Issue by lebedevsd1** [square/picasso#1602]
com.squareup.picasso.LruCache. (SourceFile:45)
com.squareup.picasso.LruCache. (SourceFile:39)
com.squareup.picasso.Picasso$Builder.build (SourceFile:835)
com.squareup.picasso.Picasso.with (SourceFile:662)

seems that Utils method is not working properly on Samsung galaxy S7 Edge
```
static int calculateMemoryCacheSize(Context context) {
    ActivityManager am = getService(context, ACTIVITY_SERVICE);
    boolean largeHeap = (context.getApplicationInfo().flags & FLAG_LARGE_HEAP) != 0;
    int memoryClass = am.getMemoryClass();
    if (largeHeap && SDK_INT >= HONEYCOMB) {
      memoryClass = ActivityManagerHoneycomb.getLargeMemoryClass(am);
    }
    // Target ~15% of the available heap.
    return 1024 * 1024 * memoryClass / 7;
  }
```

Either memoryClass was too big or it was negative.

**Comment by lebedevsd1** [comment]
Ups was using old version

**Comment by lebedevsd1** [comment]
picasso version 2.5.2

**Comment by NightlyNexus** [comment]
Oh, wow. Yes, I assume this is an overflow.
Does this happen consistently on the S7 Edge? I haven't seen this crash, and I wonder if there's a certain situation where the app is given way too much memory to use.
Picasso 3 could have `size` and `maxSize` as longs.

**Comment by lebedevsd1** [comment]
Hey, @NightlyNexus we saw this issue 3 times.
We assuming it is much more likely 0 was returned. Or it was a custom rom and format of returning value was not NNNm, but something else.
