### ISSUE TITLE
ImageView size not refreshed when loading from cache

### ISSUE THREAD

**Issue by alikyo** [square/picasso#1605]
Hello,

I have an imageView as the following

`<ImageView
            android:id="@+id/logo"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:adjustViewBounds="true"
            android:layout_gravity="center_horizontal" />`

When the image is loaded first time from the network the ImageView is rendred correctly and the height takes the height of the image. However when loading the Image the second time from the memory cache the imageView is not refreshed even if the image from the cache is there, the imageView height is not the same as the image.

Another scenario is if I set a placeholder, the second time the imageView keep the height the placeholder rather than the image loaded from the memory cache.

Any idea please ? I have already tried many workaround like invalidate the imageView on the callback but without success.

**Comment by AbhirojPanwar** [comment]
@alikyo  did you try with the resizing options of Picasso? Also try wrapping your imageview inside a frame layout? see if that works. I will try to produce the same error and get back.

**Comment by AbhirojPanwar** [comment]
@alikyo I tried reproducing the same error. Here is the code:- 

MainActivity:

```
package thenextvoyager.imageviewtest;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.ImageView;

import com.squareup.picasso.Picasso;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ImageView imageView=(ImageView) findViewById(R.id.image);
        Picasso picasso=Picasso.with(MainActivity.this);
        picasso.setIndicatorsEnabled(true);
        picasso.setLoggingEnabled(true);
        picasso.load("https://s-media-cache-ak0.pinimg.com/736x/53/32/59/533259d72d31b0f23bf1ad6091435255.jpg").into(imageView);
      }
}

```

activity_main.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="thenextvoyager.imageviewtest.MainActivity">


    <ImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:adjustViewBounds="true" />

</LinearLayout>
```
and it is working fine, I have not encountered such error. Please point out if I have missed any part of code that you have used but I havent. :)

**Comment by alikyo** [comment]
Hello,

I am loading the image inside a LayoutChangeListener because I need the image width before requesting the image url.

`imageView.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
                @Override
                public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                    imageView.removeOnLayoutChangeListener(this);
                    processLoadingImage(imageView, addImageProfileParams(imageUrl, imageView.getWidth()));
                }
            });`

`void processLoadingImage(ImageView imageView, String url) {
        picasso.load(url)
            .placeholder(R.drawable.default_product_visu_dark)
            .error(R.drawable.default_product_visu_dark)
            .into(imageView, LOG_ERROR);
    }`

When I move the call outside the listener (with a fixed Width) the issue is not reproducible.

**Comment by AbhirojPanwar** [comment]
Okay another workaround is to get the imagewidth , store it in a variable. And then you can do rest of the processing outside the listener.

```
imageView.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
                @Override
                public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                    imageView.removeOnLayoutChangeListener(this);
                    int imagewidth=imageView.getWidth();
                }
            });

                    processLoadingImage(imageView, addImageProfileParams(imageUrl, imagewidth));
```

**Comment by alikyo** [comment]
I have changed the `addOnLayoutChangeListener` to `imageView.getViewTreeObserver().addOnGlobalLayoutListener` and it is working fine now.

Thanks for help.

**Comment by AbhirojPanwar** [comment]
Ah! I see. Yeah, ViewTreeObservers are a good option if you want to check wether your layour has been drawn or not yet. :) Good to see it's working now. :)
