### ISSUE TITLE
load animation-list.xml into 

### ISSUE THREAD

**Issue by ChrisWhatever1980** [square/picasso#1607]
I thought this would work, at least neither errors nor exceptions are shown:

```
Picasso.with(this).load(R.drawable.qtidle).into(qtSelectButton);
AnimationDrawable qtIdleAnimation = (AnimationDrawable)qtSelectButton.getDrawable();
if (qtIdleAnimation != null)
    qtIdleAnimation.start();
```

However, qtIdleAnimation is null. qtidle is an animation-list:

```
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:oneshot="false">
    <item android:drawable="@drawable/qtidle1" android:duration="100" />
    <item android:drawable="@drawable/qtidle2" android:duration="100" />
    <item android:drawable="@drawable/qtidle3" android:duration="100" />
    <item android:drawable="@drawable/qtidle4" android:duration="100" />
    <item android:drawable="@drawable/qtidle5" android:duration="100" />
    <item android:drawable="@drawable/qtidle6" android:duration="100" />
    <item android:drawable="@drawable/qtidle7" android:duration="100" />
</animation-list>
```
I would like to suggest that Picasso creates an AnimationDrawable from an animation-list or returns an error code that loading of animation-list is not possible.

As an alternative, how should I use Picasso when creating the AnimationDrawable manually?
```
AnimationDrawable qtIdleAnimation = new AnimationDrawable();
qtIdleAnimation.setOneShot(false);
for (int i = 1; i <= 7; i++)
{
    int qtidleId = res.getIdentifier("qtidle" + i, "drawable", this.getPackageName());
    qtIdleAnimation.addFrame(res.getDrawable(qtidleId), 100);
}
qtSelectButton.setImageDrawable(qtIdleAnimation);
if (qtIdleAnimation != null)
    qtIdleAnimation.start();
```

**Comment by JakeWharton** [comment]
> ```
> Picasso.with(this).load(R.drawable.qtidle).into(qtSelectButton);
> ```

Is there a reason you're not doing `qtSelectButton.setDrawable(R.drawable.qtidle)` instead?

**Comment by ChrisWhatever1980** [comment]
Forgot to mention qtSelectButton is an ImageButton and as such has no setDrawable method. With setImageDrawable or any other option that does not use Picasso I get out of memory exceptions.

**Comment by JakeWharton** [comment]
We have no plans to support transformation pipelines for drawables and thus you should be setting the drawable directly onto the view with appropriately sized images.
