### ISSUE TITLE
Delay in loading image from disk cache with resize() API 

### ISSUE THREAD

**Issue by rvnareshkumar** [square/picasso#1608]
I am trying to reload the image using resize() API. Most of the time image is getting loaded from disk cache which causes a delay of 1 to 3 seconds in loading. Sometimes image gets loaded from memory cache which is loading pretty faster. Since we don't have a control on the caching mechanism is there a way I can load the image pretty faster from disk cache.

**Comment by JakeWharton** [comment]
No. Picasso loads it as fast as it can. You're limited by the disk speed, decoding speed, and the cost of switching threads.
