### ISSUE TITLE
Image from internet not loading

### ISSUE THREAD

**Issue by chizoba** [square/picasso#1609]
Image from the internet does not load for the current version (2.5.2), but works for version 2.3.3.
The .error(drawable) was what loaded in version 2.5.2

**Comment by JakeWharton** [comment]
There is not enough information to make this report actionable. Without logs, a stacktrace of the failure, a sample app, the URL of the picture, or some subset of those items it's impossible to know what's going on here.

If you're able to provide some of those we can re-open the issue.

**Comment by JakeWharton** [comment]
Also a lot of work has gone into the code on `master` since version 2.5.2 so you might want to try the 3.0.0-SNAPSHOT version and see if that magically fixes it.
