### ISSUE TITLE
can someone tell me where are the code control picture disk cache name '.0'  '.1'

### ISSUE THREAD

**Issue by zengbingao** [square/picasso#1611]
i c every picture will create 2 file in picasso-cache.one is include header info, name is inlcude'.0',another is include content info, name include '.1'.i cant find where the code do this. i c okhttp3 cache name also same with this, so i guess the code maybe in okhttp. Can someone tell me ?

**Comment by JakeWharton** [comment]
Picasso doesn't have a disk cache so this comes from the HTTP client. It's probably OkHttp but every HTTP client that has ever been supported by Picasso uses these files.
