### ISSUE TITLE
Picasso bug in recyclerview

### ISSUE THREAD

**Issue by ww6015132** [square/picasso#1615]
Now I have a recyclerview with Linearayout. 
When I'm downloading image from URL in onBindViewHolder:

`
@Override
    public void onBindViewHolder(final ItemViewHolder holder, final int position) {
           Picasso.with(context).load("someurl").into(holder.imageView);
    }`

The image are in different size. But the Image in the recyclerview seems to show the same height and some of them can not fully showing.Here is a screenshot of my recyclerview:
http://www.nyfilm.org/wp-content/uploads/2017/04/Screen-Shot-2017-04-14-at-5.16.24-PM.png

The layout xml of my itemView:

`
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="8dp">

    <ImageView
        android:id="@+id/image_item_artist_feed"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="centerCrop"/>
</LinearLayout>
`

**Comment by JakeWharton** [comment]
This doesn't seem like a problem with Picasso since the image is clearly being loaded. Have you tried setting `adjustViewBounds="true"` so that the `ImageView` resizes based on the set image?

**Comment by ww6015132** [comment]
Yes. I tried it. But based on API it says `adjustViewBounds` only works with `maxwidth/maxheight`. So I don't know if it's a good practice doing this.
And I have another question. 
Now I make the `imageview` as a background of items in `recyclerview`, and I  put the picasso code in `onBindViewholder` to download images. Now when the `recyclerview` is created, the height of all the items would be 0, and all the images have been downloaded which I don't want. I want to download the images dynamically. 
So do you think I should set a `minheight` for the `imageview` or there are other better solutions?
