### ISSUE TITLE
Image loading failed from specific Url

### ISSUE THREAD

**Issue by KeyurKba** [square/picasso#1616]
I have used Picasso so many times in my application, and thank you very much for making such good & useful library. But in my new project there is 1 issue. 

1. Image is not loading from some urls, for example take this url "http://www.free4me.dk/Images/Location/Location_9373011.jpg". This is valid Url working on all browsers & Postman. but picasso is not loading image from this server.

2. I have also checked with giving ConnectionTimeout, ReadTimeout, WriteTimeout etc, but still not working.

3. After using picasso:3.0.0-SNAPSHOT I found this error in callback
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 500

but this error comes in picasso library while browsers are able to show & download image.

**Comment by KeyurKba** [comment]
Ok update in this issue,
After using picasso:3.0.0-SNAPSHOT I found this error in callback
ecom.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 500

but this error comes in picasso library while browsers are able to show & download image.

**Comment by NickTet** [comment]
how to slove this pro

**Comment by KeyurKba** [comment]
I have used OkHttpClient and added it inside picasso dowloader. Here is my code: 

OkHttpClient.Builder b = new OkHttpClient.Builder();
        b.readTimeout(10000, TimeUnit.MILLISECONDS);
        //b.writeTimeout(15000, TimeUnit.MILLISECONDS);
        b.connectTimeout(15000,TimeUnit.MILLISECONDS);
        b.protocols(Arrays.asList(Protocol.HTTP_1_1));
        b.followRedirects(true);
        b.authenticator(Authenticator.NONE);
        b.followSslRedirects(false);
        b.interceptors().add(new okhttp3.Interceptor() {
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {
                Request newRequest = chain.request().newBuilder()
                        //.url("http://www.free4me.dk/Images/Location/Location_9373011.jpg")
                        .addHeader("Content-Type", "image/*")
                        .addHeader("User-Agent", "Mozilla")
                        .addHeader("Accept-Language", "en-US,en;q=0.8")
                        .get()
                        //.addHeader("Connection", "Keep-Alive")

                        //.method(chain.request().method(),chain.request().body())
                        .build();
                return chain.proceed(newRequest);
            }
        });
        okhttp3.OkHttpClient okHttpClient =b.build();


final Picasso picasso = new Picasso.Builder(context)
                .downloader(new OkHttp3Downloader(okHttpClient))
                .build();
