### ISSUE TITLE
Picasso rotate image in un-consistent way

### ISSUE THREAD

**Issue by Prasanna-Webhoop** [square/picasso#1624]
Picasso rotate image in un consistant way.
I am uploaded image to my server, but when i tried to show the image in my android application, image get rotates in un-consistent way. i.e it get's rotate by 90 degree.
I am using Device Samsung j6, but i found this same issue with other devices also like Sony Experia.

Please do reply on this issue,
Thank you.

**Comment by JakeWharton** [comment]
Picasso can't honor EXIF rotation on downloaded images because the built-in Android support for EXIF doesn't allow it. You should have your server or an intermediate image host like Thumbor perform the rotation so it doesn't have to be done client-side.
