### ISSUE TITLE
Remove the Context from Picasso.with()

### ISSUE THREAD

**Issue by SalvatoreT** [square/picasso#1634]
Follow the [trick that Firebase uses](https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html).

Store a reference to this application context and then the first time you called `Picasso.with()`, either use the instance you already set or create one on-the-fly. We already do that inside `with(Context)`, but we use the `Context` you pass in instead of one that we steal from a content provider.

- [x]  copy that content provider hack to set the application context onto `Picasso`
- [x]  change `with` to remove the argument and use that application context we set

**Comment by NightlyNexus** [comment]
Not everybody wants a ContentProvider or static instance of a Picasso in his or her app.

**Comment by JakeWharton** [comment]
The instance is still lazy. You can tools: remove the provider if you want, though all it does is stash a reference so it doesn't add startup overhead or anything.
