### ISSUE TITLE
load a lot of local pic faster 

### ISSUE THREAD

**Issue by andasl** [square/picasso#1640]
the thread pool is decided by current network state ,
but I want to load a lot of local pic or thumbnail， I think I need optimal size with the thread pool
instead of dynamic。
but the method is not public 
I cannot override
so...
could your please do thing with it
thinks.

**Comment by JakeWharton** [comment]
We allow supplying your own `Executor` if you want different behavior as part of the `Picasso.Builder`. We're not going to expose the auto-scaling mechanism as part of the public API though.

**Comment by andasl** [comment]
ah, I want to create a class like the default executor 'PicassoExecutorService', but  some class be used in PicassoExecutorService is not public,  BitmapHunter . 
so, I can not access it .
