### ISSUE TITLE
Loading an image from local storage fails when path is specified using String instead of File

### ISSUE THREAD

**Issue by a3y3** [square/picasso#1644]
The title says all. If you specify the path to the file as a String (considering how, the method load() has an overloaded method for load(String path)) it does not load.
It loads successfully if you covert the path from a String to a File
`File file = new File (path);
Picasso.with(context).load(file);`

**Comment by JakeWharton** [comment]
Does your string start with `file:///`?

**Comment by a3y3** [comment]
I used Environment.getExternalStorageDirectory() to store the path in a String. I'm guessing that does _not_ include "file:///"?

**Comment by Debasish1992** [comment]
Can you please paste anything specific? Like any exception or any errors you are getting while executing this? Stack trace if possible..

**Comment by ugurcmk** [comment]
@a3y3 you are right. Environment.getExternalStorageDirectory() returns path without "file///". if you add "file:///" prefix to the file then run properly
