### ISSUE TITLE
Not load this image

### ISSUE THREAD

**Issue by mslarco** [square/picasso#1650]
Please can not show this image
https://uisrael.edu.ec/wp-content/uploads/2017/07/195A0796-330x330.jpg
Can somebody help me

**Comment by JakeWharton** [comment]
With what error?

**Comment by mslarco** [comment]
07-18 17:06:56.463 14238-14238/com.mslarco.uisrael I/IMAGEN CARGANDO: imagen_url https://uisrael.edu.ec/wp-content/uploads/2017/07/195A0791-768x512.jpg
07-18 17:06:56.463 14238-14238/com.mslarco.uisrael I/IMAGEN PARA CARGAR: https://uisrael.edu.ec/wp-content/uploads/2017/07/195A0791-768x512.jpg
07-18 17:06:56.463 14238-14238/com.mslarco.uisrael W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
07-18 17:06:56.473 14238-15217/com.mslarco.uisrael W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.mslarco.uisrael/cache/picasso-cache/journal.tmp
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err: java.lang.IllegalStateException: Unrecognized type of request: Request{null}
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.BitmapHunter$2.load(BitmapHunter.java:66)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-18 17:06:56.623 14238-14238/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)``

**Comment by mslarco** [comment]
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael I/IMAGEN PARA CARGAR: https://uisrael.edu.ec/wp-content/uploads/2017/07/195A0791-300x200.jpg
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.Connection.connect(Connection.java:143)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:273)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:81)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:117)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-18 17:13:42.993 25277-25277/com.mslarco.uisrael W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by JakeWharton** [comment]
That's an HTTP exception from OkHttp trying to load your image. Picasso has no control over that. We just request the URL and decode the bytes. If the request is failing you need to sort out how to talk to your server first before something that sits on top of it, like Picasso, will work.
