### ISSUE TITLE
Picasso.load.into(ImageView) not working without hardware acceleration 

### ISSUE THREAD

**Issue by tolik85** [square/picasso#1652]
Hi,

I have a weird issue.
When I set android:hardwareAcceleration to "false" in my Manifest, Picasso.load.into(myImageView) is not presenting the image. But if I set this flag to true, it is.

Can you help find the cause of this?

Thanks!

**Comment by JakeWharton** [comment]
Seems like some kind of Android bug then. We don't control rendering. I
would file an issue on b.android.com/new with a sample project.
