### ISSUE TITLE
Android ImageView in RecyclerView has ghost after downloading and resizing by using Picasso

### ISSUE THREAD

**Issue by magiclen** [square/picasso#1653]
Please refer to https://stackoverflow.com/questions/45256445/android-imageview-in-recyclerview-has-ghost to see the screenshots.

There is an ImageView in each ViewHolder for the RecyclerView. However, some of the images shown by the ImageViews have ghost on some devices. The sources of these images are URLs loaded by Picasso. I found that this problem only happens after resizing the images.

I have tried to add `android:cacheColorHint="#00000000"` attribute to the RecyclerView, but it didn't work.

**Comment by JakeWharton** [comment]
Without a sample to reproduce the problem, I'm not sure why you think Picasso can do anything here. All it does is load the images you tell it and then set the resulting Bitmap on the target view or callback. Android is responsible for decoding images and rendering Bitmaps and one of those two seems to be failing.

**Comment by magiclen** [comment]
But Glide has no Ghost, only Picasso has.

See the partial code below:

    Picasso.with(activity).load(iconURL).config(Bitmap.Config.RGB_565).resize(iconSize, iconSize).onlyScaleDown();

   GlideApp.with(activity).load(iconURL).format(DecodeFormat.PREFER_RGB_565).override(iconSize, iconSize);

**Comment by JakeWharton** [comment]
Provide the image URLs
