### ISSUE TITLE
Image not loading when requested for first time

### ISSUE THREAD

**Issue by iamareebjamal** [square/picasso#1655]
I know there have been a lot of similar issues, but I have checked almost every one of them. None of them seems to explain why this should be the behavior.

I am using Data Binding for layout and thought the problem was that I was using a binding adapter to set the image using URL, but I tried moving the code in Activity and it is still not working.

```Java
Picasso.with(this)
    .load(Uri.parse(event.getLargeImageUrl()))
    .tag(BaseActivity.class)
    .into(headerBinding.image, new Callback() {
        @Override
        public void onSuccess() {
            Timber.d("Loaded");
        }

        @Override
        public void onError() {
            Timber.d("Error");
        }
    });
```

Neither of the callbacks is fired when the request is made for the first time, but if rotating the app, the image loads instantly (meaning it is stored in Picasso memory). The logs tell something similar too, but I don't know why it is not set.
Needless to say, neither the Context or ImageView is null

Image URL : https://media.licdn.com/media/AAEAAQAAAAAAAAdcAAAAJDNkMjFlMTNmLTNjMTMtNGRmNS04OTUwLTEwMzc2NzNhZDIxOA.png

However, this is same for any other image as well

Here are the logs for first request:
```
D/Picasso: Main        created      [R0] Request{https://media.licdn.com/media/AAEAAQAAAAAAAAdcAAAAJDNkMjFlMTNmLTNjMTMtNGRmNS04OTUwLTEwMzc2NzNhZDIxOA.png}
D/Picasso: Dispatcher  enqueued     [R0]+6ms 
D/Picasso: Hunter      executing    [R0]+7ms 
D/OkHttp: --> GET https://media.licdn.com/media/AAEAAQAAAAAAAAdcAAAAJDNkMjFlMTNmLTNjMTMtNGRmNS04OTUwLTEwMzc2NzNhZDIxOA.png http/1.1
D/OkHttp: --> END GET
D/Picasso: Hunter      removed      [R0]+487ms from 
D/Picasso: Dispatcher  canceled     [R0]+488ms 
D/OkHttp: <-- 200 OK https://media.licdn.com/media/AAEAAQAAAAAAAAdcAAAAJDNkMjFlMTNmLTNjMTMtNGRmNS04OTUwLTEwMzc2NzNhZDIxOA.png (642ms)
D/OkHttp: Accept-Ranges: bytes
D/OkHttp: Access-Control-Allow-Origin: *
D/OkHttp: Cache-Control: max-age=604800, immutable
D/OkHttp: Content-Type: image/png
D/OkHttp: Date: Sat, 22 Jul 2017 12:45:15 GMT
D/OkHttp: Expires: Sat, 29 Jul 2017 12:45:15 GMT
D/OkHttp: Last-Modified: Thu, 02 Jun 2016 02:28:36 GMT
D/OkHttp: Server: ECS (sin/BF31)
D/OkHttp: Timing-Allow-Origin: *
D/OkHttp: x-ambry-blob-size: 12539
D/OkHttp: X-Cache: MISS
D/OkHttp: X-CDN: ECST
D/OkHttp: X-CDN-CLIENT-IP-VERSION: IPV6
D/OkHttp: X-CDN-Proto: HTTP1
D/OkHttp: X-Li-Fabric: prod-lsg1
D/OkHttp: X-Li-Pop: prod-esg3
D/OkHttp: X-LI-Proto: http/1.1
D/OkHttp: X-LI-UUID: EagA4vMR1RSAnErUACsAAA==
D/OkHttp: Content-Length: 12539
W/art: Suspending all threads took: 9.016ms
D/OkHttp: <-- END HTTP (binary 12539-byte body omitted)
D/Picasso: Hunter      decoded      [R0]+772ms 
D/Picasso: Dispatcher  batched       for completion
```
No callback invoked

This is the log for the second request:
```
D/Picasso: Main        created      [R1] Request{https://media.licdn.com/media/AAEAAQAAAAAAAAdcAAAAJDNkMjFlMTNmLTNjMTMtNGRmNS04OTUwLTEwMzc2NzNhZDIxOA.png}
D/Picasso: Main        completed    [R1] from MEMORY
D/MainActivity: Loaded
```

Loaded here

**Comment by iamareebjamal** [comment]
Working on 2.6.0-SNAPSHOT

**Comment by NightlyNexus** [comment]
btw, if you're going to use a snapshot, you can use 3.0.0-SNAPSHOT.

**Comment by iamareebjamal** [comment]
When using 3.0.0-SNAPSHOT, the jar isn't included in the project. Works fine with 2.6.0, any special considerations for adding it?

`compile 'com.squareup.picasso:picasso:2.6.0-SNAPSHOT'`

I'm simply replacing the version to 3.0.0 here. Also tried appending @aar to it

**Comment by homandiy** [comment]
I cannot load the samples.
