### ISSUE TITLE
can't load with chinese character url

### ISSUE THREAD

**Issue by t894924815** [square/picasso#1656]
when i load a url like "https://cdn.soundlinks.net/%E6%9F%AF%E6%99%BA%E6%A3%A0.png"

it will catch a exception:
java.lang.IllegalArgumentException: Unexpected char 0x67ef at 18 in header value: inline; filename="柯智棠.png"; filename*=utf-8' '%E6%9F%AF%E6%99%BA%E6%A3%A0.png
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.Headers$Builder.checkNameAndValue(Headers.java:295)
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.Headers$Builder.add(Headers.java:245)
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.internal.http.Http2xStream.readSpdy3HeadersList(Http2xStream.java:237)
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:151)
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
07-29 17:07:52.687 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:287)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:80)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:117)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-29 17:07:52.688 10104-10104/net.soundlinks.summersonic W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-29 17:07:52.689 10104-10104/net.soundlinks.summersonic W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-29 17:07:52.689 10104-10104/net.soundlinks.summersonic W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by NightlyNexus** [comment]
Does this still occur in OkHttp 3.8.1?
Try using Picasso 3 snapshots or https://github.com/JakeWharton/picasso2-okhttp3-downloader

**Comment by JakeWharton** [comment]
Yeah the problem here is OkHttp 2.x and not Picasso. Using the OkHttp 3.x
Downloader or the 3.0.0 snapshots which use OkHttp 3.x directly will
resolve the issue.
