### ISSUE TITLE
Picasso Not Loading HTTPS Facebook Links

### ISSUE THREAD

**Issue by jonathansds** [square/picasso#1657]
Hi there,
Before you set the question/issue as duplicate, please read it all first.

I know it is a known issue and there's loads of question on Stackoverflow and issues on Github but believe me I tried them all.

**ISSUE**
Not loading this link:

`https://scontent.xx.fbcdn.net/v/t1.0-1/p200x200/13872950_1066865640060722_8272182690153279858_n.jpg?oh=66a4ff80019c1fbf79bee45d32f03468&oe=59F65F50
`

**MY CODE**

`Target target = new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                userPicture.setImageDrawable(FunctionUtil.roundBitmap(bitmap));
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable) {
                Resources resources = getContext().getResources();
                Bitmap bitmap = BitmapFactory.decodeResource(resources, R.drawable.ic_image_content_error);

                userPicture.setImageDrawable(FunctionUtil.roundBitmap(bitmap));
            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {
                Resources resources = getContext().getResources();
                Bitmap bitmap = BitmapFactory.decodeResource(resources, R.drawable.ic_image_placeholder);

                userPicture.setImageDrawable(FunctionUtil.roundBitmap(bitmap));
            }
        };
        Picasso.with(getContext()).load(me.getPicture().getUrl()).into(target);
`

**WHAT I HAVE TRIED**

NO CACHE:
`Picasso.with(getContext()).load(me.getPicture().getUrl()).memoryPolicy(MemoryPolicy.NO_CACHE).networkPolicy(NetworkPolicy.NO_CACHE).into(target);`

**Comment by NightlyNexus** [comment]
This is a duplicate https://github.com/square/picasso/issues/1658 right?

**Comment by jonathansds** [comment]
Oh yea, I actually thought this one hadn't been published. This is duplicated yea.
