### ISSUE TITLE
Picasso Not Loading HTTPS Facebook Links

### ISSUE THREAD

**Issue by jonathansds** [square/picasso#1658]
Hi there,
Before you set the question/issue as duplicate, please read it all first.

I know it is a known issue and there's loads of question on Stackoverflow and issues on Github but believe me I tried them all.

**ISSUE**
Not loading this link:

    https://scontent.xx.fbcdn.net/v/t1.0-1/p200x200/13872950_1066865640060722_8272182690153279858_n.jpg?oh=66a4ff80019c1fbf79bee45d32f03468&oe=59F65F50

**MY CODE**

        Target target = new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                userPicture.setImageDrawable(FunctionUtil.roundBitmap(bitmap));
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable) {
                Resources resources = getContext().getResources();
                Bitmap bitmap = BitmapFactory.decodeResource(resources, R.drawable.ic_image_content_error);

                userPicture.setImageDrawable(FunctionUtil.roundBitmap(bitmap));
            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {
                Resources resources = getContext().getResources();
                Bitmap bitmap = BitmapFactory.decodeResource(resources, R.drawable.ic_image_placeholder);

                userPicture.setImageDrawable(FunctionUtil.roundBitmap(bitmap));
            }
        };
        Picasso.with(getContext()).load(me.getPicture().getUrl()).into(target);

**WHAT I HAVE TRIED**

NO CACHE:
 `Picasso.with(getContext()).load(me.getPicture().getUrl()).memoryPolicy(MemoryPolicy.NO_CACHE).networkPolicy(NetworkPolicy.NO_CACHE).into(target);`

NEW DOWNLOADER:
    `new Picasso.Builder(getContext()).downloader(new OkHttpDownloader(getContext())).build().load(me.getPicture().getUrl()).into(target);`

BOTH:
    `new Picasso.Builder(getContext()).downloader(new OkHttpDownloader(getContext())).build().load(me.getPicture().getUrl()).memoryPolicy(MemoryPolicy.NO_CACHE).networkPolicy(NetworkPolicy.NO_CACHE).into(target);`

What am I doing wrong?

**Comment by NightlyNexus** [comment]
Are you holding a reference to your Target anywhere non-locally? Picasso only holds weak references to Targets, so it looks like it's getting garbage collected here.

**Comment by jonathansds** [comment]
No I'm not. This code is all inside a method. Should I declare Target as global property to hold an instance outside the method instead?

**Comment by NightlyNexus** [comment]
Hold a reference to it for as long as your userPicture is around (like a field in the controller class). Typically, custom Views implement the Target interface.

**Comment by jonathansds** [comment]
Humm... I will do it now. Give me 1 minute.

**Comment by jonathansds** [comment]
It worked!! Just perfectly! So my mistake was creating the Target as a local method property then when Picasso took a little bit more time to load the image maybe the Garbage Collector cleaned the Target reference which was make it impossible to Picasso to load it into the Target. That is why it SOMETIMES worked.
Thanks so much for the support, you are the best!!
