### ISSUE TITLE
Error with url with user:password@

### ISSUE THREAD

**Issue by AlbertoMrFz** [square/picasso#1660]
its possible to show image that their url has user:password@

**Comment by JakeWharton** [comment]
Picasso deals in Uris so yes. What problem are you having?

**Comment by AlbertoMrFz** [comment]
I don´t kwno how make then

**Comment by JakeWharton** [comment]
`Uri.parse` a string containing them or create a `Uri.Builder` and supply the values to the appropriate builder methods. Then hand Picasso the resulting `Uri` instance from either.
