### ISSUE TITLE
general usage question

### ISSUE THREAD

**Issue by cristianbell** [square/picasso#1661]
Hi, 

this is not an issue as it is a general usage question: 

following scenario: I have a list of "friends" in the app and I need to be able to see them in a list. Best scenario the images will be downloaded once and saved to the local storage. Always displayed from the local storage (disk) or memory and only refreshed at once a refresh is triggered.  

All implemented using `.load(url)... .into(imageView)`. I was hoping that picasso will automagically save the images to the local storage and display them from there, but it seems that it does not do that. 

I assume that the correct workflow is: _save images to local storage_ -> _display images from local storage (multiple times)_ -> _re-download them when triggered_? 
Though this is a little disappointing since I already had a class that was doing this, saving locally, displaying it when already local and re-downloading it when required. The benefit of picasso in my case is the nice caching/mem management and 3 tries before it fails..

**Comment by JakeWharton** [comment]
Picasso does not deal with storage. The only cache it has is an in-memory one. It delegates to the `Downloader` implementation for any on-disk storage, usually in the form of an HTTP cache. If you want something more persistent or managed in a different way, you can create your own `Downloader` implementation which uses an HTTP client to download files to wherever you want and then returns them to Picasso to use.

**Comment by cristianbell** [comment]
thanks for the answer, this is more or less what I thought.
