### ISSUE TITLE
image load into wrong item

### ISSUE THREAD

**Issue by MashirosBaumkuchen** [square/picasso#1673]
image (from url) load in wrong position when the datalist.picUrl contains null.

**Comment by JakeWharton** [comment]
Sounds like you're either:
* not calling Picasso when the URL is null (which is wrong)
* calling `load` in an `if` and not calling `cancel` in an else.

Without code or a sample that reproduces this report is not actionable from our side.

**Comment by MashirosBaumkuchen** [comment]
solved it with `if`, & in `else`  loading a default bitmap while `url==null`.

also where`s someone told me that we can use `gilde` to avoid it.
