### ISSUE TITLE
About the 3 methods:cancel(), pause() and resume()

### ISSUE THREAD

**Issue by nicLucian** [square/picasso#1674]
I do not understand why the cancel() method's parameter is a Tag and the others are Action.
Why the cancel()'s main work is happening in Picasso where the others in Dispatcher, why they are not in the same class.

**Comment by JakeWharton** [comment]
All three take a tag. Cancel updates state synchronously so that you can make additional requests on the main thread and ensure correct behavior. Pause and resume are meant more as hints and not guarantees.
