### ISSUE TITLE
How does Picasso solve the image mismatch issue

### ISSUE THREAD

**Issue by gongzelong0718** [square/picasso#1675]
I notice the comments @JakeWharton wrote in the previous issue.

https://github.com/square/picasso/issues/83

> But only if you are not in a list/grid adapter! Requesting an image for the same imageview/target (e.g., in an adapter getView) will do this automatically. You should only need to cancel (and you don't actually need to) if you're making requests and then leaving the screen.

https://github.com/square/picasso/issues/1302

> Picasso keeps a map of ImageView -> URL and when the same ImageView is seen twice, the loading of the original URL is canceled and and new one is started.

I have read the source codes but I think I did not get it totally.

> Picasso automatically sees when views are being re-used and will cancel old downloads for that image view

My question is how the logic above is written in the codes? What are the related codes?

**Comment by JakeWharton** [comment]
The code is in `Dispatcher`. You can follow either the `into` method on `RequestCreator` or the `cancel` method on `Picasso` to see what it does.
