### ISSUE TITLE
Caching does not work by using different Uris

### ISSUE THREAD

**Issue by stephanAuto1** [square/picasso#1679]
Version 2.5.2

First call:
Picasso.with(getActivity())
            .load(/data/user/0/com.auto1.msi.dev/app_DV79045/DV79045_1506942670831.jpg)
            .into(ivCameraCapture);

Second call:
Picasso.with(getActivity())
            .load(/data/user/0/com.auto1.msi.dev/app_DV79045/DV79045_1506943447364.jpg)
            .into(ivCameraCapture);

In the second call, Picasso uses the first jpg, DV79045_1506942670831.jpg. It should load DV79045_1506943447364.jpg.

If I switch off caching then second image is shown, call are as follows:

First call:
Picasso.with(getActivity())
            .load(/data/user/0/com.auto1.msi.dev/app_DV79045/DV79045_1506942670831.jpg)
            .into(ivCameraCapture);

Second call:
Picasso.with(getActivity())
            .load(/data/user/0/com.auto1.msi.dev/app_DV79045/DV79045_1506943447364.jpg)
            .memoryPolicy(MemoryPolicy.NO_CACHE)
            .into(ivCameraCapture);

 DV79045_1506943447364.jpg is loaded now. The call is made in one onActivityResult, perhaps there is an issue in relation to it.

**Comment by JakeWharton** [comment]
The Uri is used as the key. I can't see how this could happen. Please
provide a failing test case or sample that demonstrates the bug.
