### ISSUE TITLE
Activity instance leaking memory due to Picasso singleton

### ISSUE THREAD

**Issue by chwakil** [square/picasso#1686]
One of my activity sometimes detect by leakcanary due to memory leak by Picasso singleton.
![screenshot_2017-10-18-16-31-04](https://user-images.githubusercontent.com/4036141/31716968-9682365e-b423-11e7-9c31-fa5e28c080db.jpg)

In this activity I load fragments with images dynamically. I use Application context in Picasso.with(applictionContext) in my whole project. Why is it happening sometimes ?

**Comment by JakeWharton** [comment]
Are you canceling requests when the activity is destroyed?

**Comment by chwakil** [comment]
I do not kknow is this the proper way? But I am setting null adapter in recylerView in onDestroy() of Fragment like below:
if (this.adapter != null && this.adapter.objects != null) {
            this.adapter.objects.clear();
            this.adapter.notifyDataSetChanged();
            if (this.recyclerView != null) {
                this.recyclerView.setAdapter(null);
                this.recyclerView = null;
      }
        }

**Comment by JakeWharton** [comment]
Yep! That's exactly what I was referring to. This eagerly frees the reference when the object is going away and stops Picasso from doing work that won't be used anyway.
