### ISSUE TITLE
Picasso not loaded from 25api 

### ISSUE THREAD

**Issue by pphilipp** [square/picasso#1687]
I've been faced with the problem.
loading image is:

> https://farmer.arlafoods.de/nextshopcms/cmsimage.asp?id=5684&fkt=3

I thought that the problem related to server (.asp) response and url don't have a format like `.png` or 
`.jpg` but in other cases, I **able** to load some links like http://goo.gl/gEgYUd.
Additionally, the strange thing that I able to load this link in a browser and Postman.

Diving to the logs from Picasso I've seen that this particular url has some error.
As I understand the Dispatcher added some delay for loading image and again and again. 

> Dispatcher  batched      [R60]+431ms for completion
> Dispatcher  batched      [R60]+359ms for completion
.
.
and as a result 
> Dispatcher  batched      [R60]+2216ms for error

I've put an OkHttpClient with timeout delay in 10 sec but it doesn't help.
Is anybody has some ideas how to hold this case?

_Update_

I found some facts that the request makes based on device resolution _resize(xxx,xxx)_ .

> Main        created      [R58] Request{https://farmer.arlafoods.de/nextshopcms/cmsimage.asp?id=5684&fkt=3 resize(720,1134) centerInside}

And for resolution **720,1134** it works. But for Nexus 6p with resolution (1440,2308) the particular image, not loaded.

_Update_ 2.0
Doesen't work on any devices from 25 api.

**Comment by JakeWharton** [comment]
2048 is the maximum texture size on that device. BitmapFactory will refuse to load any image larger than that size.
