### ISSUE TITLE
Image loading issue to some devices 

### ISSUE THREAD

**Issue by rahuldevanavar91** [square/picasso#1695]
I am using Picasso for image loading everything working fine for me.

for some devices below 4.4.4 images are not loading when I debugged Picasso I got the following logs
java.net.ConnectException: failed to connect to media6.ppl-media.com/2600:9000:2027:6e00:18:659c:a80:93a1 (port 443) after 10000ms: isConnected failed: ENETUNREACH (Network is unreachable)

**Comment by JakeWharton** [comment]
That's not something Picasso controls. The inability to talk to the network is a fundamental issue far below Picasso and would fail for anyone trying to use the network.

**Comment by rahuldevanavar91** [comment]
But  its specifically happing with Picasso and android version below KitKat

**Comment by JakeWharton** [comment]
What in Picasso could cause that though? It calls into the Downloader to
fetch images from the network which uses either HttpURLConnection or OkHttp.
