### ISSUE TITLE
JNI crash

### ISSUE THREAD

**Issue by itcayman** [square/picasso#1699]
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422] "Picasso-Idle" prio=5 tid=123 Waiting
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x13475dc0 self=0xc588fc00
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422]   | sysTid=22203 nice=10 cgrp=bf_non_interactive sched=0/0 handle=0xc49a2920
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 75917508 78651192 221 ) utm=7 stm=0 core=1 HZ=100
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422]   | stack=0xc48a0000-0xc48a2000 stackSize=1038KB
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422]   | held mutexes=
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x70/0x7c
11-02 16:41:07.714 21893-21900 A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xe4/0x144
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xfc/0x208
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xdc/0x8a4
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_futex+0xdc/0x168
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   kernel: el0_svc_naked+0x24/0x28
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   native: #00 pc 00017514  /system/lib/libc.so (syscall+28)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   native: #01 pc 000b6ec9  /system/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+92)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   native: #02 pc 0029f98f  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadExibNS_11ThreadStateE+514)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a11bf  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   native: #04 pc 002afa7f  /system/lib/libart.so (_ZN3artL13Object_waitJIEP7_JNIEnvP8_jobjectxi+36)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   native: #05 pc 00000655  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__JI+96)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.lang.Object.wait!(Native method)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   - waiting on <0x0a6c1f3b> (a java.lang.Object)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.parkFor$(Thread.java:2127)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   - locked <0x0a6c1f3b> (a java.lang.Object)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   at sun.misc.Unsafe.park(Unsafe.java:325)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
11-02 16:41:07.714 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:519)
11-02 16:41:07.715 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
11-02 16:41:07.715 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
11-02 16:41:07.715 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-02 16:41:07.715 21893-21900  A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.run(Thread.java:761)
11-02 16:41:07.715 21893-21900  A/art: art/runtime/runtime.cc:422]   at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by JakeWharton** [comment]
There's nothing Picasso can do about this. The problem is in ART. Report to http://b.android.com/new.
