### ISSUE TITLE
Connection closed by peer

### ISSUE THREAD

**Issue by Faisal-Naseer** [square/picasso#1700]
I am getting an error 
```
String img = "https://www.imarketer.com.au//campaignAssets/1/ry4xi1mcmpvg5xo8rgv9/WBBHiPadComp768x1024.png";
        Log.d("HEADER_IMAGES",img);

        if(!campaign.getHeaderImage().equals("")){
            Picasso.Builder builder = new Picasso.Builder(ctx);
            builder.listener(new Picasso.Listener()
            {
                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception)
                {
                    exception.printStackTrace();

                }
            });
            builder.build().load(Uri.parse(img )).into(holder.campaign_image);
```
Connection closed by peer

**Comment by JakeWharton** [comment]
This message means the server closed the connection for some reason. Picasso will retry the request up to two more times before eventually marking it as failed. You're either not passing the necessary information in the request for the server to allow you to complete the response or the server is misconfigured. This isn't a specific problem with the library, though.

**Comment by Faisal-Naseer** [comment]
Actually the same problem arised when i was making restful request using okHttp to particular server as TLS wasn't enabled on my device. I added trust managers in ApiClient using retrofit and it started working but now in case of Picasso I have read that it takes into account okHttp then  falls back to some other library like  HttpURLConnection but my question is how can i attach TrustManager to Picasso Request. thanks..
```
 TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            trustManagerFactory.init((KeyStore) null);
            TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
            if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
                throw new IllegalStateException("Unexpected default trust managers:" + Arrays.toString(trustManagers));
            }
            X509TrustManager trustManager = (X509TrustManager) trustManagers[0];
            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, new TrustManager[] { trustManager }, null);

            okHttpClient = new OkHttpClient.Builder()
                    .readTimeout(60, TimeUnit.SECONDS)
                    .connectTimeout(60, TimeUnit.SECONDS)
                    .connectionSpecs(Collections.singletonList(spec))
                    .sslSocketFactory(new TLSSocketFactory(),trustManager)
                    .build();
```

**Comment by NightlyNexus** [comment]
You can use that OkHttpClient instance for your Picasso Downloader.

When creating your Picasso instance: `Picasso picasso = new Picasso.Builder().downloader(new OkHttp3Downloader(okHttpClient).build()`
