### ISSUE TITLE
When Trying to integrate  with Picasso i got this error when running the app and i dont use mpulse.soasta 

### ISSUE THREAD

**Issue by hanihussein** [square/picasso#1701]
Error:Execution failed for task ':app:transformClassesWithLetForDebug'.
> aspect com.soasta.mpulse.android.aspects.URLConnectionExceptionsAspect cannot be found when reweaving com.squareup.picasso.UrlConnectionDownloader [Xlint:missingAspectForReweaving]

**Comment by JakeWharton** [comment]
This isn't a problem with Picasso. Something in your build is doing AspectJ bytecode weaving and failing on a Picasso class.
