### ISSUE TITLE
Picasso to byte array return NullPointerException when drawable Bitmap. please help T^T

### ISSUE THREAD

**Issue by lwlittayat** [square/picasso#1702]
i have a ploblem when i display Picasso imageview and get bitmap is null
Picasso.with(topicass.getContext()).load(url in googleDrive).into(ImageView);
byte[] image = imageViewToByte(ImageView); // i use byte array to sqlite BLOB

//here imageViewToByte
    public static byte[] imageViewToByte(ImageView image) {
        Bitmap bitmap = ((BitmapDrawable) image.getDrawable()).getBitmap();
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.JPEG, 100, stream);
        byte[] byteArray = stream.toByteArray();
        return byteArray;
    }

please help

**Comment by JakeWharton** [comment]
Bitmaps are loaded asynchronously. Use the callback to be informed of when the image is loaded.

**Comment by lwlittayat** [comment]
I'll take a stab at it. thx JakeWharton

**Comment by lwlittayat** [comment]
professor i need some help.
when i For looping get url like this (https://images-na.ssl-images-amazon.com/images/I/91zd5c1CzML._SX522_.jpg , ...)
`for (int i = 0; i < url.length(); i++) {
    Picasso.with(this).load(url[i]).into(ImageView,new Callback() {
                    @Override
                    public void onSuccess() {
                        Log.d("PICASSO","onSuccess");
                        //do smth when picture is loaded successfully
                        byte[] byte= imageViewToByte(ImageView); //here i get byte array for insert to sqlite
                        String base64= EncodeIVtoBase64(ImageView); //here i get byte array for insert to google script

                    }

                    @Override
                    public void onError() {
                        //do smth when there is picture loading error
                        Log.d("PICASSO","onError");
                    }
                });
}
  `
i need result of this--if url1,url2,url3 i get (byte[0],byte[1],byte[2]) and string base64 3 value
but picasso onSuccess result is byte[2] and base64 last url[3]
url1 and url2 Missing 
please help . i don't know What should I do?

**Comment by JakeWharton** [comment]
Loading into the same image view will cancel previous requests. Also that
callback is on the main thread where you shouldn't be doing computationally
expensive work like base64-encoding an image.
