### ISSUE TITLE
picasso+recyclerview shows disordered(picasso:2.5.2)

### ISSUE THREAD

**Issue by cyhwtc** [square/picasso#1705]
picasso+recyclerviewload from file shows disordered.

version:2.5.2

when recyclerview scroll fast ,the imae shows disordered.

 some code here:

 private void loadByPicasso(File file, Picasso picasso, @NonNull ViewHolder holder) {
        picasso
                .load(file)
                .resize(230, 230)
                .centerInside()
                .tag(Constants.PICASSO_TAG)
                .config(Bitmap.Config.RGB_565)
                .placeholder(R.drawable.loading_bar)
                .placeholder(holder.mImageView.getDrawable())
                .error(R.drawable.ic_no_images)
                .into(holder.mImageView, new com.squareup.picasso.Callback() {
                    @Override
                    public void onSuccess() {
                        Log.d(TAG, "picasso load onSuccess");
                    }

                    @Override
                    public void onError() {
                        Log.w(TAG, "picasso load onError");
                    }
                });
    }

**Comment by JakeWharton** [comment]
Can you try with 3.0.0-SNAPSHOT?

**Comment by jouvyap** [comment]
is there any update for this issue?

**Comment by JakeWharton** [comment]
With no response from the author, no.
