### ISSUE TITLE
JPEG 2000 support ?

### ISSUE THREAD

**Issue by alikyo** [square/picasso#1707]
Hello guys,

Please, Is jp2 (JPEG 2000) supported by Picasso ?

Br.

**Comment by JakeWharton** [comment]
Picasso uses Android to decode images. If Android supports it, Picasso does too. If Android doesn't support it then Picasso doesn't.

**Comment by JakeWharton** [comment]
You can find supported formats here: https://developer.android.com/guide/topics/media/media-formats.html#image-formats
