### ISSUE TITLE
Image cannot be displayed - Error thrown

### ISSUE THREAD

**Issue by SebSpi91** [square/picasso#1716]
Hello,

we are using your library & found out that some images cannot be displayed with the library. Picasso just throw an error.

Here is the example image:

[683564.jpg.zip](https://github.com/square/picasso/files/1554755/683564.jpg.zip)

Best regards,
Sebastian

**Comment by JakeWharton** [comment]
What error?

**Comment by SebSpi91** [comment]
Hello,

this is written to the logcat:

`D/Picasso: Main created [R65] Request{file:///mnt/internal_sd/Android/data/player/files/media_files/15fbab080bcc9af869969e673676de57 resize(1920,1080) centerInside}`
`D/Picasso: Dispatcher  enqueued     [R65]+1ms `
`D/Picasso: Hunter      executing    [R65]+3ms `
`D/Picasso: Dispatcher  batched      [R65]+568ms for error`

**Comment by JakeWharton** [comment]
You need to attach an error listener on the `Picasso.Builder` and log the full stack trace on 2.x. Otherwise you can try 3.0.0-SNAPSHOT which will log the full stacktrace by default (or at least the message).
