### ISSUE TITLE
Q: How do I know if an image url is already cached?

### ISSUE THREAD

**Issue by JoyHong** [square/picasso#1719]
Dears
I checked the issue1029 related, but i think it still don't meet my needs.
Our case is that, when loading users' head portrait, firstly check whether user's head portrait url is loaded in cache, if not, replace it's first name with related color background in the imageView, then load the network image. 
So i have to know how to check the url is already cached?

**Comment by JakeWharton** [comment]
Use a placeholder Drawable which draws the color and letter. We do not have an API for querying whether or not a Uri is present in the memory cache.

**Comment by JoyHong** [comment]
it works, thanks.
