### ISSUE TITLE
Android 7.0 + 不显示 https 请求图片 android 6.0 一下可以显示

### ISSUE THREAD

**Issue by liqiang2199** [square/picasso#1721]
图片地址
https://www.kexindai.com/UploadFiles/Sys/Adv/c0f5fbd843b744bd9bfe942351ec3da2.jpg
D/Picasso: Dispatcher  retrying     [R4]+578ms 
D/Picasso: Hunter      executing    [R4]+582ms 
D/Picasso: Dispatcher  retrying     [R4]+1179ms 
D/Picasso: Hunter      executing    [R4]+1188ms 
D/Picasso: Dispatcher  batched      [R4]+1198ms for error
D/Picasso: Dispatcher  delivered    [R4]+1405ms 
D/Picasso: Main        errored      [R4]+1409ms 
D/Picasso: Main        created      [R5] Request{https://www.kexindai.com/UploadFiles/Sys/Adv/153d8e16ad4646d09c9c0b6b0e2c7359.jpg}

**Comment by BigCatLi** [comment]
Android7默认不信任用户导入的CA证书，所以需要配置文件，来信任用户导入的证书
参考资料：https://www.cnblogs.com/meitian/p/6889150.html

**Comment by JakeWharton** [comment]
Please attach an error listener to the `Picasso` instance and include the actual stacktrace of the underlying problem.
