### ISSUE TITLE
Can not load Image with https link, java.net.ProtocolException

### ISSUE THREAD

**Issue by hamidrezasahraei** [square/picasso#1724]
Hi
Everything is ok when loading images from http links.
But some of the https links does not load, stack trace:

`W/System.err: java.net.ProtocolException: Expected ':status' header not present
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.internal.http.Http2xStream.readHttp2HeadersList(Http2xStream.java:267)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:287)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:80)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:117)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at java.lang.Thread.run(Thread.java:764)
12-30 18:57:17.712 11452-11452/my.application W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)`

**Comment by MohMah** [comment]
visit #500

**Comment by JakeWharton** [comment]
This isn't a Picasso issue. Your server is speaking HTTP/2 but somehow violated the protocol.

**Comment by satishdy** [comment]
But @JakeWharton it works with every other app (chrome). Also Glide just works fine. So sure it's not a problem with just the server.
