### ISSUE TITLE
Could not resolve com.squareup.picasso:picasso:3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by mhlistener** [square/picasso#1729]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.squareup.picasso:picasso:3.0.0-SNAPSHOT.

Could not resolve com.squareup.picasso:picasso:3.0.0-SNAPSHOT.
Required by:
    project :app
 > Could not resolve com.squareup.picasso:picasso:3.0.0-SNAPSHOT.
    > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/squareup/picasso/picasso/3.0.0-SNAPSHOT/maven-metadata.xml.
          > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/squareup/picasso/picasso/3.0.0-SNAPSHOT/maven-metadata.xml'.
                   > oss.sonatype.org

**Comment by JakeWharton** [comment]
Seems like a network problem. The URL resolves fine here from the command-line and in the browser.

**Comment by mhlistener** [comment]
thank you for answer. But I have checked up my network, and the network has no problem。for example ,I can look up github now. I cant found the real problem.

**Comment by mhlistener** [comment]
@JakeWharton Have  any other possibility?

**Comment by mhlistener** [comment]
I have resolved the problem which caused by DNS ,thanks.

**Comment by mokshitgogia** [comment]
Failed to resolve: com.squareup.picasso:picasso:3.0.0-SNAPSHOT
how to solve this warning??
