### ISSUE TITLE
Cannot reset Error 

### ISSUE THREAD

**Issue by swaprely** [square/picasso#1731]
Picasso version 'com.squareup.picasso:picasso:2.5.2'

Code used -->

String imageUrl = images.get(position);
        File file = null;
        try {
// initially i used new File(imageUrl), but after changing some library for image picking, it was returning
// relative path, so to get absolute path, I call "getPath" method, which returns Uri which is absolute.
            file = new File(MediaUtil.getPath(context,Uri.fromFile(new File(imageUrl))));
        }
        catch (Exception e){file=null;}
        if(file!=null && file.exists()){
            Picasso p = new Picasso.Builder(context).listener(new Picasso.Listener() {
                @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                    exception.printStackTrace();
                }
            }).build();
            p.load(file)
                    .placeholder(R.drawable.gallery_landscape_placeholder)
                    .noFade()
                    .centerCrop()
                    .resize(600, 300)
                    .into(myImage);
        }
        else
            Picasso.with(context)
                .load(imageUrl)
                .placeholder(R.drawable.gallery_landscape_placeholder)
                .noFade()
                .resize(600, 300)
                .into(myImage);

ERROR STACK TRACE -

W/System.err: java.io.IOException: Cannot reset
W/System.err:     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

I checked issues with Cannot reset, some solutions mentioned something called Marker, but I am still unable to implement it. I think it was something in the older version of Picasso as the issues were from 2014-2015

**Comment by JakeWharton** [comment]
This has been fixed on master for the next version. You can try it now as 3.0.0-SNAPSHOT using the snapshot link in the README.

**Comment by swaprely** [comment]
ok thanks, may I know when will it be released?
