### ISSUE TITLE
Use Picasso for manipulating Bitmaps, as in already loaded ones?

### ISSUE THREAD

**Issue by KennyGoers** [square/picasso#1733]
I've been writing a bunch of bitmap manipulation code lately and progressively manipulates preloaded bitmaps in various ways (rotate, crop, transform, other things). 

I got this idea that Picasso does all that stuff AFTER loading an image, what if it were to allow me to do this with an already loaded image? I couldn't find anything in the source code, assume this would be a feature request.

As in:
Bitmap newBitmap = PIcasso.using(bitmap).rotate(x).centerCrop().get();

Seems this would be a nice usage for some cases.

Thoughts?

**Comment by JakeWharton** [comment]
Feel free to pile onto https://github.com/square/picasso/issues/1007 with your use case.
