### ISSUE TITLE
Unable to download special end of the picture problem

### ISSUE THREAD

**Issue by huodepeng** [square/picasso#1734]
Can not load special field end picture.such as  .png@!small or .png@!big

**Comment by JakeWharton** [comment]
Why is it not possible?

**Comment by huodepeng** [comment]
Can not load

**Comment by huodepeng** [comment]
public void loadBitmap(String uri, final RequestDataCallback<Bitmap> callback) {
        picasso.load(uri).into(new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                callback.dataCallback(bitmap);
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable) {
                callback.dataCallback(null);
            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {

            }
        });
    }

**Comment by JakeWharton** [comment]
That's just code. What's the underlying problem?

**Comment by huodepeng** [comment]
I need to download an image.This image is based on .png@!small or .png@!big.But I can not get bitmap this way

**Comment by JakeWharton** [comment]
There isn't enough information here as to why the load is failing. If you can provide a standalone sample, a failing test case, or the full stacktrace of the loading exception that indicates it's not just a transport or decoding problem we can take a look.
