### ISSUE TITLE
How to add asynchronly downloaded image to Picasso disk cache?

### ISSUE THREAD

**Issue by Kolyall** [square/picasso#1737]
At start of my application I have list of imageLinks
```
     List<String> imageLinks = Arrays.asList("http://example.com/1.png",
        "http://example.com/2.png",
        "http://example.com/3.png"
        ...
        "http://example.com/n.png");
```

I want to download the images async and in next run of my app without internet connection, I want to display the images with Picasso:

    mPicasso.load("http://example.com/1.png").into(imageView)

But when I'm trying to download the image in background (io) thread with rxJava. I want to download it in background (io) thread, because I need to display ProgressDialog while images are downloading and go to another activity when it will be done

    for (String imageLink:imageLinks )
        mPicasso.load(imageLink).into(new SimpleTarget()
                    @Override
                    public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                        Log.e(TAG, "onBitmapLoaded: "+imageLink);
                        subscriber.onNext(true);
                        subscriber.onCompleted();
                    })

 the error occurs:

    java.lang.IllegalStateException: Method call should happen from the main thread.
        at com.squareup.picasso.Utils.checkMain(Utils.java:136)
        at com.squareup.picasso.RequestCreator.into(RequestCreator.java:496)

My another idea is to download the images with Retrofit , but how to add downloaded image to Picasso disk cache to display it in next time?

**Comment by JakeWharton** [comment]
You can call `fetch()`, provided they have proper cache headers.
