### ISSUE TITLE
Cached image doesn't call transform method

### ISSUE THREAD

**Issue by Kolyall** [square/picasso#1738]
I first call:
`mPicasso.load("http://example.com/1.png").fetch();`

Turn off internet

Call in UI:
`mPicasso.load("http://example.com/1.png").transform(new AnyTransform()).into(imageView);`

[Bug]: Transform is not applied to cached image. Cached image is not inserted into ImageView with Transformation. It not inserted into ImageView. ImageView is empty

**Comment by jrodbx** [comment]
Closing as working.  Please re-open if you have more info or updated repro steps.
