### ISSUE TITLE
 Failed to resolve: com.squareup.picasso:picasso:3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by CoolMind** [square/picasso#1739]
Hello!
I have a problem https://github.com/square/picasso/issues/364 on Meizu U20. Try to upgrade to 3.0.0-SNAPSHOT and get:

> Failed to resolve: com.squareup.picasso:picasso:3.0.0-SNAPSHOT.

**Comment by vanniktech** [comment]
You need to add the maven snapshot url. https://oss.sonatype.org/content/repositories/snapshots

**Comment by CoolMind** [comment]
Thanks! I also saw this answer here: https://stackoverflow.com/questions/38829412/could-not-find-com-squareup-picassopicasso2-5-3-snapshot. It helps.
