### ISSUE TITLE
Using inBitmap to optimize memory allocations

### ISSUE THREAD

**Issue by Udinic** [square/picasso#174]
One of the use cases I have with Picasso is loading background images on a ViewPager. Those images are in the same size, which got me thinking I can use the inBitmap option to save up some allocations. (Read more about inBitmap here: http://developer.android.com/training/displaying-bitmaps/manage-memory.html).

To do that, I wrote some pointers/steps that can help implement this:
1. Let Picasso know about a bitmap I no longer need. For my case - I use FragmentStatePagerAdapter, so I know a bitmap is no longer used when the Fragment's onStop() is called.
2. Save the unused bitmaps along the LruCache bitmaps. There's a possibility one of these bitmap be needed soon, so there's no need to remove it from the LruCache when it's declared unused.
3. On any of the BitmapHunter decedents, we can always check the size of the bitmap before allocating a new one. This will allow us to search for a suitable bitmap in the unused bitmaps set. We'll take the least recently used bitmap that is also unused at the moment.

I've already started working on it. I'll push my branch soon.

For now, I did a small "hack" just to see if it affects the performance, and it does. I'm sure there are some things I'm not thinking about, so I'm open to ideas/suggestions.

**Comment by mmanishh** [comment]
where is the code of the solution ?
