### ISSUE TITLE
Using fit(), the image never loads.

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#1749]
Open the sample app, try loading an image from the gallery. (SampleGalleryActivity uses fit().) The image will never load.

The `target.isLayoutRequested()` check is always true in DeferredRequestCreator.onPreDraw().

**Comment by jrodbx** [comment]
Culprit commit: ed2ff2be1e262be15d5a0c8d187be2b221aec2ff

**Comment by jrodbx** [comment]
Fixed in https://github.com/square/picasso/pull/1763
