### ISSUE TITLE
Picasso.Builder.downloaderWith(OkHttpClient/Call.Factory)?

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#1751]
I want to encourage people to reuse OkHttpClient instances (or shallow copies of them).
`picassoBuilder.downloader(new OkHttp3Downloader(client)` seems hidden. You have to know about OkHttp3Downloader; there's no autocomplete in the IDE.

Would something like `Picasso.Builder.downloaderWith(OkHttpClient/Call.Factory)` encourage passing in your existing client?

**Comment by JakeWharton** [comment]
Seems fine

**Comment by JakeWharton** [comment]
Let's get rid of `Downloader`. It's just `client` and `callFactory` like Retrofit.

**Comment by NightlyNexus** [comment]
Yes, exactly what I was hoping.

**Comment by jrodbx** [comment]
As @JakeWharton mentioned in https://github.com/square/picasso/pull/1773, Picasso can be used to load local images which makes keeping the `Downloader` abstraction useful.

> I want to encourage people to reuse OkHttpClient instances (or shallow copies of them).
`picassoBuilder.downloader(new OkHttp3Downloader(client))` seems hidden. You have to know about OkHttp3Downloader; there's no autocomplete in the IDE.

How about we inline @JakeWharton's project instead?

**Comment by NightlyNexus** [comment]
Isn't that what a RequestHandler is for?

**Comment by jrodbx** [comment]
For NetworkRequestHandler, sure.  But there are other RequestHandlers that don't require an HttpClient.

**Comment by NightlyNexus** [comment]
yes, of course.
i'm not sure i understand your proposal. Why would somebody want to implement a custom Downloader in order not to make network calls?

**Comment by jrodbx** [comment]
debug/mock mode.

**Comment by NightlyNexus** [comment]
would it be too weird to make and install a custom RequestHandler for debug mode that handles HTTP requests?

**Comment by JakeWharton** [comment]
There's many levels you can handle debug/mock mode. MockWebServer to actually serve images over local HTTP, custom Call.Factory to serve images directly, or a custom RequestHandler to serve images directly without going to Downloader.

**Comment by NightlyNexus** [comment]
Done in #1787

**Comment by JakeWharton** [comment]
Now kill Downloader completely!
