### ISSUE TITLE
3.0.0-SNAPSHOT is broken

### ISSUE THREAD

**Issue by CoolMind** [square/picasso#1752]
Hello!
Please, say, what's happened? Following to recommendation I updated a library to 3.0.0-SNAPSHOT, and yesterday you broke it?
https://oss.sonatype.org/content/repositories/snapshots/com/squareup/picasso/picasso/3.0.0-SNAPSHOT/
Doesn't work on many devices!!!
Please, roll back to a previous version and update as 3.0.1-SNAPSHOT!

**Comment by JakeWharton** [comment]
This is not an actionable report. Please provide the means of failure or a sample to reproduce. Also this might be #1749.

**Comment by CoolMind** [comment]
Probably it appears for this case:

    Picasso.get().load(uri).resize(1000, 0).get();

where `uri` is an image received from Gallery or Camera. After resizing the image is not shown.

**Comment by CoolMind** [comment]
And why is it closed?
I will create an inssue again.
