### ISSUE TITLE
How to disable Picasso's OkHTTP?

### ISSUE THREAD

**Issue by CoolMind** [square/picasso#1765]
As I already wrote in https://github.com/square/picasso/issues/1753 Picasso includes it's OkHTTP client and  probably interfere with other calls. How to disable Picasso's OkHTTP library in build.gradle and use defined, for instance, `com.squareup.okhttp3:okhttp:3.7.0`?

**Comment by NightlyNexus** [comment]
Maybe something like this for your project build file?
```groovy
configurations.all {
  resolutionStrategy {
    eachDependency { details ->
      if (details.requested.group == 'com.squareup.okhttp3') {
        details.useVersion '3.7.0'
      }
    }
  }
}
```

With that said, you should consider always updating to the latest OkHttp version (3.10.0 right now). (From your other comment, it looks like you simply need to update to Retrofit 2.3.0.)

**Comment by jrodbx** [comment]
Yes that looks about right.  For more on dependency resolution strategy, see here: https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html

**Comment by CoolMind** [comment]
Thanks for Retrofit 2.3.0.
