### ISSUE TITLE
Webp image format not supported

### ISSUE THREAD

**Issue by nitinmishra27** [square/picasso#177]
I'm working on grabing some "webp" images https://lh6.ggpht.com/kktCUrKvuLPxZsywDppiRMto8ECfr3Kv70RWLnRogXqJEydm9cMdLlxDNVMaxsHoDyA=h310-rw actually it has something to do with "webp" extension of image. the format now google is using not supported by picasso

**Comment by manuel-sejourne** [comment]
How to support webp for the device under Android 4.0 ?
Can we use easily Picasso with webp-android-backport ?

**Comment by Allan-Nava** [comment]
Webp is supported implementation 'com.squareup.picasso:picasso:2.5.2' ?

**Comment by Jorgesys** [comment]
Webp format is supported with:  implementation 'com.squareup.picasso:picasso:2.8'
