### ISSUE TITLE
Square.Picasso.DownloaderResponseException: 404 The specified blob does not exist.

### ISSUE THREAD

**Issue by AkhilPatoliya** [square/picasso#1771]
E/Piccaso :https://corebib.blob.core.windows.net/images/mobileImages/homeScreen/news/Welcome.p Square.Picasso.DownloaderResponseException: 404 The specified blob does not exist.

i got this error when i am  trying to display image from microsoft azure blob storage.

**Comment by JakeWharton** [comment]
A 404 means you have the wrong URL or do not have sufficient authentication to view the resource. This isn't a problem with Picasso itself.

**Comment by AkhilPatoliya** [comment]
@JakeWharton same url is working on browser

**Comment by AkhilPatoliya** [comment]
when i am displaying images on browser with same url it's working
but i am using in my android application than it's doesn't working and i am already debug and check image url. 
url is proper and right url

**Comment by JakeWharton** [comment]
Picasso is not an HTTP client so that same URL will 404 whether requested
from Picasso or directly with OkHttp.

**Comment by obito02** [comment]
am fixed, only change the url with new, remove 404.
