### ISSUE TITLE
Basic authorization not working

### ISSUE THREAD

**Issue by kulvinder18may** [square/picasso#1779]
public class MyPicasso {

    private static MyPicasso mInstance;
    private static Picasso picasso;
    private static Context ctx;

    public static synchronized MyPicasso getInstance(Context context) {
        ctx = context;
        if (mInstance == null) {
            mInstance = new MyPicasso();
            OkHttpClient okHttpClient = new OkHttpClient.Builder()
                    .authenticator(new Authenticator() {
                        @Override
                        public Request authenticate(Route route, Response response) throws IOException {
                            String credential = Credentials.basic(Constants.BASIC_AUTH_USERNAME, Constants.BAISC_AUTH_PASSWORD);
                            return response.request().newBuilder()
                                    .header("Authorization", credential)
                                    .build();
                        }
                    })
                    .build();

            Picasso.Builder builder = new Picasso.Builder(context);
            OkHttp3Downloader downloader = new OkHttp3Downloader(okHttpClient);
            picasso = builder.downloader(downloader).build();
        }
        return mInstance;
    }

    public synchronized void downloadImage(String url, ImageView imageView) {
        if (picasso == null) throw new ExceptionInInitializerError("Picasso Initializer Error");

        downloadImage(url, imageView, null);
    }

    public synchronized void downloadImage(String url, ImageView imageView, Drawable userPlaceholder) {
        if (picasso == null) throw new ExceptionInInitializerError("Picasso Initializer Error");

        Drawable productPlaceholder = ContextCompat.getDrawable(ctx, R.mipmap.ic_launcher);

        picasso.with(ctx).load(url)
                .into(imageView);
    }

}

**********
Username password are correct....
Not any exception/error

Is there anything wrong!

**Comment by jrodbx** [comment]
This isn't a Picasso issue.   Check your API interaction logic to see why Basic Auth isn't working for you.
