### ISSUE TITLE
com.squareup.picasso:picasso:3.0.0-SNAPSHOT not working

### ISSUE THREAD

**Issue by ibnekhan** [square/picasso#1780]

**Comment by PaulWoitaschek** [comment]
This is a really vague description. Maybe you  can elabaorate what you  mean by that?

**Comment by JakeWharton** [comment]
Not an actionable report. Feel free to comment with ~more~ info.

**Comment by CoolMind** [comment]
@ibnekhan 
This library changes almost every day, so roll back to 2.5.2 or download one of stable aar's and use it. And yes, yesterday it didn't work.
