### ISSUE TITLE
Support for xml drawables

### ISSUE THREAD

**Issue by pforhan** [square/picasso#1790]
```
picasso.load(resId).transform(new TopCropTransformation()).into(rateImage);
```

if you try to `.load()` something that's not an image bitmap on disk nothing further down your picasso chain happens, because `BitmapFactory.decodeResource` returns null for xml drawables.

Perhaps construct an artificial bitmap and render the drawable into it?  Then it could continue down the chain.

Should picasso throw if it can't render a resource?  That may be a good interim solution to help developers figure out problems.

perhaps related to #1109

**Comment by JakeWharton** [comment]
> Should picasso throw if it can't render a resource?

No. It supplies you with logs and it sets your error drawable (if provided).
