### ISSUE TITLE
Library is not working with Gradle

### ISSUE THREAD

**Issue by gNiKnet** [square/picasso#1793]
I am using `implementation "com.squareup.picasso:picasso:2.71828"` with `classpath 'com.android.tools.build:gradle:3.1.0-rc01'` and I only get these methods

![picasso](https://user-images.githubusercontent.com/19204050/37148535-18a33f6e-22cb-11e8-9810-ddbb7a20f2aa.png)

There is no `with` method or anything similar.

**Comment by mree58** [comment]
check this :

https://github.com/square/picasso/commit/e7e919232fe2b15772a7fcd9e15ead2304c66fae

**Comment by gNiKnet** [comment]
@mree58 thank you. The documentation should be updated, e.g. the website.
