### ISSUE TITLE
Request.networkPolicy is never assigned.

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#1797]
This is broken. :(

**Comment by NightlyNexus** [comment]
https://github.com/square/picasso/blob/6b18cb8599c83d288e59595fcc453db386cc85f1/picasso/src/main/java/com/squareup/picasso/NetworkRequestHandler.java#L51
no way that's reporting the right thing now.

**Comment by jrodbx** [comment]
What's broken here?

**Comment by NightlyNexus** [comment]
`throw new ResponseException(response.code(), request.networkPolicy)`
request.networkPolicy will always be 0. the field is never assigned.

**Comment by jrodbx** [comment]
🤦‍♂️
