### ISSUE TITLE
Use SystemClock.elapsedRealtimeNanos().

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#1798]
to avoid theoretical problem of a user changing the system clock time.

**Comment by jrodbx** [comment]
`Request` id logic uses `System.nanoTime` which isn't affected.  `StatsSnapshot` is used for OOM analysis and other debugging/logging.  Is there another scenario that could be impacted?

**Comment by NightlyNexus** [comment]
Yes, there are no other cases. I should have looked deeper.
