### ISSUE TITLE
Example of a Target interface implementation?

### ISSUE THREAD

**Issue by brk3** [square/picasso#18]
If someone could provide a short example of the best way to implement the Target interface in order to be notified when an image is ready it would be much appreciated

**Comment by ifeins** [comment]
@JakeWharton Doesn't this apply to any view, not just one that extends `ImageView`?

Basically, isn't the definition that if the object that implements `Target` gets recycled then there is no need to override `hashCode` and `equals`?
So in that regard, if the `ViewHolder` in a `RecyclerView` implements `Target` then there is no need to override `hashCode` and `equals`.

**Comment by JakeWharton** [comment]
View holder instances are re-used, so I'm not sure that's accurate.
