### ISSUE TITLE
picasso.with no more?

### ISSUE THREAD

**Issue by jonneymendoza** [square/picasso#1808]
Hi i have update to the latest 2.7 and now all my exisiting code using Picasso.with is broken?

**Comment by JakeWharton** [comment]
Correct. It's `Picasso.get()` now.

**Comment by ialex90** [comment]
Hi, just wonder something about this, no require to open this ticket though.

Isn't it this a breaking change that should be introduced in a major update version? I mean, if this library follows **Semantic Versioning** this breaking change shouldn't be treated or included as a minor update but as a major.

And is there any place where we can see the reason of this change to understand better the library? Some pros - const of this new feature and final decision taken.

Thanks :)
