### ISSUE TITLE
support load gif?

### ISSUE THREAD

**Issue by MirrorFlower** [square/picasso#1815]
support load gif?

**Comment by JakeWharton** [comment]
Picasso supports GIF. You are, presumably, referring to animated GIFs which Android's `BitmapFactory`, the mechanism which powers Picasso, does not. In the future we'll have a way to plug in support for custom decoders that can return `Drawable` instances such that you'll be able to hook up third-party decoders or ones in the platform that are brand spankin' new.

**Comment by MirrorFlower** [comment]
copy that,thanks~

**Comment by tobiastromm** [comment]
Hi : -)

Any update on supporting animated GIFs?

**Comment by evgenii-paringer** [comment]
I have seen it already implemented, also old good Movie class can do the trick, see there,  
https://github.com/koral--/android-gif-drawable

**Comment by socialcodia** [comment]
When the picasso library able to load and play the gif image?

**Comment by aisnote** [comment]
same request

> When the picasso library able to load and play the gif image?
