### ISSUE TITLE
NullPointerException when picasso. ... .get()

### ISSUE THREAD

**Issue by night2tl** [square/picasso#1829]
When using 
new Picasso.Builder(applicationContext)
            .listener(sPicassoListener)
            .loggingEnabled(true)
            .downloader(new UrlConnectionDownloader(applicationContext))
            .build();

I compile with this:
compile 'com.squareup.picasso:picasso:2.5.2'

device details supplied below:
I'm getting the following error:
{"event":"SdkException","timestamp":1520848860150,"device_info":{"SDK":"8.1.0","OsSdkVersion":"27","Brand":"google","Manufacturer":"Google","Model":"Pixel 2","Board":"walleye","Bootloader":"mw8998-002.0067.00","DeviceProductName":"walleye","IndustrialDesignName":"walleye"},"exceptionType":"java.lang.NullPointerException","errorMessage":"Stacktrace message = 'Attempt to invoke virtual method 'void com.android.okhttp.internal.Internal.addLenient(com.android.okhttp.Headers$Builder, java.lang.String, java.lang.String)' on a null object reference'.","stackTrace":"com.android.okhttp.internal.huc.JavaApiConverter.extractOkHeaders(JavaApiConverter.java:430)
com.android.okhttp.internal.huc.JavaApiConverter.createOkRequest(JavaApiConverter.java:279)
com.android.okhttp.AndroidShimResponseCache.get(AndroidShimResponseCache.java:60)
android.net.http.HttpResponseCache.get(HttpResponseCache.java:206)
com.squareup.okhttp.internal.http.OkResponseCacheAdapter.get(OkResponseCacheAdapter.java:38)
com.squareup.okhttp.internal.http.HttpEngine.initResponseSource(HttpEngine.java:224)
com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:185)
com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:350)
com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:297)
com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:508)
com.squareup.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:93)
com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
LoadImageCorrectlyHandler$3.apply(LoadImageCorrectlyHandler.java:91)
LoadImageCorrectlyHandler$3.apply(LoadImageCorrectlyHandler.java:80)
io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
io.reactivex.Observable.subscribe(Observable.java:10981)
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
java.lang.Thread.run(Thread.java:764)
"}

**Comment by JakeWharton** [comment]
This is a bug in Android's version of OkHttp, not Picasso. Picasso no longer allows the use of the platform HttpURLConnection client on the latest 2.x release nor in the 3.x snapshot. No action to take.

**Comment by night2tl** [comment]
Does it have to do with Android Oreo? As I experience it on Oreo devices?
