### ISSUE TITLE
Why is the version so weird-looking (2.71828)?

### ISSUE THREAD

**Issue by Zhuinden** [square/picasso#1830]
Is there any significance to this strange in versioning format compared to the previous semantic versioning?

Strangest question I've ever asked, but I'm curious.

**Comment by jrodbx** [comment]
`e` ≈ 2.71828.  We're geeks!

**Comment by JakeWharton** [comment]
It's a number between 2 and 3 and it's large to signify backwards-incompatible changes: https://github.com/square/picasso/blob/master/CHANGELOG.md#version-271828-2018-03-07

**Comment by Zhuinden** [comment]
Ah, that also puts the commit message in place

> Prepare version e.

I guess math classes were surprisingly long ago 😞 thanks for clearing up the mystery 😄
