### ISSUE TITLE
There is a conflict between picasso and MediaPlayer

### ISSUE THREAD

**Issue by lipangit** [square/picasso#1832]
There is conflict between Picasso and MediaPlayer.

This url http://store01.msxxapp.com/video/20180312054511_IzAD2N.mp4 in [JZVD](https://github.com/lipangit/JiaoZiVideoPlayer)  can not play again in some phone.

**Comment by JakeWharton** [comment]
And what leads you to believe that Picasso is at fault?

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/37322994-db283f78-26bb-11e8-9078-505edaebca46.png)

Picasso is bad , remove picasso is good, I try it for many times, The conclusion is completely accurate, but I do not know why.

**Comment by JakeWharton** [comment]
That's Glide.

**Comment by lipangit** [comment]
You can download jzvd and replace the http://store01.msxxapp.com/video/20180312054511_IzAD2N.mp4 url in MainActivity, First play is good, but Second play is bad

**Comment by lipangit** [comment]
Yes Glide is good, but picasso is bad

**Comment by lipangit** [comment]
Please reopen the issue

**Comment by JakeWharton** [comment]
Picasso doesn't play mp4s so i wouldn't expect that to work.

**Comment by lipangit** [comment]
Picasso load the thumbnail, jzvd play video. but when the picasso load thumbnail the video play again will error

**Comment by lipangit** [comment]
I result is accurate but I do not know why

**Comment by lipangit** [comment]
I think there are very serious problems here, not short-term solutions

**Comment by lipangit** [comment]
good luck

**Comment by alirezasbri** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/1685

**Comment by lipangit** [comment]
@jacobtabak  do you believe now?

**Comment by jacobtabak** [comment]
I am a believer
