### ISSUE TITLE
How to migrate code with no Cache API

### ISSUE THREAD

**Issue by aldenml** [square/picasso#1834]
Hi @NightlyNexus, I'm having a hard time figuring out how to accommodate for the lack of this configuration point (`Cache` interface). Previously I was able to provide a custom cache implementation with disk fallback, and the advantage was that this cache sit in the the very front of the image retrieval workflow. I didn't need to deal with details like transformations, I was saving to disk the strictly necessary bits given the key.

The best I can do now is provide a custom `RequestHandler`, but this will sit after `ResourceRequestHandler` which makes me impossible to save scaled resources in the "disk" cache.

My questions are:

1-) Is providing a custom `RequestHandler` the right approach? the only one?
2-) Is the limitation of having `ResourceRequestHandler` always in front something that you considered?

Thanks

PR for reference: https://github.com/square/picasso/pull/1769
CC: @gubatron

**Comment by JakeWharton** [comment]
The Cache was definitely the wrong place to do this before since all interaction happened on the UI thread. A request handler will be where we allow this functionality as they'll always be called on a thread you can block on local I/O or computation and they'll soon function in a chain.

**Comment by aldenml** [comment]
Well, that was not the case (or still it's not the case), since I can see that the actual cache hit can happens in the dispatcher, even if `into(...)` call `checkMain()`, I believe that's the case when the request is `deferred`. But I take your comment as a confirmation that a request handler is the right approach.

What about the limitation that `ResourceRequestHandler` is always at the beginning? What happens if I have big resources to show only in small views? How do I cache them effectively with transformations?

**Comment by JakeWharton** [comment]
We can move the resource handler farther down the chain once we support request handler delegation. Basically this means that instead of request handlers being a list that we go down one by one, we assemble them into a chain and each one (optionally) calls into the next one. Right now the resource one is first so that custom request handlers only have to check the `Uri` and not handle both.

**Comment by aldenml** [comment]
Thanks for the explanation!
