### ISSUE TITLE
Picasso 3 & 2.71828: cannot access Source class file for okio.Source not found

### ISSUE THREAD

**Issue by anonym24** [square/picasso#1836]
I get such error for line `return new Result(bm, Picasso.LoadedFrom.DISK);`

```
    private class VideoRequestHandler extends RequestHandler {

        @Override
        public boolean canHandleRequest(Request data) {
            return ("video".equals(data.uri.getScheme()));
        }

        @Override
        public Result load(Request data, int arg1) throws IOException {
            Bitmap bm = ThumbnailUtils.createVideoThumbnail(data.uri.getPath(), MediaStore.Images.Thumbnails.MINI_KIND);
            return new Result(bm, Picasso.LoadedFrom.DISK);
        }
    }
```

**Comment by anonym24** [comment]
seems new version of library is missing dependency ` implementation 'com.squareup.okio:okio:1.14.0'`

**Comment by anonym24** [comment]
I added but it didn't help..

**Comment by anonym24** [comment]
actually same error with picasso 2.71828

**Comment by anonym24** [comment]
only 2.5.2 works fine

**Comment by JakeWharton** [comment]
Okio is a transitive dependency of OkHttp, for which there is a dependency present.
```
releaseRuntimeClasspath - Resolved configuration for runtime for variant: release
+--- com.squareup.okhttp3:okhttp:3.10.0
|    \--- com.squareup.okio:okio:1.14.0
+--- com.android.support:support-annotations:27.1.0
\--- com.android.support:exifinterface:27.1.0
     \--- com.android.support:support-annotations:27.1.0
```
And you can see these dependencies are correctly in the Maven pom: https://oss.sonatype.org/content/repositories/snapshots/com/squareup/picasso3/picasso/3.0.0-SNAPSHOT/picasso-3.0.0-20180314.141103-27.pom.

If you're using Gradle you can check your dependencies by running the `dependencies` task on the project. All signs point to this being a problem with your build configuration and not with Picasso itself so closing.

**Comment by anonym24** [comment]
yes I didn't need it was resolved, no errors with import, but it still didn't work with 2.7 or 3 version, only 2.5.2 works.

try my code please before closing this issue, please!

**Comment by anonym24** [comment]
it's a little different issue (not about resolving), but

>  cannot access Source class file

**Comment by anonym24** [comment]
anyway 2.5.2 works fine, if you don't want to fix it then I'm ok with 2.5.2

**Comment by JakeWharton** [comment]
Works locally for me. If your IDE cannot access the file then it's still a build system / IDE problem.

**Comment by anonym24** [comment]
well I cloned from this git 2.5.2, 2.7 & 3 versions only 2.5.2 worked, there was no difference how I added every library to my project

**Comment by anonym24** [comment]
ok I want to try it again but using remote library `implementation 'com.squareup.picasso:picasso:2.71828'`
but how can I do next  mPicassoInstance = Picasso.with(mContext, new VideoRequestHandler());

for Picasso 2.7 or 3.*?

it has only get method (`mPicassoInstance = Picasso.get()`) with no paramaters...

**Comment by NightlyNexus** [comment]
`new Picasso.Builder().addRequestHandler(...)...build()` and then reuse this Picasso instance.

**Comment by anonym24** [comment]
@NightlyNexus  

also Why Disk Cache doesn't work?

```
        mPicassoInstance = new Picasso.Builder(mContext.getApplicationContext())
                .addRequestHandler(new VideoRequestHandler())
                .build();
        Picasso.setSingletonInstance(mPicassoInstance);
```

```
 mPicassoInstance
                        .load("video:" + videoFile.getAbsolutePath())
                        .placeholder(R.drawable.ic_video)
                        .noFade()
                        .into(mImageView, new Callback.EmptyCallback() {
                            @Override
                            public void onSuccess() {
                                //
                            }
                        });
```

I loaded app, minimized it, cleared from history
checked app private folder (with root explorer) and
`app/cache/picasso-cache` folder is empty
so of course when I strated app again it loaded thumbnail again from videofiles (no from cached, because it doesn't exist)
