### ISSUE TITLE
Couldn't get facebook profile thumbnail

### ISSUE THREAD

**Issue by Laeyoung** [square/picasso#1845]
Couldn't get facebook profile thumbnail from today. 
 
ex)
```kotlin
Picasso.get()
       .load(https://graph.facebook.com/v2.12/1486396794715080/picture?type=large)
       .into(ivProfilePhoto)
```

This code returned HTTP 504 error.
I remember it worked fine yesterday.
I checked on iOS and Web, and it worked fine.

**Comment by vsevolod-sp** [comment]
+1. The problem appeared 2 days ago.

**Comment by NightlyNexus** [comment]
What version of Picasso?

**Comment by vsevolod-sp** [comment]
was 2.5.2, updated to 2.71828 - the problem remained

**Comment by marioamgad9** [comment]
I have the same problem... Suddenly all my Facebook photos are not loading.

[Example](https://graph.facebook.com/10210733453966844/picture?height=300&width=300&migration_overrides=%7Boctober_2012%3Atrue%7D) of a photo that is not loading

(It was working perfectly 2 days ago and I didn't change anything)

**Comment by jrodbx** [comment]
Assuming you didn't bump the version of Picasso before experiencing this issue, I suspect something has changed on Facebook's side.  

FWIW, @marioamgad9's example fails to load on my mobile Chrome browser.

**Comment by jrodbx** [comment]
...as soon as I posted that, the example now loads.  Definitely seems like something on Facebooks end.  Closing.
