### ISSUE TITLE
Not able to update a single AppWidget

### ISSUE THREAD

**Issue by C0br4** [square/picasso#1846]
At the moment picasso only takes a whole int array of AppWidget ids which are updated in one batch. I would expect to be able to also give picasso a single widget id as int as well. Of course one can give picasso an array with only one int inside but it looks like kind of an oversight to me.

**Comment by JakeWharton** [comment]
I'm pretty sure this API is modeled after the platform API.

**Comment by jrodbx** [comment]
Creating a new Action to support a single appWidgetId seems like overkill.  Maybe adding another into(...) overload?
