### ISSUE TITLE
use for svg 

### ISSUE THREAD

**Issue by mashahbazi** [square/picasso#1875]
can use picasso for svg?
i use it for svg and png in work for png but dont work on svg.
please help

**Comment by MGaetan89** [comment]
Did you find a solution for that?

**Comment by mashahbazi** [comment]
no i use glide for this

    On Monday, May 28, 2018, 1:40:10 PM GMT+4:30, Gaëtan Muller <notifications@github.com> wrote:  
 
 
Did you find a solution for that?
