### ISSUE TITLE
Permit disk caching of transformed bitmaps

### ISSUE THREAD

**Issue by Nodjo** [square/picasso#1889]
When applying a transform to a bitmap, that transformed bitmap will be cached in memory but once it's evicted from there, the original image will be reloaded from the disk and the transform will be run again.

Would it be possible to permit caching the transformed bitmap on the disk along, or in place of, the original image?

**Comment by NightlyNexus** [comment]
In Picasso 3, there will be interceptors where you can bring in your own disk cache.
Otherwise, no. There's just the HTTP cache, which Picasso does not control.
