### ISSUE TITLE
picasso-2.71828.pom not downloaded from maven2

### ISSUE THREAD

**Issue by pechaz** [square/picasso#1893]
Hi Everyone,
Recently I start new project and try to use picasso-2.71828. Unfortunately I cant download it by gradle  in android app.
How can I get it for my new projects?

here is the the link that android studio try to download library:
https://dl.google.com/dl/android/maven2/com/squareup/picasso/picasso/2.71828/picasso-2.71828.pom

**Comment by JakeWharton** [comment]
You need to include `mavenCentral()` in your repositories list.
