### ISSUE TITLE
Pictures not loading on some devices

### ISSUE THREAD

**Issue by MegaAndroidDeveloper666** [square/picasso#1902]
Hi!
I've encountered a strange bug. On some devices pictures are loading, but on some I have this error.
```
05-22 13:38:47.875 6818-6818/ru.blahblah.debug D/Picasso: Main        created      [R0] Request{http://... ... ....png}
05-22 13:38:47.899 6818-7409/ru.blahblah.debug D/Picasso: Dispatcher  enqueued     [R0]+25ms 
05-22 13:38:47.901 6818-7411/ru.blahblah.debug D/Picasso: Hunter      executing    [R0]+27ms 
05-22 13:38:48.750 6818-7409/ru.blahblah.debug D/Picasso: Dispatcher  retrying     [R0]+877ms 
05-22 13:38:48.753 6818-7454/ru.blahblah.debug D/Picasso: Hunter      executing    [R0]+879ms 
05-22 13:38:49.346 6818-7409/ru.blahblah.debug D/Picasso: Dispatcher  retrying     [R0]+1472ms 
05-22 13:38:49.367 6818-7462/ru.blahblah.debug D/Picasso: Hunter      executing    [R0]+1489ms 
05-22 13:38:49.401 6818-7409/ru.blahblah.debug D/Picasso: Dispatcher  batched      [R0]+1527ms for error
05-22 13:38:49.610 6818-7409/ru.blahblah.debug D/Picasso: Dispatcher  delivered    [R0]+1736ms 
05-22 13:40:23.327 6818-6818/ru.blahblah.debug D/Picasso: Main        errored      [R0]+95s HTTP 504
```

Url is valid and opens properly in browser. Even on device, that connot load image via Picasso.
Tried some things like connect timeout, read timeout - nothing happened. What could be wrong?
I have ended up with this code.
```
OkHttpClient client = new OkHttpClient.Builder().protocols(Arrays.asList(Protocol.HTTP_1_1))
                .connectTimeout(10, TimeUnit.SECONDS)
                .readTimeout(15, TimeUnit.SECONDS)
                .build();
        Picasso picasso = new Picasso.Builder(MApp.getInstance().getApplicationContext())
                .downloader(new OkHttp3Downloader(client))
                .listener(new Picasso.Listener() {
                    @Override
                    public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                        Log.d("Picasso", exception.getMessage());
                    }
                })
                .build();
        picasso.setLoggingEnabled(true);
        picasso
                .load(url)
                .error(R.drawable.other_cat)
                .into(h.icon);
```

**Comment by JakeWharton** [comment]
And what exception message gets logged?

**Comment by alperenbabagil** [comment]
I get "java.io.IOException: Failed to decode stream" error. It looks like I have an authentication problem. Server returns 302 and redirects to login page

**Comment by JakeWharton** [comment]
Ok. So no action to take from Picasso's side then.

**Comment by alperenbabagil** [comment]
No, I think problem in Picasso. I tried to reach our service via HttpURLConnection by setting cookies and it returned code 200.
I think UrlConnectionDownloader of picasso somehow removes cookies of HttpURLConnection inside.

**Comment by JakeWharton** [comment]
`UrlConnectionDownloader` doesn't exist on the latest version anymore.

But you can peek at the 2.5.2 version and see that it doesn't mess with cookies: https://github.com/square/picasso/blob/picasso-parent-2.5.2/picasso/src/main/java/com/squareup/picasso/UrlConnectionDownloader.java

**Comment by MegaAndroidDeveloper666** [comment]
@JakeWharton I just receive HTTP 504 and nothing else.

**Comment by igaryhe** [comment]
This is due to some network security mechanism in Android Pie.
Found a solution here:
https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie
