### ISSUE TITLE
Picasso does not load thumbnail from locally stored Video

### ISSUE THREAD

**Issue by PritishSawant** [square/picasso#1906]
https://stackoverflow.com/questions/50587681/glide-picasso-wont-load-thumbnail-path-of-locally-stored-video

**Comment by JakeWharton** [comment]
This is not enough information for an actionable report. Please provide an isolated sample which reproduces the issue, or a failing test case, or information about the failure (such as a stacktrace or log), or really any way where we can discern what is actually happening.

**Comment by jrodbx** [comment]
Please open another issue if you can provide a repro sample, failing test case, or stacktrace.
