### ISSUE TITLE
Its marking red near implementation 'com.android.support:appcompat-v7:27.1.1' when updated to new version i.e. 2.71828

### ISSUE THREAD

**Issue by Legend-Mortal** [square/picasso#1913]
Message displayed: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.1.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:exifinterface:27.1.0

This red mark is displayed near implementation 'com.android.support:appcompat-v7:27.1.1'

**Comment by NightlyNexus** [comment]
force the support library dependencies to use the same version.

if you're using Grade:
```groovy
configurations.all {
  resolutionStrategy {
    eachDependency { details ->
      // Force all of the primary support libraries to use the same version.
      if (details.requested.group == 'com.android.support') {
        details.useVersion versions.supportLibrary
      }
    }
  }
}
```

**Comment by yccheok** [comment]
Is adding `implementation 'com.android.support:exifinterface:27.1.1'` is better solution?

**Comment by dave-kennedy** [comment]
Is a fix planned for this workaround?
