### ISSUE TITLE
Please update your wiki

### ISSUE THREAD

**Issue by GitHubMurt** [square/picasso#1915]
Please update wiki that consist deprecated methods and calls.
http://square.github.io/picasso/

Btw. is there any other manual?

**Comment by jrodbx** [comment]
I just reviewed the wiki and I didn't find any deprecated methods/calls with respect to 2.e.

If you're referring to 3.0, the wiki will be updated prior to its final release.  We don't update the wiki for snapshots, as the APIs can change at any time.

**Comment by GitHubMurt** [comment]
Picasso.get().load("http://i.imgur.com/DvpvklR.png").into(imageView);

I'm using Picasso 2.5.2
implementation 'com.squareup.picasso:picasso:2.5.2'

Please tell me where is `get()` method? because I can't find it since I started using this library.

**Comment by jemaystermind** [comment]
@GitHubMurt Use `2.71828` instead of `2.52`?

**Comment by GitHubMurt** [comment]
You are correct, my bad
