### ISSUE TITLE
Disk Cache doesn't work when I use RequestHandler for video file thumbnails 

### ISSUE THREAD

**Issue by anonym24** [square/picasso#1916]
```
        mPicassoInstance = new Picasso.Builder(mContext.getApplicationContext())
                .addRequestHandler(new VideoRequestHandler())
                .build();
        Picasso.setSingletonInstance(mPicassoInstance);
```

```
        mPicassoInstance
                .load("video:" + videoFile.getAbsolutePath())
                .placeholder(R.drawable.ic_video)
                .noFade()
                .into(mImageView, new Callback.EmptyCallback() {
                    @Override
                    public void onSuccess() {
                        //
                    }
                });
```

```
  private class VideoRequestHandler extends RequestHandler {

        @Override
        public boolean canHandleRequest(Request data) {
            return ("video".equals(data.uri.getScheme()));
        }

        @Override
        public Result load(Request data, int arg1) throws IOException {
            Bitmap bm = ThumbnailUtils.createVideoThumbnail(data.uri.getPath(), MediaStore.Images.Thumbnails.MINI_KIND);
            return new Result(bm, Picasso.LoadedFrom.DISK);
        }
    }
```

`implementation 'com.squareup.picasso:picasso:2.71828'`

I loaded app, minimized it and cleared it from history (phone memory)
I checked app private folder (with root explorer) and I found that `app/cache/picasso-cache` folder is empty
So of course when I start app again it doesn't load from cache (which doesn't exist) but loads thumbnails again from videofiles, slowly

**Comment by JakeWharton** [comment]
The disk cache is only for HTTP requests as it's a part of the HTTP client and not part of Picasso. We have no plans to introduce our own disk cache at this time.

**Comment by anonym24** [comment]
@JakeWharton but can you still label it as enhancement ?

**Comment by JakeWharton** [comment]
We're not going to add a disk cache. In Picasso 3.0 you'll be able to stick a request interceptor in between loads to a content provider and implement your own disk caching policy.

**Comment by anonym24** [comment]
@JakeWharton also mb we don't even need to cache video thumbnails
does Android do it for us (MediaStore database) 
I tried this https://stackoverflow.com/a/28324037/4548520
but unfortunately it didn't work (always returns 0 id for any file I try, `Uri.fromFile(videoFile)`)

I mean this ` Bitmap bm = ThumbnailUtils.createVideoThumbnail(data.uri.getPath(), MediaStore.Images.Thumbnails.MINI_KIND);` creates new thumbnail (hard and slow task)

but from SO page it seems they trying to find existing thumbnails from database using cursor:

```
 Cursor thumbCursor = null;
    try {

        thumbCursor = context.managedQuery(
                MediaStore.Video.Thumbnails.EXTERNAL_CONTENT_URI,
                thumbColumns, MediaStore.Video.Thumbnails.VIDEO_ID + " = "
                        + fileId, null, null);

        if (thumbCursor.moveToFirst()) {
            String thumbPath = thumbCursor.getString(thumbCursor
                    .getColumnIndex(MediaStore.Video.Thumbnails.DATA));

            return thumbPath;
        }

    } finally {
    }

```
