### ISSUE TITLE
Picasso Unable to download image from HTTPS url

### ISSUE THREAD

**Issue by uzairayub** [square/picasso#1918]
`com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504`
this is the basic cause 
Intent permissions is on .
Internet is on.

**Comment by JakeWharton** [comment]
This is not enough information for an actionable report. An HTTP 504 is either a response from the server in which case it's a server problem or it's a response from the HTTP cache in which case the image could not be loaded normally and also wasn't satisfiable from the cache. If you enable logging you'll receive more information to help diagnose the cause. But as of now, I don't see any action for us to take.

**Comment by virendragupta30** [comment]
This is the error- 
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
2018-10-11 18:10:32.671 29935-29935/com.truweight.controllers W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)
2018-10-11 18:15:25.362 29935-29935/com.truweight.controllers W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

Only these information, we are getting from e.printStackTrace()
