### ISSUE TITLE
Outdated dependency on com.android.support holds users from upgrading to newer versions.

### ISSUE THREAD

**Issue by coder966** [square/picasso#1919]
Previously, the version 2.5.2 did not have a dependency on com.android.support
[see](http://repo1.maven.org/maven2/com/squareup/picasso/picasso/2.5.2/picasso-2.5.2.pom) but now 2.71828 does [see](http://repo1.maven.org/maven2/com/squareup/picasso/picasso/2.71828/picasso-2.71828.pom).

It is not recommended to mix versions of support library as it may produce unexpected crashes.
AS shows the warning: 

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.1.0.

**Comment by JakeWharton** [comment]
We do not track or make releases for updated dependency versions. If you are using a particular version of the support libraries then you should be forcing the same version for all of them.

See https://github.com/square/picasso/issues/1913#issuecomment-393785576
