### ISSUE TITLE
Sometime can't load image from disk cache when offline

### ISSUE THREAD

**Issue by KpStP** [square/picasso#1920]
I use the below code to pre fetch image.
`Picasso.with(context).load(imageUrl).memoryPolicy(MemoryPolicy.NO_STORE).get()`
Then restart the application, and use the below code to show image to screen, when the network is offline.
`Picasso.with(context).load(imageUrl).into()` or `Picasso.with(context).load(imageUrl).get()`

The method `RequestCreator.into()` always show image properly. But method ` RequestCreator.get()` will got the problem, more than half images will display properly, but some images from specified websites will not.
For example Picasso can’t load below images when offline: 1. https://img.buzzfeed.com/buzzfeed-static/static/2018-06/12/20/asset/buzzfeed-prod-web-02/sub-buzz-4037-1528851390-5.png
2. http://www.nasa.gov/sites/default/files/thumbnails/image/nhq201806080012.jpg

When I used RequestCreator.networkPolicy(NetworkPolicy.OFFLINE) to force Picasso load image from disk cache. All the images will display properly.

What causes these problems?
Thank you in advance.

**Comment by NightlyNexus** [comment]
What version of Picasso? Is this reproducible in the sample app in this project?

**Comment by NightlyNexus** [comment]
there's a good chance the http cache-control header from those responses isn't set for what you want. i haven't looked, though.

**Comment by NightlyNexus** [comment]
you could write an okhttp3.Interceptor to rewrite the response headers.

**Comment by KpStP** [comment]
@NightlyNexus After added cache-control header in okhttp3.Interceptor, the problem is solved. Thank you.

**Comment by KpStP** [comment]
@NightlyNexus

**Comment by KpStP** [comment]
@NightlyNexus After I added cache-control header, the problem has solved for a while, now the problem has suddenly returned. Now, method `RequestCreator.into()` is also occur this problem.
