### ISSUE TITLE
Cache Disk isn't used

### ISSUE THREAD

**Issue by anonym24** [square/picasso#1936]
I checked app private folder and it doesn't create any cache files when using:

```
Picasso.get()
                        .load(item.getUrl())
                        .networkPolicy(NetworkPolicy.OFFLINE)
                        .placeholder(R.drawable.placeholder)
                        .error(R.drawable.placeholder)
                        .into(imageView);
```

`implementation 'com.squareup.picasso:picasso:2.71828'`

So when I scrolling my items in recyclerview I see placeholder all the time
but it should just instantly load from disk so we wouldn't even have time to placeholder...
but unfortunately I see this annoying placeholder all the time

**Comment by JakeWharton** [comment]
The disk cache is a property of the HTTP client, not Picasso, and Picasso has very little control over it. If you only ever make requests with the offline policy, the URL will never be fetched by the HTTP client and stored in the HTTP client's disk cache for future use in offline more. Moreover, even if you do make online requests, the HTTP client will honor the caching semantics defined by the headers of the response. Picasso has no control over this. We merely ask the HTTP client for the URL.

**Comment by anonym24** [comment]
where should check path to that cache? mb it loads actually from cache but with big delay (because when I implemented manual cache to load File image directly to imageView it worked very instantly - `BitmapFactory.decodeFile(path, options)`, but here some delays or it doesn't use cache at all and images just download from internet fast but still I can see placeholder before it loaded)

**Comment by JakeWharton** [comment]
The default cache is installed into the application cache directory as an 'http' subdirectory.
