### ISSUE TITLE
load into not working on API 19

### ISSUE THREAD

**Issue by JulesFrechette** [square/picasso#1941]
Permissions are present in the manifest yet it seems impossible to load an image from an URL into an ImageView on API 19. Works fine on more recent devices. Unfortunately zero logs are available to provide more information.

Picasso.with( ).load( ).into( );

**Comment by JakeWharton** [comment]
If no logs are available, how can we be expected to discern any underlying cause or problem?

**Comment by lifalzarano** [comment]
I was having the same issue on API 19, but I found that it went away once I upgraded to the latest version of Picasso.
