### ISSUE TITLE
how to disable appcompat 27.1.0 inner picasso and use appcompat 27.1.1

### ISSUE THREAD

**Issue by Shahriyar13** [square/picasso#1945]
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.1.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:exifinterface:27.1.0 less... (Ctrl+F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).

picasso using 27.1.0 and i'm using 27.1.1

**Comment by JakeWharton** [comment]
Use a resolution strategy to force all of the versions to be the same. See https://github.com/square/picasso/issues/1913#issuecomment-393785576
