### ISSUE TITLE
Piccaso loads wrong image in large size recycleview

### ISSUE THREAD

**Issue by dineshoffl** [square/picasso#1952]
Piccaso loads wrong image in large size recycleview . am facing this issue . i have 200 items in my recycleview each item has imageview when scrolling recycleview item images are dynamicaly changed and loads wrong image in recycleview item.

**Comment by JakeWharton** [comment]
Please provide a failing test case or executable sample that demonstrates the problem. This is not enough information to diagnose where the problem lies.

**Comment by dineshoffl** [comment]
if (flg.getFlag()!=null&&!flg.getFlag().equals("")){
            Picasso.with(context).load(
                    context.getString(R.string.flagimageback)+flg.getFlag()).into(imgview);
            holder.name.setText(flg.getName());
        }

this is my code in onbindViewholder method in recycleview

**Comment by JakeWharton** [comment]
You are missing a call to `cancelRequest` in an `else` block.
