### ISSUE TITLE
Image is not loading on new version 2.71828

### ISSUE THREAD

**Issue by naveenchandan** [square/picasso#1954]
hi,
the images are not loading in new version,
but it is loading in old version 2.5.2

**Comment by JakeWharton** [comment]
This is not enough information for an actionable report. Please provide a sample URL, Picasso logs, any exceptions being passed to the exception handler, and the code you are using.

**Comment by naveenchandan** [comment]
Here is the code i am using to get image in new version of picasso...
Picasso.get()
.load("url of the image")
.into(imageView);
and code for old version...
Picasso.with(mContext)
                    .load("url of the image")
                    .into(imageView);
the image is loading in new version but it  is not loading in old version

**Comment by h-tolou** [comment]
hi
i remove this line from build.gradle
implementation 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0
then my problem solved

**Comment by dandragut** [comment]
Removing the `com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0` dependency apparently works because Picasso comes with it...
https://github.com/JakeWharton/picasso2-okhttp3-downloader/issues/31
