### ISSUE TITLE
Gradle conflict

### ISSUE THREAD

**Issue by emaborsa** [square/picasso#1973]
Picasso Version 2.71828 works fine with appcompat up to 27.1.0 (com.android.support:appcompat-v7:27.1.0)
When updating to com.android.support:appcompat-v7:27.1.1 there is a conflict:

_All com.android.support libraries must use exact the same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.1.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support.exifinterface:27.1.0_

In order to work with the 27.1.1 I need to use Picasso Version 2.5.2

**Comment by NightlyNexus** [comment]
See https://github.com/square/picasso/issues/1913#issuecomment-393785576
