### ISSUE TITLE
Image is not displayed in targetSDK 28

### ISSUE THREAD

**Issue by psingh-dmi** [square/picasso#1979]
I am trying to upgrade my App for Android P. Below is my Configuration
        compileSdkVersion 28
        buildToolsVersion '28.0.2'
           minSdkVersion 17
         targetSdkVersion 28
    implementation 'com.squareup.picasso:picasso:2.71828'
I am not getting error or warning.

**Comment by JakeWharton** [comment]
This is not enough information for an actionable bug report. Without an exception happening during the load, logs indicating what is happening, or a sample app reproducing the problem we have no way to know what's going on

**Comment by moallemi** [comment]
> I am trying to upgrade my App for Android P. Below is my Configuration
> compileSdkVersion 28
> buildToolsVersion '28.0.2'
> minSdkVersion 17
> targetSdkVersion 28
> implementation 'com.squareup.picasso:picasso:2.71828'
> I am not getting error or warning.

I think it is because of clearText http. According to [Android documentation](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted):

> Starting with Android 9.0 (API level 28), cleartext support is disabled by default.

and because of this picasso can not load images
