### ISSUE TITLE
Unable to find module with Gradle path ':picasso' (needed by modules: 'picasso-pollexor', 'picasso-provider', 'picasso-sample'.)

### ISSUE THREAD

**Issue by saminh97** [square/picasso#1986]
I get this error. What should I do?

**Comment by jrodbx** [comment]
Repro steps?  Sounds like an Android Studio, not a Picasso issue.

**Comment by saminh97** [comment]
Clone it in usual way. VCS-> checkout from version control -> git. Then clone it

**Comment by jrodbx** [comment]
Works for me in Android Studio 3.2 RC 2.  Try filing a bug with Google: https://issuetracker.google.com?
