### ISSUE TITLE
NetworkRequestHandler cannot handle uppercased HTTP or HTTPS schemes

### ISSUE THREAD

**Issue by Grohden** [square/picasso#1990]
I'm getting a `BitmapHunter Exception - Unrecognized type of request` even though everything seems fine, as stated in the title, somehow my URL ended up using **HTTP** (UPPERCASE) and here:

https://github.com/square/picasso/blob/6f3189fb94f0c1a647a5ada605c505e00caf51f5/picasso/src/main/java/com/squareup/picasso3/NetworkRequestHandler.java#L46-L52

Is my (and possible others) problem, i don't know if it's intended to NOT support the UPPERCASE case scheme, but using `(SCHEME_HTTP.equalsIgnoreCase(scheme) || SCHEME_HTTPS.equalsIgnoreCase(scheme))` would solve the problem.

Also, this is a silly mistake that is not easy to find, if the insensitive case is intended, at least put some good exception message..

**Comment by JakeWharton** [comment]
PR welcome
