### ISSUE TITLE
升级问题

### ISSUE THREAD

**Issue by ZCSDK** [square/picasso#1995]
picasso的开发团队，升级以后，应该要兼容旧版本。我们用的2.5.2版本的。客户用的2.71828版本的。新版本出来是不是应该兼容一下老版本。

**Comment by NightlyNexus** [comment]
Picasso e is deliberately not binary compatible.

From the [CHANGELOG](https://github.com/square/picasso/blob/415f5c3bdf74363a4027f25e6ea939a3915367b3/CHANGELOG.md#version-271828-2018-03-07), "This version is not fully backwards compatible with previous 2.x releases! It is intended to be a stable, pre-3.0 release that users of 3.0.0-SNAPSHOT can use in the mean time."
