### ISSUE TITLE
java.lang.NoSuchMethodError: No static method

### ISSUE THREAD

**Issue by ZCSDK** [square/picasso#1996]
java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.sobot.demo-1/base.apk)

**Comment by JakeWharton** [comment]
This method was removed. You should update your code and libraries before updating the Picasso version.

**Comment by Renascienza** [comment]
@JakeWharton is not exactly a good thing, remove public APIs like that. In fact is OOP 101 avoid to do it. 

To avoid break projects without need, you can just do:

`
@Deprecated("your reason and observations about get context behind the curtains")
public static Picasso with(Context context){
   return Picasso.get();
}
`
