### ISSUE TITLE
Resampling Images

### ISSUE THREAD

**Issue by kashifo** [square/picasso#2006]
I want to know what image resampling algorithm is picasso using in resize method? 
It'd be better if we use Lanczos Resampling to reduce loss of quality.

**Comment by JakeWharton** [comment]
Picasso delegates all resizing operation to the Android operating system. It has no control on what algorithm is being used.

If you want you can supply your own transformation that does resizing, but it has the downside of requiring that the full-size image be decoded prior to calling your transformer whereas Android can resize it while doing the initial decode.
