### ISSUE TITLE
Abstract Request

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#2007]
Requests can have different properties, and different RequestHandlers can use or not use those properties.

For example, network Requests have HTTP headers. (Picasso 2 has no API to add a request header to a single request.)

Request needs to support variable property types, possibly via type inheritance.

**Comment by NightlyNexus** [comment]
yeah, a tag or map would work.

**Comment by JakeWharton** [comment]
I like a Map because it will have symmetry with #639

**Comment by Ramkishorevit** [comment]
@NightlyNexus It would be great to have HTTP headers support for the network requests. Could you please highlight some more examples of different properties apart from the HTTP headers? So that I can get more insight on implementing this. Also I am assuming the equation here is to represent the headers as a single Map.

**Comment by NightlyNexus** [comment]
`@swankjesse` suggested having an API just for HTTP headers. Then, any other non-HTTP usages/handers/interceptors could read data off of custom headers (rare case), similar to how data can be passed into OkHttp Interceptors currently. I am in favor of that.

**Comment by Ramkishorevit** [comment]
@NightlyNexus so you mean something like this,

`Picasso.with(context).load(uri).addHeader(map).into(view);`

But personally I feel header is a property that has more closer association with the Uri. Wouldn't it be good if we do something like,

`PicassoUri uri = new PicassoUri(url, headerMap);
  Picasso.with(context).load(uri).into(view);`
Just a thought. I like both anyways. Please let me know your thoughts on this.

**Comment by JakeWharton** [comment]
The headers do not affect things like caching which your snippet implies by
combining it with the Uri. Plus I don't want to invent another type for
carrying composite data–the request is already that type.

**Comment by Ramkishorevit** [comment]
@JakeWharton Thanks. That makes a lot of sense.
