### ISSUE TITLE
Picasso change coordination of image

### ISSUE THREAD

**Issue by Miteshmakwana73** [square/picasso#2008]
i am using [ClickableAreasImages](https://github.com/Lukle/ClickableAreasImages) 

while implementing  picasso with this library it's not working properly clickable  x,y position change automatic
```
Picasso.get().load(Config.URL_IMAGE+imageurl).into(image,new com.squareup.picasso.Callback() {
            @Override
            public void onSuccess() {
                ClickableAreasImage clickableAreasImage = new ClickableAreasImage(new PhotoViewAttacher(image), MainActivity.this);

                // Define your clickable area (pixel values: x coordinate, y coordinate, width, height) and assign an object to it
                List<ClickableArea> clickableAreas = getClickableAreas();
                clickableAreasImage.setClickableAreas(clickableAreas);
            }

            @Override
            public void onError(Exception e) {

            }
        });
```
this what i have done so far

**Comment by JakeWharton** [comment]
This is not enough information to be an actionable report, moreover it's not clear why or how you think Picasso is broken or how we should fix it. If you have a sample that reliably demonstrates a problem with Picasso or a test case that fails that would go a long way to conveying what needs fixed.

**Comment by Miteshmakwana73** [comment]
getting [this output](https://i.stack.imgur.com/1paPU.png)
