### ISSUE TITLE
Problem showing drawable shapes as placeholder

### ISSUE THREAD

**Issue by TapanM** [square/picasso#2012]
I'm trying to load a url of image with drawable as placeholder like this:

` <shape xmlns:android="http://schemas.android.com/apk/res/android"
                 android:shape="oval">
    <solid android:color="@color/black" />
</shape>`

into an ImageView:

`<ImageView
        android:id="@+id/imageview"
        android:layout_height="60dp"
        android:layout_width="60dp"/>`

Picasso call:

`Picasso.get().load(url).placeholder(R.drawable.default_shape).into(imageview)`

But the shape is never showed

**Comment by NightlyNexus** [comment]
What version of Picasso? Can you reproduce it in the sample?
I couldn't reproduce in the sample on master.

**Comment by TapanM** [comment]
Picasso version - 2.71828. 
Url image is showing but if you give wrong url or image takes time to load then placeholder drawable is not showing.

**Comment by NightlyNexus** [comment]
I ran the sample app with Picasso e, and I was able to see the black oval placeholder you posted above.
Let me know if you're able to reproduce in the sample or a minimal sample that demonstrates the problem.
