### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/squareup/picasso/OkHttpDownloader

### ISSUE THREAD

**Issue by Thien658jjh** [square/picasso#2013]
I got this Exception with picasso:2.71828 
How can I fix it  ? 
thanks !

**Comment by JakeWharton** [comment]
This class was removed. Only `OkHttp3Downloader` exists in that version.

**Comment by Thien658jjh** [comment]
So what can I do ? @JakeWharton

**Comment by JakeWharton** [comment]
You haven't really detailed what the problem is. Something you have is referring to the old class and it needs recompiled.
