### ISSUE TITLE
com.android.support:exifinterface version issue

### ISSUE THREAD

**Issue by marvix** [square/picasso#2019]
Hello,

I'm facing an issue with _com.android.support:exifinterface_ version, Picasso using version 27.1.0, and the SKD version is 28, is there a fix for this or should I downgrade the SDK to 27?

`+--- com.android.support:support-annotations:28.0.0
+--- com.android.support:exifinterface:28.0.0
|    \--- com.android.support:support-annotations:28.0.0
\--- com.squareup.picasso:picasso:2.71828
       +--- com.squareup.okhttp3:okhttp:3.10.0
       |       \--- com.squareup.okio:okio:1.14.0
       +--- com.android.support:support-annotations:27.1.0 -> 28.0.0
       \--- com.android.support:exifinterface:27.1.0 -> 28.0.0 (*)

`

`dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:design:28.0.0-rc01'
    implementation 'com.android.volley:volley:1.1.+'
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'com.android.support:exifinterface:28.0.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
}`

The error : 

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0-rc01, 27.1.0. Examples include 'com.android.support:animated-vector-drawable:28.0.0-rc01' and 'com.android.support:exifinterface:27.1.0'

**Comment by NightlyNexus** [comment]
Force all of the support library dependency versions to be the same in your build. If you're using Gradle, see [#1913 (comment)](https://github.com/square/picasso/issues/1913#issuecomment-393785576).

**Comment by marvix** [comment]
I tried this before, but it results more errors:

> Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0-rc01.	
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:design:28.0.0-rc01.	
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.0.	
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:exifinterface:27.1.0.	
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0-rc01.	
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.android.support:design:28.0.0-rc01.	
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.0.	
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.android.support:exifinterface:27.1.0.	
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0-rc01.	
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.android.support:design:28.0.0-rc01.	
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.0.	
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.android.support:exifinterface:27.1.0.	
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0-rc01.	
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.android.support:design:28.0.0-rc01.	
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.0.	
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.android.support:exifinterface:27.1.0.	
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0-rc01.	
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.android.support:design:28.0.0-rc01.	
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.0.	
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.android.support:exifinterface:27.1.0.	



> dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:design:28.0.0-rc01'
    implementation 'com.android.volley:volley:1.1.+'
    implementation 'com.google.code.gson:gson:2.8.5'

//    implementation 'com.android.support:support-annotations:28.0.0'
//    implementation 'com.android.support:exifinterface:28.0.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
}
configurations.all {
    resolutionStrategy {
        eachDependency { details ->
            // Force all of the primary support libraries to use the same version.
            if (details.requested.group == 'com.android.support') {
                details.useVersion versions.supportLibrary
            }
        }
    }
}
