### ISSUE TITLE
Option to post HUNTER_COMPLETE at the front of the message queue?

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#2026]
At startup, our app gets dozens of messages backed up on our message queue in the main thread handler.
This can cause 100+ ms of delay in delivering the HUNTER_COMPLETE message to show our first images.
If Picasso continues using the message queue, maybe it should have a way to mark the images as the top priority?

**Comment by JakeWharton** [comment]
Have you actually tried this? Are these disk cached images? I just worry about causing an arms race. If everyone posts to the front of the queue then we're back in the same situation.

**Comment by NightlyNexus** [comment]
We are trying posting to the front of the queue currently. We've seen good results from testing, and we'll have production comparisons in a couple weeks.

Yes, they are disk cached images.

Yeah, I'm not sure what the best solution is here, sine there's no general priority for messages.

**Comment by NightlyNexus** [comment]
we saw a significant performance benefit from doing this hack in production. we should probably be limiting other things we put in the messages queue at startup, but i still want to ensure that our images are the highest priority.

**Comment by JakeWharton** [comment]
We have a priority setting, right? Let's use that?

**Comment by NightlyNexus** [comment]
the priority used to be for priority relative to other images, but i'm in favor of this signal.

**Comment by JakeWharton** [comment]
Cool. Want to try to implement?
