### ISSUE TITLE
Easily set PicassoThread's thread priority?

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#2027]
PicassoThread sets the priority to background right now. Images are very important to the app I work on, and increasing this priority to foreground has been beneficial to us. If Picasso continues to use the ExecutorService, perhaps it should set the priority to foreground instead or have an API to configure it without needing to bring your own ExecutorService?

**Comment by zhouyuebo** [comment]
fuck!草尼玛，老发这些破邮件，项目删除了还发。
一个垃圾项目有什么好维护的，代码又乱又长。

在 2018-10-31 02:34:20，"Jake Wharton" <notifications@github.com> 写道：


How about a thread factory?

**Comment by JerryIreya** [comment]
@zhouyuebo idiot

**Comment by NightlyNexus** [comment]
Yeah, a thread factory works, and we have to make sure such an API doesn't clobber the existing ExecutorService API. that is, it's an error to set set both a thread factory and an executor service on a Picasso.Builder.

**Comment by JakeWharton** [comment]
Cool. Would welcome a PR if you're interested.
