### ISSUE TITLE
Images don't  load in onBindViewHolder() with the new version.

### ISSUE THREAD

**Issue by huxaiphaer** [square/picasso#2037]
Am using the new version of `Picasso` but it's not loading.
Below is how I implemented it in code .

 ```
@Override
    public void onBindViewHolder(@NonNull DeveloperHolder holder, int position) {


        final DeveloperModel dm = itemList.get(position);
        final String username = dm.getName();
        final int profile_pic = dm.getProfile_pic();
        final String url = dm.getUrl();

        holder.usernameTxt.setText(username);

        Picasso.get().load("http://i.imgur.com/DvpvklR.png").into(holder.profileImg);

        holder.root.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new Intent(DevelopersAdapter.this.context, DetailsActivity.class);
                i.putExtra(USERNAME,username);
                i.putExtra(URL,url);
                i.putExtra(PROFILE_PIC,profile_pic);
                context.startActivity(i);
            }
        });
    }
```

**Comment by NightlyNexus** [comment]
set an error log listener or add a callback to the `into` and check in onError. Is this with Android Pie? Avoid plain http and use https://i.imgur.com/DvpvklR.png

**Comment by bladeofgod** [comment]
i maybe got this problem too, throw Exception context == null;
also occur at onBindViewHolder  while load data

**Comment by gusthavosouza** [comment]
@NightlyNexus it's look's like PicassoContentProvider never call onCreate method to get a context instance.

@bladeofgod can you post more information about? Like picasso version, android.

**Comment by ThiagoBfim** [comment]
Try using https.

` Picasso.get().load("https://i.imgur.com/DvpvklR.png").into(holder.profileImg);`
