### ISSUE TITLE
throw context == null  at recyclerview,its occured after update androidX

### ISSUE THREAD

**Issue by bladeofgod** [square/picasso#2039]
i load image into imageview at recyclerview,but throw an exception (context == null) , when  i got androidX.

**Comment by NightlyNexus** [comment]
Stack trace? Test case? Can you reproduce it in the sample app?
The error message seems to make clear that null is being passed in somewhere incorrectly.

**Comment by bladeofgod** [comment]
> Stack trace? Test case? Can you reproduce it in the sample app?
> The error message seems to make clear that null is being passed in somewhere incorrectly.

thanks reply, i was resolved at stackflow web, they told me  this is a bug, and i change to Glide to load my image.

**Comment by JakeWharton** [comment]
It's unlikely a bug but if you've moved so will we.

**Comment by NightlyNexus** [comment]
From the [SO post](https://stackoverflow.com/questions/53350223/picasso-throw-an-exception-context-null), it looks like Picasso e.
```
java.lang.IllegalStateException: context == null
    at com.squareup.picasso.Picasso.get(Picasso.java:681)
```
dunno how this would happen unless the content provider is getting removed from the build.

**Comment by NightlyNexus** [comment]
It already is nuked, thankfully. It's in a separate artifact, picasso-provider.

**Comment by NightlyNexus** [comment]
And I personally don't mind either way about having that artifact.

**Comment by jigneshappdev** [comment]
Please put the below code in Application class. If Android version is 7.0 over, you need to add the below code.

`Picasso.setSingletonInstance(new Picasso.Builder(this).build());`
