### ISSUE TITLE
Website has different dependency 

### ISSUE THREAD

**Issue by pratikbutani** [square/picasso#2042]
What is use of this `3` in dependency : `implementation 'com.squareup.picasso3:picasso:2.71828'`

I found this on official [website](http://square.github.io/picasso/) and its not working also in my project.

I think its by mistake.

**Comment by NightlyNexus** [comment]
yeah, it's an accident. `com.squareup.picasso:picasso:2.71828`

**Comment by NightlyNexus** [comment]
Fixed by #2044
