### ISSUE TITLE
Unable to build apk due to error generated by Picasso

### ISSUE THREAD

**Issue by fferoz** [square/picasso#2050]
I am trying to build APK with cordova build android command but error occured during build and build can't be generated. The error is with PICASSO library. Please find all the relevant details below. 

**Ionic info:**
    
     `Ionic:
     ionic (Ionic CLI) : 4.8.0 (/usr/lib/node_modules/ionic)
     Ionic Framework   : ionic1 1.3.1
     @ionic/v1-toolkit : 1.0.18

    Cordova:

    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
    Cordova Platforms     : android 6.4.0
    Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 19 other plugins)

    System:

    Android SDK Tools : 26.1.1 (/home/coeus-sol/Android/Sdk)
    NodeJS            : v8.11.3 (/usr/bin/node)
    npm               : 5.6.0
    OS                : Linux 4.15`

platforms/android/com-sarriaroman-photoviewer/abc123photoviewer.gradle has following code
    
    `repositories
    {
    jcenter()
    }
    dependencies {
    implementaion 'com.commit451:PhotoView:1.2.4'
    implementaion 'com.squareup.picasso:picasso:2.5.2'
    }
    android {}`
   

    `BUILD FAILED in 3s
        38 actionable tasks: 36 executed, 2 up-to-date
    /var/www/projects/ionic_practice/test/app_mobile_new/platforms/android/gradlew: Command failed with exit code 1 Error output:
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    /var/www/projects/ionic_practice/test/app_mobile_new/platforms/android/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:171: error: cannot find symbol
                picasso.fit();
                       ^
      symbol:   method fit()
      location: variable picasso of type Picasso
    /var/www/projects/ionic_practice/test/app_mobile_new/platforms/android/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:175: error: cannot find symbol
                picasso.centerInside();
                       ^
      symbol:   method centerInside()
      location: variable picasso of type Picasso
    /var/www/projects/ionic_practice/test/app_mobile_new/platforms/android/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:179: error: cannot find symbol
                picasso.centerCrop();
                       ^
      symbol:   method centerCrop()
      location: variable picasso of type Picasso
    /var/www/projects/ionic_practice/test/app_mobile_new/platforms/android/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:200: error: cannot find symbol
                        .into(photo, new com.squareup.picasso.Callback() {
                        ^
      symbol:   method into(ImageView,<anonymous Callback>)
      location: class Picasso
    /var/www/projects/ionic_practice/test/app_mobile_new/platforms/android/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:224: error: cannot find symbol
                        Piccasso picasso = Picasso.with(PhotoActivity.this)
                        ^
      symbol: class Piccasso
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    5 errors
    
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log 
    output.`

**Comment by Faran123** [comment]
@jrodbx hey, 
Any help here please?

Thanks in advance!

**Comment by JakeWharton** [comment]
The error message indicates the problem is in PhotoView, not Picasso.

**Comment by Faran123** [comment]
so what's your suggestions here please?

**Comment by JakeWharton** [comment]
The code in that file needs fixed. It isn't compatible with the API of the Picasso version you are using.

**Comment by nickgrim** [comment]
@Faran123: you've also got a typo in there, I think:
```
  location: class Picasso
/var/www/projects/ionic_practice/test/app_mobile_new/platforms/android/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:224: error: cannot find symbol
                    Piccasso picasso = Picasso.with(PhotoActivity.this)
                    ^
  symbol: class Piccasso
```

Perhaps you mean `Picasso` instead of `Piccasso`?
