### ISSUE TITLE
Does not load image from url in oreo 8.0

### ISSUE THREAD

**Issue by Ahsaashafeez** [square/picasso#2051]
I am trying to get image loaded from URL returned by firebase, now the thing is that is doesn't load image from url in oreo 8.0, though i have checked the url in toast, it's fine!

**Comment by yesidlazaro** [comment]
can you check if your URL start with "https", if not , maybe that´s the problem

**Comment by Potass** [comment]
I have probably the same problem.

Using Android 9, Picasso version 2.71828, Picasso2 OkHttp3 Downloader version 1.1.0 and urls starting with https://.

When requesting image, it never gets downloaded and therefore Picasso's Callback is never called.

```
Main        created      [R1] Request{/images/banner_2.jpg}
Main        changed      [R1]+0ms into Request{https://some_domain/documents?fn=/images/banner_2.jpg} 
Dispatcher  enqueued     [R1]+2ms 
Hunter      executing    [R1]+3ms 
```

**Everything works like a charm with Picasso version 2.5.2.**

**Comment by MFlisar** [comment]
I use Picasso 2.5.2 and after I made a software to android oreo update on my phone images were not loaded anymore.

In my case @yesidlazaro tipp helper, loading https urls works, but http urls do not...

**Comment by JakeWharton** [comment]
Android forbids cleartext by default as of 8. This isn't an issue with Picasso directly. You can read more on the Android developer docs for Oreo.
