### ISSUE TITLE
StrictMode policy violation

### ISSUE THREAD

**Issue by BulatMukhutdinov** [square/picasso#2054]
When I turn strict mode on it trows `android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage` becase of picasso. How can I fix it?

**Comment by JakeWharton** [comment]
Picasso doesn't create sockets directly. We call into HTTP libraries for that. Your issue is likely that OkHttp doesn't tag its sockets.
