### ISSUE TITLE
Remove check for recycled original bitmap from BitmapHunter

### ISSUE THREAD

**Issue by Flyktsodan** [square/picasso#2055]
We started seeing this crash but only on Huawei Mate 20 Pro running Android 9. Could this be an issue with those specific devices or simply means we run out of memory?

Fatal Exception: java.lang.IllegalStateException: Transformation max-width-190 mutated input Bitmap but failed to recycle the original.
       at com.squareup.picasso.BitmapHunter$6.run(BitmapHunter.java:490)

Picasso version: 2.71828
Picasso Transformations version: 2.1.2

**Comment by JakeWharton** [comment]
Please include the full source of the custom transformation.

**Comment by JakeWharton** [comment]
Well that's disappointing because I was hoping it was implemented
incorrectly! I have a hard time seeing how this could happen except by the
framework returning a recycled bitmap by way of some misguided attempt at
an optimization that probably only makes things worse.

**Comment by NightlyNexus** [comment]
Not directly related to the issue, but is this ISE a necessary check? Maybe Picasso shouldn't care what you do with the original Bitmap in a Transformation?
https://github.com/square/picasso/blob/9328ac88f920f5bd9f4a94e7ca263c33a2146960/picasso/src/main/java/com/squareup/picasso3/BitmapHunter.java#L435

**Comment by JakeWharton** [comment]
It probably doesn't matter in 2019. In 2013 it mattered. The GC will
reclaim and the finalizer will take care of really old platforms which
require the native allocation to be freed. Let's nuke.

**Comment by NightlyNexus** [comment]
that's what i figured. pre-ICS days.

**Comment by JakeWharton** [comment]
PR welcome!
