### ISSUE TITLE
Picasso Update to implementation 'com.squareup.picasso:picasso:2.71828' got error Picasso.with couldn't be resolved

### ISSUE THREAD

**Issue by SUBINPTPM** [square/picasso#2058]
I recently update to com.squareup.picasso:picasso:2.71828 from com.squareup.picasso:picasso:2.5.2.But while trying to run or build project got an error as Picasso.with couldn't be resolved.

Try to build or run project after

1.Clean project

2.invalid cache and restart

But still got the same. But if its revert back to com.squareup.picasso:picasso:2.5.2 to make everything work fine. Is this known bug or any solution for this bug for com.squareup.picasso:picasso:2.71828 version?

StackOverflow question: https://stackoverflow.com/q/54533316/6299045

**Comment by JakeWharton** [comment]
That method has been removed and changed to `Picasso.get()`.
