### ISSUE TITLE
after add lilbrary implementation 'com.squareup.picasso:picasso:2.71828' library implementation 'com.android.support:appcompat-v7:28.0.0' error

### ISSUE THREAD

**Issue by SaputraGo** [square/picasso#2063]
please help me , after add implementation picasso my library appcompact error

**Comment by pavel-zlotarenchuk** [comment]
I have the same problem
I think the fact is that outdated dependencies are used in Picasso

**Comment by JakeWharton** [comment]
Dupe of #1913. Please see https://github.com/square/picasso/issues/1913#issuecomment-393785576 for how to force a single version of the legacy support libraries across your whole app.
