### ISSUE TITLE
Performance issues when using Target

### ISSUE THREAD

**Issue by redd29** [square/picasso#2071]
Images when loaded with Target tend to lag in the views. I tried using a plain Target
`
...
public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
    mImageViewPoster.setImageBitmap(bitmap);
...
`

would still cause a major drop in performance.

**Comment by JakeWharton** [comment]
There's no information here to make this issue actionable. How do we replicate the performance problems? What are the problems relative to? How do we measure a fix?
