### ISSUE TITLE
Supplied non-absolute file path is not being disk cached

### ISSUE THREAD

**Issue by eypibee** [square/picasso#2073]
Using the latest version of Picasso **(2.71828)**, I'm attaching a URL which is not absolutely directing to the file (without file extension eg. .jpg). When I reopen the activity and load again the URL with **NetworkPolicy.OFFLINE**, it throws network related exception which has 504 code. I checked the cache directory (Picasso-Cache) but it does not have any files. Unlike the memory cache, it saves it. Is this some sort of a limitation?

**Comment by JakeWharton** [comment]
If the disk cache is empty then the response didn't have caching headers allowing it to be cached

**Comment by eypibee** [comment]
> If the disk cache is empty then the response didn't have caching headers allowing it to be cached

Thanks, @JakeWharton . We're now dealing with the cache-control which was earlier set to no-store and no-cache.

**Comment by eypibee** [comment]
Hi @JakeWharton . It is still not caching the image. I checked the **CacheStrategy.java** and noticed from the **Factory** class that it checks the headers from the response. 

What are the most important headers should we include?

**Comment by JakeWharton** [comment]
Picasso doesn't have a disk cache. You're interacting with OkHttp at that point. I'm not an expert in HTTP caching headers, but surely there's a bunch of resources on the internet that you can consult as OkHttp honors standard caching headers.
