### ISSUE TITLE
Picasso hangs main thread in Android tests

### ISSUE THREAD

**Issue by chklow** [square/picasso#2074]
When running android tests, after fetching an image with Picasso, the test fails with the error 

```TestRunner: java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=com.testapp.presentationcomponent.implementation.MainActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1552971774975 and now the last time the queue went idle was: 1552971774975. If these numbers are the same your activity might be hogging the event queue.```
Where the thread holding it up is
```
03-17 01:20:05.574 11786 11831 E THREAD_STATE:   Thread[Picasso-refQueue,5,main]

03-17 01:20:05.574 11786 11831 E THREAD_STATE:     java.lang.Object.wait(Native Method)

03-17 01:20:05.574 11786 11831 E THREAD_STATE:     java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:113)

03-17 01:20:05.574 11786 11831 E THREAD_STATE:     com.squareup.picasso.Picasso$CleanupThread.run(Picasso.java:613)
```

CleanupThread is running on the main thread but the Android tests depends on the main thread to be idle in order to continue. Is it possible to change the behavior of CleanupThread to not run on the main thread?

**Comment by JakeWharton** [comment]
> CleanupThread is running on the main thread

CleanupThread is its own thread so it's not running on the main thread. What makes you think this is what's stalling the main thread?

**Comment by chklow** [comment]
Sorry, after investigation, I found that there was a different issue hanging the main thread.
