### ISSUE TITLE
Cannot use any method in Picasso

### ISSUE THREAD

**Issue by reeshabhkumarranjan** [square/picasso#2075]
After adding the latest version in the dependencies, both `Picasso.get()` and `Picasso.with()` are not resolved. I do not know what the issue might be. I suspect something with proguard. But `minifyEnabled` is set to `false` in my build.gradle file. Any idea what I need to do?

**Comment by JakeWharton** [comment]
If you're talking about the 3.0.0-SNAPSHOT then yes, both were removed. You have to maintain your own singleton instance now.

**Comment by reeshabhkumarranjan** [comment]
Well, I am using 2.71828 version. Do I have to do the same in it too?

**Comment by JakeWharton** [comment]
That version should have Picasso.get()

**Comment by reeshabhkumarranjan** [comment]
Yes, it has. I was doing a silly mistake.
