### ISSUE TITLE
Max age parameter has no effect

### ISSUE THREAD

**Issue by cixweb** [square/picasso#2080]
Hi, I'm trying to modify cache control header with a custom value of max age parameter. I'm using Picasso global instance and a custom downloader with an OkHttp Interceptor applied on a request in which I sets max age at 15 seconds. I'm noticing that the header have been modified but it seems that has no effect because  Picasso continue to read the image in cache even if max age has been crossed.  I would expect that  Picasso reloads image from network after that  max age parameter has been exceeded. Can't someone help me with this mystery?

**Comment by JakeWharton** [comment]
Picasso does not honor cache headers in its memory cache. It doesn't know anything about HTTP, in fact. In order to make memory caching simple and sustainable from a complexity perspective, we assume all rendered bitmaps to be immutable forever (or, in reality, for as long as the process lives). If you need time-based caching I would recommend altering the request `Uri` in some way or you can explicitly purge items from the cache when something times out. We're not going to add these complex features to the cache because it's unclear how they should apply when the image source isn't HTTP. You also can use the `NO_STORE` and/or `NO_CACHE` memory policies if you want to always defer to the HTTP cache at the expense of decoding the bitmap over and over again.

**Comment by cixweb** [comment]
Thank you for such a complete reply. So, is it not correct to use Picasso with custom downloader to manipulate header of HTTP response?  I append my sample code to manipulate max age parameter.

`static PicassoCP getInstance(Context context){

        if(mPicassoCP == null) {
            synchronized (PicassoCP.class) {
                if(mPicassoCP == null) {
                    mPicassoCP = new PicassoCP(context);
                }
            }
        }
        return mPicassoCP;
    }


    private PicassoCP(Context context){
        customPicassoInstance = buildCustomPicassoInstance(context);
    }

    public static class CacheInterceptor implements Interceptor {
        @Override
        public Response intercept(Chain chain) throws IOException {
            Response response = chain.proceed(chain.request());

            CacheControl cacheControl = new CacheControl.Builder()
                .maxAge(80, TimeUnit.SECONDS)
                .build();

            return response.newBuilder()
                .removeHeader("Pragma")
                .removeHeader("Cache-Control")
                .header("Cache-Control", cacheControl.toString())
                .build();
        }
    }

    public static Picasso buildCustomPicassoInstance (Context context){

        OkHttpClient okHttpClient1 = new OkHttpClient.Builder()
            .addNetworkInterceptor(new CacheInterceptor())
            .cache(new Cache(context.getCacheDir(), Integer.MAX_VALUE))
            .build();

        OkHttp3Downloader downloader = new OkHttp3Downloader(okHttpClient1);
        Picasso picasso = new Picasso.Builder(context).
            downloader(downloader).
            build();
        picasso.setLoggingEnabled(true);
        picasso.setIndicatorsEnabled(true);
        return picasso;
    }`
 
`   private void loadImage (final ImageView imageView) {

        PicassoCP.getInstance(getApplicationContext()).getCustomPicassoInstance().load(URL)
            .networkPolicy(NetworkPolicy.OFFLINE)
            .into(imageView, new Callback() {
                @Override
                public void onSuccess() {
                }

                @Override
                public void onError(Exception e) {
                    PicassoCP.getInstance(getApplicationContext()).getCustomPicassoInstance().load(URL)
                        .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
                        .error(R.drawable.ic_launcher_background)
                        .into(imageView, new Callback() {

                            @Override
                            public void onSuccess() {
                            }

                            @Override
                            public void onError(Exception e) {

                            }

                        });
                }
            });
    }`

**Comment by JakeWharton** [comment]
You can do that, but you're manipulating the HTTP cache and not the memory
cache. If you restart your app you'll see the max age you set be honored.
But while the app is alive and while the image is available in the memory
cache it will not be respected.

**Comment by cixweb** [comment]
Than you so much for a comprehensive response.
