### ISSUE TITLE
picasso placeholder nonsupport AppCompatDelegate 

### ISSUE THREAD

**Issue by jingchao920315** [square/picasso#2082]
drawable Choice problem

**Comment by JakeWharton** [comment]
This is not enough information for an actionable report. Please provide a failing test case or sample which demonstrates the problem.

**Comment by jingchao920315** [comment]
I mean in case we want some theme-depended drawable (vector, for example, which could be passed theme's color as attribute, not constant color value). By that a placeholder's drawable could be "lighter" in dark theme, and "darker" in light theme, dynamically. (IMO, caching a placeholder drawable is not necessary, as it doesn't consume too much resource).

The problem now is: Picasso will use a final ApplicationContext for its #getDrawable() action, which will not listen to theme's attributes.

Don't know if you are interested in theming and support libraries or not, but it would be nice if Picasso supports something like ContextCompat.getDrawable().

**Comment by JakeWharton** [comment]
Got it. We're tracking that use case with #1275.

**Comment by jingchao920315** [comment]
Activity `  AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);`

placeholder image Resources  no change drawable-night-xxhdpi 

Need to change：Picasso -Builder
`    /** Start building a new {@link Picasso} instance. */
    public Builder(@NonNull Context context) {
      if (context == null) {
        throw new IllegalArgumentException("Context must not be null.");
      }
      this.context = context.getApplicationContext();
    }`
change to 
`  /** Start building a new {@link Picasso} instance. */
    public Builder(@NonNull Context context) {
      if (context == null) {
        throw new IllegalArgumentException("Context must not be null.");
      }
      this.context = context;
    }`

**Comment by jingchao920315** [comment]
in Activity call 

```
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);

```
placeholder image Resources no change drawable-night-xxhdpi

The main reason:

```
  private Drawable getPlaceholderDrawable() {
    if (placeholderResId != 0) {
      if (Build.VERSION.SDK_INT >= 21) {
        return picasso.context.getDrawable(placeholderResId);
      } else if (Build.VERSION.SDK_INT >= 16) {
        return picasso.context.getResources().getDrawable(placeholderResId);
      } else {
        TypedValue value = new TypedValue();
        picasso.context.getResources().getValue(placeholderResId, value, true);
        return picasso.context.getResources().getDrawable(value.resourceId);
      }
    } else {
      return placeholderDrawable; // This may be null which is expected and desired behavior.
    }
  }
```
picasso.context is ApplicationContext no AppCompatActivity theme

Need to change：Picasso -Builder

```
    /** Start building a new {@link Picasso} instance. */
    public Builder(@NonNull Context context) {
      if (context == null) {
        throw new IllegalArgumentException("Context must not be null.");
      }
      this.context = context;
    }
    
```

**Comment by jingchao920315** [comment]
in Activity call 

```
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);

```
placeholder image Resources no change drawable-night-xxhdpi

The main reason:

```
  private Drawable getPlaceholderDrawable() {
    if (placeholderResId != 0) {
      if (Build.VERSION.SDK_INT >= 21) {
        return picasso.context.getDrawable(placeholderResId);
      } else if (Build.VERSION.SDK_INT >= 16) {
        return picasso.context.getResources().getDrawable(placeholderResId);
      } else {
        TypedValue value = new TypedValue();
        picasso.context.getResources().getValue(placeholderResId, value, true);
        return picasso.context.getResources().getDrawable(value.resourceId);
      }
    } else {
      return placeholderDrawable; // This may be null which is expected and desired behavior.
    }
  }
```
picasso.context is ApplicationContext Can't get AppCompatActivity theme

Need to change：Picasso -Builder

```
    /** Start building a new {@link Picasso} instance. */
    public Builder(@NonNull Context context) {
      if (context == null) {
        throw new IllegalArgumentException("Context must not be null.");
      }
      this.context = context;
    }
    
```
