### ISSUE TITLE
Won't load images from URLs with "attachment" disposition type in response header

### ISSUE THREAD

**Issue by KukyMan** [square/picasso#2083]
**When in the URL response header is this** _(which just means that it will act like a downloadable file in a browser)_: 
`content-type: image/jpeg`
...
`content-disposition: attachment;`...

**instead of just this:**
`content-type: image/jpeg`

Picasso won't load it.

Log:
`04-25 18:36:42.086 4077-4805/xxx D/Picasso: Dispatcher  enqueued     [R1]+2ms 
04-25 18:36:42.091 4077-4886/xxx D/Picasso: Hunter      executing    [R1]+4ms 
04-25 18:36:42.906 4077-4805/xxx D/Picasso: Dispatcher  retrying     [R1]+820ms 
04-25 18:36:42.911 4077-4889/xxx D/Picasso: Hunter      executing    [R1]+824ms 
04-25 18:36:43.451 4077-4805/xxx D/Picasso: Dispatcher  retrying     [R1]+1364ms 
04-25 18:36:43.456 4077-4890/xxx D/Picasso: Hunter      executing    [R1]+1369ms 
04-25 18:36:43.461 4077-4805/xxxs D/Picasso: Dispatcher  batched      [R1]+1377ms for error
04-25 18:36:43.671 4077-4805/xxx D/Picasso: Dispatcher  delivered    [R1]+1578ms 
04-25 18:36:43.671 4077-4077/xxx D/Picasso: Main        errored      [R1]+1579ms HTTP 504`

**Comment by JakeWharton** [comment]
Picasso doesn't download images from HTTP. It just passes the request along to your chosen HTTP client. Which one are you using?

**Comment by KukyMan** [comment]
I'm using OKHttp 3.5. I think a work around should be something like modifying the response.body before it passes? I have no idea.

**Comment by JakeWharton** [comment]
While that's a really old version of OkHttp, I don't recall it ever caring about that header, and it certainly doesn't now: https://github.com/square/okhttp/search?utf8=%E2%9C%93&q=disposition.

What version of Picasso? Can you attach an error listener and log the exception that occurs?

**Comment by KukyMan** [comment]
Picasso version: picasso:2.71828
Exception: com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504

**Comment by KukyMan** [comment]
Hey, that was just my bad, i forgot to handle cookies (the image was viewable only for logged users). Sorry for wasting your time. Any idea how to atach a cookie jar for the okhttp client used by picasso?

**Comment by JakeWharton** [comment]
You can set a custom `OkHttpClient` by creating it and then calling `.downloader(new OkHttpDownloader(yourClient))` on your `Picasso.Builder`.
