### ISSUE TITLE
Lint failed when upgraded to 2.71828

### ISSUE THREAD

**Issue by lakshyagupta21** [square/picasso#2088]
I'm trying to compile the project with 2.71828 Picasso version but lint is failing with the following description
 
`All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 27.1.0. Examples include com.android.support:asynclayoutinflater:28.0.0 and com.android.support:exifinterface:27.1.0`

I've included `   'com.android.support:support-v4:28.0.0'
` in my gradle.

**Comment by JakeWharton** [comment]
See https://github.com/square/picasso/issues/1913#issuecomment-393785576. You need to force all support library dependencies to the same version you want.
