### ISSUE TITLE
Picasso Get() method not loading images from YouTube ???

### ISSUE THREAD

**Issue by SaRan111997** [square/picasso#2090]
I'm Try Serveral Way To Slove This Problem But I Can't Slove it. I Think Problem In Picasso API Because Below Pie Devices Version Works Fine By This Method. But Pie And Higher Devices Are Not Image Loading Properly 

My Android Pie Device Are Not Load Thumbnail Image From YouTube String. 

This Is My Code. I'm  Checked Serveral Times  But No Use On My Side. So I'm Share With For Your Review Any Suggestion !!!!
//Youtube Image Not Loading on Pie Devices
 ****if (str_type != null && str_type.equals("youtube")) {
            Picasso.get()
                    .load(Constant.YOUTUBE_IMAGE_FRONT + str_video_id + Constant.YOUTUBE_IMAGE_BACK)
                    .placeholder(R.drawable.ic_thumbnail)
                    .into(video_thumbnail);****

        } 
// Else Part Images Loaded On All Devices 
else {
            Picasso.get()
                    .load(Config.ADMIN_PANEL_URL + "/upload/" + str_thumbnail)
                    .placeholder(R.drawable.ic_thumbnail)
                    .into(video_thumbnail);
        }

        txt_category.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(ActivityDetailVideo.this, ActivityRelatedCategory.class);
                intent.putExtra(Constant.KEY_VIDEO_CATEGORY_ID, str_cid);
                intent.putExtra(Constant.KEY_VIDEO_CATEGORY_NAME, str_category);
                startActivity(intent);
            }
        });

        video_thumbnail.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                if (Tools.isNetworkAvailable(ActivityDetailVideo.this)) {

                    if (str_type != null && str_type.equals("youtube")) {
                        Intent intent = new Intent(ActivityDetailVideo.this, ActivityYoutubePlayer.class);
                        intent.putExtra(Constant.KEY_VIDEO_ID, str_video_id);
                        startActivity(intent);
                    } else if (str_type != null && str_type.equals("Upload")) {
                        Intent intent = new Intent(ActivityDetailVideo.this, ActivityVideoPlayer.class);
                        intent.putExtra("url", Config.ADMIN_PANEL_URL + "/upload/video/" + str_url);
                        startActivity(intent);
                    } else {
                        if (str_url != null && str_url.startsWith("rtmp://")) {
                            Intent intent = new Intent(ActivityDetailVideo.this, ActivityRtmpPlayer.class);
                            intent.putExtra("url", str_url);
                            startActivity(intent);
                        } else {
                            Intent intent = new Intent(ActivityDetailVideo.this, ActivityVideoPlayer.class);
                            intent.putExtra("url", str_url);
                            startActivity(intent);
                        }
                    }

                    loadViewed();
                    showInterstitialAd();

                } else {
                    Toast.makeText(getApplicationContext(), getResources().getString(R.string.network_required), Toast.LENGTH_SHORT).show();
                }

            }
        });

        video_description.setBackgroundColor(Color.parseColor("#ffffff"));
        video_description.setFocusableInTouchMode(false);
        video_description.setFocusable(false);
        video_description.getSettings().setDefaultTextEncodingName("UTF-8");

        WebSettings webSettings = video_description.getSettings();
        Resources res = getResources();
        int fontSize = res.getInteger(R.integer.font_size);
        webSettings.setDefaultFontSize(fontSize);

        String mimeType = "text/html; charset=UTF-8";
        String encoding = "utf-8";
        String htmlText = str_description;

        String text = "<html dir='rtl'><head>"
                + "<style type=\"text/css\">body{color: #525252;}"
                + "</style></head>"
                + "<body>"
                + htmlText
                + "</body></html>";

        video_description.loadData(text, mimeType, encoding);
    }

**Comment by JakeWharton** [comment]
There is simply not enough information to debug what's going on here, but the fact that it varies based on Android version points to it not being a Picasso problem. Are you fetching images over HTTP? Android 9 disabled that by default.

**Comment by SaRan111997** [comment]
Thank You For Your Reply :)
