### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [square/picasso#2095]
Greetings, I'm here today to offer my services. As a graphic designer in development and an open-source enthusiast, I wish to contribute to this wonderful project by making a logo for it, the process is totally free and we would be working together to create the design that fits best with your project. Certainly, you can quit whenever you want. In case you agree, I would like to ask you a few simple questions about your project to have a better understanding of it and so deliver a better result, also you could share with me any preferences you may have about colors, shapes, etc.

Sorry for disturbing if this is not the proper channel to request this, best regards.

**Comment by JakeWharton** [comment]
Thanks for the offer, but the project is somewhat stagnant at this point and I wouldn't want you to waste your time in a place where it's unlikely to have a large benefit.
