### ISSUE TITLE
Transformation is much slower than Target

### ISSUE THREAD

**Issue by fraherm** [square/picasso#2099]
I am trying to apply a blur effect on an image. I realized that the transformation takes ~450ms if I apply the blur effect as a `Transformation`. If I do the same thing through the `Target` interface it is a lot faster.
I have a problem finding out what the reason is. I like to show the image fast and still cache it. Does anyone know what the reason could be that `Transformation` is slower than `Target`?

Run with `BlurTransformation`
```
D/Picasso: Main        created      [R16] Request{https://... BlurTransformation-25.0-2.0}
D/Picasso: Dispatcher  enqueued     [R16]+0ms 
D/Picasso: Hunter      executing    [R16]+1ms 
D/Picasso: Main        created      [R17] Request{https://...}
D/Picasso: Main        completed    [R17] from MEMORY
D/Picasso: Hunter      decoded      [R16]+51ms 
D/Picasso: Hunter      transformed  [R16]+201ms from custom transformations
D/Picasso: Dispatcher  batched      [R16]+203ms for completion
D/Picasso: Dispatcher  delivered    [R16]+443ms 
D/Picasso: Main        completed    [R16]+456ms from DISK
```

**Comment by JakeWharton** [comment]
How are you measuring? These logs indicate events and not the actual time spent doing a particular thing. If you are relying on these events then moving code from a transformation to target will not cause it to be measured as logging ends prior to calling the target callback. If you actually put markers around the operation and time it in both locations you'll find that it takes the same amount of time. The advantage of the transformation, though, is that your ~150ms computational blur is done on a background thread whereas when done in a target it's done on the main thread and you'll drop about 10 frames.
