### ISSUE TITLE
BitmapHunter.java line 468 com.squareup.picasso.BitmapHunter$4.run

### ISSUE THREAD

**Issue by chandanainflux** [square/picasso#2112]
I'm getting a lot of app crashes happening because of this issue
I'm using Picasso for loading all the images with a particular width and height transformation
and I got to know this crashes in Crashlytics and a lot of users got affected to it

Fatal Exception: java.lang.NullPointerException: Transformation scaleRespectRatio00 returned null after 0 previous transformation(s).

Code: 

Transformation transform = new ScaleToFitWidthHeightTransform(width, height);
Picasso.get()
                                .load(image_url)
                                .transform(transform)
                                .error(R.drawable.banner_place_holder)
                                .into(banner_image);

public class ScaleToFitWidthHeightTransform implements Transformation {

    private int mWidth, mHeight;

    public ScaleToFitWidthHeightTransform(int width, int height) {
        mWidth = width;
        mHeight = height;
    }

    @Override
    public Bitmap transform(Bitmap source) {
        Bitmap scaleBitmap = null;
        if (mWidth > 0 && mHeight > 0) {
            scaleBitmap = Bitmap.createScaledBitmap(source, mWidth, mHeight, true);
            if (scaleBitmap != source) {
                source.recycle();
            }
        }
        return scaleBitmap;

    }

    @Override
    public String key() {
        return "scaleRespectRatio" + mWidth + mHeight;
    }
}

Transformation list:
scaleRespectRatio00
       at com.squareup.picasso.BitmapHunter$4.run + 468(BitmapHunter.java:468)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7078(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 964(ZygoteInit.java:964)

**Comment by JakeWharton** [comment]
Something is passing 0 as the width or height into the constructor of your transformation, the `if` prevents it from running, and it returns null. Either prevent 0 and remove the `if` or return the source bitmap in an `else`.

**Comment by chandanainflux** [comment]
will this fix work?

`if (width != 0 && height != 0) {
                    val transform = ScaleToFitWidthHeightTransform(width, height)
                    if (transform != null) {
                       Picasso.get()
                                        .load(image_url)
                                        .transform(transform)
                                        .placeholder(R.drawable.film_place_holder)
                                        .error(R.drawable.film_place_holder)
                                        .into(binding.ivFilmImage)
}
                }`

**Comment by JakeWharton** [comment]
Yes. You can lose that null check, too.
