### ISSUE TITLE
Picasso  support gif?

### ISSUE THREAD

**Issue by raqusty** [square/picasso#2113]
Hello
Does Picasso support gif?
If so, how do I use it? Are there any examples?

**Comment by JakeWharton** [comment]
Static gif, yes. Animated, no. It might eventually, but for now use Coil or Glide if you require animated gif support.

**Comment by raqusty** [comment]
> Static gif, yes. Animated, no. It might eventually, but for now use Coil or Glide if you require animated gif support.

Thank you for your reply.
How do you use it?
I used a local gif, but it didn't move.
