### ISSUE TITLE
Error in Picasso method

### ISSUE THREAD

**Issue by ineem** [square/picasso#2125]
Hello,
I'm working on a project that I need to upload an image to firebase,
I added the implementation on gradle and I make sure that the import exist, but I have an error when I write this line (Picasso.with(this).load(mImageUri).into(mImageView);) it didn't recognize "with(this)".
I don't know where the problem is? 

![implementation](https://user-images.githubusercontent.com/50343000/68978906-24031400-080d-11ea-8453-98e9785a9996.PNG)

![import](https://user-images.githubusercontent.com/50343000/68978907-249baa80-080d-11ea-8a6f-6fe97ac2dc0a.PNG)

![with](https://user-images.githubusercontent.com/50343000/68978909-249baa80-080d-11ea-92e4-4ed84a8094d7.PNG)

**Comment by JakeWharton** [comment]
You can replace `Picasso.with(this)` with `Picasso.get()` since you appear to be using version 2.7.
