### ISSUE TITLE
Please change com.android.support:exifinterface:27.1.0 to 28.0.0

### ISSUE THREAD

**Issue by 2002demon** [square/picasso#2128]
Hello!
I have this error, becouse last picasso 2.71828 uses com.android.support:exifinterface:27.1.0:

All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 27.1.0. Examples include 'com.android.support:animated-vector-drawable:28.0.0' and 'com.android.support:exifinterface:27.1.0'

Can you fix this?

**Comment by JakeWharton** [comment]
We do not track dependency updates unless they have a feature which is needed. If you are using the legacy support libraries, you can either force all of them to the same version or add an explicit dependency on exifinterface 28.

**Comment by 2002demon** [comment]
I use currently newest versions: com.android.support:support-v4:28.0.0

Previosly i had picasso:2.5.2 without errors:
`implementation 'com.squareup.picasso:picasso:2.5.2'`

Then i have just updated to: 
`implementation ('com.squareup.picasso:picasso:2.71828')`
and i have this error - see above.

Now i have found this solution:
```
    implementation ('com.squareup.picasso:picasso:2.71828') {
        exclude group: 'com.android.support'
        exclude module: ['exifinterface', 'support-annotations']
    }
```

Is this right way? Or everything is wrong in Picasso?

**Comment by JakeWharton** [comment]
No, that is wrong. You either need to force all versions of support dependencies to 28 using a resolution strategy or explicitly depend on exifinterface version 28.
