### ISSUE TITLE
Picasso 2.0.0 seems not working in Android 2.3

### ISSUE THREAD

**Issue by daimajia** [square/picasso#213]
I tested in three device , Android 4.2.1 and two Android 2.3 devices.

4.2.1 works well , however the others can not set image correctly in ListView Adapter...

I changed to Picasso 1.1.1 , all work well.

**Comment by XclusR** [comment]
I have same problem with latest picasso with simplest code:

Picasso.with(this).load(url).into(image);

Works on android > 4.0, but didn't dowloads images on 2.3.

Libraries versions:
    compile 'com.squareup.picasso:picasso:2.4.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'

**Comment by XclusR** [comment]
Here is picasso log:
Main        created      [R0] Request{https://...}
Dispatcher  enqueued     [R0]+227ms
Hunter      executing    [R0]+374ms

Also there are lot of unresolved methods errors:
Could not find method java.nio.file.Files.newOutputStream, referenced from method okio.Okio.sink
Could not find method java.nio.file.Files.newInputStream, referenced from method okio.Okio.source
Could not find method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getContentLengthLong, referenced from method com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getContentLengthLong
Could not find method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFieldLong, referenced from method com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFieldLong
Could not find method com.squareup.okhttp.internal.Util.emptySink, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine
Could not find method com.squareup.okhttp.internal.http.HttpMethod.hasRequestBody, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine
Could not find method com.squareup.okhttp.internal.http.HttpMethod.hasRequestBody, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine
Could not find method com.squareup.okhttp.internal.http.HttpEngine.hasResponseBody, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getErrorStream
Could not find method com.squareup.okhttp.internal.http.HttpEngine.getResponseBodyBytes, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream
DexOpt: couldn't find static field
