### ISSUE TITLE
Further roadmap for Picasso? 

### ISSUE THREAD

**Issue by wbinarytree** [square/picasso#2140]
Hey. 
Firstly thanks for the great library. Seems v2.71828 is a release long times ago and seems 3.0 is still in Snapshot. 
I'm willing to use `ImageDecoder` for Android P devices and above to use those animated image feature. But I'm not sure which version of Picasso and when it will be shipped. 
Would you guys give us a roadmap or insight of this? I see there is already some code working on it. 
Thanks!

**Comment by jrodbx** [comment]
Support for ImageDecoder will ship in Picasso 3.0 which is actively under development.  

See https://github.com/square/picasso/milestone/13 for the latest set of issues (current date of Jan 1 will likely get pushed back though).  Feel free to submit feature requests through the issue tracker and we'll prioritize them accordingly!
