### ISSUE TITLE
Only HTTPS URLs work for me, but the site lists a HTTP URL.

### ISSUE THREAD

**Issue by adcar** [square/picasso#2159]
Hi. The line of code that the [site](https://square.github.io/picasso/) lists in the intro doesn't work for me:

```Picasso.get().load("http://i.imgur.com/DvpvklR.png").into(imageView);```

I'm assuming Android doesn't allow HTTP URLs anymore (or maybe I needed separate permission?)

Anyway, I fixed it by changing the URL to HTTPS:
```Picasso.get().load("https://i.imgur.com/DvpvklR.png").into(imageView);```

I think the introduction should reflect this.

If you're curious, my emulator uses API 29 and my project supports API 25+

**Comment by JakeWharton** [comment]
Android 8 or 9 disables http by default. You have to add a manifest entry to enable it. Picasso doesn't know the difference between http or https and asks the HTTP client to load the URL regardless of what you choose. It's being blocked by the OS.

**Comment by adcar** [comment]
@JakeWharton  I already fixed the issue. I just think the website should be changed to a HTTPS url to prevent any confusion.

**Comment by JakeWharton** [comment]
I see. Yes we should! Want to send a PR?

**Comment by adcar** [comment]
I just looked into it... but it looks like someone already did:

[https://github.com/square/picasso/commit/8db96e501cfcac77777b31cb24955b2a13da5dbb](https://github.com/square/picasso/commit/8db96e501cfcac77777b31cb24955b2a13da5dbb)

It's still not updated on the [website](https://square.github.io/picasso/) though.

**Comment by jrodbx** [comment]
Requires a new release which is TBD.
