### ISSUE TITLE
Need Picasso to invalidate cache only when the image is updated on the server.

### ISSUE THREAD

**Issue by adilsachwani** [square/picasso#2163]
Need to invalidate cache only at the time when a new image is updated on the server from my application. Not invalidating it every time. Cause a user normally changes that image once a year maybe.

**Comment by JakeWharton** [comment]
Picasso cache only lives as long as the process. OkHttp's HTTP cache respects standard cache headers. The easiest way to achieve this is have the images cached forever and then change the URL when a new picture is uploaded.

**Comment by adilsachwani** [comment]
@JakeWharton like I need to change the URL of the image every time it's updated on the server?

**Comment by adilsachwani** [comment]
I wanted to have the image on the server with the same name and URL every time it's updated on the server. Isn't this possible to invalidate the cache with it?
Thanks.

**Comment by JakeWharton** [comment]
You can use HTTP cache headers like ETag with the downside that every access will require a round-trip to the server. OkHttp will respect whatever you set. Picasso will not, though, so keep that in mind. You won't see new images until they're evicted from the memory cache manually, naturally, or when the process is killed.

It's far better to set the cache time to a ridiculously long value and change the URL when a new image is uploaded, though.
