### ISSUE TITLE
BitmapHunter always delay fail by 500ms even when there should be no retries

### ISSUE THREAD

**Issue by fruxo** [square/picasso#2167]
How to reproduce: 
-Use Picasso.load(File) to make a request for a file that's missing (or that would throw some other IOException).

Result: 
The result callback fires after 500ms, even though there should be no retries for those requests (its RequestHandler.getRetryCount() returns 0).

Reason:
BitmapHunter.run catches IOException and schedules a retry after RETRY_DELAY. After that delay it checks if there's any retries and if not it calls the result callback.
I would expect it to check first if there's any retries, like this:

      if (retryCount > 0) {
        dispatcher.dispatchRetry(this);
      } else {
        dispatcher.dispatchFailed(this);
      }

That would speed up the request by 500ms.

**Comment by JakeWharton** [comment]
Sounds good. Feel free to send a PR if you want.
