### ISSUE TITLE
Picasso Library Error

### ISSUE THREAD

**Issue by aliusama9739** [square/picasso#2169]
Hi!
I am creating a wallpapers app and have added 500 images using Picasso.load (Picasso Library) but when I scroll down the app and reach at the end, the app is crashed with the following error:

 java.lang.IllegalArgumentException: Path must not be empty.
         at com.squareup.picasso.Picasso.load(Picasso.java: 332)

**Comment by JakeWharton** [comment]
You are passing `""` to `load` which is not allowed.
