### ISSUE TITLE
Load image from external storage  permission denied

### ISSUE THREAD

**Issue by agustinsivoplas** [square/picasso#2180]
I am trying to load an image from the local storage (test with a hardcoded path). When the user grants read external storage permission I am getting this error:

```
Picasso.get().load("file:///sdcard/Download/download.png").error(R.drawable.ic_empty_profile_avatar).into(yourImageView, object : Callback{
                override fun onError(e: Exception) {
                    Log.e(TAG, "onError: ${e.message}", e)
                }

                override fun onSuccess() {
                }
            })
```

```
onError: /sdcard/Download/download.png: open failed: EACCES (Permission denied)
    java.io.FileNotFoundException: /sdcard/Download/download.png: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1185)
        at com.squareup.picasso.ContentStreamRequestHandler.getInputStream(ContentStreamRequestHandler.java:47)
```

<img width="392" alt="Screen Shot 2020-08-11 at 19 21 31" src="https://user-images.githubusercontent.com/1648539/89954778-16e24c80-dc08-11ea-92f5-612e9abfb688.png">

After to try multiples solution I figured out that if I set: `android:requestLegacyExternalStorage="true"` in the manifest works

<img width="384" alt="Screen Shot 2020-08-11 at 19 23 24" src="https://user-images.githubusercontent.com/1648539/89954804-25c8ff00-dc08-11ea-86fe-6c9fe5c35cb8.png">

I dont know if this is a Picasso bug or I am doing something wrong. I am using 2.71828, my app is compiled with SDK 30.

Any help is appreciated.

**Comment by JakeWharton** [comment]
This is a change in the OS which is limiting storage access which started in Android 9 or 10. There's more information here: https://developer.android.com/preview/privacy/storage. It's not something that Picasso has any control over.
