### ISSUE TITLE
Use AppStartup instead of PicassoContentProvider

### ISSUE THREAD

**Issue by yogurtearl** [square/picasso#2189]
Can use androidx AppStartup instead of `PicassoContentProvider`
https://developer.android.com/topic/libraries/app-startup

This is better for start up time and allows predictable ordering of library initializers.

**Comment by JakeWharton** [comment]
Didn't we remove the content provider? If not, we should. Static singletons are a 2014 convenience and a 2020 burden.

**Comment by yogurtearl** [comment]
The content provider is still there on `master` didn't look to see if/how it is still used.
https://github.com/square/picasso/blob/master/picasso-sample/src/main/java/com/example/picasso/provider/PicassoContentProvider.kt

**Comment by yogurtearl** [comment]
oh, ha, just realized that is in the sample app. 😂  maybe update the sample to use androidx AppStartup?

**Comment by JakeWharton** [comment]
Yep! Would make for a much better copy/paste pattern, if one decides to go that route.
