### ISSUE TITLE
About DispatcherThread

### ISSUE THREAD

**Issue by nicLucian** [square/picasso#2191]
There are three kinds of threads:Main Dispatcher and work thread.
I'm wondering what is the purpose for DispatcherThread. I mean we could send messages directly from main thread to work thread.

**Comment by JakeWharton** [comment]
It allows us to do bookkeeping that may be expensive off the main thread without concurrency. Doing it all again I would eliminate the dispatcher thread, but Picasso was built for 2015 Android not 2020 Android.
