### ISSUE TITLE
Flip image

### ISSUE THREAD

**Issue by Leeeeerich** [square/picasso#2198]
If the image will be big size, it will flip -90 degree

**Comment by JakeWharton** [comment]
I'm not sure if this is a feature request or a bug report. In either case, there is no real actionable information.

**Comment by Leeeeerich** [comment]
Hey, sorry I can't send a screenshot from my app and this bug is not critical for me, going to Glide, but you can open image in the application with Picasso:

![1615545374831](https://user-images.githubusercontent.com/26391015/110929055-383b2080-8330-11eb-8d31-8fc517867694.jpg)

it image I upload through GDrive and learned what android GDrive maybe use Picasso and have the same problem:

![1615545435270](https://user-images.githubusercontent.com/26391015/110929277-789a9e80-8330-11eb-801f-92e897f1beff.jpg)

![1615545435260](https://user-images.githubusercontent.com/26391015/110929294-7df7e900-8330-11eb-9ded-cac6f6e31a52.jpg)

My mobail phone is Xiaomi Mi 10 Lite,
Picture size: 3000x4000px, 4.63Mb
Exif data: f/1.89 1/20 ISO517 5.43mm
