### ISSUE TITLE
Error 504 when loading "served" images

### ISSUE THREAD

**Issue by fiote** [square/picasso#2202]
android:usesCleartextTraffic="true" is set on the manifest, so that's not the problem.

Normal image urls (ending with .png, .jpeg, etc) will load up just fine.

Served urls (like https://www.pontofrio-imagens.com.br/Control/ArquivoExibir.aspx?IdArquivo=1264532317) will fail to load with error 504.

It's also not about the image's size, because I tried a "normal" image (4x the "served" one's size/weight) and it worked as well.

Is there any type of configuration that I can use to make this work?

**Comment by JakeWharton** [comment]
Picasso does not differentiate. It makes a request for the resource through OkHttp the same as anything else. If you are seeing 504's it's likely because the device is offline and Picasso made one last attempt to load a cached-but-stale version of the image and it was not available.

**Comment by fiote** [comment]
I have a list of images. Picasso can load all images BUT those kind. So it's not a "network availability" issue. I'm thinking the server could be blocking those requests. 

Is there a way to set picasso's agent like we do in curl to 'fake' who's requesting the image?

**Comment by fiote** [comment]
It was indeed the server blocking requests. Thanks!
