### ISSUE TITLE
ANR Crash while building Picasso when creating application after tapping to push notification by user

### ISSUE THREAD

**Issue by sm-tester** [square/picasso#2204]
Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 pkg=com.delta.buz cmp=com.delta.buz/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) }

Look at screenshot below from play store crash report:

<img width="1352" alt="Screen Shot 2021-05-01 at 16 42 01" src="https://user-images.githubusercontent.com/3168694/116781590-450d0280-aa9d-11eb-9725-c9cef3f1790c.png">

Picasso version is: 'com.squareup.picasso:picasso:2.71828'

Short Application class definition:

```
public class DeltaBuz extends MultiDexApplication {

    public WeakReference<Context> baseCon = new WeakReference<>(null);

    @Override
    protected void attachBaseContext(Context base) {
        Context bCon = LocaleRepo.onAttach(base);
        baseCon = new WeakReference<>(bCon);
        super.attachBaseContext(bCon);
    }

    @Override
    public void onCreate() {
        super.onCreate();

        initNetworkServices();
    }

    private void initNetworkServices() {
        Picasso picasso;

        if(Utilities.Companion.getDEBUG()) {
            picasso = new Picasso.Builder(this)
                    .listener((picasso1, uri, exception) -> {
                        exception.printStackTrace();
                    })
                    .build();
        }
        else {
            picasso = new Picasso.Builder(this).build();
        }

        Picasso.setSingletonInstance(picasso);
    }
}
```

**Comment by JakeWharton** [comment]
Not much we can do here. The filesystem is the underlying cause, not Picasso. We have to set up OkHttp's cache dir and that involves a check for whether the directory exists. Maybe request that OkHttp defer touching/opening the cache until first use? Otherwise you can manually configure OkHttp and neglect to install a cache, but then you don't get image caching.
