### ISSUE TITLE
Picasso not loading images from http urls

### ISSUE THREAD

**Issue by Softkeydel** [square/picasso#2208]
'com.squareup.picasso:picasso:2.71828'
Picasso.get().load(image).into(view)

**Comment by JakeWharton** [comment]
No information provided. Picasso just passed the URL to OkHttp so there's nothing specific to Picasso you would do to fix this. The problem is elsewhere, probably Android blocking cleartext traffic.

**Comment by Softkeydel** [comment]
@JakeWharton 
Android blocking cleartext traffic.
This was the issue.
Thanks
