### ISSUE TITLE
Downloading the JAR from your website gives a 404 error

### ISSUE THREAD

**Issue by DonaldDuck313** [square/picasso#2212]
If you go to https://square.github.io/picasso/#download and click "Latest JAR", the link goes to a 404 web page.

**Comment by JakeWharton** [comment]
Thanks. It's an `.aar` now. You can edit the URL for now or visit https://search.maven.org/artifact/com.squareup.picasso/picasso to see all versions and download binaries.

**Comment by youarenot667543** [comment]
Juu
