### ISSUE TITLE
Picasso sometimes does not show images from Google Drive URL

### ISSUE THREAD

**Issue by RaulRohjans** [square/picasso#2220]
I am trying to use Picasso on my Android app and google drive images work inconsistently for some reason. Sometimes I launch the app and they appear, other times they wont. The problem isn't from the URL either since I can see the image in a browser.

This is how I am loading the image into the image view.
`Picasso.get().load("https://drive.google.com/uc?id=1JegtjfmA_1NcDcg7-MwTixPQQ7RFUaXn").into(img);`

When Picasso doen't load the image, this error shows up:
`
W/System.err: com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 403
W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)
`

Any ideas? Thank you in advance

**Comment by JakeWharton** [comment]
HTTP 403 means the server understood the request but refused to fulfill the response. Perhaps you are being rate limited or something, but this isn't strictly a problem in Picasso itself.
