### ISSUE TITLE
Resize with keep aspect ratio

### ISSUE THREAD

**Issue by nicolaslauquin** [square/picasso#226]
I'd like to be able to resize an image by keeping a ratio aspect. Right now it is "complex" to do with a new Target and we are losing some great "build in" feature of Picasso.

One example would be for a resize on width:

``` java
Picasso.with(context).load(url).resize(400, -1).into(imageView);
```

Thanks

**Comment by lawloretienne** [comment]
I'm just confirming that this worked for me.  I have the imageView xml set to centerInside then i just specify a width, in my case it is the width of the screen, and then it maintains the aspect ratio.  I just pass in 0 for the height.

Picasso.with(context).load(url).resize(width, 0).into(imageView);
