### ISSUE TITLE
Q: How to get a bitmap object from a already cached image?  

### ISSUE THREAD

**Issue by daimajia** [square/picasso#227]
i want to reuse the cached image~  

is there a method to get a  bitmap object from a cached image?

**Comment by vinodtiwari** [comment]
Hi daimajia - Could you please share your solution? I'm also trying to do the same.

**Comment by laobie** [comment]
@vinodtiwari i think using `Picasso.with(context).load(url).get()` instead of `...into(target)`, u can get a Bitmap Object, then u can transform it to a File or other Object

**Comment by YeYintLwin** [comment]
`public static Bitmap getBitmapFromPicassoCached(Context context, String url)
	{
		final String CACHE_PATH = context.getCacheDir().getAbsolutePath() + "/picasso-cache/";

		File[] files=new File(CACHE_PATH).listFiles();
		for (File file:files)
		{
			String fname= file.getName();
			if (fname.contains(".") && fname.substring(fname.lastIndexOf(".")).equals(".0"))
			{
				try
				{
					BufferedReader br=new BufferedReader(new FileReader(file));
					if (br.readLine().equals(url))
					{
						String image_path=  CACHE_PATH + fname.replace(".0", ".1");						
						if (new File(image_path).exists())
						{
							return BitmapFactory.decodeFile(image_path);
						}
					}
				}
				catch (FileNotFoundException|IOException e)
				{
				}
			}
		}
		return null;
	}`

**Comment by YeYintLwin** [comment]
`public static Bitmap getBitmap(Context context, String url)
	{
		final String CACHE_PATH = context.getCacheDir().getAbsolutePath() + "/picasso-cache/";

		File[] files=new File(CACHE_PATH).listFiles();
		for (File file:files)
		{
			String fname= file.getName();
			if (fname.contains(".") && fname.substring(fname.lastIndexOf(".")).equals(".0"))
			{
				try
				{
					BufferedReader br=new BufferedReader(new FileReader(file));
					if (br.readLine().equals(url))
					{
						String image_path=  CACHE_PATH + fname.replace(".0", ".1");						
						if (new File(image_path).exists())
						{
							return BitmapFactory.decodeFile(image_path);
						}
					}
				}
				catch (FileNotFoundException|IOException e)
				{
				}
			}
		}
		return null;
	}`

**Comment by YeYintLwin** [comment]
Try this
`public static Bitmap getBitmap(Context context, String url)
	{
		final String CACHE_PATH = context.getCacheDir().getAbsolutePath() + "/picasso-cache/";
		File[] files=new File(CACHE_PATH).listFiles();
		for (File file:files)
		{
			String fname= file.getName();
			if (fname.contains(".") && fname.substring(fname.lastIndexOf(".")).equals(".0"))
			{
				try
				{
					BufferedReader br=new BufferedReader(new FileReader(file));
					if (br.readLine().equals(url))
					{
						String image_path=  CACHE_PATH + fname.replace(".0", ".1");						
						if (new File(image_path).exists())
						{
							return BitmapFactory.decodeFile(image_path);
						}
					}
				}
				catch (FileNotFoundException|IOException e)
				{
				}
			}
		}
		return null;
	}`

**Comment by jewom** [comment]
Thanks @YeYintLwin ! It works!!
