### ISSUE TITLE
Images loaded from the file system render with the wrong orientation

### ISSUE THREAD

**Issue by afollestad** [square/picasso#2275]
This was originally noticed in POS but I was able to reproduce it in the sample app by using "Load from gallery" and selecting this photo:

<img src="https://user-images.githubusercontent.com/1820165/156857451-351ed204-f4c8-4a51-acdd-9d3df4f9fd56.jpeg" width="300" />

_(If GitHub strips the EXIF data here, `exiftool -Orientation=6 -n [file-name]` could be used to help repro)_

---

It looks like the left image below when loading it using Picasso from a `content://` URI. Seems like `ExifInterface` isn't working here, somehow?

Interestingly, it looks like [BitmapHunter's MatrixTransformation](https://github.com/square/picasso/blob/42adcede6aac7a6ce618f453fdfd3ddaecc43079/picasso/src/main/java/com/squareup/picasso3/BitmapHunter.kt#L151) calling `preRotate` on the `Matrix` is what sets it to the wrong orientation.

<table>
  <tr>
    <th>Current behavior</th>
    <th><a href="https://github.com/square/picasso/blob/42adcede6aac7a6ce618f453fdfd3ddaecc43079/picasso/src/main/java/com/squareup/picasso3/MatrixTransformation.kt#L118">preRotate commented out</a></th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/1820165/156857527-4edf9c4e-2e4a-44e0-99f6-c1f55362daa9.png" width="400" /></th>
    <th><img src="https://user-images.githubusercontent.com/1820165/156858339-033ad80d-f4c8-4942-8697-ac3e018cc40c.png" width="400" /></th>
  </tr>
</table>

**Comment by afollestad** [comment]
`androidx.exifinterface.media.ExifInterface` seemed to fix it (via a transformation) in POS. Maybe using the AndroidX version of this class in Picasso would solve it?

**Comment by afollestad** [comment]
Interestingly, it seems as though `MatrixTransformation` calling `preRotate` on the Matrix is what sets it to the wrong orientation - and the width/height changes around that.

**Comment by jrodbx** [comment]
Also, part of this is investigating different RequestHandler code paths
