### ISSUE TITLE
Android Studio shows a strange version

### ISSUE THREAD

**Issue by NathanFallet** [square/picasso#2314]
Android Studio wants me to update my version of picasso, but this looks strange... what is it?
<img width="705" alt="image" src="https://user-images.githubusercontent.com/30439790/185784750-ad57829c-3537-414c-bfe0-fd6460eca0ce.png">

**Comment by sdfgsdfgd** [comment]
SAME HERE SOMEONE HELP US I'm getting the exact same error, it's trying to force me to downgrade from 2.8 to 2.71828

**Comment by sdfgsdfgd** [comment]
HELPPP

**Comment by jrodbx** [comment]
Duplicate of #2179
