### ISSUE TITLE
Images at certain URLs do not load (was: Images that need to be resized up do not display at all)

### ISSUE THREAD

**Issue by pushbit** [square/picasso#234]
I have two ImageViews; one is 218x192 and the other is 278x192.  If I load the same 250x250 image into both of these views with resize([ImageView size]) and centerCrop(), the image is displayed in the first ImageView (which resizes the image down to 218) but not in the second ImageView (which would resize the image up to 278).  Only the placeholder is displayed in the second ImageView.  I believe this is a regression in 2.0.0 and the upsizing was working previously.

**Comment by neerajakshid** [comment]
I have few images that cant be loaded as well. I am using version 2.4.0 as well. Did any of you found an work around for this issue?

**Comment by Neptilo** [comment]
The only workaround I used at the time was avoiding using some filters like fitting, resizing or centering, but of course you don't get the same result visually.

**Comment by neerajakshid** [comment]
@Neptilo Thanks for the quick response  :)

**Comment by krisha23** [comment]
Well I have `com.squareup.picasso:picasso:2.5.2'` and I'm not using any of these calls : fit(), centerCrop(), centerInside(), resize() or resizeDimen()

My code for an adapter is as simple as this - 
`Picasso.with(context).load(path).into(imageView, new Callback() {
        @Override public void onSuccess() {
        }

        @Override public void onError() {
        }
      });`

However, some images some images still fail to load.

**Comment by pphilipp** [comment]
I've been faced with the similar problem.
loading image is:

> https://farmer.arlafoods.de/nextshopcms/cmsimage.asp?id=5684&fkt=3

I thought that the problem related to server (.asp) response and url don't have a format like `.png` or 
`.jpg` but in other cases, I **able** to load some links like http://goo.gl/gEgYUd.
Additionally, the strange thing that I able to load this link in a browser and Postman.

Diving to the logs from Picasso I've seen that this particular url has some error.
As I understand the Dispatcher added some delay for loading image and again and again. 

> Dispatcher  batched      [R60]+431ms for completion
> Dispatcher  batched      [R60]+359ms for completion
.
.
and as a result 
> Dispatcher  batched      [R60]+2216ms for error


I've put an OkHttpClient with timeout delay in 10 sec but it doesn't help.
Is anybody has some ideas how to hold this case?
