### ISSUE TITLE
Picasso Not displaying images from disc cache

### ISSUE THREAD

**Issue by kosttek** [square/picasso#237]
Downloading images and caching in memory is working. But there are no displayed image when I turn off internet connection. I expect that there should be displayed images from disc cache ...
Whole problem is described on stackoverflow
http://stackoverflow.com/questions/18633422/square-picasso-not-displaying-images-from-disc-cache

**Comment by PluginIO** [comment]
This issue was closed because a third party solution handled it correctly?

**Comment by JakeWharton** [comment]
Picasso isn't an HTTP client. Want a better disk cache? You need a better
HTTP client.

**Comment by PluginIO** [comment]
Oh no... one of these conversations. So, you see, Picasso does download assets right?! And when you use a load from cache policy, it doesn't actually have any way to load the file if it doesn't exist in the cache. Well, we are programmers, we are there to automate processes of fallback policies. Just saying, and I'll leave that there other than to say that I was easily able to incorporate OkHttp and I am testing but Glide did this just fine so I'll hop on over back to that.

**Comment by JakeWharton** [comment]
Glide has it's own disk cache whereas Picasso chooses not to. That's why
Glide as a library is 5x larger and 5x more complex internally. Hence the
need for an HTTP client that doesn't suck when using Picasso.

Also, we don't care at all what you use.
