### ISSUE TITLE
Strict mode violations on scrolling

### ISSUE THREAD

**Issue by LukeStClair** [square/picasso#245]
On fast scrolling, I can pretty often create strict mode violations with the following trace. This is on the new 2.x release:

E/StrictMode( 4246): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
E/StrictMode( 4246): java.lang.Throwable: Explicit termination method 'close' not called
E/StrictMode( 4246):    at dalvik.system.CloseGuard.open(CloseGuard.java:184)
E/StrictMode( 4246):    at java.io.FileInputStream.<init>(FileInputStream.java:80)
E/StrictMode( 4246):    at libcore.io.DiskLruCache.get(DiskLruCache.java:391)
E/StrictMode( 4246):    at libcore.net.http.HttpResponseCache.get(HttpResponseCache.java:98)
E/StrictMode( 4246):    at android.net.http.HttpResponseCache.get(HttpResponseCache.java:204)
E/StrictMode( 4246):    at libcore.net.http.HttpEngine.initResponseSource(HttpEngine.java:257)
E/StrictMode( 4246):    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:218)
E/StrictMode( 4246):    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282)
E/StrictMode( 4246):    at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
E/StrictMode( 4246):    at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:64)
E/StrictMode( 4246):    at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:45)
E/StrictMode( 4246):    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:111)
E/StrictMode( 4246):    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:82)
E/StrictMode( 4246):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
E/StrictMode( 4246):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/StrictMode( 4246):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/StrictMode( 4246):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/StrictMode( 4246):    at java.lang.Thread.run(Thread.java:841)
E/StrictMode( 4246):    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:218)

**Comment by dimsuz** [comment]
+1 Just encountered this with Picasso `2.5.2`, here's the stack trace:

```
E  A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
E  java.lang.Throwable: Explicit termination method 'close' not called
E      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
E      at java.io.FileInputStream.<init>(FileInputStream.java:80)
E      at okio.Okio.source(Okio.java:161)
E      at com.squareup.okhttp.internal.io.FileSystem$1.source(FileSystem.java:44)
E      at com.squareup.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1002)
E      at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:430)
E      at com.squareup.okhttp.Cache.get(Cache.java:180)
E      at com.squareup.okhttp.Cache$1.get(Cache.java:139)
E      at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:229)
E      at com.squareup.okhttp.Call.getResponse(Call.java:273)
E      at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
E      at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
E      at com.squareup.okhttp.Call.execute(Call.java:81)
E      at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:117)
E      at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
E      at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
E      at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
E      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E      at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E      at java.lang.Thread.run(Thread.java:856)
E      at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by praveensleeps** [comment]
I see the same issue and logs as @dimsuz
