### ISSUE TITLE
Some images are not loaded when centerCrop and fit are used

### ISSUE THREAD

**Issue by lexer** [square/picasso#249]
This happens for this image: http://lyftapi.s3.amazonaws.com/development/photos/320x200/car.jpg

picasso.load(photoUrl)
.centerCrop()
.fit()
.into(photoImageView);

Tested on: Nexus 4. Android 4.3

**Comment by CocaCode** [comment]
same trouble in 2.4 dunno how to fix this.

**Comment by TheBlusky** [comment]
same with 2.5.

**Comment by mardawi** [comment]
Still happening with 2.5.2
https://jarirfiles.blob.core.windows.net/images/240x330/3000.jpg

**Comment by daemontus** [comment]
It's going to be fixed in 2.5.3 - If you look at the milestone, there is a pull request that should finally fix this problem. Sadly, I don't think it's merged yet (so it's not in snapshots yet), so if you want to use it, you'll have to compile it from source. (At least that's what I did)

See: https://github.com/square/picasso/pull/1035

**Comment by zzt93** [comment]
I came across different problem. use `resize()` can show the image but `fit()` fail to show it.
The following show image(although image is distorted).
```
        Point size = getScreenSize();
        Picasso.with(this).load(uri).resize(size.x, size.y).into(imageView);
```
buf using `fit()` can't show it.
Maybe the file is too large? For if I don't use resize() it will cause error(“Bitmap too large to be uploaded into a texture”).

**Comment by rafaelcgo** [comment]
Is it fixed and released?
I still have the 2.5.2 version and experience the same problem with: https://dk85f78xh5nsf.cloudfront.net/attachments/store/d2dd5c574a588f9ce29bd9c26cfee332fc47a4067ef037846c522c924595/jif3cover.jpg

**Comment by daemontus** [comment]
As far as I can tell, it's not released. You probably have to build it yourself, or download it from the snapshot repository (it's merged, so it should be there).

**Comment by piterwilson** [comment]
This is rather serious ... can someone post a code snippet for the `NetworkBitmapHunter` fix? Thanks

**Comment by neutt22** [comment]
I'm still experiencing this issue with 2.5.2. Images taken from phone cam dont show up

**Comment by reallychenchi** [comment]
me too, with version 2.5.2, the picture attached 
![a](https://user-images.githubusercontent.com/472366/30428058-c8216176-9984-11e7-8f9b-9f719aa8be4b.jpg)

**Comment by where-is-s** [comment]
+1, doesn't work for me too. Oneplus 3T, Android 7.1.1, Picasso 2.5.2. When loading a big picture from camera with fit() or resize() options from SD card, I get the following log:

```
D/Picasso: Main        created      [R1] Request{file:///storage/emulated/0/Android/data/com.xxx.xxx/files/Pictures/cover.jpeg resize(1080,550)}
D/Picasso: Hunter      executing    [R1]+1ms 
D/Picasso: Dispatcher  enqueued     [R1]+1ms 
I/ExifInterface_JNI: Raw image not detected
W/ExifInterface: Skip the tag entry since tag number is not defined: 2
D/AppTracker: App Event: start
D/Picasso: Dispatcher  batched      [R1]+506ms for error
D/Picasso: Dispatcher  delivered    [R1]+709ms 
D/Picasso: Main        errored      [R1]+709ms
```

However, the same image loads correctly into ImageView if I don't use fit() or resize().

**Comment by rpavliuk** [comment]
Resize and centerCrop wasn't working when my ImageView was wrap_content or match_parent. After I hardcoded width and height for ImageView everything has started to work
