### ISSUE TITLE
Q: Keep old image while newest one is loading

### ISSUE THREAD

**Issue by pablojacobi** [square/picasso#257]
Hi!

I have a View which change his image each certain period. When I change the image, the old one is deleted from the view and the placeholder is shown (if has, else show nothing), and after load, the new image is shown. This behaviour happens even with noFade(). I need to find a way to keep showing the first image while the second one is loaded, and then show it immediately. Is this possible?

Thanks in advance,

Regards!

**Comment by anonym24** [comment]
place holder isn't working for vector drawables <= 21 API, but Android default method works fine `mImageView.setImageResource(R.drawable.vector_drawable_image);`, Picasso sucks..

**Comment by anonym24** [comment]
because Picasso uses weird method:   

```
private Drawable getPlaceholderDrawable() {
    if (placeholderResId != 0) {
      return picasso.context.getResources().getDrawable(placeholderResId);
    } else {
      return placeholderDrawable; // This may be null which is expected and desired behavior.
    }
  } 
```

**Comment by kilicpl** [comment]
JayH5 , if I understood correctly that s a very good idea., thx a lot.
But how can you set the imageResource taken from Url at the first place?

For example
 imageView = findViewById(R.id.myimage);
 imageView.setImageResource(photo1.getUrls().getRegular());    --here I ve a problem!!
                                Picasso.with(MainActivity.this).load(photo1.getUrls().getRegular()).placeholder(imageView.getDrawable()).fit().into(imageView);
