### ISSUE TITLE
Pass a drawable directly to Picasso.load 

### ISSUE THREAD

**Issue by StErMi** [square/picasso#263]
Hi, this is much more a feature request.

Can you please add support to pass to Picasso.load a Drawable?

At the moment it supports: File, ResourceID, Uri and Paths

**Comment by gouravd** [comment]
Another use case would be to apply transformations easily through Picasso. Mostly CircleTransformation for Images/Profile images

**Comment by fmagalhaes** [comment]
gouvard +1

**Comment by abhi007tyagi** [comment]
gouravd +1 I too want this feature for Rounded Profile Pics
