### ISSUE TITLE
AIRPLANE_MODE_ON check; logcat complains.

### ISSUE THREAD

**Issue by dentex** [square/picasso#274]
I think that the lines

```
import static android.provider.Settings.System.AIRPLANE_MODE_ON;
```

and/or

```
static boolean isAirplaneModeOn(Context context) {
  ContentResolver contentResolver = context.getContentResolver();
  return Settings.System.getInt(contentResolver, AIRPLANE_MODE_ON, 0) != 0;
}
```

in `picasso/src/main/java/com/squareup/picasso/Utils.java` are causing my logcat to spawn `W/Settings(12641): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.`

https://developer.android.com/reference/android/provider/Settings.System.html#AIRPLANE_MODE_ON

**Comment by ketkipawar** [comment]
I have 3 tabs in my project and the tab switches automatically due to this above crash. I have put the code for isAirplaneModeOn but still no diference and log still shows the warning on tab switch.
