### ISSUE TITLE
could picasso load image from disk first . 

### ISSUE THREAD

**Issue by mikezit** [square/picasso#295]
when i use picasso , say , i have loaded 100 pictures before in disk cache . and now , i will loaded 105 pictures , the 5 new picture will load from network . in my app , i will see the 100 picture will not be visible at least the 5 picture be loaded from network .  could i let picasso load disk-cached pictures first ?

**Comment by thailemon** [comment]
so how is this done now...? i want to "preload" a lot of images that are saved to disk into memory  without doing HTTP calls.
