### ISSUE TITLE
placeholder for animation drawable

### ISSUE THREAD

**Issue by michaelgilos** [square/picasso#298]
Does picasso support animation drawable for placeholder? AnimationDrawables needs to explicitly call start() after setting them =(

PicassoDrawable.java
static void setPlaceholder(ImageView target, int placeholderResId, Drawable placeholderDrawable) {
    if (placeholderResId != 0) {
      target.setImageResource(placeholderResId);
      AnimationDrawable anim = (AnimationDrawable) target.getDrawable();
      anim.start();
    } else {
      target.setImageDrawable(placeholderDrawable);
    }
  }

**Comment by heronghua** [comment]
@dnkoutso Was it fixed in 2.5.
