### ISSUE TITLE
Using callback for CompoundDrawables

### ISSUE THREAD

**Issue by kobelobster** [square/picasso#308]
Hi, I want, to use Picasso for compound drawables since It's doing a great job for ImageViews. But it doesn't really work. The place where the image should come just stays white.

This is what I've done so for. bitmap is the URL of the Image. 

``` java
    Picasso.with(getActivity().getApplicationContext()).load(bitmap).into(new Target() {
        public void onBitmapLoaded(Bitmap bitmapPic, LoadedFrom from){
        Drawable d = new BitmapDrawable(getResources(), bitmapPic);
        textView[picassoCounter].setCompoundDrawablesWithIntrinsicBounds(d, null, null, null);
        textView[picassoCounter].setCompoundDrawablePadding(5);                       

        }

        public void onBitmapFailed(Drawable errorDrawable){
        Drawable d = getResources().getDrawable(R.drawable.nofavicon);
        textView.setCompoundDrawablesWithIntrinsicBounds(d, null, null, null);
        textView.setCompoundDrawablePadding(5); 
              }

public void onPrepareLoad(Drawable placeHolderDrawable){
                          }
                        });
```

**Comment by Sullivan72** [comment]
@selmanon, look at this solution http://stackoverflow.com/questions/24180805/onbitmaploaded-of-target-object-not-called-on-first-load#answers

It seems because of WeakRefence, in the link above is the answer or "Subclass TextView and implement Target on that class", like said JakeWharton above.

**Comment by mwshubham** [comment]
http://stackoverflow.com/a/36310327/5028508

**Comment by Miha-x64** [comment]
[TextView subclass](https://gist.github.com/Miha-x64/c3b0cff4f38690455d85d5c415024ebe), as suggested by Jake Wharton. In Kotlin, with Anko bindings.

**Comment by prashand** [comment]
There's a solution for this here. [PicassoTargetableTextView](https://stackoverflow.com/a/53131079/1800515)
