### ISSUE TITLE
Fade in duration

### ISSUE THREAD

**Issue by andreaswong** [square/picasso#309]
Hi,

I'm loving the slick fade-in on when the image has finished loaded, a question though, is there a way to increase the fade-in time?

**Comment by kaharoth74** [comment]
It will be very usefull to could specify the fade duration, 200ms is not always the best fade time.

**Comment by softvision-mariusduna** [comment]
Agree

**Comment by ToshMeston** [comment]
Agree

**Comment by jimitpatel** [comment]
Agree

**Comment by onuryurtturk** [comment]
Agree 200ms not enough

**Comment by almaz010891** [comment]
Agree
