### ISSUE TITLE
Custom request headers

### ISSUE THREAD

**Issue by magucc** [square/picasso#324]
Hi,

I can't see there is a way to have custom headers implemented with when getting an image by URL. Some API's require some authentication token for access to images. 

If I were to implement this myself I guess adding this to UrlConnectionDownloader.java would be the way to go. Are there any plans for full implementation?

Mani

**Comment by ciskeboekelo** [comment]
It seems OkHttpDownloader.openConnection() was removed in v2.5.0
What is the new way to request headers?

**Comment by JakeWharton** [comment]
@ciskeboekelo Sorry for the delay here. OkHttp interceptors are the right thing to use here. You no longer have to subclass any of Picasso's classes!

**Comment by pwightman** [comment]
So to be clear, one *must* include OkHttp as a dependency if they want to add a header? No way to add a header otherwise? (I've been googling this for an hour trying to find relevant information, but it's been hard to come by!)

**Comment by JakeWharton** [comment]
You can subclass UrlDownloader if you're not using OkHttp.
