### ISSUE TITLE
Transformations on placeholder and error images

### ISSUE THREAD

**Issue by matt-oakes** [square/picasso#337]
It would be great if there was optionally a way to enable transformations to also take effect on placeholder images. Current I have a custom transformation which clips the image into a circle.

Currently I can work around it by just making the placeholder asset a circle, but it would be convenient if it could just use the transformations I've defined.

**Comment by vkislicins** [comment]
Has this changed at all? I'm actually looking for a way not to apply transformation to my placeholder images as at the moment they do get transformed right before switched to the downloaded image.

**Comment by luccasmaso** [comment]
Here placeholder images still don't apply to transformations.
