### ISSUE TITLE
Large Images not Loading when used in Android ListView Adapter

### ISSUE THREAD

**Issue by NauraaIndvik** [square/picasso#370]
Hello, First of all thanks for such a great library, we have used it in our quite a few apps, but last week we started observing that some of the images are not loading, the particular images which are not showing up are the ones which have large lengths as compared to widths, for example: https://instalol-instalol.netdna-ssl.com/images/the-story-of-cats-1390319274.jpg, the image is 410 Kb in size and I don't think that is an issue, Any work around for this would be greatly appreciated.

Thanks and keep up the good work :+1:

**Comment by aiteu** [comment]
I use picasso load large picture, and used resize() method, but logcat error msg is : java.io.IOException: Failed to decode stream. How avoid this error?

**Comment by JakeWharton** [comment]
Try 2.6.0-SNAPSHOT version
