### ISSUE TITLE
Add parameter to Callback's onSuccess and onError

### ISSUE THREAD

**Issue by winne2** [square/picasso#379]
I do not understand how to make sensible use of the
RequestCreator.into(ImageView target, Callback callback)
method introduced with picasso 2.0. In my opinion, the Callback should give access to the (HTTP) response in onSuccess and the exception in onError (like in retrofit.client.Response.Callback). The latter could be easily achieved through passing exception through join.error() in Picasso.complete(BitmapHunter).

Or what is the proper approach to debug and handle HTTP errors?

**Comment by rohitbandil** [comment]
I am getting this error in the log - "301 Moved Permanently"
