### ISSUE TITLE
Add a method to pass an image thumbnail URL as placeholder

### ISSUE THREAD

**Issue by ronaldoeyeem** [square/picasso#383]
There're several use cases where apps shows a thumbnail image and `onClick()` it expands to a full sized image.

It would be a great feature to be able to easily smooth transition between those two states by calling:

``` Java
Picasso.with(this).load(full_img_url).placeholderUrl(thumb_url).placeHolder(drawable).into(target);
```

In that case, Picasso would

``````
if( thumbnail image available from local cache ){
     // that would be expected case
     // the thumbnail is already on screen, so it should be cached too
     use the image thumbnail as placeholder
} else{
    // and fall back in case anything happens
    use the supplied drawable as placeholder
}```
``````

**Comment by dyguests** [comment]
I'had a same problem..

I'll click a thumbImg in a listView to jump to another Activity with bigImg.

The code should like this:

	//in another Activity
	
	Drawable cachedThumbImgDrawable = getCachedDrawable(thumbUrl);
	
	Picasso.with(content)
		.load(bigUrl)
		.placeHolder(cachedThumbImgDrawable)
		.into(imageView);

	/*try to find cached drawable*/
	Drawable getCachedDrawable(String url){
		//if find drawable.....
		return drawable;
		
		//or find nothing
		return null;
	}
	
but I don't know to how to getCachedDrawable().

**Comment by VishalNarvani** [comment]
Anyone had a luck with this?

**Comment by abdelhady** [comment]
@VishalNarvani the code I posted earlier works fine with me.

**Comment by rgr-myrg** [comment]
@abdelhady Your solution works perfectly.  I'm able to load a thumbnail and subsequently a full sized image in sequence using your solution. Many thanks.

**Comment by sudikrt** [comment]
What if i dont have a thumb url

**Comment by Pedramrn** [comment]
It would be a good feature, Just like what instagram does. I'm not a fan of nested calls, Does the fade animation works fine?
And by the way Glide has this feature built in already.
