### ISSUE TITLE
how to show full bitmap 

### ISSUE THREAD

**Issue by alikslee** [square/picasso#419]
Picasso.with(this).load(thumb_url).into(imageView) //
![a](https://f.cloud.github.com/assets/5061232/2266622/3f082936-9e9e-11e3-8d72-e59faac1792e.PNG)

Picasso.with(this).load(midle_url).into(imageView)
//not display 
//Bitmap too large to be uploaded into a texture
![device-2014-02-26-121831](https://f.cloud.github.com/assets/5061232/2266632/97ed487e-9e9e-11e3-8043-f93c8b1f9793.png)

Picasso.with(this).load(midle_url).resize(screenWidth, screenHeight).fit().into(imageView)
//bitmap be cut, not full
![device-2014-02-26-122137](https://f.cloud.github.com/assets/5061232/2266636/bf5746e4-9e9e-11e3-9e34-eb3c976612c1.png)
.into(imageView)

**Comment by mrdazhuk** [comment]
fit works perfectly. Thanks!
