### ISSUE TITLE
fit() does not work with adjustViewBounds="true"

### ISSUE THREAD

**Issue by mattiaslinnap** [square/picasso#425]
I am trying to use Picasso to load images which have unknown proportions, and after loading size the ImageView in the layout to the actual image proportions. This works without .fit().

For example, I have an ImageView with attributes

* layout_width="match_parent"
* layout_height="wrap_content"
* adjustViewBounds="true"

The ImageView should be sized in the layout using it's width, and the height should be adjusted depending on the proportions discovered from the image file. Using Picasso.with(context).load(url).into(view) this works exactly as expected! But as the image file could be large, it's wasteful of memory.

The approach fails when .fit() is added after the load call - the image never shows up, perhaps because it has been "fitted" to 0px height?

I have also tried the following layout attributes:

* layout_height="wrap_content", adjustViewBounds="false": no image seen
* layout_height="wrap_content", adjustViewBounds="true": no image seen
* layout_height="Xdp", adjustViewBounds="false": proportions not adjusted
* layout_height="Xdp", adjustViewBounds="true": proportions not adjusted

This issue should probably be considered together with https://github.com/square/picasso/pull/365 - but I think it would be nicer to not have to add arguments to fit(), as these are already available in the ImageView XML attributes.

**Comment by dnkoutso** [comment]
See #457 and please re-open if issue persists.
