### ISSUE TITLE
Picasso throws exception on empty url

### ISSUE THREAD

**Issue by juliocbcotta** [square/picasso#426]
What's up doc?
while doing some tests with Picasso, I found that Picasso can't handle empty urls/paths..
Looking at the Picasso.java code I found that:

``` Java
public RequestCreator load(String path) {
    if (path == null) {
      return new RequestCreator(this, null, 0);
    }
    if (path.trim().length() == 0) {
      throw new IllegalArgumentException("Path must not be empty.");
    }
    return load(Uri.parse(path));
  }

```

Why this approach? I mean, if the developer is naive enough to not verify the path for am empty string, the app will crash if the path is empty. I think a more graceful way to handle it is try to use the error drawable or throws an exception that is not a run time exception.

The same can be done here:

``` Java
 public RequestCreator load(int resourceId) {
    if (resourceId == 0) {
      throw new IllegalArgumentException("Resource ID must not be zero.");
    }
    return new RequestCreator(this, null, resourceId);
  }
```

That's all folks.

**Comment by DanielReYin** [comment]
It is not make sense, maybe it is right in your point.

**Comment by Ravikiran303** [comment]
com.squareup.picasso.RequestCreator@52b9dfb0 this is what i getting when i am as result when i am passing image url to imageview extracted from realtime database..plz help me view image in listview
