### ISSUE TITLE
Downloader 302 errors

### ISSUE THREAD

**Issue by kobyy** [square/picasso#434]
Hello,
I've been testing with the newest Picasso version (2.2.0) and I have been getting these errors when I try loading images with Picasso:
"com.squareup.picasso.Downloader$ResponseException: 302 forced.302"

I am trying to load a listview with facebook profile images and it seems that out of 50 images, maybe only 10 actually get loaded with the rest returning that error. Any help would be appreciated, thanks

**Comment by milaptank** [comment]
Hello Sir 
I had same error occur  and follow same as you have ask for
I am using `com.squareup.picasso:picasso:2.5.2`  and i have read comment "in version 2.5.2, Picasso is using OkHttp by default"
from this http://stackoverflow.com/a/24180040/1293313

OKHttp Jar : http://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.2.0/okhttp-3.2.0.jar

Error :
Error:(63, 29) error: cannot access OkHttpClient
class file for com.squareup.okhttp.OkHttpClient not found


Than how to use OkHttpDownloader?

**Comment by HelenaSewell** [comment]
Had the same problem as @milaptank , I sorted it by using this:
https://github.com/JakeWharton/picasso2-okhttp3-downloader
Picasso does include OkHttp, but it seems to be OkHttp3. The regular version of OkHttpDownloader seems to expect plain "OkHttp" (no "3"). So using OkHttp3Downloader fixed the issue for me!
