### ISSUE TITLE
Support load from InputStream

### ISSUE THREAD

**Issue by chelsea-a-jones** [square/picasso#447]
A feature request/suggestion: we're packaging a lot of images into an expansion file for our app.  If we could pass an InputStream into Picasso, we could use the ZipInputStream for an image in the expansion file directly, without needing to extract the images first.

**Comment by thalesgaldino** [comment]
Could anyone help me?
http://stackoverflow.com/questions/28802526/android-expansion-file-to-custom-picasso-downloader-inputstream

**Comment by InI4** [comment]
@JakeWharton I thought I could need that InputStream too. Unfortunately the referenced link is a 404 now. All the other stuff I google looks like weird workarounds. 

What I'd really like to have, is access to cached images from within a WebView component rendering HTML with <img src="..."> tags. I have a WebViewClient working in place, but of course I'd really want to have all the cool caching, transforming Picasso features. Especially cause most of the images refered in the HTML are actually already loaded via Picasso in other places within the App ...

**Comment by eleventigers** [comment]
@InI4 here's the file in question: https://github.com/f2prateek/u2020/blob/7dabf33a70b3144bbf6dc4180212e6def997b2e0/src/debug/java/com/jakewharton/u2020/data/MockDownloader.java

**Comment by InI4** [comment]
Thank you @eleventigers but this code seems to solve a different problem. 

My problem is, that I'd really like to have access to Picassos download cache stored bitmaps in form of `InputStream`s to avoid that "download bitmap, compress to png" overhead. I still wonder if it wouldn't be possible to attach an `.getAsStream()` to `RequestCreator`. It would of course require a new kind of `BitmapHunter`
