### ISSUE TITLE
Using fit() on an ImageView with a WRAP_CONTENT dimension does nothing

### ISSUE THREAD

**Issue by kwazi** [square/picasso#457]
This is closely related to #425 but I thought it was better to separate them as I wanted to discuss a solution thats specific to this.

https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/RequestCreator.java#L437-443

getMeasuredWidth() and getMeasuredHeight() will always be zero for a WRAP_CONTENT dimension. Meaning the query is deferred indefinitely.

I'm happy to make a pull request for this but I'm unsure which route I should take. Options that I see include:

1) Throw an exception for making such a request (fit() on an ImageView with a LayoutParam of WRAP_CONTENT)
2) Forget about deferring the request because we're still "fitting" into a WRAP_CONTENT view, so I can just do a check and ignore the deferred, pulling the entire image into the View.
3) This is user error and we should ignore it? It seems #365 might be an option as to how the user could work around it when they only have one dimension. But wouldn't work if both dimens are WRAP_CONTENT and it requires the user to know the API..

(2) has the benefit that it should fix #425

Open to other ideas and I'll be happy to whip up a pull request.

**Comment by dnkoutso** [comment]
@mstfchelik also try Picasso 2.5.0 now. Clsoing.

**Comment by lilac** [comment]
@dnkoutso I still encounter this problem when using Picasso 2.4. Which commit fixed this issue?

**Comment by dnkoutso** [comment]
Did you try Picasso 2.5?

**Comment by lilac** [comment]
@dnkoutso Yes, it is the same as 2.4.

**Comment by khaykov** [comment]
I also have this issue in 2.5.2.

**Comment by mzekrallah** [comment]
I also still have this in 2.5.2.1 ..

**Comment by LGRI** [comment]
I have this issue in 2.5.2

**Comment by krzysiekbielicki** [comment]
IMHO https://github.com/square/picasso/blob/303366b749b2b58ea3a1561ff64e093941ebfbbd/picasso/src/main/java/com/squareup/picasso/DeferredRequestCreator.java#L69
is responsible for this behavior.

What if we change it to
`((width <= 0 || height <= 0) && !target.getAdjustViewBounds()) || target.isLayoutRequested()`
?

**Comment by cagdasc** [comment]
In my project ImageView `layout_width/layout_height = match_parent/wrap_content`, the image does not fit in ImageView. It locates center in view and smaller than original size. @cdbkr [solution](https://github.com/square/picasso/issues/457#issuecomment-38787601) is working. The other way If ImageView `layout_width/layout_height`(match_parent both of them) and `adjustViewBounds`(true) attributes set are acceptable for your project, it will work.
