### ISSUE TITLE
Resize() and fit() don't properly resize when loading a local file (throws bitmap too large exception)

### ISSUE THREAD

**Issue by pfives** [square/picasso#461]
I attempt to use local files if they exist on the user's phone rather than fetching a remote image url. 

For panoramic photos, the file on the phone is something like 4500 x 500, huge images. If we fetch the image from the server, it is already scaled down so it comes back at a reasonable size of 640 x 200 or something. 

So if I try to load the phone file to fill the width of the screen:

Picasso.with(context).load(new File(localAssetUrl)).resize(screenWidth, photoHeight).into(rowHolder.mainPhoto);

it throws the "bitmap too large to be loaded into a texture" exception with the 4500 width instead of the screenWidth (which is around 1050).

Loading the same image from the server works great.

I thought the whole point of resize() (also tried fit()) was supposed to take care of this issue but it doesn't seem to work properly when using local files, or am I not just incorrect about that? 

As a workaround I'm planning to check the size of the local file and if it's too large just load from the server but this seems like an unnecessary step.

**Comment by AllenVork** [comment]
As long as i use resize, big file will never be loaded.What i am doing is to show all the images in the sdcard.The photos i toke by camera is in this case and never be shown unless i remove the resize option.
