### ISSUE TITLE
Could not load image from a redirected url

### ISSUE THREAD

**Issue by jfk4080** [square/picasso#463]
Picasso can not load image from URL: 

http://graph.facebook.com/1610564116/picture?width=250&height=250 

What is the problem? 

Thank you for your help

**Comment by hk0i** [comment]
So what's the resolution for this exactly? When my URL shortener redirects an http url to https it doesn't load. 

For example: 
http://goo.gl/FvWi1r

becomes
https://s3.amazonaws.com/gs-geo-images/1589f18c-67c7-4f8c-815d-7067ad2136d9.jpg

and the image will not load.

I *should* have control over the image urls to avoid this, but I'm still wondering what's the appropriate way to handle this in case it becomes unavoidable.

**Comment by gorodechnyj** [comment]
Still having this issue in 2.5.2:
http://placehold.it/150/7735a
->
https://placeholdit.imgix.net/~text?txtsize=14&bg=7735a&txt=150%C3%97150&w=150&h=150

Not displaying a thing

**Comment by colonelmo** [comment]
Please reopen as this is still an issue.

**Comment by alejogamboa** [comment]
Hello. Finally someone solve it?

**Comment by oscarg798** [comment]
I have the same problem but I solved doing changing the picasso downloader to OkHttpDownloader, so as OkHttp now is on version 3 you will need to add this to gradle    
 compile 'com.squareup.okhttp:okhttp:2.5.0'
 
 Picasso.Builder builder = new Picasso.Builder(context);
        builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                holder.getIvSpeakerPicture()
                        .setImageDrawable(context.getResources()
                                .getDrawable("your drawable id"));
            }
        });
        builder.downloader(new OkHttpDownloader(context));
        builder.build().load("your url").into(holder.getIvSpeakerPicture());

**Comment by maduperera** [comment]
Hi, @oscarg798  what is "holder" in above code. I couldn't find a reference for that.

**Comment by hk0i** [comment]
@maduperera it looks like a view holder, I'm guessing `getIvSpeakerPicture()` returns an image view.

**Comment by maduperera** [comment]
Oh no! 
it really is. How did I missed getIvSpeakerPicture().  hehe.
Thanks @hk0i. And Thanks @oscarg798, it worked as you said.

**Comment by oscarg798** [comment]
@maduperera yeap holder is the viewholder as @hk0i  said :D

**Comment by DrewSz** [comment]
@oscarg798 Thanks a lot man..Spent forever trying to get this.

**Comment by mariofelesdossantosjunior** [comment]
I was with the same problem replacing Picasso by Fresco

**Comment by jumperson** [comment]
I had the same problem using this code.
```
Picasso.with(context)
```

I fixed it by this code.
```
val downloader = OkHttp3Downloader(context)
Picasso.Builder(context).downloader(downloader).build()
```

OkHttpClient has a followRedirects property and a followSslRedirects property.
Both are set to true by default.

**Comment by huyhai** [comment]
thanks

**Comment by shtsht** [comment]
I added this one and tried the way jumperson posted and worked well
https://github.com/JakeWharton/picasso2-okhttp3-downloader

@jumperson 
thanks a lot!

**Comment by hrishikesh-kadam** [comment]
Hey guys I have made `CustomPicasso` gist from @jumperson and @shtsht comments using @JakeWharton's picasso2-okhttp3-downloader

`CustomPicasso` gist - https://gist.github.com/hrishikesh-kadam/09cef31c736de088313f1a102f5ed3a3

**Comment by feng88724** [comment]
`compile 'com.squareup.okhttp:okhttp:2.5.0'`


```
Picasso.Builder builder = new Picasso.Builder(mContext);
builder.downloader(new OkHttpDownloader(mContext));
builder.build().load(image).into(viewHolder.image);
```
