### ISSUE TITLE
Picasso erasing image even though no placeholder is set

### ISSUE THREAD

**Issue by Queatz** [square/picasso#469]
At PicassoDrawable.java:63 (https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/PicassoDrawable.java#L63) Picasso sets the image to null, causing it to flash white when changing the image from one to another.

**Comment by SaitejaP** [comment]
Hi, I am facing the same issue. Is it implemented? Can I replace a image with another without placeholder or flash?
