### ISSUE TITLE
Picasso.shutdown() should close downloader's disk cache

### ISSUE THREAD

**Issue by AlexanderSofronov** [square/picasso#486]
I'm trying to use Picasso in my app. I have 2 views: with large images and with small ones, and users may switch between views. I'm using custom Picasso object created by Picasso.Builder and when the user switches the view, I'm shutting down old Picasso object and creating new one.

The problem is when I'm using OkHttpDownloader and switching the view, from time to time I'm getting all the images loaded from the network, not from the disk cache. Looks like disk cache is getting corrupted and cleaned:

unexpected journal line: READ 0064bd130dfac7892734572eeREAD 8eaf1b031b6b7355579860e113018779, removing

I'm guessing that 's because the disk cache is not closed when Picasso object is shutting down.

Interesting that I can't reproduce this with UrlConnectionDownloader. Also, I tried to create my custom downloader which uses DiskLruCache for caching images and I found that the behavior is different depending on which version of DiskLruCache is used:
- when I'm using com.jakewharton.disklrucache.DiskLruCache I can't reproduce the corrupted cache issue
- when I'm using com.squareup.okhttp.internal.DiskLruCache I can reproduce cache corruption with my custom downloader.

So it looks like DiskLruCache version in OkHttp is less stable. But I'm not sure that this is a bug in OkHttp because closing the disk cache properly fixes the issue.

All my experiments were done with:
- Picasso 2.2.0
- OkHttp 1.5.4
- DiskLruCache 2.0.2

**Comment by eygraber** [comment]
This causes issues if multiple (subsequent) Picasso instances are created using the same OkHttpClient instance, since its Cache will get shut down.

**Comment by JakeWharton** [comment]
File a new bug for that.
