### ISSUE TITLE
Bitmap but failed to recycle the original

### ISSUE THREAD

**Issue by ghost** [square/picasso#489]
04-29 11:19:42.732: E/AndroidRuntime(29247): java.lang.IllegalStateException: Transformation borderrounded mutated input Bitmap but failed to recycle the original.
04-29 11:19:42.732: E/AndroidRuntime(29247):    at com.squareup.picasso.BitmapHunter$3.run(BitmapHunter.java:282)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at android.os.Handler.handleCallback(Handler.java:615)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at android.os.Handler.dispatchMessage(Handler.java:92)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at android.os.Looper.loop(Looper.java:137)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at android.app.ActivityThread.main(ActivityThread.java:4863)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at java.lang.reflect.Method.invokeNative(Native Method)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at java.lang.reflect.Method.invoke(Method.java:511)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
04-29 11:19:42.732: E/AndroidRuntime(29247):    at dalvik.system.NativeStart.main(Native Method)
Please help me on this issue.

**Comment by vitrol4** [comment]
Thanks @JakeWharton, it works very well for me too.

**Comment by EternalCoding** [comment]
Thank u so much~ @JakeWharton~

**Comment by himanshuvirmani** [comment]
I have done the recycling but 1 in 100 users are still getting this exception. Does recycle take time which leads to this? If yes, how to overcome that?

Thanks in Advance
