### ISSUE TITLE
error while loading selector drawable

### ISSUE THREAD

**Issue by rsegismont** [square/picasso#497]
Hello, I can't load a drawable selector with picasso 2.2.

Here is the code that doesn't work : 

<code>Picasso.with(getContext()).load(imageId).into(imageView);</code>

But if I use this code instead : 

<code> imageView.setImageResource(imageId) </code>

It works well

and here is my selector : 

<selector xmlns:android="http://schemas.android.com/apk/res/android">

```
<!-- pressed -->
<item android:drawable="@drawable/home_lucky_selected" android:state_pressed="true"/>
<!-- focused -->
<item android:drawable="@drawable/home_lucky_selected" android:state_focused="true"/>
<!-- selected -->
<item android:drawable="@drawable/home_lucky_selected" android:state_selected="true"/>

<!-- default -->
<item android:drawable="@drawable/home_lucky"/>
```

</selector>

Thanks by advance !

**Comment by JakeWharton** [comment]
We haven't gotten to this in 4 years and there hasn't been other requests for such functionality. I'm going to permanently punt unless it comes up a lot in the future.
