### ISSUE TITLE
Save to a File API

### ISSUE THREAD

**Issue by JakeWharton** [square/picasso#506]
If you download an image, there's no easy way to save that to the FS for sharing, attaching to email, etc. It should be synchronous and avoid decoding the image.

`.save(File)`

**Comment by gdmec07120731** [comment]
I get it

**Comment by nicolabeghin** [comment]
any news on this?

**Comment by maikotrindade** [comment]
Guys since we dont have this feature implemented you could use this solution: http://stackoverflow.com/questions/32799353/saving-image-from-url-using-picasso

**Comment by JakeWharton** [comment]
That's precisely what we're trying to avoid. Needlessly roundtripping
through Bitmap and the main thread just to write a file.

**Comment by Piasy** [comment]
Any update or plans about this issue?

**Comment by 275269652** [comment]
Error:In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight and Error:In <declare-styleable> FontFamilyFont, unable to find attribute android:font  please tell me why and we should do  for this questions?  thanks!!!

**Comment by JakeWharton** [comment]
Duping onto #1049.
