### ISSUE TITLE
heavy performance issue

### ISSUE THREAD

**Issue by gbrbks** [square/picasso#507]
Hello guys!

I experienced a strange behavior if I try to load a couple 480x320 jpg file into a 100dp x 100dp imageviews (5-6 max on the screen in portrait mode) in a gridview, it is lagging heavily except if it comes from the cache itself. However when i'm trying to load much smaller pictures it is totally smooth. I'm 99% sure that is related to the cache because if i'm using the .skipMemoryCache() function it is much more better! This is happening on all device not just on my n5. 

The library usage is not overly complicated. 
Picasso.with(mContext).load(mModel.getImageLink()).into(mPreviewImage);

There are 4 more textviews next to the image in the cell. If'm not loading any images then it is totally okay. The overdraws are minimized everything is green and blue. The latest okhttp 1.5.4 is present. There could be  2000 elements in the adapter. I'm using your awesome library from the beginning and never experienced such a performance drop.

sample urls:
big
http://d1bko2jzh7ix12.cloudfront.net/5/c6c469346129c00b9c69b63d092a6f68/gm.jpg
small
http://d1bko2jzh7ix12.cloudfront.net/5/c6c469346129c00b9c69b63d092a6f68/t.jpg

Thanks in advance!

Cheers,
Gabor

**Comment by Moudi2020** [comment]
am fasting same problem posted initially.. i have a pager viewer and a listview in each tab .. i have multiple rows and in each row there is an image... switching fragments from pager is laggy because of picasso.. 
Picasso.with(context).load(link).into(Image);
