### ISSUE TITLE
how to clean cache,how to set disk cache path

### ISSUE THREAD

**Issue by hejunbinlan** [square/picasso#508]
I want to clean memory cache and disk cache,how can I do?
how to set disk cache path?

**Comment by rothschild86** [comment]
working nicely!

if i could suggest one thing... i find that boolean methods are much more fluid in builders of all sorts. (seen it in other libraries and always works out great).

for example, if i have:

```java
  public RequestCreator cacheInMemory(boolean cacheInMemory) {
	    return cacheInMemory ? this : memoryPolicy(MemoryPolicy.NO_STORE);
	  }
```

then i can do:

```java
Picasso.with(MyApp.getAppInstance()).load(url).fit().centerCrop().cacheInMemory(deviceRam > 1024).cacheOnDisk(isFrequentlyRequested);

```

Try doing that with the current syntax and you are looking at nested if statements just to get it done... not pretty :)

**Comment by JakeWharton** [comment]
That would require 5 methods be added which I'm not too crazy about.

**Comment by rothschild86** [comment]
Just food for thought. Ideally it'd be on every method. say, .centerCrop(isVerticalImage).fit(maxWidth < 480). The whole builder becomes exponentially more flexible.

**Comment by JakeWharton** [comment]
But that flexibility comes at the expense of the common case, which is you always want to invoke those methods the same way.
```java
Picasso.with(context)
    .load(url)
    .resize(400, 400)
    .centerCrop(true)
    .fit(true)
    .cacheInMemory(true)
    .cacheOnDisk(true)
    .fade(true)
    .into(imageView);
```
