### ISSUE TITLE
Requesting cached bitmap off the main thread

### ISSUE THREAD

**Issue by savvasdalkitsis** [square/picasso#524]
Picasso unfortunately doesn't provide a way to access cached bitmaps directly but there is a workaround that we have been using for quite some time now without any problems.

Using the following code, we can synchronously retrieve a bitmap if it is cached while at the same time request that bitmap to be fetched from the network if it isn't.

``` java
   @Override
    public Bitmap retrieve(String url, Transformation imageTransformation) {
        CacheTarget cacheTarget = new CacheTarget();
        picasso.load(url)
                .transform(imageTransformation)
                .into(cacheTarget);
        return cacheTarget.getCacheBitmap();
    }

    private static class CacheTarget implements Target {
        private Bitmap cacheBitmap;

        @Override
        public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
            cacheBitmap = bitmap;
        }

        @Override
        public void onBitmapFailed(Drawable errorDrawable) {}

        @Override
        public void onPrepareLoad(Drawable placeHolderDrawable) {}

        public Bitmap getCacheBitmap() {
            return cacheBitmap;
        }
    }
```

This still works just fine but with the introduction of the newest version of Picasso, we lost the ability to call the load into method from a thread other than the main thread.

In our use-case, the code above was invoked in a piece of code which was driven by a 3rd party library (clusterkraf) which controls the threading strategy. Effectively, we use the above code when we generate map placemark thumbnails, if we have a cached bitmap. If we don't, we display a default one and request it be fetched from the network, until the next time the map updates in which case it will be in cache.

Since we can't call the load method directly any more and since we can't change the call stack to happen on the main thread, we've effectively lost the ability to load cached bitmaps onto our map.

An idea for a potential workaround was to inject our custom memory cache object into this class and try to load the bitmap from the mem cache directly but that has two problems:
-  We lose the ability to reference bitmaps stored in disk cache (which will be the majority of the bitmaps. The mem cache won't hold too many bitmaps, especially in low memory phones)
- We can't directly query the mem cache since the key that the bitmap is cached against is not simply the url to the image but an internal representation of the url plus the transformation name. We could replicate that but that is a horrible and brittle hack (if the internal representation changes, our code will stop working)

Would it be possible to expose a way to retrieve images stored in disk and mem cache which would also work from a thread other than the main? If not, do you have any ideas or suggestions as to how we can alleviate this problem?

**Comment by AdarshYadav** [comment]
Finally found solution here:- http://www.opensourcealternative.org/tutorials/android-tutorials/android-picasso-save-image-tutorial/


 Picasso.with(this)
 .load(currentUrl)
 .into(target);
 
 }
 
 private Target target = new Target() {
 @Override
 public void onBitmapLoaded(final Bitmap bitmap, Picasso.LoadedFrom from) {
 new Thread(new Runnable() {
 @Override
 public void run() {           
 
 File file = new File(Environment.getExternalStorageDirectory().getPath() +"/actress_wallpaper.jpg");
 try 
 {
 file.createNewFile();
 FileOutputStream ostream = new FileOutputStream(file);
 bitmap.compress(CompressFormat.JPEG, 75, ostream);
 ostream.close();
 } 
 catch (Exception e) 
 {
 e.printStackTrace();
 }
 
 }
 }).start();
 }
 @Override
 public void onBitmapFailed(Drawable errorDrawable) {
 }
 
 @Override
 public void onPrepareLoad(Drawable placeHolderDrawable) {
 if (placeHolderDrawable != null) {
 }
 }
 };

**Comment by 1zaman** [comment]
@JakeWharton: Is there any way to get the cached bitmap synchronously from the main thread? The `get()` method does not work on the main thread.

**Comment by JakeWharton** [comment]
No. Why do you need it?

**Comment by 1zaman** [comment]
I need to invalidate a ListView at some points in order to use
progress/status indicators in the list items. The ListView contains images
that are loaded through Picasso (it's actually quite a complex structure
where each list item contains a ViewPager which also contains images in
each item). Using Picasso causes a disruptive event upon each invalidation
where all the images are temporarily changed into their placeholders before
the images are asynchronously loaded from the cache.

**Comment by FabianTerhorst** [comment]
To get a bitmap from main thread would be nice for getting a bitmap from cache inside the ondraw method from a custom view.
