### ISSUE TITLE
Large images do not load

### ISSUE THREAD

**Issue by christopherperry** [square/picasso#526]
I'm loading very large images from a local 'Uri' and scaling with `resize()` (also calling `skipMemoryCache()`). Picasso silently fails. Smaller images load fine with the same code. I was using an older version of Picasso and was seeing OOM logged. I tried the latest version and the problem persists, but the log is now nonexistent.

Can you point me to the code that decodes the Bitmaps?

**Comment by AllenVork** [comment]
I encountered the same problem.when i invoke resize option,big pictures(such as the pictures that the camera captures) will not show
