### ISSUE TITLE
Image not use sdcard cached file

### ISSUE THREAD

**Issue by rayboot** [square/picasso#537]
My image url is http://timefaceapi.timeface.cn/uploads/thumbnail/2014/04/21/14/3035_tgEZni.jpg!m205x136.jpg
and i found the cache file in my sdcard.
But everytimes load the image is from network, never use the sdcard cache file.
I use picasso (v 2.3.2) and okhttp (v 2.0.0).
My init method is 

            picasso = new Picasso.Builder(MyApp.getInstance()).downloader(
                    new OkHttpDownloader(
                            createDefaultCacheDir(MyApp.getInstance())))
                    .indicatorsEnabled(isDebug)
                    .build();

And the load method is 

        PicUtil.getPicasso()
            .load("http://timefaceapi.timeface.cn/uploads/thumbnail/2014/04/21/14/3035_tgEZni.jpg!m205x136.jpg")
                .placeholder(R.drawable.cell_default_image)
                .error(R.drawable.cell_default_image)
                .fit()
                .centerInside()
                .skipMemoryCache()
                .into(photoView);

Any wrong ?

**Comment by amehdi** [comment]
I Also have a same problem with an emulator and a real device. Is there any progress on this?

**Comment by dnkoutso** [comment]
The images load fine from disk. See blue indicators (used to be yellow for disk cache)

```
    // Trigger the download of the URL asynchronously into the image view.
    Picasso.with(context) //
        .load(url) //
        .placeholder(R.drawable.placeholder) //
        .error(R.drawable.error) //
        .memoryPolicy(MemoryPolicy.NO_CACHE) //
        .fit() //
        .tag(context) //
        .into(view);
```

![device-2015-05-09-120701](https://cloud.githubusercontent.com/assets/310370/7551605/eb851cb6-f643-11e4-870c-d75e57d18372.png)
