### ISSUE TITLE
won't load camera images

### ISSUE THREAD

**Issue by ram626** [square/picasso#539]
I am trying to use Picasso to load images in an app from the SD card. If I load images that were not taken by the camera they load in fine, but if I try to get images that were taken by the camera they don't load. 

Images over http work too, just not the camera ones.

I have also tried downloading the image from that URL and putting it on the phones storage, it loads fine that way too, it only seems to be images taken from the phones camera. Tested it on Galaxy S2 and S5 and a Galaxy Ace 3. So it could be a Samsung/Galaxy issue only.

Calling Code:

``` java
    String file = "/storage/extSdCard/DCIM/Camera/20140609_204344.jpg";

    picasso
        .load(new File(file)) // this does not work
        //.load("http://upload.wikimedia.org/wikipedia/commons/4/4e/Pleiades_large.jpg")// this works
        .fit()
        .error(R.drawable.logo)
        .into(this.imageView);
```

Exception that occurs:

```
06-09 21:31:47.662: W/System.err(16633):    java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
06-09 21:31:47.672: W/System.err(16633):    at android.graphics.Bitmap.createBitmap(Bitmap.java:783)
06-09 21:31:47.672: W/System.err(16633):    at com.squareup.picasso.BitmapHunter.transformResult(BitmapHunter.java:457)
06-09 21:31:47.672: W/System.err(16633):    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:154)
06-09 21:31:47.672: W/System.err(16633):    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:101)
06-09 21:31:47.672: W/System.err(16633):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
06-09 21:31:47.672: W/System.err(16633):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-09 21:31:47.672: W/System.err(16633):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-09 21:31:47.672: W/System.err(16633):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-09 21:31:47.672: W/System.err(16633):    at java.lang.Thread.run(Thread.java:841)
06-09 21:31:47.672: W/System.err(16633):    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)
```

**Comment by tunjid** [comment]
@dnkoutso Hello, sorry for commenting on a closed issue but I'm experiencing the same bug on a 2013 Moto X on the latest release (2.5.2).

The Moto X is running Kit Kat 4.4.4.

**Comment by dnkoutso** [comment]
Use

```java
Picasso picasso = new Picasso.Builder(context).listener(new Picasso.Listener() {
      @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
        exception.printStackTrace();
      }
    }).build();
```

See what the stacktrace says.

**Comment by tunjid** [comment]
@dnkoutso I did just that, it threw no exception, but it still failed to load the image.

**Comment by leolanzinger** [comment]
@dnkoutso having the same issue here. Picasso 2.5.2 fails to load images from camera. It doesn't throw any exception, the only trace I get of this error is when I attach a `Target` to the `ImageView` and it triggers the `onBitmapFailed()` method.
I am using a Moto G on Android 5.0.1.
**NB:** it may useful to know that I **don't** get this error using the camera of Genymotion emulator.

Thanks

**Comment by khafan** [comment]
I'm getting java.lang.IllegalStateException: Unrecognized type of request: Request{/storage/sdcard0/Pictures/[my folder]/[image_name].jpg} on cyanogenmod kitkat

**Comment by danielchristopher1** [comment]
Getting this too.

**Comment by Sinnup** [comment]
Hey, I've got the same problem, I implemented what dnkoutso said and I get "java.io.IOException: Cannot Reset"

**Comment by JakeWharton** [comment]
Try 2.6.0-SNAPSHOT

**Comment by Sinnup** [comment]
Thanks @JakeWharton , I'm not really experimented on this, how could I implement that version into my Android Studio project? Do I put it in graddle?

**Comment by jdoes** [comment]
@JakeWharton it works with 2.6.0 SNAPSHOT

**Comment by Sinnup** [comment]
I've got an issue to compile, it does not.

compile 'com.squareup.picasso:picasso:2.6.0-SNAPSHOT'

I've writen also : 
buildscript {
    repositories {
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }

**Comment by dpedroza** [comment]
Use Glide lib, it resolves this problem.

compile 'com.github.bumptech.glide:glide:3.7.0'

**Comment by Sinnup** [comment]
@dpedroza  Thanks a lot, it works as expected.

**Comment by jiancchen** [comment]
on motox 5.0.1 removing fit and center crop when loading images from file prevents this issue

**Comment by DevJay22** [comment]
I am experiencing this too.


Camera images don't seem to load especially the ones with sizes greater than 1mb.


Is there any hack or fix available?

**Comment by jasennett** [comment]
I'm seeing this issue as well on a MotoX (2nd Gen) on Android 5.1.  Saved or edited files display properly, but anything from the camera does not display.  Removing fit, center crop, etc as @jiancchen suggested did not resolve it for me.  Seeing the issue on picasso version 2.5.2 and 2.6.0-SNAPSHOT
