### ISSUE TITLE
Is picasso check for okHttp broken?

### ISSUE THREAD

**Issue by Macarse** [square/picasso#541]
In version 2.3.2 it search for `com.squareup.okhttp.OkUrlFactory` (https://github.com/square/okhttp/blob/master/okhttp-urlconnection/src/main/java/com/squareup/okhttp/OkUrlFactory.java)
but I don't see that class available in okHttp 1.6. 

I see that class is part of okhttp-urlconnection, should we start adding okhttp-urlconnection as an additional dependency?

**Comment by mansukhgagal** [comment]
use this combination it work for me

compile 'com.squareup.okhttp:okhttp:2.2.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
compile 'com.squareup.picasso:picasso:2.4.0'

**Comment by davidkable** [comment]
use this  it also work for me

compile 'com.squareup.picasso:picasso:2.4.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
 compile 'com.squareup.okhttp:okhttp:2.7.2'

thanks @mansukhgagal
