### ISSUE TITLE
Offline cache for redirect url  is not working

### ISSUE THREAD

**Issue by soarcn** [square/picasso#544]
Hi,

I try to show the images from my server, it is a url will redirect to another server to display pictures.

for example:
http://122.193.22.153:8080/seeyou/api/appiconpkg/com_liulishuo_engzo
=> http://img.yingyonghui.com/icon/72/1262016.png

everything goes right, but local file cache would not work.

I notice that the image was actually written to disk already, but it would not work if the first url is unreachable( for example no network connection).

So how can I get this work? thanks!

**Comment by rjam** [comment]
I know this is old, but with the recent changes I'm thinking if using a ```stableKey``` on these requests would help? If a request with redirects is cached using a stable key, and then a request is made to the original url with the same ```stableKey``` shouldn't this trigger a cache hit?

**Comment by JakeWharton** [comment]
Only in the memory cache.

**Comment by eygraber** [comment]
@JakeWharton did this behavior change? I request images from a URL that always redirects, and I use `stableKey`. If I load the images, and then close (and force close) the app, the next time I open it, those images are loaded from disk when I use the same `stableKey`. However, if there is no internet connection they never load, even when cached on disk (is that from the OkHttp side of things?).
