### ISSUE TITLE
OKHTTP integration issue

### ISSUE THREAD

**Issue by mrtristan** [square/picasso#558]
using latest intellij ce

``` Objective-C
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.
    To use OkHttp with this version of Picasso, you'll need:
    1. com.squareup.okhttp:okhttp:1.6.0 (or newer)
    2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)
    Note that OkHttp 2.0.0+ is supported!
            at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:246)
            at com.squareup.picasso.Picasso$Builder.build(Picasso.java:596)
            at com.squareup.picasso.Picasso.with(Picasso.java:473)
```

linked jars:

![jars](http://i.imgur.com/VDwX5Dc.png)

is this because it's an RC2? could this be on my side?

**Comment by cornelbalaban** [comment]
I have the following dependencies:
    compile 'com.squareup.picasso:picasso:2.4.0'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'

and still I have the same error :(. Can it be conflicting with the HTTP client used by Retrofit ?
