### ISSUE TITLE
Is incremental loading possible?

### ISSUE THREAD

**Issue by RedNifre** [square/picasso#563]
If I have the same image in multiple resolutions on a server, is it possible to do incremental loading with picasso, either directly, or by implementing it using picasso features?

What I'm looking for is something like "load({smallURL,mediumURL,largeURL)" and I want to see the largeURL image, but while it's loading, it should show the mediumURL image if that exists locally (don't load over the net), or if that doesn't exist, it shows the smallURL image, but if that doesn't exist it uses no placeholder at all.

I could implement that around picasso if I could query the cache. E.g. if picasso can tell me that it already has the low resolution image on disk, I could use the low resolution one as a placeholder while the large image is loading over the network.

Is this possible somehow? Or is the only way to load all sizes in sequence, always?

**Comment by JakeWharton** [comment]
Duping onto #1397
