### ISSUE TITLE
PicassoDrawable#getConstantState() returning null.

### ISSUE THREAD

**Issue by nhaarman** [square/picasso#569]
At the moment, `PicassoDrawable#getConstantState()` returns `null` when the `Drawable` is retrieved from an `ImageView`. Instantiating a new `PicassoDrawable`, and calling `getConstantState()` on it does *not* return `null`:

    Picasso.with(mContext).load(myUrl).into(mImageView); // Bitmap is currently cached
    ConstantState constantState = mImageView.getDrawable().getConstantState(); // returns null
    
    ConstantState constantState2 = new PicassoDrawable(mContext, mBitmap, null, null, true, true).getConstantState(); // returns a valid instance

The new activity transition API's introduced in `Android-L` use this method, therefore throwing `NullPointerExceptions`.

**Comment by dnkoutso** [comment]
Sample app works fine with getConstantState not returning null in Android 5.0.

Perhaps this was an error due to the fact that PicassoDrawable was just extending Drawable back then and not BitmapDrawable.

Closing.
