### ISSUE TITLE
DiskLruCache freezes device

### ISSUE THREAD

**Issue by MarekZeman91** [square/picasso#575]
I thought sometimes it's because the size passed into resize() is 0.

But now this occurred in Log.

07-08 03:57:52.387  13994-14082/cz.MarekZeman.APP_NAME W/System﹕ DiskLruCache /data/data/cz.MarekZeman.APP_NAME/cache/picasso-cache is corrupt: unexpected journal line: READ 1c9073f82eee6afREAD 67edf21a7970bc1d403577c1148d7eec, removing
07-08 03:57:52.391      794-832/? W/ResourceType﹕ Skipping entry 0x7f040001 in package table 0 because it is not complex!
07-08 03:57:52.393      794-832/? W/ResourceType﹕ Skipping entry 0x7f040003 in package table 0 because it is not complex!
07-08 03:57:52.396      794-832/? I/am_activity_launch_time﹕ [0,299869073,cz.MarekZeman.APP_NAME/.MainActivity,902,902]

Any idea how to prevent this freezing?

**Comment by JakeWharton** [comment]
DiskLruCache is managed by OkHttp, not Picasso, so there's nothing we can do here.
