### ISSUE TITLE
Unable to load images with no extension

### ISSUE THREAD

**Issue by MikeSpitz** [square/picasso#594]
Hi,

Testing with Nexus 4 API19 on GenyMotion v2.2.2. When I try to load an image from:

https://domain.com/photo/1

It returns the image in the browser with the following headers:
Content-Type:image/png

It's a nodeJS server using express that returns the file buffer from a database.

The logcat produces:
```
07-22 10:09:13.402    1611-1657/appname D/skia﹕ --- SkImageDecoder::Factory returned null
07-22 10:09:13.402    1611-1657/appname D/skia﹕ --- SkImageDecoder::Factory returned null
07-22 10:09:14.086    1611-1660/appname D/skia﹕ --- SkImageDecoder::Factory returned null
07-22 10:09:14.086    1611-1660/appname D/skia﹕ --- SkImageDecoder::Factory returned null
```

I have tried attaching .png to the request URI but that doesn't seem to work either. When I try to load an image from another site with an extension it works fine.

I'm calling it from a listview adapter:

```java
 Picasso picasso = new Picasso.Builder(context).listener(new Picasso.Listener(){
                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception e) {
                       System.out.println("Never gets here");
                      e.printStackTrace();
                }
            }).build();
            if(!passenger.getId().equals("-1")) {
                String uri = photoURL + passenger.getId(); //id is string
                picasso.with(context).load(uri)
                        .placeholder(R.drawable.passenger_tick)
                        .resize(50, 50)
                        .into(contactPicture);
            }
```

**Comment by dnkoutso** [comment]
Try with Picasso 2.5.0 we fixed an issue related to 504 and content-length 0.

Closing.

**Comment by maniaZTD** [comment]
In my case I solved this error with encode the url 
Because image url that i wanted to download has the Persian letters(or other Unicode character) in it 
So I replaced all Persian characters with encoded UTF-8 letters

**Comment by hoseinit** [comment]
@maniaZTD I can't get it work with uri.encode() ,  what is your propoal?
