### ISSUE TITLE
OutOfMemory each time after phone isn't in use

### ISSUE THREAD

**Issue by oliverhausler** [square/picasso#604]
I have a problem similar to #565, where OutOfMemory is silently discarded. What I don't understand is why does the memory problem only occur after the phone had been sleeping for some time, but then consistently. This looks to me like some process (either one of my own or Picasso's) is not correctly awoken after being put to sleep or does not work anymore. When I look at the stack trace, GC seems not to be able to free the resources used by Picasso, so these keep blocked until the app is restarted. Then everything is back to normal. Note that it doesn't seem to make a difference if the image comes from cache or over http. Images being loaded are reasonably small (<>100kB).

08-04 11:45:41.476  24586-24586/cc.closeup.android I/System.out﹕ ****https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-9/1560657_10152007864918375_1741296254_n.jpg?oh=f901fa3f3371f1952fc50071161ecc8c&oe=54565FC5&__gda__=1415200026_af365c3c59d6016e367febe62fc6a003
08-04 11:45:41.556  24586-24607/cc.closeup.android D/dalvikvm﹕ GC_FOR_ALLOC freed 232K, 38% free 40007K/63744K, paused 28ms, total 28ms
08-04 11:45:41.556  24586-24607/cc.closeup.android I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 3689296-byte allocation
08-04 11:45:41.591  24586-24607/cc.closeup.android D/dalvikvm﹕ GC_BEFORE_OOM freed 1K, 38% free 40006K/63744K, paused 32ms, total 33ms
08-04 11:45:41.591  24586-24607/cc.closeup.android E/dalvikvm-heap﹕ Out of memory on a 3689296-byte allocation.
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ "Picasso-/hphotos-ak-xpa1/v/t1.0-9/1560657_10152007864918375_1741296254_n.jpg" prio=5 tid=16 RUNNABLE
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x424fe9a8 self=0x5cdafa78
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ | sysTid=24607 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1557864552
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ | state=R schedstat=( 43581173547 9122764298 37502 ) utm=3987 stm=371 core=1
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at android.graphics.Bitmap.nativeCreate(Native Method)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:833)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.BitmapHunter.transformResult(BitmapHunter.java:457)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:154)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:101)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:841)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)
08-04 11:45:41.591  24586-24607/cc.closeup.android I/dalvikvm﹕ [ 08-04 11:45:41.746 24586:24605 D/dalvikvm ]
    GC_FOR_ALLOC freed 1063K, 39% free 38953K/63744K, paused 23ms, total 23ms
08-04 11:45:41.746  24586-24605/cc.closeup.android I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 7464976-byte allocation
08-04 11:45:41.781  24586-24605/cc.closeup.android D/dalvikvm﹕ GC_BEFORE_OOM freed 0K, 39% free 38953K/63744K, paused 32ms, total 32ms
08-04 11:45:41.781  24586-24605/cc.closeup.android E/dalvikvm-heap﹕ Out of memory on a 7464976-byte allocation.
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ "Picasso-7f0200b6" prio=5 tid=14 RUNNABLE
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x424fbd50 self=0x5cdae6c0
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ | sysTid=24605 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1557850904
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ | state=R schedstat=( 46239790143 9932566700 39758 ) utm=4197 stm=426 core=3
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:683)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:513)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:541)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.ResourceBitmapHunter.decodeResource(ResourceBitmapHunter.java:51)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.ResourceBitmapHunter.decode(ResourceBitmapHunter.java:38)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:144)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:101)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:841)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)
08-04 11:45:41.781  24586-24605/cc.closeup.android I/dalvikvm﹕ [ 08-04 11:45:41.781 24586:24605 D/skia     ]
    --- allocation failed for scaled bitmap

Do you know of this problem? Can I prevent it from happening? Is there a way to further debug this? Is it a problem that I call Picasso from within its onError() callback?

When I attach the debugger, the code crashes on the Picasso.with... line.

                    screenSurface.setAlpha(0f);
                    Picasso.with(getContext()).load(imageUrl).noFade().fit().centerCrop().into(screenSurface, new Callback() {

                        @Override public void onSuccess() {
                            screenSurface.animate().alpha(1f).setDuration(Constants.PICASSO_FADE_DURATION); // fade image
                        }

                        @Override public void onError() {
                            Picasso.with(getContext()).load(R.drawable.testpattern).into(screenSurface, new EmptyCallback() {

                                @Override public void onSuccess() {
                                    screenSurface.animate().alpha(1f).setDuration(Constants.PICASSO_FADE_DURATION); // fade image
                                }

                            });

                            raiseCommand(PlaybackCommand.ERROR);
                        }

                    });

**Comment by dnkoutso** [comment]
@oliverhausler is this still an issue? If not please close. I kinda lost track. Do you use fit() in your requests?

**Comment by oliverhausler** [comment]
Sorry, cost me a lot of time, but I tracked this one down, and I guess we can't do anything about it. Happens on various older Samsung devices, like the Note 2 and Tab 3.

http://stackoverflow.com/questions/23637835/pause-gc-error-post-android-4-4-2-upgrade/29594861#29594861
