### ISSUE TITLE
Error loading image from Uri

### ISSUE THREAD

**Issue by ziggy42** [square/picasso#605]
I have a GridView in which I put some Images picked from the phone  (I'm targeting only KitKat at the moment). I'm passing an ArrayList of Uri to the Adapter and all works fine. But I want that the images stay here also after the activity is destroyed so I'm using inside my Fragment:

I'm saving/restoring with:

```
public void restore() {
    Set<String> set = mSharedPreferences.getStringSet("IMAGES", null);

    if(set != null)
        for(String uriString : set) {
            imagesUri.add(Uri.parse(uriString));
            Log.i("Immagine: ", Uri.parse(uriString) + "");
        }

    gridViewAdapter.notifyDataSetChanged();
}

public void save() {
    imagesUriSet = new HashSet<String>();
    for(Uri i : imagesUri)
        imagesUriSet.add(i.toString());
    mSharedPreferences.edit().putStringSet("IMAGES",imagesUriSet).commit();
}
```

But the images that are displayed are R.drawable.error.
If I add an image that should be already in the GridView, then the other changes from R.drawable.error to the actual image. 

Am I missing something?

**Comment by dnkoutso** [comment]
Not sure. Do you have sample URIs?

**Comment by dnkoutso** [comment]
Re-open if you provide more information about the issue.
