### ISSUE TITLE
Should cancel request in list view sample

### ISSUE THREAD

**Issue by lkesteloot** [square/picasso#606]
In the list view sample, any on-going requests for a row should be cancelled when the row is re-used (in SampleListDetailAdapter.java):

```
} else {
  holder = (ViewHolder) view.getTag(); 
  Picasso.with(context).cancelRequest(holder.image);
}
```

Otherwise, if the request is still on-going and the row is re-used, when the request finishes it'll get put into the wrong row. In this particular example it may not, since another request will be done for the same row, but in my case some rows didn't have photos and they were being populated anyway. Since this is an example people will copy, it should be safe for this kind of use.

Let me know if you want a pull request.

**Comment by mmanishh** [comment]
I am facing the same problem . When i don't have image on row , another image gets loaded of another row. 

Here is my code of the adapter



 if (feedModel.getProfilePic() != null && !feedModel.getProfilePic().isEmpty()) {
            Picasso.with(activity)
                    .load(feedModel.getProfilePic())
                    .placeholder(R.drawable.ic_profile)
                    .error(R.drawable.ic_profile)
                    .tag("profilePic")
                    .into(rowViewHolder.imgProfilePic);
        }
        else{
            Picasso.with(activity).cancelTag("profilePic");
        }

**Comment by fangzhzh** [comment]
@mmanishh  this works for me
```
        if (!TextUtils.isEmpty(avatarId)) {
            Picasso.with(context)
                    .load(composeAvatarURL(avatarId))
                    .into(imageView);
        } else {
            if (!mini) {
                Picasso.with(context)
                        .load((String)null)
                        .into(imageView);
            }
        }
```
