### ISSUE TITLE
Getting the exact error message in Picasso Callback onError

### ISSUE THREAD

**Issue by timschambers** [square/picasso#617]
Hi,

I have an app in production which uses Picasso to load a variety of image URLs. 
Some of these URLs point to "invalid" images which cannot be rendered by Picasso. So far, I have handled these exceptions by indicating what the error was to the end-user.

My dilemma lies in that these "cannot render image" exceptions are all generic. Neverminding the problems I can predict in advance (i.e. check if the image URL has a valid MIME type) my app can't articulate the precise reason why an image failed to load. To date, this lack of specificity has confused my users over whether the problem is with my app or the server from which the images are being loaded.

Are there plans to percolate the rendering exception that Picasso encounters to the callback for Picasso.load.into?

Looking forward to hearing other's thoughts on this matter.

**Comment by vikasgulati** [comment]
Hey @timschambers, Were you able to get a workaround for this? Thank!

Hey @dnkoutso, had the same doubt as @timschambers w.r.t "No reason why you cant expose this". Is there a way to get the exact error reason? Thanks!

**Comment by JakeWharton** [comment]
No. This is a breaking change. Don't expect it until 3.0.

**Comment by timschambers** [comment]
Hi,

I made a change to the code that allowed the errors to get percolated up
the call chain. You can do something similar via downloading the source,
setting a breakpoint on the exception handler and then stepping
out-and-out.

 I do not advise making the same changes, however, as, Jake points out,
they are not guaranteed to work version to version.
