### ISSUE TITLE
Not displaying in ListView

### ISSUE THREAD

**Issue by ynnadkrap** [square/picasso#620]
I'm using 2.3.3 and everything seems to be working fine except in my custom ListView. Most of the time, Picasso loads my images perfectly fine, but there are a few occasions where the image never loads and the spinner continues spinning. Additionally, sometimes the loading spinner will be present with the image loaded behind it with some opacity set (don't have a screenshot of this yet, but I'll try to grab one). 

Here's how I'm loading my images:

    Picasso picasso = new Picasso.Builder(getContext()).listener(
		new Listener() {
                @Override
                 public void onImageLoadFailed(Picasso arg0,
                                        Uri arg1, Throwable arg2) {
                           if (Constants.debug) Log.i(LOG_TAG, "imageloadfailed");
                           arg2.printStackTrace();          
                 }
                }).debugging(true).build();	
    picasso.load(imgUrl).into(h.picture);

I'm never getting to the onImageLoadFailed(....), and the images never load despite waiting a fair amount of time on a good network. 

Here's an example of an image I'm trying to load:
http://res.cloudinary.com/spotlight-images/image/upload/v1408387652/IMG_1408387652509.jpg

Edit:
I recently switch from AQuery to Picasso, and this problem did not occur with AQuery. 

One of the two weird views:
![screenshot_2014-08-19-10-17-59-1](https://cloud.githubusercontent.com/assets/2474082/3967302/ed35e67e-27ab-11e4-90ba-1a93a59d504f.png)

**Comment by dnkoutso** [comment]
Image loads fine in 2.5.0.
