### ISSUE TITLE
Target onBitmapLoaded() not being called

### ISSUE THREAD

**Issue by mradzinski** [square/picasso#625]
I've implemented the Target interface on a class, however the onBitmapLoaded() method is not being called. I debugged and noticed that onPrepareLoad() it's called perfectly fine, then the image downloads from the network fine (no error reported), but right at the end when onBitmapLoaded() should be called this doesn't happen.

This is my class implementing Target:

```
public class CustomTarget implements Target{
    private Context context;
    private String fileName;

    public CustomTarget (String fileName, Context context) {
        this.fileName = fileName;
        this.context = context;
    }

    @Override
    public void onBitmapLoaded(final Bitmap bitmap, Picasso.LoadedFrom from) {
        Log.d("CustomTarget ", "onBitmapLoaded"); <--- This doesn't get called hence not logged
       //Other stuff here...
    }

    @Override
    public void onBitmapFailed(Drawable errorDrawable) {
        Log.d("CustomTarget ", "onBitmapFailed"); // <--- This doesn't get called hence not logged
        //Other stuff here...
    }

    @Override
    public void onPrepareLoad(Drawable placeHolderDrawable) {
        Log.d("CustomTarget ", "onPrepareLoad"); // <--- This gets called and logged :)
    }
}
```

And I'm loading the image from network like this:

```
CustomTarget target = new CustomTarget("photo001", this);
Picasso.with(this).load("...").into(target);
```

Picasso Logs this:
    08-20 23:54:05.639    3483-3483/com... D/Picasso﹕ Main        created      [R0] Request{...jpg}
    08-20 23:54:05.687    3483-3500/com... D/Picasso﹕ Dispatcher  enqueued     [R0]+46ms
    08-20 23:54:05.687    3483-3502/com... D/Picasso﹕ Hunter      executing    [R0]+48ms
    08-20 23:54:07.483    3483-3502/com... D/Picasso﹕ Hunter      decoded      [R0]+1843ms
    08-20 23:54:07.483    3483-3500/com... D/Picasso﹕ Dispatcher  batched      [R0]+1844ms for completion
    08-20 23:54:07.687    3483-3483/com... D/Picasso﹕ Main        completed    [R0]+2046ms from NETWORK
    08-20 23:54:07.687    3483-3500/com... D/Picasso﹕ Dispatcher  delivered    [R0]+2048ms

Any ideas what could be happening?
Thanks!

**Comment by Robbypatel1357** [comment]
http://stackoverflow.com/a/43134498/5488468 May be it worked
