### ISSUE TITLE
Certain URLs failed to load image for no reasons 

### ISSUE THREAD

**Issue by tom91136** [square/picasso#626]
I'm trying to load:

    http://www.space.com/images/i/000/040/845/i120/supernova-explosion-impression-1000.jpg

It works in Chrome and all other known browsers (Including the Android default browser)
But it doesn't load in Picasso

Sample app:
https://www.dropbox.com/s/2ku5luoqzdg9zlb/picasso-sample-2.3.4-SNAPSHOT.apk?dl=0

I've tested the image URL in fiddlers web proxy with empty headers and the server was able to respond 

RAW REQUEST:

    GET http://www.space.com/images/i/000/040/845/i120/supernova-explosion-impression-1000.jpg HTTP/1.1
    Host: www.space.com

RAW RESPOND:

    HTTP/1.1 200 OK
    Date: Sun, 24 Aug 2014 14:14:37 GMT
    Set-Cookie: amfID=; path=/;
    AMF-Ver: 4.03
    Last-Modified: Wed, 23 Jul 2014 02:19:54 GMT
    ETag: "7656b6-371c-4fed2f9c70680"
    Accept-Ranges: bytes
    Content-Length: 14108
    Connection: close
    Content-Type: image/jpeg
    Set-Cookie: TSf4ec54=33778add26a95b890464e00b35d20362955874e63254897c53f9f344; Path=/

When I load many of those images, the log looks like this:

     D/Picasso﹕ Main        created      [R160] Request{http://www.space.com/images/i/000/040/845/i120/supernova-explosion-impression-1000.jpg RGB_565}
     D/Picasso﹕ Hunter      joined       [R160]+1ms to [R145]+8s, [R157]+7s, [R160]+1ms
     D/Picasso﹕ Main        created      [R161] Request{http://www.space.com/images/i/000/040/845/i120/supernova-explosion-impression-1000.jpg RGB_565}
     D/Picasso﹕ Main        created      [R162] Request{http://www.space.com/images/i/000/040/700/i120/deep-space-la-silla-1000.jpg RGB_565}
     D/Picasso﹕ Main        created      [R163] Request{http://www.space.com/images/i/000/040/658/i120/gum-15-1000.jpg RGB_565}
     D/Picasso﹕ Main        created      [R164] Request{http://www.space.com/images/i/000/040/442/i120/paranal-observatory-sun-set-1024.jpg RGB_565}
     D/Picasso﹕ Main        created      [R165] Request{http://www.space.com/images/i/000/040/367/i120/Cerro-Armazones-eso-1000.jpg RGB_565}
     D/Picasso﹕ Main        created      [R166] Request{http://www.space.com/images/i/000/040/302/i120/atv-shielding-after-impact-test-1024.jpg RGB_565}
     D/Picasso﹕ Hunter      removed      [R160]+3ms from [R145]+8s, [R157]+7s
     D/Picasso﹕ Hunter      joined       [R161]+5ms to [R145]+8s, [R157]+7s, [R161]+5ms
     D/Picasso﹕ Hunter      joined       [R162]+4ms to [R146]+8s, [R162]+4ms
     D/Picasso﹕ Hunter      joined       [R163]+4ms to [R147]+8s, [R163]+4ms
     D/Picasso﹕ Hunter      joined       [R164]+4ms to [R148]+8s, [R164]+4ms
     D/Picasso﹕ Hunter      joined       [R165]+4ms to [R149]+8s, [R165]+4ms
     D/Picasso﹕ Hunter      joined       [R166]+4ms to [R150]+8s, [R166]+4ms
     D/Picasso﹕ Dispatcher  retrying     [R147]+8s, [R163]+14ms
    /dalvikvm﹕ GC_FOR_ALLOC freed 538K, 27% free 3941K/5364K, paused 2ms, total 2ms
     D/Picasso﹕ Hunter      executing    [R145]+12s, [R157]+12s, [R161]+4398ms
     D/Picasso﹕ Dispatcher  retrying     [R146]+12s, [R162]+4900ms
     D/Picasso﹕ Hunter      executing    [R147]+14s, [R163]+6s
     D/Picasso﹕ Hunter      executing    [R146]+14s, [R162]+6s
     D/Picasso﹕ Dispatcher  retrying     [R149]+15s, [R165]+7s
     D/Picasso﹕ Hunter      executing    [R149]+15s, [R165]+7s
     D/Picasso﹕ Dispatcher  retrying     [R148]+15s, [R164]+7s
     D/Picasso﹕ Dispatcher  retrying     [R150]+15s, [R166]+7s
     D/dalvikvm﹕ GC_FOR_ALLOC freed 2198K, 27% free 11016K/14948K, paused 5ms, total 6ms
     D/Picasso﹕ Hunter      executing    [R148]+19s, [R164]+11s
     D/Picasso﹕ Dispatcher  retrying     [R145]+20s, [R157]+19s, [R161]+12s
     D/Picasso﹕ Hunter      executing    [R150]+21s, [R166]+13s
     D/Picasso﹕ Hunter      executing    [R145]+21s, [R157]+21s, [R161]+13s
     D/Picasso﹕ Dispatcher  batched      [R145]+21s, [R157]+21s, [R161]+13s for error
     D/Picasso﹕ Main        errored      [R145]+22s
     D/Picasso﹕ Main        errored      [R157]+22s
     D/Picasso﹕ Main        errored      [R161]+14s
     D/Picasso﹕ Dispatcher  delivered    [R145]+22s, [R157]+22s, [R161]+14s
     D/Picasso﹕ Dispatcher  retrying     [R146]+22s, [R162]+14s
     D/Picasso﹕ Hunter      executing    [R146]+22s, [R162]+14s
     D/Picasso﹕ Dispatcher  batched      [R146]+22s, [R162]+14s for error
     D/Picasso﹕ Dispatcher  retrying     [R147]+22s, [R163]+14s
     D/Picasso﹕ Hunter      executing    [R147]+22s, [R163]+14s
     D/Picasso﹕ Dispatcher  batched      [R147]+22s, [R163]+14s for error
     D/Picasso﹕ Main        errored      [R146]+22s
     D/Picasso﹕ Main        errored      [R162]+14s
     D/Picasso﹕ Main        errored      [R147]+22s
     D/Picasso﹕ Main        errored      [R163]+14s
     D/Picasso﹕ Dispatcher  delivered    [R146]+22s, [R162]+14s, [R147]+22s, [R163]+14s
     D/Picasso﹕ Dispatcher  retrying     [R149]+22s, [R165]+14s
     D/Picasso﹕ Hunter      executing    [R149]+22s, [R165]+14s
     D/Picasso﹕ Dispatcher  batched      [R149]+22s, [R165]+14s for error
     D/Picasso﹕ Main        errored      [R149]+23s
     D/Picasso﹕ Main        errored      [R165]+14s
     D/Picasso﹕ Dispatcher  delivered    [R149]+23s, [R165]+14s
     D/Picasso﹕ Dispatcher  retrying     [R148]+27s, [R164]+19s
     D/Picasso﹕ Hunter      executing    [R148]+27s, [R164]+19s
     D/Picasso﹕ Dispatcher  batched      [R148]+27s, [R164]+19s for error
     D/Picasso﹕ Main        errored      [R148]+27s
     D/Picasso﹕ Main        errored      [R164]+19s
     D/Picasso﹕ Dispatcher  delivered    [R148]+27s, [R164]+19s

**Comment by formatBCE** [comment]
Same problem for me.

**Comment by dnkoutso** [comment]
Has anyone increased the Marker field in NetworkRequestHandler?

Most common reason for this problem is this.

We are fixing in 2.5.1

**Comment by formatBCE** [comment]
@dnkoutso, can you drive me through?

**Comment by dnkoutso** [comment]
https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/NetworkRequestHandler.java#L30

Unfortunately you have to fork the library and increase that number. Its most likely the reason why the image doesnt load.

**Comment by formatBCE** [comment]
As i see, all issues driven by MARKER appearing when fit() or resize() methods ara been applied. But in my case, it's not so.

**Comment by dnkoutso** [comment]
Moved to 2.5.1. Marker issue it appears to be the case here.

@formatBCE what is your URL you use that doesn't load?

**Comment by formatBCE** [comment]
Sorry for inconvenience, problem was on server side, for now all images are
loading successfully.

чт, 12 февр. 2015, 18:57, Dimitris <notifications@github.com>:

**Comment by dnkoutso** [comment]
@formatBCE thanks! Still keeping this on because of MARKER issues.

**Comment by oliverhausler** [comment]
I don't know if this is related, but Picasso suddenly stopped loading certain images, which it loaded earlier. After uninstall/reinstall of the app it worked again.

before:

04-11 08:36:38.900  20448-20448/cc.closeup.android D/Picasso﹕ Main        created      [R0] Request{https://storage.googleapis.com/closeup0002/7836f5829298440787be11cf53b8fd39.jpeg resize(1280,720) centerCrop}
04-11 08:36:38.910  20448-20740/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R0]+15ms
04-11 08:36:38.915  20448-20770/cc.closeup.android D/Picasso﹕ Hunter      executing    [R0]+20ms
04-11 08:36:38.935  20448-20448/cc.closeup.android D/Picasso﹕ Main        created      [R2] Request{https://storage.googleapis.com/closeup0002/8edb01cc933942439b815c32b62aff39.jpeg resize(1280,720) centerCrop}
04-11 08:36:38.940  20448-20448/cc.closeup.android D/Picasso﹕ Main        created      [R4] Request{https://storage.googleapis.com/closeup0002/a7c0aeb1914248aaaffc7bcc549ff8db.jpeg resize(1280,720) centerCrop}
04-11 08:36:38.940  20448-20743/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R2]+7ms
04-11 08:36:38.950  20448-20777/cc.closeup.android D/Picasso﹕ Hunter      executing    [R4]+11ms
04-11 08:36:38.950  20448-20746/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R4]+11ms
04-11 08:36:38.950  20448-20776/cc.closeup.android D/Picasso﹕ Hunter      executing    [R2]+16ms
04-11 08:36:39.500  20448-20746/cc.closeup.android D/Picasso﹕ Dispatcher  retrying     [R4]+559ms
04-11 08:36:39.500  20448-20784/cc.closeup.android D/Picasso﹕ Hunter      executing    [R4]+563ms
04-11 08:36:39.505  20448-20740/cc.closeup.android D/Picasso﹕ Dispatcher  retrying     [R0]+605ms
04-11 08:36:39.505  20448-20743/cc.closeup.android D/Picasso﹕ Dispatcher  retrying     [R2]+568ms
04-11 08:36:39.505  20448-20786/cc.closeup.android D/Picasso﹕ Hunter      executing    [R2]+570ms
04-11 08:36:39.505  20448-20787/cc.closeup.android D/Picasso﹕ Hunter      executing    [R0]+610ms

after:

04-11 08:40:08.380  22348-22348/cc.closeup.android D/Picasso﹕ Main        created      [R0] Request{https://storage.googleapis.com/closeup0002/7836f5829298440787be11cf53b8fd39.jpeg resize(1280,720) centerCrop}
04-11 08:40:08.385  22348-22348/cc.closeup.android D/Picasso﹕ Main        created      [R2] Request{https://storage.googleapis.com/closeup0002/8edb01cc933942439b815c32b62aff39.jpeg resize(1280,720) centerCrop}
04-11 08:40:08.390  22348-22348/cc.closeup.android D/Picasso﹕ Main        created      [R4] Request{https://storage.googleapis.com/closeup0002/a7c0aeb1914248aaaffc7bcc549ff8db.jpeg resize(1280,720) centerCrop}
04-11 08:40:08.395  22348-22764/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R2]+7ms
04-11 08:40:08.395  22348-22808/cc.closeup.android D/Picasso﹕ Hunter      executing    [R2]+8ms
04-11 08:40:08.405  22348-22767/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R4]+14ms
04-11 08:40:08.405  22348-22810/cc.closeup.android D/Picasso﹕ Hunter      executing    [R4]+16ms
04-11 08:40:08.410  22348-22761/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R0]+32ms
04-11 08:40:08.415  22348-22812/cc.closeup.android D/Picasso﹕ Hunter      executing    [R0]+35ms
04-11 08:40:09.150  22348-22812/cc.closeup.android D/Picasso﹕ Hunter      decoded      [R0]+774ms
04-11 08:40:09.160  22348-22808/cc.closeup.android D/Picasso﹕ Hunter      decoded      [R2]+771ms
04-11 08:40:09.160  22348-22810/cc.closeup.android D/Picasso﹕ Hunter      decoded      [R4]+772ms
04-11 08:40:09.320  22348-22812/cc.closeup.android D/Picasso﹕ Hunter      transformed  [R0]+943ms
04-11 08:40:09.370  22348-22761/cc.closeup.android D/Picasso﹕ Dispatcher  batched      [R0]+991ms for completion
04-11 08:40:09.415  22348-22808/cc.closeup.android D/Picasso﹕ Hunter      transformed  [R2]+1027ms
04-11 08:40:09.430  22348-22764/cc.closeup.android D/Picasso﹕ Dispatcher  batched      [R2]+1044ms for completion
04-11 08:40:09.535  22348-22810/cc.closeup.android D/Picasso﹕ Hunter      transformed  [R4]+1145ms
04-11 08:40:09.535  22348-22767/cc.closeup.android D/Picasso﹕ Dispatcher  batched      [R4]+1145ms for completion
04-11 08:40:09.570  22348-22761/cc.closeup.android D/Picasso﹕ Dispatcher  delivered    [R0]+1193ms
04-11 08:40:09.570  22348-22348/cc.closeup.android D/Picasso﹕ Main        completed    [R0]+1192ms from NETWORK
04-11 08:40:09.685  22348-22764/cc.closeup.android D/Picasso﹕ Dispatcher  delivered    [R2]+1246ms
04-11 08:40:09.700  22348-22348/cc.closeup.android D/Picasso﹕ Main        completed    [R2]+1314ms from NETWORK
04-11 08:40:09.735  22348-22767/cc.closeup.android D/Picasso﹕ Dispatcher  delivered    [R4]+1346ms
04-11 08:40:09.745  22348-22348/cc.closeup.android D/Picasso﹕ Main        completed    [R4]+1357ms from NETWORK

**Comment by oliverhausler** [comment]
I don't know if this is related, but Picasso suddenly stopped displaying certain images (which were most possibly cached on disk). After uninstall/reinstall it worked normally again.

before:

04-11 08:36:38.900  20448-20448/cc.closeup.android D/Picasso﹕ Main        created      [R0] Request{https://storage.googleapis.com/closeup0002/7836f5829298440787be11cf53b8fd39.jpeg resize(1280,720) centerCrop}
04-11 08:36:38.910  20448-20740/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R0]+15ms
04-11 08:36:38.915  20448-20770/cc.closeup.android D/Picasso﹕ Hunter      executing    [R0]+20ms
04-11 08:36:38.935  20448-20448/cc.closeup.android D/Picasso﹕ Main        created      [R2] Request{https://storage.googleapis.com/closeup0002/8edb01cc933942439b815c32b62aff39.jpeg resize(1280,720) centerCrop}
04-11 08:36:38.940  20448-20448/cc.closeup.android D/Picasso﹕ Main        created      [R4] Request{https://storage.googleapis.com/closeup0002/a7c0aeb1914248aaaffc7bcc549ff8db.jpeg resize(1280,720) centerCrop}
04-11 08:36:38.940  20448-20743/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R2]+7ms
04-11 08:36:38.950  20448-20777/cc.closeup.android D/Picasso﹕ Hunter      executing    [R4]+11ms
04-11 08:36:38.950  20448-20746/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R4]+11ms
04-11 08:36:38.950  20448-20776/cc.closeup.android D/Picasso﹕ Hunter      executing    [R2]+16ms
04-11 08:36:39.500  20448-20746/cc.closeup.android D/Picasso﹕ Dispatcher  retrying     [R4]+559ms
04-11 08:36:39.500  20448-20784/cc.closeup.android D/Picasso﹕ Hunter      executing    [R4]+563ms
04-11 08:36:39.505  20448-20740/cc.closeup.android D/Picasso﹕ Dispatcher  retrying     [R0]+605ms
04-11 08:36:39.505  20448-20743/cc.closeup.android D/Picasso﹕ Dispatcher  retrying     [R2]+568ms
04-11 08:36:39.505  20448-20786/cc.closeup.android D/Picasso﹕ Hunter      executing    [R2]+570ms
04-11 08:36:39.505  20448-20787/cc.closeup.android D/Picasso﹕ Hunter      executing    [R0]+610ms

after:

04-11 08:40:08.380  22348-22348/cc.closeup.android D/Picasso﹕ Main        created      [R0] Request{https://storage.googleapis.com/closeup0002/7836f5829298440787be11cf53b8fd39.jpeg resize(1280,720) centerCrop}
04-11 08:40:08.385  22348-22348/cc.closeup.android D/Picasso﹕ Main        created      [R2] Request{https://storage.googleapis.com/closeup0002/8edb01cc933942439b815c32b62aff39.jpeg resize(1280,720) centerCrop}
04-11 08:40:08.390  22348-22348/cc.closeup.android D/Picasso﹕ Main        created      [R4] Request{https://storage.googleapis.com/closeup0002/a7c0aeb1914248aaaffc7bcc549ff8db.jpeg resize(1280,720) centerCrop}
04-11 08:40:08.395  22348-22764/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R2]+7ms
04-11 08:40:08.395  22348-22808/cc.closeup.android D/Picasso﹕ Hunter      executing    [R2]+8ms
04-11 08:40:08.405  22348-22767/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R4]+14ms
04-11 08:40:08.405  22348-22810/cc.closeup.android D/Picasso﹕ Hunter      executing    [R4]+16ms
04-11 08:40:08.410  22348-22761/cc.closeup.android D/Picasso﹕ Dispatcher  enqueued     [R0]+32ms
04-11 08:40:08.415  22348-22812/cc.closeup.android D/Picasso﹕ Hunter      executing    [R0]+35ms
04-11 08:40:09.150  22348-22812/cc.closeup.android D/Picasso﹕ Hunter      decoded      [R0]+774ms
04-11 08:40:09.160  22348-22808/cc.closeup.android D/Picasso﹕ Hunter      decoded      [R2]+771ms
04-11 08:40:09.160  22348-22810/cc.closeup.android D/Picasso﹕ Hunter      decoded      [R4]+772ms
04-11 08:40:09.320  22348-22812/cc.closeup.android D/Picasso﹕ Hunter      transformed  [R0]+943ms
04-11 08:40:09.370  22348-22761/cc.closeup.android D/Picasso﹕ Dispatcher  batched      [R0]+991ms for completion
04-11 08:40:09.415  22348-22808/cc.closeup.android D/Picasso﹕ Hunter      transformed  [R2]+1027ms
04-11 08:40:09.430  22348-22764/cc.closeup.android D/Picasso﹕ Dispatcher  batched      [R2]+1044ms for completion
04-11 08:40:09.535  22348-22810/cc.closeup.android D/Picasso﹕ Hunter      transformed  [R4]+1145ms
04-11 08:40:09.535  22348-22767/cc.closeup.android D/Picasso﹕ Dispatcher  batched      [R4]+1145ms for completion
04-11 08:40:09.570  22348-22761/cc.closeup.android D/Picasso﹕ Dispatcher  delivered    [R0]+1193ms
04-11 08:40:09.570  22348-22348/cc.closeup.android D/Picasso﹕ Main        completed    [R0]+1192ms from NETWORK
04-11 08:40:09.685  22348-22764/cc.closeup.android D/Picasso﹕ Dispatcher  delivered    [R2]+1246ms
04-11 08:40:09.700  22348-22348/cc.closeup.android D/Picasso﹕ Main        completed    [R2]+1314ms from NETWORK
04-11 08:40:09.735  22348-22767/cc.closeup.android D/Picasso﹕ Dispatcher  delivered    [R4]+1346ms
04-11 08:40:09.745  22348-22348/cc.closeup.android D/Picasso﹕ Main        completed    [R4]+1357ms from NETWORK

**Comment by oliverhausler** [comment]
This may be a new issue, so I started one in #972.

**Comment by JakeWharton** [comment]
Closed by #1280.

**Comment by rohitbandil** [comment]
"http://placehold.it/150/dff9f6" this url is not loading using picasso.

**Comment by EvgenyTerebenin** [comment]
@rohitbandil I have such problem with these URLs. I am parsing photos JSON from the site
