### ISSUE TITLE
Allow defining custom Action for Picasso / Add Fetch listener

### ISSUE THREAD

**Issue by danielesegato** [square/picasso#634]
I need to pre-load some image (warm-up) when my app start.

I'd like to have a way to wait for those images to be fetched before showing the UI that contains them.

I'd like to be able to do something like this:

Picasso.with(getContext()).load(myImage).fetch(myListener);

I've see the FetchAction is created by Picasso and then submitted with package protected Picasso.submit() method. This means we can't create custom Action Request.

Fetch doesn't give any way of obtaining a listener (fail / success).

**Comment by dnkoutso** [comment]
Fetch has a callback now in 2.5.0.
