### ISSUE TITLE
Allow query Picasso for cache hits.

### ISSUE THREAD

**Issue by danielesegato** [square/picasso#635]
I'd like to be able to ask Picasso if an image is already in cache or not:

	int cacheState = Picasso.with(getContext()).getCacheState(myUrl);
	switch (cacheState) {
	    case Picasso.NOT_CACHED:
		break;
	    case Picasso.CACHED:
		break;
	    case Picasso.CACHED_STALE:
		break;
	    // etc...
	}

Is that possible?
Thanks

**Comment by dnkoutso** [comment]
@danielesegato #634 is now released. Have you tried it? This like a year old issue. Closing.
