### ISSUE TITLE
Bitmap loaded of Target object not called on first load

### ISSUE THREAD

**Issue by vijaykd** [square/picasso#659]
I have implemented picasso for loading profile image on my Google map v2 from a given URL. The problem is that it doesn't load the image first time I load it. I have to reload them again to make profile image come up.

Here is what I have tried but doesn't seem to work:

     public class Maps extends Fragment implements GoogleMap.OnMyLocationChangeListener
     {
         private Target target = new LoadingImage();

         protected void onPostExecute(String file_url)
          {
             for (int i = 0; i < nameList.size(); i++)
             {
                userName = nameList.get(i).getName();
                lati = nameList.get(i).getLati();
                longi = nameList.get(i).getLongi();
                photoUrl = nameList.get(i).getImage();

                gotoLocation(Double.parseDouble(lati), Double.parseDouble(longi), userName, photoUrl, ZOOMVALUE);
            }
         }

      private void gotoLocation(double lat, double lng, String name, String url, float zoom)
         {
             final String uname = name; 
             curlat = lat;
            curlong = lng;

           Picasso.with(getActivity()).load(url).resize(100, 100).into(target)
        }

     public class LoadingImage implements Target 
      {	
	 	@Override
		public void onBitmapFailed(Drawable arg0) 
		{
			markerOptionsforfriends = new MarkerOptions().position(new LatLng(curlat, curlong)).icon(BitmapDescriptorFactory.fromResource(R.drawable.profilepic)).title(uname).anchor(0.5f, 1);
			markerforfriends = googleMap.addMarker(markerOptionsforfriends);  
		}

		@Override
		public void onBitmapLoaded(Bitmap b, LoadedFrom arg1) 
		{
			Log.e("Target","Clicked");

			bitmapMarkerforfriends = BitmapDescriptorFactory.fromBitmap(b);

			if(b != null)
			{
				markerOptionsforfriends = new MarkerOptions().position(new LatLng(curlat, curlong)).icon(bitmapMarkerforfriends).title(uname).anchor(0.5f, 1);
			}
			else
			{
				markerOptionsforfriends = new MarkerOptions().position(new LatLng(curlat, curlong)).icon(BitmapDescriptorFactory.fromResource(R.drawable.profilepic)).snippet(uname).anchor(0.5f, 1);
			}

			markerforfriends = googleMap.addMarker(markerOptionsforfriends);                    
			
		}

	@Override
	public void onPrepareLoad(Drawable arg0) 
		{
			// TODO Auto-generated method stub
			
	 	}	
	    }
      }

**Comment by dnkoutso** [comment]
Add a global exception listener `picasso.listener(new Listener...)` and print out the exception. Add an error drawable and see if that shows up.

It would be an indicator that decoding fails for some reason. Second time it probably works due to memory caching.
