### ISSUE TITLE
NetworkRequestHandler hangs on downloader.load(data.uri, data.loadFromLocalCacheOnly);

### ISSUE THREAD

**Issue by jaredrummler** [square/picasso#662]
Trying out the new `RequestHandler` but images are no longer loading via the `NetworkRequestHandler`. If I use `UrlConnectionDownloader` instead of `OkHttpDownloader` it no longer hangs. Perhaps it's because I am using the latest version of okhttp and not the master branch? It hangs on line 99 of OkHttpDownloader. 

```java
HttpURLConnection connection = urlFactory.open(new URL(uri.toString()));
```
https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/OkHttpDownloader.java#L99

**Comment by dnkoutso** [comment]
Closing. Not Picasso related.
