### ISSUE TITLE
ViewPager showing Error when fetching full screen image

### ISSUE THREAD

**Issue by lkapuna** [square/picasso#687]
Hi, 
I have a problem when fetching big image to ViewPager like 60% it shows the error image
i'm loading the images in grid view, then when pressing small image to larger the problem appear
the image is taking the correct url address and not showing any error what so ever
the images are not more then 100-300 kb.
i'm using

public void onResume() {
		super.onResume();
		Bundle bundle = getArguments();
		if(bundle != null){
			url = bundle.getString("url");
//			System.out.println("url full image is "+url);
			PicassoBigCache.INSTANCE.getPicassoBigCache(getActivity().getApplicationContext())
			.load(url).placeholder(R.drawable.loading).error(R.drawable.error).skipMemoryCache().into(image);
			
		}
		
	} 

can you please assist?... 
Thanks

**Comment by JakeWharton** [comment]
Probably #754
