### ISSUE TITLE
Rotate if necessary

### ISSUE THREAD

**Issue by julianonunes** [square/picasso#691]
How can I rotate the picture automatically if the photo has been taken in a different orientation?

**Comment by afollestad** [comment]
Not sure why Picasso still can't respect exif rotation when Glide can.

**Comment by JakeWharton** [comment]
Because we don't implement JPEG parsing.

**Comment by kaiifalcutela** [comment]
@JakeWharton so this happens on jpg images only?

**Comment by tpfaff** [comment]
Are there any plans to support parsing the exif tags for orientation?

**Comment by JakeWharton** [comment]
Not unless Android adds an API for it.

**Comment by afollestad** [comment]
@tpfaff checkout [Glide](https://github.com/bumptech/glide), it's used at Target and Google (e.g. Google Photos)

**Comment by JakeWharton** [comment]
You can leave Target off that list.

**Comment by tpfaff** [comment]
@JakeWharton Looks like they added one in support lib 25.1.0 

> 
Added ExifInterface support library. This library unbundles support for reading Exif information from JPEG and raw formatted files and setting the Exif information on JPEG image files.

**Comment by xanscale** [comment]
https://stackoverflow.com/a/66588700/2642478
