### ISSUE TITLE
Display GIF files

### ISSUE THREAD

**Issue by niteshkhatri** [square/picasso#700]
Hi, thanks for such a great library. Can I display GIF files using this library?

**Comment by xmenxwk** [comment]
android do support gif, all you need to do is make it work.

**Comment by JakeWharton** [comment]
Feel free to send a pull request for it.

**Comment by SeanOceanHu** [comment]
Hi @JakeWharton , we are currently using Picasso to load images in our app, and it works just perfect :+1:   : )
However now we need to load Gifs now, tried Glide but there's some flickering issue : (
So we are sticking to Picasso, can you give some hints on how to use Picasso to load Gif into ImageView ? Much thanks ~

**Comment by JakeWharton** [comment]
Picasso displays GIF Bitmaps because Android supports decoding them.
Picasso does not support animated GIFs because Android does not support
them. There are no workarounds or ways to add this support at this time.

**Comment by vladimirarevshatyan** [comment]
there is workaround and ION did it,you should check it ,i love picasso,but i had to migrate to ION for animated gif displays,it just loads the link and if it is gif it is animating it,i did not look at source code on how the lib actually doing it,but you might want to have a look

**Comment by Shreyas-R** [comment]
Gif support added ??

**Comment by vladimirarevshatyan** [comment]
gif support has been added a long time ago,but yet the 1.9mb gif is rendering so slowly that you better not render it at all!

**Comment by raytheon-chen** [comment]
Apng support added？

**Comment by JakeWharton** [comment]
Picasso does not support formats. Android supports formats. When asking a
question of whether a format is supported you need to ask Android, not
Picasso.
