### ISSUE TITLE
Custom cache keys

### ISSUE THREAD

**Issue by pcopenhaver-gpfw** [square/picasso#738]
I am using Picasso to load images from AWS and each request is authenticated via a series of query strings in the URL. These query string are replace every time I get a new list of URLs. As a result, every time I sync my list of URLs, both my memory and disk caches are essentially invalidated because they are keyed off the URLs, which include the query strings.

Is there any way to provide my own custom cache keys instead of always keying caches on the image URLs?

**Comment by MrYangYang** [comment]
May I ask how to?
