### ISSUE TITLE
java.io.IOException: Failed to decode stream.

### ISSUE THREAD

**Issue by yoslabs** [square/picasso#745]
I have this issue with picasso, I have the latest version of picasso and okhttp, here is the stack trace,

11-09 17:20:56.879: W/System.err(2167): 	at com.squareup.picasso.NetworkRequestHandler.decodeStream(NetworkRequestHandler.java:123)
11-09 17:20:56.879: W/System.err(2167): 	at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:75)
11-09 17:20:56.879: W/System.err(2167): 	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
11-09 17:20:56.879: W/System.err(2167): 	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
11-09 17:20:56.879: W/System.err(2167): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-09 17:20:56.879: W/System.err(2167): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-09 17:20:56.879: W/System.err(2167): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-09 17:20:56.879: W/System.err(2167): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-09 17:20:56.879: W/System.err(2167): 	at java.lang.Thread.run(Thread.java:841)
11-09 17:20:56.879: W/System.err(2167): 	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)

How can I solve this issue ? thank you.

**Comment by dnkoutso** [comment]
Use a custom request handler if you need more control on this.

Closing.
