### ISSUE TITLE
If no placeholder loading lags and Progress Bar goes out of view.

### ISSUE THREAD

**Issue by cycorax12** [square/picasso#747]
I used Picasso as image processing library in my application. Its being amazing integration till now. However to improvise and make image loading more faster I removed Placeholder while loading and loading of image was faster than ever. However I encountered following issues.
1. Lags while scrolling in listview and gridview (was not lagging if placeholder was in place)
2. ProgressBar used in callback goes out of view.

Rather than using placeholder i am using something like this now.

placeholder(Color.WHITE)

**Comment by JakeWharton** [comment]
It's not clear what the problem is here. Can you reproduce this in our sample app so we can observe the behavior locally?
