### ISSUE TITLE
Picasso and Lollipop problem

### ISSUE THREAD

**Issue by CeccoCQ** [square/picasso#749]
Hi, 
I've this error:
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7700000155 in tid 2532 (Picasso-/102055)
and my app crashes everytime in the Android AVD 5.0.

I've this code in my fragment:
            Picasso.with(getActivity())
                    .load(imageUrl)
                    .fit()
                    .centerCrop()
                    .placeholder(R.drawable.placeholder)
                    .into(navigationImageImageView);

All works correctly before 5.0. 
Can you help me?

**Comment by Papipo** [comment]
Using

```
URL.setURLStreamHandlerFactory(new OkUrlFactory(client));
```

didn't fix the issue for me. It fails on Lollipop but works fine on KitKat.
