### ISSUE TITLE
Album-art drwaing problems

### ISSUE THREAD

**Issue by newgifted** [square/picasso#757]
Hi,

Picasso draws wrong thumbnails sometimes when I trying to draw content://media/external/audio/albumart/598 .
It draws thumbnail of content://media/external/images/thumbnails where image_id=598

I think the Picasso processes album art as the general image. 

Can you fix it?

**Comment by dnkoutso** [comment]
Not enough info for this problem. Please provide screenshots and/or sample app.

**Comment by JakeWharton** [comment]
We will re-open when you provide said info and we verify it's an actual problem.

**Comment by vbarthel-fr** [comment]
Hi !

I have just faced the same issue. I want to load an album art, but Picasso doesn't  seem to load the proper image.

For want I understand: ```.fit()``` is used and the ```imageView``` is small so it falls into the ```MediaStoreRequestHandler.PicassoKind.MINI``` category leading to call ```Images.Thumbnails.getThumbnail(...)``` in [MediaStoreRequestHandler.java#L84
](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/MediaStoreRequestHandler.java#L84) and for a reason I don't understand it does not return a null bitmap but a bitmap of an other image.

Here is the code that reproduces the 'bug' on a 4.3 device:

```java
public class MainActivity extends ActionBarActivity {

    private static final Uri ALBUM_ART_URI = Uri.parse("content://media/external/audio/albumart/65");
    private static final Uri THUMBNAIL_URI = Uri.parse("content://media/external/images/thumbnails/65");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final ImageView imageView1 = (ImageView) findViewById(R.id.activity_main_image_view_1);
        final ImageView imageView2 = (ImageView) findViewById(R.id.activity_main_image_view_2);
        final ImageView imageView3 = (ImageView) findViewById(R.id.activity_main_image_view_3);

        findViewById(R.id.activity_main_btn_load).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                imageView1.setImageURI(ALBUM_ART_URI);
                imageView2.setImageURI(THUMBNAIL_URI);
                Picasso.with(v.getContext())
                        .load(ALBUM_ART_URI)
                        .fit()
                        .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
                        .into(imageView3);
            }
        });
    }

}
```

and a screenshot of the result:

![screenshot_2015-04-14-15-54-33](https://cloud.githubusercontent.com/assets/3321467/7141402/ac69cf52-e2d1-11e4-8e66-454f4353d823.png)

Hope it can help !
