### ISSUE TITLE
fit().centercrop() doesn't match the width of imageview

### ISSUE THREAD

**Issue by raylee4204** [square/picasso#769]
when using fit().centercrop() on an imageview with `match_parent` width, the resized image doesn't fill the width of the imageview.

The following screenshot was taken from a Nexus 9 with lollipop.

![device-2014-11-27-151750](https://cloud.githubusercontent.com/assets/2085389/5221457/dafdbebe-7648-11e4-8071-4104d312b54a.png)

**Comment by JakeWharton** [comment]
Fix was merged. Will be in next release.
