### ISSUE TITLE
Is there any way to resize image only if the original one is bigger than the max size?

### ISSUE THREAD

**Issue by UglyTroLL** [square/picasso#772]
Is there any way to resize image only if the original one is bigger (width > maxWidth || height > maxHeight) than the max size using Picasso?
I was planning to have a custom transformation for it, but it's hard to avoid OOM if I dont use resize() and centerInside() in that way. But if I use resize(), the Bitmap I get (as the parameter) in Transformation is already resized (to max size).
Is it possible to add a resizeIfBigger() method into picasso? Or is it possbile to do what I want to do here in the current version?
Thanks

**Comment by JakeWharton** [comment]
What about an `.onlyIfBigger()` API that enables this behavior for the existing resize methods (similar to `.centerCrop()` & `.centerInside()`?) This way we don't need overloads for `resize()` and `resizeDimen()`.

**Comment by JakeWharton** [comment]
But maybe named better...

**Comment by JakeWharton** [comment]
`.onlyScaleUp()`

**Comment by dnkoutso** [comment]
Closing.
