### ISSUE TITLE
Loading same icon multiple times using recyclerview causes blanks

### ISSUE THREAD

**Issue by martintreurnicht** [square/picasso#787]
Our app has a list that shows the same icon recurring using the new recyclerview, the icons show up the first time but after scrolling down and back up i'm left with blank spaces.

This doesn't seem to occur when using different images, my guess is it is some kind of concurrency issue 
![screenshot_2014-12-09-19-41-44](https://cloud.githubusercontent.com/assets/1970728/5362476/0a2120d6-7fdc-11e4-8128-aad0518f1bf8.png)

**Comment by JakeWharton** [comment]
Show code. We can't know how you are using the library.

**Comment by dnkoutso** [comment]
Please provide sample app with the problem.
