### ISSUE TITLE
Picasso should ignore OkHttp on API7, API8

### ISSUE THREAD

**Issue by rothschild86** [square/picasso#790]
Picasso should ignore OkHttp on API7, API8. Picasso has minSdk of 7. OkHttp has a minSdk of 9. An app should not crash on API 7 just because OkHttp is present, since picasso is capable of using the native implementation on API 7 :) Unless there's some other underlying reason...

**Comment by JakeWharton** [comment]
Okhttp 1.6 still works with Picasso which was supported back to Android 2.1 so we can't blindly do this. Now that we've switched to OkHttp 2's native API things get interesting...

**Comment by JakeWharton** [comment]
The minimum is bumped to 14 on master.
