### ISSUE TITLE
display images from list of bitmaps into listview

### ISSUE THREAD

**Issue by Slake07** [square/picasso#826]
i want to display images into listview from bitmaps but its scoll so slowly due to large bitmap.. how can i solve using your library.?

**Comment by JakeWharton** [comment]
Please use the 'picasso' tag on StackOverflow for general questions. The issue tracker is for bugs and explicit feature requests only.

**Comment by JakeWharton** [comment]
Try adding `.fit()` for a quick solution.

**Comment by Slake07** [comment]
i already tried on stackoverflow and it all show me loading images using url and not using bitmap. thats why i asked here.

**Comment by JakeWharton** [comment]
This library isn't a magic bullet. You still need to use reasonable principles.

The sample uses very large images which load and scroll fine. It just uses `.fit().centerCrop()`.

Other than that, you haven't provided any information for anyone to even begin to try and figure out what you are doing let alone be able to help you in a meaningful way.

**Comment by Slake07** [comment]
My adapter class:

class ListDetailAdapter extends BaseAdapter {
  private final Context context;
  private final List<Bitmap> urls = new ArrayList<Bitmap>();

  public DetailAdapter(Context context) {
    this.context = context;
    Collections.addAll(urls, Data.URLS);
  }

  @Override public View getView(int position, View view, ViewGroup parent) {
    ViewHolder holder;
    if (view == null) {
      view = LayoutInflater.from(context).inflate(R.layout.detail_item, parent, false);
      holder = new ViewHolder();
      holder.image = (ImageView) view.findViewById(R.id.photo);
      holder.image1 = (ImageView) view.findViewById(R.id.photo1);
     
      view.setTag(holder);
    } else {
      holder = (ViewHolder) view.getTag();
    }

    holder.image.setImageBitmap(urls.get(postion));
    holder.image1.setImageBitmap(urls.get(postion));

    return view;
  }

  @Override public int getCount() {
    return urls.size();
  }

  @Override public String getItem(int position) {
    return urls.get(position);
  }

  @Override public long getItemId(int position) {
    return position;
  }

  static class ViewHolder {
    ImageView image;
    ImageView image1;
  }
}

In above code, i am loading bitmap into two images. where bitmap size are big. so it takes time when i am scrolling my listview. so now, i want to use your library for loading bitmap so that i can scroll fast.

I think now you have some information and you can help me regarding my problem. if you still need any information then tell me. i will provide.

**Comment by JakeWharton** [comment]
There are no calls to Picasso in that code.

**Comment by Slake07** [comment]
because i dont know how to use your library for loading bitmap into imageview. thats the point, i am asking question here.

**Comment by JakeWharton** [comment]
```java
Picasso.with(context).load(url).fit().centerCrop().into(holder.image);
Picasso.with(context).load(url).fit().centerCrop().into(holder.image2);
```

**Comment by Slake07** [comment]
as per your code, it loads from url and i already told you, i want to load bitmap, not url. you can see my code.

**Comment by JakeWharton** [comment]
If you are saying that you already have `Bitmap` objects and are trying to load them into the `ImageView` then Picasso doesn't support that at present.
