### ISSUE TITLE
Bitmap not show

### ISSUE THREAD

**Issue by 6a209** [square/picasso#828]
in my app one bitmap in cache is 

cat c4bec33ed1a5ed7499479b4552b26cb9.0

GET
0
HTTP/1.1 200 OK
21
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 2592000
Age: 33298
Cache-Control: max-age=86400
Content-Disposition: inline; filename="19m4he_ieydgyjrg4ydazjumuytambqmeyde_345x130.jpg"
**Content-Length: 0**
Content-Transfer-Encoding: binary
Content-Type: image/jpeg
Date: Sun, 04 Jan 2015 02:48:56 GMT
ETag: "FoiokaWeTSOuotc0OPS51tIgXlIj"
Expires: Sun, 04 Jan 2015 17:33:58 GMT
Proxy-Connection: Keep-alive
Server: PWS/8.1.20.9
X-Android-Received-Millis: 1420339761365
X-Android-Response-Source: CONDITIONAL_CACHE 304
X-Android-Selected-Transport: http/1.1
X-Android-Sent-Millis: 1420339761330
X-Log: mc.g/404;mc.g:2;RS:2;mc.s;IO:8
X-Px: ht h0-s9.p2-hgh.cdngp.net
X-Reqid: PGYAAOfWXBMu8bUT
X-Whom: nb263

------------------------------------

**Content-Length: 0**  ; I think this is because the bitmap does not show;
 I don't know why in that time the length is 0, but now is not 0, however the bitmap does not show yet.
only  when I do rm the file 
“rm c4bec33ed1a5ed7499479b4552b26cb9.0” then it  will be ok~
but I not find  the api to rm this file in Picasso

**Comment by JakeWharton** [comment]
The reason the content length is zero is that a validation request returned a 304 status code (per `X-Android-Response-Source: CONDITIONAL_CACHE 304`). It looks like perhaps a bug in the HTTP response cache in AOSP is incorrectly caching a validation response.

@swankjesse does that seem accurate?

An easy workaround would be to drop OkHttp into your application. Picasso will automatically pick it up and use it as a superior HTTP client and caching mechanism.

**Comment by swankjesse** [comment]
Yeah, we fixed this in OkHttp. We didn't anticipate a `Content-Length` header to be served with `304 Not Modified`, particularly one that disagrees with the length of the original response.

**Comment by JakeWharton** [comment]
Cool, thanks.

So it looks like using OkHttp is your best path forward. This is likely already fixed on the newest versions of Android (or it will be on subsequent versions) but using OkHttp gives you consistent, correct behavior across all API levels.

**Comment by 6a209** [comment]
can you tell me the fixed version of OkHttp?

**Comment by swankjesse** [comment]
It's definitely fixed in 2.2. Possibly older versions too.
