### ISSUE TITLE
oom  issue

### ISSUE THREAD

**Issue by machinezhou** [square/picasso#830]
hi jack，
i met oom problems occasionally,  and i don't know how to avoid it although i already done alot of works like center crop or resize. 
log as follow: 

java.lang.RuntimeException: ===============BEGIN PICASSO STATS ===============
    Memory Cache Stats
    Max Cache Size: 14380470
    Cache Size: 14309788
    Cache % Full: 100
    Cache Hits: 1686
    Cache Misses: 1123
    Network Stats
    Download Count: 137
    Total Download Size: 53094415
    Average Download Size: 387550
    Bitmap Stats
    Total Bitmaps Decoded: 258
    Total Bitmap Size: 110076868
    Total Transformed Bitmaps: 256
    Total Transformed Bitmap Size: 84666276
    Average Bitmap Size: 426654
    Average Transformed Bitmap Size: 329440

java.lang.RuntimeException: ===============BEGIN PICASSO STATS ===============
    Memory Cache Stats
    Max Cache Size: 14380470
    Cache Size: 14354668
    Cache % Full: 100
    Cache Hits: 2257
    Cache Misses: 1397
    Network Stats
    Download Count: 160
    Total Download Size: 57027829
    Average Download Size: 356423
    Bitmap Stats
    Total Bitmaps Decoded: 356
    Total Bitmap Size: 129653362
    Total Transformed Bitmaps: 321
    Total Transformed Bitmap Size: 98007400
    Average Bitmap Size: 364194
    Average Transformed Bitmap Size: 275301
    ===============END PICASSO STATS ===============

thank you

**Comment by JakeWharton** [comment]
The cache only occupies 1/7th of the heap size so you are still blowing the other 6/7ths of the heap in your application. Picasso can't do anything to stop that. The rest of your application is using a ton of memory.

While Picasso is usually the library that sees the OutOfMemoryError, it's almost never the actual underlying cause. Your application in general needs to reduce it's memory use. You can try making Picasso's memory cache smaller, but that will only delay the problem, not eliminate it.
