### ISSUE TITLE
Set wallpaper with picasso?

### ISSUE THREAD

**Issue by ramswaroop** [square/picasso#833]
I want to download an image from a URL and set it as wallpaper ([see docs] (http://developer.android.com/reference/android/app/WallpaperManager.html#setBitmap(android.graphics.Bitmap))).

In short, I want a bitmap which i can set as wallpaper.

Is it possible with picasso? If yes, how?

**Comment by dnkoutso** [comment]
Use a `Target` to execute the request and get a `Bitmap`. Then use the `Bitmap` anyway you want.

Closing this as its not an issue with Picasso.

**Comment by ramswaroop** [comment]
I  was thinking of implementing like this:
```java
mSetWallpaperBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    Bitmap wallpaper = Picasso.with(getActivity()).load(mMedia.getDisplayUrl()).get();
                    WallpaperManager wallpaperManager = WallpaperManager.getInstance(getActivity());
                    wallpaperManager.setBitmap(wallpaper);
                } catch (Exception e) {
                    Log.e(TAG, e.getLocalizedMessage());
                }
            }
        });
```

Is it correct?
