### ISSUE TITLE
Tell Picasso how to load images

### ISSUE THREAD

**Issue by AOrobator** [square/picasso#838]
Is there a way to tell Picasso how to load images? In my specific use case, I'm creating a music playing app, where album art is embedded in a song file, so passing in the file of the song wouldn't work. Ideally I'd pass in some interface with a `public Bitmap getBitmap()` function in the loading process.

**Comment by JakeWharton** [comment]
Yes. Look at [`RequestHandler`][1]. There's examples in the sample app.

 [1]: http://square.github.io/picasso/javadoc/com/squareup/picasso/RequestHandler.html
