### ISSUE TITLE
Is Picasso supporting OkHttp Interceptors ?

### ISSUE THREAD

**Issue by pdegand** [square/picasso#840]
Hi, 

I tried to combine the new Interceptors from OkHttp 2.2 with Picasso to add Headers to the images request but it looks like the Interceptor is never called.

Here is the code : 

    OkHttpClient client = new OkHttpClient();
    client.networkInterceptor().add(new Interceptor() {
      @Override
      public Response intercept(final Chain chain) throws IOException {
        Request newRequest = chain.request().newBuilder().addHeader("Cookie", mCookies).build();
        return chain.proceed(request);
      }
    };
    Picasso picasso = new Picasso.Builder(getContext())
            .downloader(new OkHttpDownloader(client))
            .build();
    picasso.load("www.example.com/img.jpg").into(mImageView);

When inspecting the request with something like Charles Proxy or with a breakpoint inside the `intercept()` method, the Interceptor is never called.

Any idea ? Is this even supported by Picasso ? I suggest yes because it's supposed to be performed by OkHttp only.

Thanks

**Comment by meisterfuu** [comment]
OkHttpClient client = new OkHttpClient();
okHttpClient.networkInterceptor()

schouldnt the second line be
"client.networkInterceptorS().add(...)"
?

**Comment by pdegand** [comment]
Yep, it's just a copy/paste error.

**Comment by pdegand** [comment]
From OkHttp Wiki : 

     OkHttp's interceptors [...] do not work with [...] Picasso ≤ 2.4.

I'm f*cked.

**Comment by dnkoutso** [comment]
We're aiming to add support for this in our next release, 2.5.

**Comment by pdegand** [comment]
Thx for the effort, I will stay tuned for the next release !

**Comment by anthonymonori** [comment]
Any update on this one?

**Comment by cotfas** [comment]
I`m using this method of Header Auth

=========================
OkHttpClient client = new OkHttpClient();
client.networkInterceptor().add(new Interceptor() {
  @Override
  public Response intercept(final Chain chain) throws IOException {
    Request newRequest = chain.request().newBuilder().addHeader("Cookie", mCookies).build();
    return chain.proceed(request);
  }
};
=========================

With setting Picasso as setSingletonInstance

And it is causing memory leaks (Tested with Picasso 2.5.2 and 3.0.0-Snapshoot)
