### ISSUE TITLE
Is it possible to load an R.color.green resource in to ImageView as background color?

### ISSUE THREAD

**Issue by hugoM1** [square/picasso#841]
Im trying to do this but nothing happens.
Picasso.with(context)
                .load(R.color.green)
                .fit()
                .transform(new RoundedTransformation())
                .into(colorImage);

Is it possible to load an R.color.green resource in to ImageView as background color? or load an rgb color as background for an ImageView?
Thanks for help.

**Comment by JakeWharton** [comment]
Can't you just use a `<shape>` that's a circle and reference the color from it?

**Comment by JakeWharton** [comment]
If not, you can make a rectangle `<shape>` that fills the color and use the `R.drawable` instead of `R.color` in your original line.

**Comment by martinbonnin** [comment]
@JakeWharton I can't make this work. Looks like `load(R.drawable.shapeId)` calls `BitmapFactory.decodeResource`, which does not work for shape drawables.

More generally, is there a way to set a solid color on an ImageView using Picasso ? I'm afraid just doing imageView.setImageResource(R.drawable.shapeId) will not cancel the existing requests (if any).

**Comment by martinbonnin** [comment]
Ah, just found `Picasso.cancelRequest()` :-). That'll do the job.
