### ISSUE TITLE
Cannot load very large images

### ISSUE THREAD

**Issue by Nikitenko** [square/picasso#843]
For example:
http://rockcity.ru/images/normal/30324.jpg
http://rockcity.ru/images/normal/30336.jpg

**Comment by JakeWharton** [comment]
What behavior do you see? What version of Picasso? Are you using OkHttp?
What is logged? How are you calling Picasso?

URLs by themselves are not helpful in diagnosing problems.

**Comment by Nikitenko** [comment]
"What behavior do you see?"
ImageView remained empty.

"What version of Picasso?"
version: 'com.squareup.picasso:picasso:2.4.0'

"Are you using OkHttp?"
No

"What is logged?"
D/skia﹕ too Large Progressive Image (1, 3508 4961)
W/skia﹕ libjpeg error 105 <  Ss=%d, Se=%d, Ah=%d, Al=%d> from Not support too Large Progressive Image!! [0 0]
D/skia﹕ --- decoder->decode returned false

"How are you calling Picasso?"
Picasso.with(AfficheActivity.this)
	.load(iconUrl)
	.into(posterImage);

**Comment by dnkoutso** [comment]
The image is huge. Of course it wont' load it.

E/dalvikvm-heap( 1547): Out of memory on a 69612764-byte allocation.

Use `fit()` or `resize()`

**Comment by drummor** [comment]
`skia: too Large Progressive Image (1, 5184 x 3456)> limit(16777216)`
how to resolve this problem
