### ISSUE TITLE
EXIF support for downloaded images.

### ISSUE THREAD

**Issue by panagath** [square/picasso#846]
Picasso auto rotates by 90degrees an image coming from the web that has the following EXIF data:

Resolution : 3264 x 2448 
Orientation : rotate 90

It would be nice if we could have an option to disable auto rotation using EXIF.

**Comment by JakeWharton** [comment]
Why do you want to ignore EXIF?

**Comment by JakeWharton** [comment]
Also, EXIF is not read from the web. Only content providers and files.

**Comment by panagath** [comment]
I have cases of images online, that although on the browser they appear correctly on "portrait" orientation. On Android Picasso rotates them to "landscape" and the image has the wrong direction.

Are you sure that EXIF orientation is not working with online? Because I have this issue with online images.

**Comment by JakeWharton** [comment]
Your issue is that the EXIF is not applied to the image.

**Comment by panagath** [comment]
Good. It still is a problem :) . Is anyone about to do it? Are there any limitations? Would it help if I forked and made the required changes?

**Comment by JakeWharton** [comment]
There's no issue for it, so this can cover that. Support was attempted in #692 and #699. We have no plans to add support for version 2 as it entails more work and a potential (albeit optional) dependency on a large, third-party jar.

**Comment by dnkoutso** [comment]
@panagath A custom transformation can be applied here from your side to check and read the EXIF.

Picasso can be extended in various ways to fix unique cases like these. We aim for the mainstream/majority of cases and slowly open up as we see fit.

A transformation will occur in the bg thread of the pipeline so no performance hit there.

**Comment by abhi007tyagi** [comment]
I am having the same issue. Some images on URL are in portrait and some are landscape.
Portrait images are coming as rotated images on Picasso. How can I transform image from URL to appear correctly?

**Comment by piotrek1543** [comment]
May I ask for final solution for this problem?

**Comment by tilo** [comment]
+1

**Comment by imcrypticcoder** [comment]
Why this issue is closed ?  Thanks for bothering me Picasso. Totally disappointed. Need to move to Glide or Fresco. Bye.

**Comment by JakeWharton** [comment]
Bye!!1!1

**Comment by piotrek1543** [comment]
@JakeWharton maybe it's time not to disable comments on this issue as it closed and as you said how situation with EXIF values looks like. Cheers!

**Comment by alinooreddine** [comment]
Glide is the perfect and best one, recommended by Google and has been used in many Google open source projects.
https://github.com/bumptech/glide

**Comment by SurbhiVSambare** [comment]
I am facing the same issue.. I am uploading portrait images but after uploading they becomes landscape..
how to resolve this issue..? please let me know asap..

**Comment by thesultanster** [comment]
I am facing the same issue as @SurbhiVSambare

**Comment by NehaVerma993** [comment]
Same issue for me as well

**Comment by xanscale** [comment]
https://stackoverflow.com/a/66588700/2642478
