### ISSUE TITLE
Received response with 0 content-length...

### ISSUE THREAD

**Issue by LinkOut** [square/picasso#847]
Got that error, and image does not load.

I'm simply using the library from gradle: 
compile 'com.squareup.picasso:picasso:2.4.0'
No other squareup library is using.

I'm using picasso like this:            Picasso.with(getActivity()).load("URL").placeholder(R.drawable.mdraw).error(R.drawable.mdraw).into(imageView);

**Comment by 6a209** [comment]
to see => https://github.com/square/picasso/issues/828

**Comment by JakeWharton** [comment]
Yep. Sounds like that issue. You'll have to use the latest version of OkHttp to work around this problem since the bug is in Android's HTTP client on some versions.

**Comment by LinkOut** [comment]
Well ok, i've tested on many Android clients, with different OS versions and the problem is still there, this problem only happens when Picasso try to load the image from cache. Networking works fine.

**Comment by JakeWharton** [comment]
Try with OkHttp
