### ISSUE TITLE
Picasso doesn't seem to download image - Stuck on placeholder

### ISSUE THREAD

**Issue by palmithor** [square/picasso#849]
I am using Picasso and I really like using it. I am though having problem about image not being displayed. The weird thing is that it displays the placeholder and doesn't update it to the image (not sure if really is downloading it?). Below is my code, image of the view, the log as well as the dependencies I am using. 

This is the view where I am loading the images, I am loading the same image into two views using the same method. One is loading and the other one is not (that is the android man should be replaced with the picture of the kitten)
![alt text](http://i58.tinypic.com/20rtjlg.png)

```
Main        created      [R6] Request{http://cl.jroo.me/z3/S/_/v/e/a.baa-Cool-and-funny-kitten.jpg resize(1018,810) centerInside}
Main        created      [R7] Request{http://cl.jroo.me/z3/S/_/v/e/a.baa-Cool-and-funny-kitten.jpg resize(1018,810) centerInside}
Dispatcher  enqueued     [R6]+0ms
Hunter      joined       [R7]+0ms to [R6]+0ms, [R7]+0ms
Hunter      executing    [R6]+0ms, [R7]+0ms
Hunter      decoded      [R6]+8ms
Hunter      transformed  [R6]+20ms
Dispatcher  batched      [R6]+20ms, [R7]+20ms for completion
Dispatcher  delivered    [R6]+221ms, [R7]+221ms
```

```
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
    compile 'com.squareup.picasso:picasso:2.4.0'
    compile 'com.squareup.okio:okio:1.2.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
```

```java
    private void loadImage(final ImageViewHolder viewHolder, final int placeholder) {
        Picasso picasso = Picasso.with(viewHolder.image.getContext());
        picasso.setIndicatorsEnabled(true);
        picasso.setLoggingEnabled(true);

        picasso.load("http://cl.jroo.me/z3/S/_/v/e/a.baa-Cool-and-funny-kitten.jpg")
                .placeholder(placeholder)
                .centerInside()
                .fit()
                .into(viewHolder.image, new Callback() {
                    @Override
                    public void onSuccess() {
                        Log.d(TAG, "success");
                    }

                    @Override
                    public void onError() {
                        Log.d(TAG, "onError");
                    }
                });
    }
```

**Comment by 6a209** [comment]
you can see the cache dir is the cache are err?

**Comment by 6a209** [comment]
check your disk cache is err?
default in /data/data/your_app_packge_name/cache/picasso-cache you can see some things like this 

ff7600fd3d40c1e792a36b246868ff9d.0
ff7600fd3d40c1e792a36b246868ff9d.1
ff7f55f3dc84d06edaa2749109b94b1c.0
ff7f55f3dc84d06edaa2749109b94b1c.1
.....

this value (ff7f55f3dc84d06edaa2749109b94b1c) equale md5(image url)

**Comment by palmithor** [comment]
Well.. I have checked the cache and there isn't a file with the md5 for the url.

url: http://cl.jroo.me/z3/S/_/v/e/a.baa-Cool-and-funny-kitten.jpg
MD5: 1be06c840d37277ec9005aa68e308c9b

When I follow the logs I cannot even see a request being sent.

**Comment by 6a209** [comment]
curl -I http://cl.jroo.me/z3/S/_/v/e/a.baa-Cool-and-funny-kitten.jpg
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 15 Jan 2015 11:38:35 GMT
Content-Type: text/html
Connection: keep-alive
X-Powered-By: PleskLin

**http code is 404**

**Comment by palmithor** [comment]
Uhm, I don't get the same results here:
```
curl -I http://cl.jroo.me/z3/S/_/v/e/a.baa-Cool-and-funny-kitten.jpg
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=604800
Content-Type: image/jpeg
Date: Thu, 15 Jan 2015 11:40:36 GMT
Etag: "2269116175"
Expires: Thu, 22 Jan 2015 11:40:36 GMT
Last-Modified: Fri, 26 Apr 2013 19:32:43 GMT
Server: ECAcc (sto/EA31)
X-Cache: HIT
Content-Length: 13417
```

**Comment by 6a209** [comment]
what you devices rom and version? try comment  the okhttp 

    //compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
    compile 'com.squareup.picasso:picasso:2.4.0'
    //compile 'com.squareup.okio:okio:1.2.0'
    // compile 'com.squareup.okhttp:okhttp:2.2.0'

**Comment by palmithor** [comment]
I have tried a Genymotion emulator with versions 17 and 19 as well as a Nexus 5 device on 5.0.1.

Btw, got the same result after commenting out okhttp and the other libs.

**Comment by palmithor** [comment]
Sorry for the inconvenience, this has something to do with the other library. I tried setting the label also from a webservice and it sometimes shows the whole text from the callback and sometimes only half. 

You've been of great help!

**Comment by palmithor** [comment]
Thanks for your help. This was a stupid mistake. It was because of the view.

**Comment by jaygauten** [comment]
@palmithor: what do you mean by "it was because of the view"? please elaborate, im having the same problem where the library wont load the image and stuck at displaying the placeholder. thanks..
