### ISSUE TITLE
Question: Can I detect when a load from file fails?

### ISSUE THREAD

**Issue by fwaltman** [square/picasso#851]
My app has a preloaded database of locations and an associated image in the assets folder. However occasionally a new location is added (via download) and in this case the image is stored in the local file system (since assets are read only).

What I'd like to do is try and load it from assets (which is working OK) but if the image isn't found in the assets folder to try and load from the file system.

My current (pre Picasso) way was to catch a FileNotFoundException on the assets.open() and do the alternate load there.

I can work around it by adding a field to the database but that has other issues so if there is a simple way to do it with Picasso that would be better.

Thanks in advance.

**Comment by dnkoutso** [comment]
You could use a custom `RequestHandler` to perform this.

`Target` will also invoke `onBitmapFailed` if the image failed to load in which you can re-execute the request.

**Comment by fwaltman** [comment]
Thanks!
