### ISSUE TITLE
Image cache issue.

### ISSUE THREAD

**Issue by FaizanAnwar** [square/picasso#852]
I am using picasso in my android project and i have situation where i have to change image with same url but different content in it. But now issue is that it is on cache and it only changed when i delete the application. I have found this link https://github.com/square/picasso/commit/83f2fd530f3ac7402ed382a1ef3960eaa6773d4d?diff=unified where invalidate methods are defined but i can't able to find them or access them. I am using version 2.0.4. 
Please tell me that these methods are available for use? 
Thanks

**Comment by JakeWharton** [comment]
Those methods will be released in 2.5 sometime before the end of this month. If you need access to them now you can build Picasso from source yourself or depend on a snapshot version which is pushed to Sonatype's snapshot repo.
