### ISSUE TITLE
Picasso 2.4.0 not working on Android Gingerbread.

### ISSUE THREAD

**Issue by XclusR** [square/picasso#854]
Picasso 2.4.0 not working on Android Gingerbread.

Here is simple code, which works on Androi 4.0 (ICS), but didn't works on 2.3 (Gingerbread):
Picasso.with(this).load(url).into(image);

Libraries versions:
compile 'com.squareup.picasso:picasso:2.4.0'
compile 'com.squareup.okhttp:okhttp:2.2.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'

Here is some log data:
Main created [R0] Request{https://...}
Dispatcher enqueued [R0]+227ms
Hunter executing [R0]+374ms

Also there are lot of unresolved methods errors:
Could not find method java.nio.file.Files.newOutputStream, referenced from method okio.Okio.sink
Could not find method java.nio.file.Files.newInputStream, referenced from method okio.Okio.source
Could not find method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getContentLengthLong, referenced from method com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getContentLengthLong
Could not find method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFieldLong, referenced from method com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFieldLong
Could not find method com.squareup.okhttp.internal.Util.emptySink, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine
Could not find method com.squareup.okhttp.internal.http.HttpMethod.hasRequestBody, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine
Could not find method com.squareup.okhttp.internal.http.HttpMethod.hasRequestBody, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine
Could not find method com.squareup.okhttp.internal.http.HttpEngine.hasResponseBody, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getErrorStream
Could not find method com.squareup.okhttp.internal.http.HttpEngine.getResponseBodyBytes, referenced from method com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream
DexOpt: couldn't find static field

**Comment by XclusR** [comment]
Please refer to similar issue:
https://github.com/square/picasso/issues/213

**Comment by JakeWharton** [comment]
What's the error? You haven't said anything about what's not working.

**Comment by SimonVT** [comment]
You need to use the same version of okhttp and okhttp-urlconnection.

**Comment by JakeWharton** [comment]
Whoops. Yep that's it.

**Comment by XclusR** [comment]
Sorry for delayed response.
Not working(doesn't loads images) even with following config:
   compile 'com.squareup.picasso:picasso:2.4.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'

Tested on Samsung Galaxy S and on emulator.

**Comment by dnkoutso** [comment]
Can you please attach a listener to picasso and show the exception?

"Not working" isn't exactly enlightening for us to know what the problem is.

**Comment by XclusR** [comment]
There is no any exception. Here is how I attached listener:

            Picasso.Builder builder = new Picasso.Builder(getApplicationContext());
            builder.listener(new Picasso.Listener() {

                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                    exception.printStackTrace();
                    Log.e("Picasso Error", exception.getMessage());
                }
            });
            Picasso pic = builder.build();
            pic.load(url).into(imageView);

**Comment by dnkoutso** [comment]
What is the url you load, does it work on ICS+?

**Comment by XclusR** [comment]
Yes. At least it was tested on L. Let me create simple test app to check the issue.

**Comment by XclusR** [comment]
After slight investigation discovered, that it doesn't work on particular images, for example for google-hosted images:
"https://lh3.ggpht.com/0MPCRaSfVK_wayiecMI33j4l4dpVwee4317fWl1aH0OIL37220o2HNcfOIdsbV8znVrY=w300-rw"
