### ISSUE TITLE
Picasso memory leak in Android 4.4 Kitkat

### ISSUE THREAD

**Issue by supersume** [square/picasso#856]
I am using Picasso for the sole purpose of loading local images (Mediastore Uris and Application image resources). Picasso is by far the most efficient library for this task. However, there seems to be a memory leak in Android 4.4 devices when loading local images. The exact same app has a heap size of 24MB on an Android 4.1.1 device and a 120MB heap on a Kitkat device. The app becomes laggy and crashes at times (Out of memory). The situation can be replicated by creating a Gridview containing multiple images from the drawable folder of the app (In my case, its the wallpaper chooser activity).

**Comment by JakeWharton** [comment]
Please provide a pull request modifying the sample app or a standalone sample app which easily and unquestionably demonstrates the leak. We absolutely do not have the bandwidth to look into potential problems like this when we have to spend a ton of time figuring out just how to even reproduce the issue.

**Comment by dnkoutso** [comment]
Sorry insufficient information for us to work with. Giving enough data is not enough. Every app and case is unique. Different URLs, different imageview sizes, different memory requirements.
