### ISSUE TITLE
onBitmapLoaded called only once.

### ISSUE THREAD

**Issue by de-Stan** [square/picasso#857]
First of all i want to thank you for this amazing tool.

I'm having a problem getting multiple images and saving them in the local storage. I did search the issues but i couldn't find a solution. 
This is what i have done so far.

First my fragment implements Target:
```Java
public static class MyFragment extends Fragment implements Target
```

Second i call Picasso this way:
```Java
Picasso.with(getActivity())
 .load(clipData.getItemAt(i).getUri()) // a url basically
 .resize(100, 100)
 .into(this);
```
this is in a for loop

And i override onBitmapLoaded like this:
```Java
 @Override
        public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from)
        {
            //Save file code is here normally.
            Log.e("LOADED", "REACHED");
        }
```
The thing is that Log is firing only once. Meaning that the callback is called only once.

Thanks in advance.

**Comment by mattprecious** [comment]
Picasso only allows one queued/in-flight request per target. If you're doing this in a loop, every new request will cancel the previous one. You'll need to create a new `Target` instance on every iteration instead of passing `this`.

**Comment by JakeWharton** [comment]
And make sure you keep a reference to those individual `Target` instances in a List or array as a field, for example.

**Comment by de-Stan** [comment]
Got it, thank you.

**Comment by EpicDrakkar** [comment]
Just came here to say, thank you (For you solution and amazing tool!). New Instance of target does work. Thank you
