### ISSUE TITLE
Image does not loaded

### ISSUE THREAD

**Issue by favn1585** [square/picasso#858]
Hello. Thanks for great library. I am trying to load image and I get onError() in callback.
fit(), resize(w, h) and android:largeHeap="true" does not help.

![20141224_202002 1 jpg](https://cloud.githubusercontent.com/assets/3111598/5873450/3d09980c-a2ff-11e4-8ad5-177e1034f6c9.jpg)

Device - nexus 5

http://dl-web.dropbox.com/get/Public/20141224_202002%5B1%5D.jpg?_subject_uid=4228683&amp;w=AACQfgQ3ZcYMm4OB7AIsF92MRt9NQ6OJ2cYh3M2Qn5YqtQ&amp;dl=1

**Comment by favn1585** [comment]
Picasso.with(context)
                .load(getValidUri(photoUri))
                .tag(PTAG)
                .placeholder(R.drawable.bg_app_gray)
                .error(R.drawable.bg_app_gray)
                .fit()
                .centerInside()
                .into(imageView, callback);

**Comment by saltcoffee** [comment]
the same problem with u.
picasso version 2.4.0

can not load image with the demo code.

Picasso.with(context).load("http://i.imgur.com/DvpvklR.png").into(imageView);

my device:nexus 5, android 5.0.1

**Comment by Lollypo** [comment]
me too
i run a simple demo with android annotions

**Comment by yychun1217** [comment]
me too. My problem is here: http://stackoverflow.com/questions/28426468/picasso-cannot-load-images-for-some-url-no-special-characters?noredirect=1#comment45189039_28426468

**Comment by dnkoutso** [comment]
I get a 403 on the original poster link.

**Comment by dnkoutso** [comment]
Use 

```java
Picasso picasso = new Builder(context).listener(new Listener() {
            @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
              exception.printStackTrace();;
            }
          }).indicatorsEnabled(true).build();
```

And paste the stacktrace. Re-open issue when you have more concrete information.
