### ISSUE TITLE
scrolling issue with picaso

### ISSUE THREAD

**Issue by kprasad30** [square/picasso#863]
I am using gridview in android which loading images from AWS s3. Also using picaso library & calling it in getview of adapter.
Now if I scroll up & down, it sends multiple request for same images. Also those images taking lot of time to load causing performance issues.

**Comment by JakeWharton** [comment]
This issue has no information on which is actionable.

> multiple request for same images

Picasso will merge requests for the same URL and only download it once. If you can write code which clearly demonstrates this being broken we'll take a look at it.
