### ISSUE TITLE
Add support for RippleDrawable

### ISSUE THREAD

**Issue by danijoo** [square/picasso#874]
Will there be support for RippleDrawables in the future?

You can add ripple effects to images by wraping the Drawable in a RippleDrawable. Would be nce to have a function for that with picasso.

**Comment by JakeWharton** [comment]
You can use the success callback in order to wrap the `Drawable` which was set on the `ImageView`. Unless there's some other specific functionality that I'm not seeing which cannot be accomplished in this fashion, I don't see any reason to support it in the library.
