### ISSUE TITLE
centerCrop + exif rotation = incorrect cropping

### ISSUE THREAD

**Issue by ansman** [square/picasso#875]
Summary
---
If you load an image from a file where the data is is rotated with the center crop option it is incorrectly displayed.

It would appear as if the cropping is done before the rotation is applied.

Code
---
```java
Picasso.with(this)
    .load(file)
    .fit()
    .centerCrop()
    .into(imageView);
```

Image
---
![Landscape_6](https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_6.jpg)

Result
---
The pink stuff is the image view.

![Result](http://f.cl.ly/items/2w42472Y2a1V2v2C1P0X/device-2015-02-07-205112.png)

**Comment by jacobtabak** [comment]
See #699

**Comment by JakeWharton** [comment]
I was going to fix this for 2.5.0, but didn't have time. We'll get to it.

**Comment by jrogstad** [comment]
Just curious if you guys still anticipate this to be fixed in next release.  Are there any recommended workarounds?

**Comment by dnkoutso** [comment]
Use a custom transformation to apply the rotation yourself?

**Comment by cbruegg** [comment]
This also bit me today. As integrated support for OkHttp 3 is also missing from 2.5.2, I've switched to the 2.5.3-SNAPSHOT release, which includes this fix.
Simply add the repository "https://oss.sonatype.org/content/repositories/snapshots" and change "2.5.2" to "2.5.3-SNAPSHOT" in your build system of choice. I hope the official release of 2.5.3 is coming soon..
