### ISSUE TITLE
Updating cached image

### ISSUE THREAD

**Issue by booker0108** [square/picasso#879]
I have loaded an image from URL_A and it is automatically cached.

However, I tried to replace the image on URL_A and Picasso is not updating the image from the same URL.

Is there any setting for this function?

Thanks!

**Comment by booker0108** [comment]
Using Okhttp solved my problem

**Comment by hotchemi** [comment]
Have you tried `Picasso.invalidate(String path)`? May #438 helps you.

**Comment by JakeWharton** [comment]
Yep. Use `invalidate` or the cache control when the image changes. Otherwise, normal HTTP caching header semantics apply. In general, it's easier to use a new file name than bother with all of these things.
