### ISSUE TITLE
Image loading error in the absence of http: or https:

### ISSUE THREAD

**Issue by harshvishu** [square/picasso#880]
Image loading error when using URL like :"//i.imgur.com/rAJbCoVb.jpg"
I am using Picasso to load images from multiple websites and sometimes JSON response doesn't contain protocol.

**Comment by JakeWharton** [comment]
Picasso uses the scheme to determine how to load the image. If it's not
http or https then how is it supposed to know to use the internet?
Furthermore, since Picasso has no scheme it cannot load the image
implicitly like a browser would.

**Comment by JakeWharton** [comment]
Parse the URL with the Uri class and add either the http or https scheme.

**Comment by harshvishu** [comment]
Thanks for the help.

**Comment by prashantwosti** [comment]
Picasso.with(this).load(Uri.parse("http://image.tmdb.org/t/p/w300/pbEpUO80POIbER8M18Z0wEyIGAv.jpg")).into(mImageViewTest);

still not loading.
