### ISSUE TITLE
Picasso not loading some images when using fit()

### ISSUE THREAD

**Issue by yychun1217** [square/picasso#881]
I am using Picasso (Version: 2.5.0) for my project. In my listView, there are images to be loaded from online. I used fit() & centerInside() to resize my images. Most of the images are loaded successfully, while a few get an error. I have checked that the url contains no special characters, and they are of acceptable length.

My code is as below:
Picasso.with(mContext) 
.load(UrlEncoder.encode(interiorDesign.getBrand_image_url())) 
.config(Bitmap.Config.RGB_565)
.error(R.drawable.blank)
.fit() 
.centerInside() 
.into(holder.brand); 

In fact, I encounter the same problem when using fit() & centerCrop().

For your reference, Here is my question in Stackoverflow.
Here: http://stackoverflow.com/questions/28426468/picasso-cannot-load-images-for-some-url-no-special-characters?noredirect=1#comment45189039_28426468

**Comment by dnkoutso** [comment]
Known issue: https://github.com/square/picasso/issues/465 will be fixed in 2.5.1.

**Comment by andrejvanderzee** [comment]
Looks like same issue I am seeing with large images:

02-28 22:17:02.152    6367-6367/com.fansz.prestaging E/FanszApplication﹕ http://staging.assets.fansz.com/uploads/f92/c/234b40c5bd9346818f2f7f0e9726cf92/img_20150227_150634.jpg
    java.io.IOException: Cannot reset
            at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
            at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by dnkoutso** [comment]
We are on it. thanks for the report.

**Comment by andrejvanderzee** [comment]
Thanks for your fast (!) reply. Is there anything to say about when 1.5.1 will be out? Will that be days, weeks or months? 

Is there a snapshot release with fix available?

**Comment by dnkoutso** [comment]
We do not plan for releases, they just happen. If you want me to guess it would be 2 weeks from now but no guarantees.

In the meantime, while it sucks, you can fork the library and increase the `65536` marker in NetworkRequestHandler to something bigger.

We are working on this since its our biggest bug at the moment.

**Comment by andrejvanderzee** [comment]
Thanks a lot, this temporarily fix looks to work fine :)

**Comment by alemedero** [comment]
Any news about this bug? Thanks in advance.

**Comment by dnkoutso** [comment]
Sorry none yet. But we will get to it.

**Comment by JakeWharton** [comment]
Dupe #364.
