### ISSUE TITLE
Does disc cache expire?

### ISSUE THREAD

**Issue by jaydeep17** [square/picasso#883]
I download like a 100 images, close the app re-run it the images get displayed even without internet connectivity. But after a few hours, it re-downloads the images.

So my question is, "does picasso disc cache expire after a few hours?".

If yes, I'd like it to know how to retain it.

**Comment by JakeWharton** [comment]
Picasso has no disk cache. You are seeing the behavior of whichever HTTP client is being used and it is completely transparent to Picasso. Caching in the HTTP client depends on a bunch of rules which are specified by multiple headers in the HTTP response. There's a long but informative site on these headers [here](http://www.mobify.com/blog/beginners-guide-to-http-cache-headers/). It sounds like the cache headers of whatever images you are downloading only allow the HTTP client that is being used by Picasso to retain the images for a few hours.
