### ISSUE TITLE
Callback not called when image is from memory cache

### ISSUE THREAD

**Issue by Queatz** [square/picasso#884]
This works:
```java
Picasso.with(mContext).load(url).noPlaceholder().noFade().skipMemoryCache().into(i, callback)
```

This doesn't:
```java
Picasso.with(mContext).load(url).noPlaceholder().noFade().into(i, callback)
```

The `callback` should be called no matter where the image is loaded from.  Lost half a day tracking this down, please look into it!

**Comment by dnkoutso** [comment]
![screen shot 2015-02-11 at 8 39 30 pm](https://cloud.githubusercontent.com/assets/310370/6161920/207b99c2-b22e-11e4-8a39-0e313b73b71e.png)

Just updated sample app and it works fine. The callback is invoked for both NETWORK/DISK or MEMORY loading.

**Comment by dnkoutso** [comment]
Can you be more specific? What version of Picasso? Are you canceling the request at all?

**Comment by Queatz** [comment]
Latest Picasso.  I am cancelling the request under certain circumstances, it's kinda complex.  I think it might be a race condition and loading from memory happens faster.  Looking more into it, will close this issue if it's not a Picasso one.

**Comment by Queatz** [comment]
Was a race condition on my end, closing.  Sorry about that!

**Comment by dnkoutso** [comment]
No worries!
