### ISSUE TITLE
Image flickers when I scroll up once image is loaded.

### ISSUE THREAD

**Issue by bhupendra-nitt** [square/picasso#888]
Picasso works just fine only issue I am facing is while I scroll down the listview and when again I scroll up, the images are not there. If image was already loaded it should not flicker, but it does. How to overcome this?

**Comment by crispi7** [comment]
I'm not sure but I think that is the listview implementation. To save memory listview "delete" views that are not visible

**Comment by bhupendra-nitt** [comment]
Picasso caches the images and that can be used later. That works just fine. But when i am scrolling up, placeholder is visible first and after that the image comes.

**Comment by crispi7** [comment]
Thats normal, the placeholder is created before the Picasso.load(). Maybe you have some heavy conde that lets you see the transition. Please post your code, I can not reproduce this

**Comment by bhupendra-nitt** [comment]
public class ContactAdapter extends ArrayAdapter<Contact> {

    List<Contact> contactList;
    LayoutInflater vi;
    int Resource;
    ViewHolder holder;
 



    class ViewHolder {

        public ImageView imageview;
        public TextView firstName;
        public  TextView lastName;
        public TextView location;
        public TextView status;

    }


    public ContactAdapter(Context context, int resource, List<Contact> objects) {
        super(context, resource, objects);
        vi = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        Resource = resource;
        contactList = objects;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View v = convertView;

        if (convertView == null) {
            holder = new ViewHolder();
            v = vi.inflate(Resource, null);
            holder.imageview = null;
            holder.imageview = (ImageView) v.findViewById(R.id.imageView);
     //       Picasso.with(getContext()).load(contactList.get(position).getAvatar_profile()).placeholder(R.drawable.ic_launcher).into(holder.imageview);

            holder.firstName = (TextView) v.findViewById(R.id.firstName);
            holder.lastName = (TextView) v.findViewById(R.id.lastName);
            holder.location = (TextView) v.findViewById(R.id.location);
            holder.status = (TextView) v.findViewById(R.id.Status);
            v.setTag(holder);
        } else {
            holder = (ViewHolder) v.getTag();
        }


        holder.imageview.setImageResource(R.drawable.ic_launcher);
        Picasso pic = Picasso.with(getContext());
        pic.setIndicatorsEnabled(true);
        String url = contactList.get(position).getAvatar_profile();
        pic.load(url).placeholder(R.drawable.ic_launcher).into(holder.imageview);
        holder.firstName.setText(contactList.get(position).getFirst_name());
        holder.lastName.setText(contactList.get(position).getLast_name());
        holder.location.setText(contactList.get(position).getLocation());
        holder.status.setText(contactList.get(position).getLocation());
        return v;
    }
}

This is my adapter.

**Comment by dnkoutso** [comment]
Please paste some URLs you are downloading. You are also not using `fit()` for some reason.

**Comment by AdamCopperfield** [comment]
Yes, it is the ListView implementation, but how some giants, e.g Facebook app, avoid image flickers in their feed?

**Comment by bhupendra-nitt** [comment]
I am used LruDiskCache it resolved the issue and then I used volley for caching image, it also solved my problem. Using Picasoo with Retrofit may solve problem too.
