### ISSUE TITLE
result.getBitmap() returns null in 2.5.0

### ISSUE THREAD

**Issue by tomrozb** [square/picasso#890]
I was using custom `NetworkRequestHandler` implementation with 2.4.0 and everything worked fine. I've updated Picasso to 2.5.0 (also removed `okhttp-urlconnection`) and noticed that sometimes `result.getBitmap()` returns null. The image loads without any problems in browser, if you try load it once again with Picasso it loads successfully in most cases. 

I've reverted to 2.4.0 and this bug doesn't occur so it seems the problem has been introduced in 2.5.0.

Below are my dependencies. It doesn't matter if I include `okhttp-urlconnection` or not. 
```
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
    compile 'com.squareup.picasso:picasso:2.5.0'
```

I'm overriding `load` method in custom request handler. The `result` value is obtained from `NetworkRequestHandler` standard implementation using `super`
```
Result result = super.load(data, network);
```

As I mentioned for some requests the result contains no bitmap (null). Has anyone noticed this bug?

**Comment by JakeWharton** [comment]
Use the `InputStream` method instead.

**Comment by tomrozb** [comment]
Ok I've changed the code to use `getStream` when `getBitmap` returns null. What's the problem now loading image fails sometimes with "Failed to decode stream" message. The image is perfectly fine, I'm sure about this. 

```
12:44:19.291                         E  java.io.IOException: Failed to decode stream.                                                                             
12:44:19.291                         E      at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)                                                                           
12:44:19.291                         E      at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)                                                                                   
12:44:19.291                         E      at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)                                                                                    
12:44:19.291                         E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)                                                                         
12:44:19.291                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)                                                                                        
12:44:19.291                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)                                                                 
12:44:19.291                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)                                                                 
12:44:19.291                         E      at java.lang.Thread.run(Thread.java:818)                                                                                                           
12:44:19.291                         E      at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)
```

**Comment by dnkoutso** [comment]
Whats the URL? Can you paste more code ?

**Comment by tomrozb** [comment]
The image is served using servingUrl obtained from Images API for AppEngine. I cannot post any particular URL but I think you can use any photo from Google+

The code I'm using:
```
Bitmap bitmap = result.getBitmap();
if (bitmap == null) {
    ByteStreams.copy(result.getStream(), fileOutputStream);
} else {
    bitmap.compress(CompressFormat.WEBP, 100, fileOutputStream);
}
fileOutputStream.flush();
fileOutputStream.close();
```

This issue doesn't occur in 2.4.0 (code is the same, except the if statement). As I mentioned the image is perfectly served using browser or when you retry to load it with Picasso. I've noticed that this occurs when loading multiple images at the same time. I'm using it to load images in `ListView` and it happens when you scroll very fast through the list.

**Comment by tomrozb** [comment]
Can you reopen this issue or I have to report it as a new one? The problem with `java.io.IOException: Failed to decode stream` is worth investigation IMHO.

**Comment by JakeWharton** [comment]
Please provide a concrete URL or sample app to reproduce. We do not have the time to chase down images to try and reproduce your error.

**Comment by dnkoutso** [comment]
Please reopen issue with a concrete URL for us to work with. This is not enough information to debug.
