### ISSUE TITLE
Picasso.invalidate(filepath) and Picasso.invalidate(new File(filepath)) should do the same

### ISSUE THREAD

**Issue by Nodjo** [square/picasso#898]
If an image is loaded with a File, and we want to invalidate it because it has changed, we must provide a File object as the parameter when calling Picasso.invalidate(), when I'd expect providing the filepath (as a String) would work.

This is caused by the fact that when Picasso is given a filepath (as a String), it will create a key in the form"uri:file:///[filepath]", but when it is given a File, it will create a key in the form "uri:/[filepath]".

I feel that the key should be the same in both cases, because i can't see how *filepath* and *new File(filepath)* could be two different assets.

**Comment by JakeWharton** [comment]
They might point to the same object when the Uri is resolved but they are different Uris and Picasso deals only in Uris. If you are interacting with files, make sure you use one of the two consistently.

Why are you mixing between the two?

**Comment by Nodjo** [comment]
I just happened to mix them, there's no real reason for that. The load() and the invalidate() are in different places in the app.

I get that Picasso only works with Uris and it does make sense. It's just counter intuitive that load(String filepath) and load(new File()) won't have the same key. Indeed, I'll make sure to use them consistently now

**Comment by JakeWharton** [comment]
How are you getting your string paths? Just calling `.getAbsolutePath()`?

**Comment by Nodjo** [comment]
Basically, I have a MainActivity which shows a set of thumbnails, each thumbnail represents a different "world" and when the user clicks a thumbnail, it'll launch the WorldActivity with the corresponding worldId provided in the extra.

If the user never entered a world, the thumbnail shows that world's default picture. Once he's opened it, then when he presses back, a screenshot is taken just before closing WorldActivity. This screenshot is then downscaled and used inside the thumbnail in replacement of the default picture.

Saving the screenshot on the disk is done asynchronously and we also store the filepath to that screenshot. To do that, a filepath is built (so that there's one unique filepath for each world as each world may have its screenshot), then I call a utility method to save the bitmap as a file with that filepath. Finally, I need to invalidate a possible previous screenshot in Picasso's cache. At that point, I had a handle on both the filepath and the File, but I happened to call:

Picasso.with(context).invalidate(filepath);

(I've fixed that and now I do provide the File here)

Now, when loading this screenshot in MainActivity, even if I have a filepath for a certain service, it might happen that the file is deleted or unaccessible (it's stored on the external storage) so before asking Picasso to try to load that screenshot, I just check if the file seems available :

            final File file = TextUtils.isEmpty(imagePath) ? null : new File(imagePath);
            if (file != null && file.exists() && file.canRead()) {
                //Load that screenshot file
               Picasso.load(file).(...);
            } else {
                //Load the default world preview
            }

I happen to provided the File here rather than the filepath as I've had to create it to ensure it could be read.

**Comment by miscoder** [comment]
i had the same problem , loading a file and invalidating with the same file solved the problem .
