### ISSUE TITLE
Annotate resize(int, int) with @Px

### ISSUE THREAD

**Issue by dbarwacz** [square/picasso#903]
I'm aware this is more of a useful feature rather than bug. There is resizeDimen(int,int) but when I made a mistake and called resize(R.dimen,R.dimen) Picasso fails to load image. Is there an option to supply @DimenRes to arguments or any other way of checking in Runtime that input is too big and then throwing IllegalArgumentException?

**Comment by JakeWharton** [comment]
Blocked by #876.

**Comment by JakeWharton** [comment]
Blocked by support-annotations v24 release.

**Comment by hzsweers** [comment]
Does this have to block the 2.6 release? Seems like the timetable for v24 would be when N is released, which might be months away still

**Comment by JakeWharton** [comment]
It's not blocking the release. The issue itself is blocked by their
release. Based on the velocity of 2.6... I dare say they might win.
