### ISSUE TITLE
Wrong cropping when loading image in onStart related to rotation/orientation change

### ISSUE THREAD

**Issue by TommyVisic** [square/picasso#905]
Possibly related to #875?

Image cropped incorrectly if loaded in Activity.onStart(), and if returning to the activity such that a orientation change occurs. E.g. given Activity A is forced to *portrait* mode via manifest and Activity B is forced to *landscape* mode via manifest, and Activity A shows an image, if user goes to A, then to B, then backs to A, the image will not be cropped as expected.

```
@Override
    protected void onStart() {
        super.onStart();

        Picasso.with(this).load(R.drawable.sample).fit().centerCrop().into(imageView);
    }
```

First start of Activity A (shows expected results):
![1](https://cloud.githubusercontent.com/assets/3027722/6377299/e4990578-bce8-11e4-8b95-c71686743025.png)

Returning to Activity A from B:
![2](https://cloud.githubusercontent.com/assets/3027722/6377290/d2dcd558-bce8-11e4-93df-4df9654fd3f6.png)

In my case, Activity A shows an image that can change based on state from some business component, so it felt natural to check this state in onStart and load the image there rather than in onCreate. Moving the Picasso call to onCreate does indeed fix the issue. It remains fixed even if I turn on "Don't keep activities" in developer options.

I'm guessing that the the ImageView is measuring itself while still in landscape mode from the previous activity? Since I'm using fit() and Picasso is in differed mode, it sees this measure and thinks it can use the landscape dimensions and sets/loads the image to the ImageView. Then when the activity goes to portrait mode, the ImageView resizes itself.

On Nexus 5 with Lollipop (5.01).

**Comment by dnkoutso** [comment]
fit() will check if the imageview already has a width and height before waiting on them. If they are calculated then the request is executed as normal.

I do not think this is a Picasso issue.
