### ISSUE TITLE
Error on Moto E only in 2.5.0

### ISSUE THREAD

**Issue by DineshAnandan** [square/picasso#906]
Hi,

Am using this line to load image 

Picasso.with(this).load(file).resize(0, 600).into(image_view, picasso_callback);

It's works fine in some device like nexus 6. But onError method called in MOTO E devices. If i use 2.4.0 jar then there is no problem. It appears only in 2.5.0

**Comment by jacobtabak** [comment]
What exception?

**Comment by dnkoutso** [comment]
Please provide more info

**Comment by DineshAnandan** [comment]
@dnkoutso @jacobtabak  There is no trace in logcat. Just onError method called in picasso callback.

**Comment by jacobtabak** [comment]
You can set a global error callback on your Picasso instance that will tell
you the error.

**Comment by dnkoutso** [comment]
`picasso.setListener(new Listener() { exception.printStackTrace() }`

**Comment by DineshAnandan** [comment]
`02-27 11:01:41.368: W/System.err(10613): java.io.IOException: Cannot reset
02-27 11:01:41.376: W/System.err(10613): 	at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
02-27 11:01:41.379: W/System.err(10613): 	at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
02-27 11:01:41.381: W/System.err(10613): 	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
02-27 11:01:41.383: W/System.err(10613): 	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
02-27 11:01:41.385: W/System.err(10613): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-27 11:01:41.386: W/System.err(10613): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-27 11:01:41.386: W/System.err(10613): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-27 11:01:41.387: W/System.err(10613): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-27 11:01:41.387: W/System.err(10613): 	at java.lang.Thread.run(Thread.java:841)
02-27 11:01:41.388: W/System.err(10613): 	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)`

**Comment by JakeWharton** [comment]
The bane of my existence

**Comment by jacobtabak** [comment]
This is new in 2.5, we had same problem, reverted, and it was resolved.
Don't have a device to track down what it is specifically, but so far it
happens on moto e and moto x.

**Comment by dnkoutso** [comment]
Known issue, and dup marked for 2.5.1.

**Comment by dp-singh** [comment]
Is there any way to sort out this issue?

**Comment by dnkoutso** [comment]
Dup of #907

**Comment by dnkoutso** [comment]
`BitmapHunter` extend the mark from 65535 to something higher for now. Its unfortunate you have to fork the library for this.

**Comment by skhaz** [comment]
Bump.

**Comment by dp-singh** [comment]
Is there any modification about this thing in the 2.5.2 version?
