### ISSUE TITLE
Picasso 2.5.0 does not display big images

### ISSUE THREAD

**Issue by darzul** [square/picasso#907]
Hello,

I have some heavy pictures, about 10Mo for each one. On Picasso 2.4.0 there is no problems to display them, but with Picasso 2.5.0 any pictures are displayed.

Here is how I display the pictures: 

mPicasso.load(file)
               .error(R.drawable.ic_launcher)
               .resize(mScreenWidth, 0)
               .into(iv);

Here are the log for one image:

D/Picasso﹕ Main        created      [R5] Request{file:///storage/emulated/0/Pictures/Weekend en Corse/DSC_0008.JPG resize(1080,0)}
D/Picasso﹕ Dispatcher  enqueued     [R5]+34ms
D/Picasso﹕ Dispatcher  enqueued     [R5]+32ms
D/Picasso﹕ Dispatcher  batched        [R5]+556ms for error
D/Picasso﹕ Main           errored         [R5]+748ms
D/Picasso﹕ Dispatcher  delivered      [R5]+766ms

I have another set of pictures which are more little and there is no problem on Picasso 2.5.0 (3Mo per picture).

Here is a picture impossible to display:

![dsc_0110](https://cloud.githubusercontent.com/assets/4621928/6416784/0ee589a2-bea9-11e4-9604-f49b4071c2cc.JPG)

**Comment by dnkoutso** [comment]
Attach a listener please, `picasso.setListener(new Listener() { exception .printStackTrace() }`

**Comment by darzul** [comment]
Could you be more specific please ?

I don't find setListener() method

**Comment by dnkoutso** [comment]
Apologies, I wrote this rather quickly:

```java
Picasso picasso = new Picasso.Builder(context).listener(new Picasso.Listener() {
      @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
        exception.printStackTrace();
      }
    }).build();
```

Then use that instance for the loading part instead.

**Comment by darzul** [comment]
W/System.err﹕ java.io.IOException: Cannot reset
W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)
W/System.err﹕ java.io.IOException: Cannot reset
W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)

**Comment by dnkoutso** [comment]
Ouch. This keeps coming up. Known issue and will be fixed in 2.5.1.

Please use 2.4.0 for now, I apologize for this problem, we will fix it.

**Comment by darzul** [comment]
Ok thanks for your quick answers :) and for your very useful libs !

**Comment by JakeWharton** [comment]
Dupe #364.
