### ISSUE TITLE
Image flicker in adapter after onResume and notifyDataSetChanged.

### ISSUE THREAD

**Issue by matthew-reilly** [square/picasso#914]
Have a pretty basic adapter for a list view. It seems whenever the fragment is resumed and notifyDataSetChanged is called, the images all change from in-memory to disk resources. Confirmed via the triangle indicators. During this a short flicker is seen for every image in the list.

This only happens when the fragment is resumed *and* the necessary images are no longer in memory. 

Is this the expected behavior?

``` @Override
    public View getView(int index, View convertView, ViewGroup arg2) {
        ViewHolder holder;
        if (convertView == null) {
            LayoutInflater inflater = (LayoutInflater) getContext()
                    .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            convertView = inflater.inflate(R.layout.row_person, null, false);
            holder = new ViewHolder();
            holder.icon = (ImageView) convertView.findViewById(R.id.icon);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }

        Picasso.with(getContext())
                .load(match.subject.getMainPicture())
                .into(holder.icon);

        return convertView;
    }

```

**Comment by JakeWharton** [comment]
Yes. The `Bitmap` instances were expunged from the memory cache due to the LRU policy and they are reloading from disk. Since the load from disk takes multiple frames and cannot be done synchronously we fade them in when they complete (in batches of ~200ms).

**Comment by legentz** [comment]
So, there's no way to avoid this flickering? 
What is the best solution to load different and large images inserted into a Stack without stressing RAM (loaded one after another)? How Picasso can grant me that when i remove the element from the adapter image will be recycled? 
Obviously if I use NO_STORE as MemoryPolicy option each time notifydatasetchanged or requestlayout (etc..) image flickering appears. Maybe you have a suggestion! 

I understand that these are a kind a noob questions but i need to remove all my doubts :)
Thanks.

**Comment by masiha68** [comment]
is there nobody  help us?

**Comment by legentz** [comment]
@masiha68 which MemoryPolicy are you using? Explain your setup and situation, please...

**Comment by masiha68** [comment]
i just use picasso and recyclerView and cardView together
and when recyclerView are in scrolling text get flickered ...
3 day i am searching for solution and i found when image size undefined flickring happens
but i don't know how i can set image size when image are downloaded from server and have different size
//sorry for my bad english //

**Comment by masiha68** [comment]
it is my solution  ...but does not work 
` public static void setImage( final ImageView imageView,String url)
    {

        Picasso.with(context).load(url).into(new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                 w = bitmap.getWidth();
                  h = bitmap.getHeight();
                Log.i("log","w and h "+w+""+h);
               // imageView.setImageBitmap(bitmap);
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable) {

            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {

            }


        });
        imageView.requestLayout();

        imageView.getLayoutParams().width= size.toDp(w);
        imageView.getLayoutParams().height= size.toDp(h);
       
        Picasso.with(G.context)
                .load(url).placeholder(R.drawable.avatar)
                .error(R.drawable.remove)
                .noFade()
                .into(imageView);
     
    }`

**Comment by legentz** [comment]
Why do you need custom trasformation (i mean the new Target() callback) ?!
Why don't you try a simpler thing like this:

```
Picasso.with(context)
  .load(url)
  .resize(50, 50) // Your preferred size
  .centerCrop()
  .into(imageView)
```
Also, why are you calling Picasso.with(...) 2 times? I don't get it :/

**Comment by masiha68** [comment]
i wanna to set size for imageView before set image and i get image size by
Picasso.with(context).load(url).into(new Target() {
        @Override
        public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
             w = bitmap.getWidth();
              h = bitmap.getHeight();
            Log.i("log","w and h "+w+""+h);
           // imageView.setImageBitmap(bitmap);
        }
        @Override
        public void onBitmapFailed(Drawable errorDrawable) {
        }
        @Override
        public void onPrepareLoad(Drawable placeHolderDrawable) {
        }
    });

**Comment by legentz** [comment]
Do you want to set container's size or of the image itself?
What result do you obtain using the code i showed you above?

**Comment by masiha68** [comment]
resize is not a good idea ...because same time image are very small or very large 
` What result do you obtain using the code i showed you above?`
it solved my problem with flicked but image small

**Comment by legentz** [comment]
```
Picasso.with(context)
  .load(url)
  .resize(50, 50) // Your preferred size
  .centerCrop()
  .into(imageView)
```
So, this code above solved your flickering problem. Good! Now your image's small...
Did you try to change **resize(50, 50)** ? If yes, do you mean that's the container your problem?

**Comment by masiha68** [comment]
resize value are ox or dp or % ?

**Comment by legentz** [comment]
> **public Request.Builder resize(int targetWidth, int targetHeight)**
> Resize the image to the specified size in pixels. Use 0 as desired dimension to resize keeping aspect ratio.

**Comment by legentz** [comment]
[https://square.github.io/picasso/2.x/picasso/](https://square.github.io/picasso/2.x/picasso/)

That's the doc!

**Comment by masiha68** [comment]
resize are worked and i set resize(400,300) and another value 120 ,200 , ....
but my problem is image size undefined ...when images are very small how i can set resize ?
