### ISSUE TITLE
Upgrade from 2.4.0 to 2.5.0 broke fit()

### ISSUE THREAD

**Issue by kmadsen** [square/picasso#915]
This code didn't change, but upgrading from to 2.5.0 makes it so this image will not view. Removing fit() will make it work.

File file = new File(path);
picasso
  .load(file)
  .fit()
  .into(imageView);

<ImageView
  android:id="@+id/image_view"
  android:layout_width="match_parent"
  android:layout_height="match_parent" />

The file must be stored locally:
example path: "/storage/emulated/0/Android/data/example.com/cache/photo_tmp.jpg"

More notables: 
using .load(R.raw.photo_tmp) works as expected
other photos with the exact same path are working as expected
reproduced on Moto G 4.4.4 and Moto X 4.4.4

Image source is from the Moto G back camera

![photo_tmp](https://cloud.githubusercontent.com/assets/3021882/6453496/753707fc-c0f3-11e4-9003-9fefc1a04b3d.jpg)

**Comment by dnkoutso** [comment]
Are you sure this is not MarkableInputSTream error?

See this: https://github.com/square/picasso/issues/907

We are working on it.

**Comment by kmadsen** [comment]
Looks like this is probably the same issue. Should I close it or would it be useful?

Here is the output with debugging:
D/Picasso﹕ Main        created      [R10] Request{file:///storage/emulated/0/Android/data/example.com/cache/photo_tmp.jpg resize(720,1134) centerInside}
D/Picasso﹕ Hunter      executing    [R10]+11ms
D/Picasso﹕ Dispatcher  enqueued     [R10]+11ms
D/Picasso﹕ Dispatcher  batched      [R10]+520ms for error
D/Picasso﹕ Main        errored      [R10]+722ms
D/Picasso﹕ Dispatcher  delivered    [R10]+722ms

**Comment by kmadsen** [comment]
Yeah, followed your directions from the other issue and get the same MarkableInputStream stack trace.
