### ISSUE TITLE
PicassoExecutorService based on availableProcessors

### ISSUE THREAD

**Issue by Macarse** [square/picasso#917]
Not an issue, just a question:

Is there a reason why `PicassoExecutorService` (https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/PicassoExecutorService.java) hardcodes the number of threads instead of using something like `Runtime.getRuntime().availableProcessors()`?

**Comment by JakeWharton** [comment]
It's not doing CPU-bound work.

**Comment by Macarse** [comment]
Yes, I was thinking if there was a better way of handling this logic making it more device specific.

**Comment by JakeWharton** [comment]
It has nothing to do with the device and all to do with the network
connectivity.

**Comment by Macarse** [comment]
Ok
