### ISSUE TITLE
Picasso not loading image from local file

### ISSUE THREAD

**Issue by sd6352051** [square/picasso#920]
Here is the local file path
/storage/emulated/0/xxxxx/1425879337987.jpg

Here is the code
Picasso.with(getContext()).load(new File(local file path)).into(mImageView);

i use picasso 2.5.0

**Comment by vuhung3990** [comment]
you can view image by other app, example: this file mayble a text file but rename to "text.jpg"

**Comment by sd6352051** [comment]
@vuhung3990 this path from my gallery

**Comment by vuhung3990** [comment]
@sd6352051 it work perfect, good luck: <pre>Picasso.with(context).load("file://"+path).config(Bitmap.Config.RGB_565).fit().centerCrop().into(imageView);</pre>

**Comment by sd6352051** [comment]
@vuhung3990 you are right,thanks,but i use load(new File(local file path)) not worked.

**Comment by sd6352051** [comment]
@vuhung3990 hi 

its worked
Picasso.with(context).load("file://"+path).config(Bitmap.Config.RGB_565).fit().centerCrop().into(imageView);

its not worked
Picasso.with(context).load("file://"+path).config(Bitmap.Config.RGB_565).centerCrop().into(imageView);
Why is that？

**Comment by vuhung3990** [comment]
here is answer of author: http://stackoverflow.com/questions/20823249/resize-image-to-full-width-and-fixed-height-with-picasso

**Comment by valterh4ck3r** [comment]
Very Thanks  @vuhung3990  !
