### ISSUE TITLE
Debugging indicators are not shown when using a custom ImageView

### ISSUE THREAD

**Issue by osrl** [square/picasso#925]
With custom ImageViews (like [RoundedImageView](https://github.com/vinc3m1/RoundedImageView/)) indicators are not visible.

**Comment by JakeWharton** [comment]
Dupe #791.

**Comment by osrl** [comment]
Hello @JakeWharton. I saw  #791. But even if I don't round the corners, the result is still the same. Is it still related to the issue?

**Comment by JakeWharton** [comment]
The indicator is applied to the `Drawable` which is set on the view. As long as it's a subclass of `ImageView` it'll work. It does not work on `Target.

**Comment by osrl** [comment]
My problem was `center_crop`. Thanks for pointing
