### ISSUE TITLE
Getting "No address associated with hostname" inconsistently on same image

### ISSUE THREAD

**Issue by Svantulden** [square/picasso#926]
Hi, 

Sometimes (seems random) I'm getting an error on loading an image with Picasso. The error image gets shown and when using `onImageLoadFailed` to debug the error message, I'm getting: 
```
W/System.err﹕ java.net.UnknownHostException: Unable to resolve host "cdn.route.nl": No address associated with hostname
W/System.err﹕ at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
W/System.err﹕ at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
W/System.err﹕ at java.net.InetAddress.getAllByName(InetAddress.java:215)
W/System.err﹕ at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
W/System.err﹕ at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
W/System.err﹕ at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
W/System.err﹕ at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:93)
W/System.err﹕ at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)
```

The weird thing is, when I restart the app and load the same image again (I double checked that it has the same URL), it loads correctly like nothing is wrong. I am using Lollipop (also `compileSdkVersion 21` & `targetSdkVersion 21`) on a Nexus 5 with Picasso `2.5.0`. This happens pretty randomly. 

For the code that I am using to load the image: 
```Java
Picasso picasso = new Picasso.Builder(getActivity()).listener(new Picasso.Listener() {
            @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                Log.d("IMAGE FAILED", "ERROR: "+exception.getMessage());
                exception.printStackTrace();
            }
        }).build();
        picasso.load(mRouteMapString).placeholder(R.drawable.ic_maploading).error(R.drawable.ic_noimage).into(mRouteImageView);
```

The [image in question](http://cdn.route.nl/routemaps/app/133.png) is stored at Amazon S3. Do you have any idea what can cause this error? 

When I searched for the problem, the only solution I found was setting internet permissions in the manifest, but these are already there in my application (I'm making several calls until I get to the image in question)

**Comment by JakeWharton** [comment]
This happens entirely below Picasso. We know nothing about the mechanism through which URLs undergo DNS lookup let alone anything with the HTTP client (we just make a request). It's completely transparent to us.

Try including the OkHttp 2.2.0 jar standalone in your app (with the latest Picasso).

Other than that, please ask this question on StackOverflow with the 'picasso' tag. It's not strictly an issue with Picasso but rather an issue with the Android OS that you happen to observe while using Picasso.

**Comment by Svantulden** [comment]
Apologies, did not know you used OkHttp to handle the networking. It seemed to me it was an issue with Picasso as the problem occurred when I switched to lollipop and version 2.5.0. 

In the end I heard from the IT department that we had some internet malfunctions which caused the DNS server to spazz.

**Comment by vishal901** [comment]
W/System.err( 1689): java.net.UnknownHostException: Unable to resolve host : No address associated with hostname

this is not issue for picasso lib.

actual issue are in image url like...

http:www.ancd.com/abc.png (server url not coming // please check )

replace
http://www.ancd.com/abc.png

i solve this issue.
