### ISSUE TITLE
how to fix this??

### ISSUE THREAD

**Issue by iceAnson** [square/picasso#928]
[CDS]EAGAIN or EWOULDBLOCK in Recvfrom
03-16 17:40:37.707  27986-28194/com.lingan.seeyou I/System.out﹕ [CDS]read byte is 0
03-16 17:40:37.708  27986-28194/com.lingan.seeyou W/System.err﹕ java.net.SocketTimeoutException
03-16 17:40:37.710  27986-28194/com.lingan.seeyou W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:495)
03-16 17:40:37.710  27986-28194/com.lingan.seeyou W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
03-16 17:40:37.711  27986-28194/com.lingan.seeyou W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
03-16 17:40:37.711  27986-28194/com.lingan.seeyou W/System.err﹕ at okio.Okio$2.read(Okio.java:136)
03-16 17:40:37.711  27986-28194/com.lingan.seeyou W/System.err﹕ at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
03-16 17:40:37.711  27986-28194/com.lingan.seeyou W/System.err﹕ at okio.RealBufferedSource.indexOf(RealBufferedSource.java:244)
03-16 17:40:37.711  27986-28194/com.lingan.seeyou W/System.err﹕ at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:191)
03-16 17:40:37.712  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:187)
03-16 17:40:37.712  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:78)
03-16 17:40:37.712  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:665)
03-16 17:40:37.712  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.Call.getResponse(Call.java:240)
03-16 17:40:37.712  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.Call.execute(Call.java:84)
03-16 17:40:37.712  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:116)
03-16 17:40:37.713  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
03-16 17:40:37.713  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:216)
03-16 17:40:37.713  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:162)
03-16 17:40:37.713  27986-28194/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
03-16 17:40:37.713  27986-28194/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
03-16 17:40:37.714  27986-28194/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
03-16 17:40:37.714  27986-28194/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
03-16 17:40:37.714  27986-28194/com.lingan.seeyou W/System.err﹕ at java.lang.Thread.run(Thread.java:838)
03-16 17:40:37.714  27986-28194/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:391)

**Comment by JakeWharton** [comment]
Socket timeouts are caused by slow, broken, or failing connections to the remote host. Picasso will retry the request up to three times, otherwise the image won't be able to be loaded. This is a problem with the network, not Picasso.
