### ISSUE TITLE
Picasso image loading limit

### ISSUE THREAD

**Issue by Chiniga** [square/picasso#934]
Good Day!

I would like to ask if Picasso has a limit as to how many images it can load simultaneously. Thank you!

**Comment by JakeWharton** [comment]
2 on 2G, 3 on 3G, 4 on 4G, 5 on Wi-Fi

**Comment by JakeWharton** [comment]
You can supply your own Executor to Picasso.Builder if you want to change
this behavior.

**Comment by Chiniga** [comment]
How about locally stored images? Thank you very much!

**Comment by JakeWharton** [comment]
It's the same. We don't distinguish remote vs. local images.

**Comment by Chiniga** [comment]
Okay. Thank you very much for the response!
