### ISSUE TITLE
Intermittent segfauls 

### ISSUE THREAD

**Issue by gumballhead** [square/picasso#938]
Every once in awhile, my app will just quit with no error message, but this will show up in the logs:

```
A/libc﹕ @@@ ABORTING: LIBC: ARGUMENT IS INVALID HEAP ADDRESS IN dlfree addr=0x411c6270
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 24227 (Picasso-Dispatc)
```

I seem to be the only one who sees this problem among my coworkers, and I get it pretty regularly. I'm on a first gen Moto X running Jellybean. If there's anything I can do to help track this down, let me know. I know these native errors are tough.

**Comment by gumballhead** [comment]
Just noticed that GC was called right before it, if that helps...

```
D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x000a
D/dalvikvm﹕ GC_CONCURRENT freed 1297K, 30% free 11939K/16992K, paused 2ms+3ms, total 26ms
D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 23ms
D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 16ms
D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 15ms
A/libc﹕ @@@ ABORTING: LIBC: ARGUMENT IS INVALID HEAP ADDRESS IN dlfree addr=0x411c6270
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 24227 (Picasso-Dispatc)
```

**Comment by dnkoutso** [comment]
What version of Picasso? Also did you use 2.5.1? Please try 2.5.2 instead.

**Comment by gumballhead** [comment]
This seems to be our fault. We were using a custom cache that basically wrapped an `LruCache` and a `DiskLruCache` as a common entry point for many types of objects throughout our app. We needed to synchronize all of the methods, which is still kind of a mystery to me because both `LruCache` and `DiskLruCache` are both pretty heavily synchronized. However, it seems to be working fine now.
