### ISSUE TITLE
Circle!

### ISSUE THREAD

**Issue by crysan** [square/picasso#940]
Hi!
Use your library for a long time and was happy with everything. Thank U! 
The question is how to make a round image means Picasso? And if you did, then you can implement this feature?

**Comment by dnkoutso** [comment]
Use a `Transformation` that does that. I found one here: https://gist.github.com/julianshen/5829333

**Comment by crysan** [comment]
Ty!

**Comment by crysan** [comment]
Wait to close. 
Now the background is displayed placeholder:
                        .placeholder(R.drawable.male28)
                        .transform(new CircleTransform())
