### ISSUE TITLE
Load image with custom header(session cookie) without using another client

### ISSUE THREAD

**Issue by KeizerDev** [square/picasso#950]
Hi,

Is it possible to do something like:
``` 
 Picasso.with(getActivity().getApplicationContext())
                .header("session-id", "3412-231...")
                .load("https://example.com/index.php?foo=bar")
                .resize(50, 50).
```
If not is it possible make a custom class for it?
If so where should I make it?

Thanks in advance!

**Comment by JayNewstrom** [comment]
You can do this using a custom downloader (https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/Downloader.java) or using the existing OkHttpDownloader with an Interceptor (https://github.com/square/okhttp/wiki/Interceptors)
