### ISSUE TITLE
Picasso Not displaying cached images after few days

### ISSUE THREAD

**Issue by vikashparajuli** [square/picasso#951]
For this image http://128.199.78.231/symnepal.com/wp-content/uploads/2014/10/chivas.jpg Image is only cached for few days. Any solution for this problem?

**Comment by JakeWharton** [comment]
Picasso caches images in memory for as long as the process is alive and as long as other images don't push it out of the cache. The HTTP client (either Android's or OkHttp) is responsible for disk caching and it will honor the cache headers defined in RFC 2616.

If you want to change the cache headers of an image you can try using [OkHttp's interceptors][1] (you'll have to use a network interceptor to re-write the header). The scope of this is beyond a GitHub issue.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by vikashparajuli** [comment]
can i ignore Cache Headers ?
