### ISSUE TITLE
How to use in an Android JUnit test case

### ISSUE THREAD

**Issue by HughJeffner** [square/picasso#953]
Is there any way to know when all visible images are loaded during a JUnit test?  `getInstrumentation().waitForIdleSync()` does not seem to wait until they are all loaded.

Thanks

**Comment by JakeWharton** [comment]
Not efficiently. We'll add something.

The best thing to do for now is to pass your own `Executor` to `Picasso.Builder`. When the executor becomes empty (i.e., all work is done), sleep for 250 milliseconds and then everything should be ready.

**Comment by HughJeffner** [comment]
Alright will do, thanks for the suggestion.
