### ISSUE TITLE
Latest version 2.5.2

### ISSUE THREAD

**Issue by Ph1b** [square/picasso#955]
I cannot see any release notes on 2.5.1 and 2.5.2.

Also when using like you recomend on the README:

```
compile 'com.squareup.picasso:picasso:2.5.2'
```

That is not found by gradle.

**Comment by JakeWharton** [comment]
Release notes: https://github.com/square/picasso/blob/master/CHANGELOG.md

Proof it's on Maven central: http://search.maven.org/#search%7Cga%7C1%7Cpicasso
