### ISSUE TITLE
Janky RecyclerView Scrolling

### ISSUE THREAD

**Issue by AOrobator** [square/picasso#956]
I'm using Picasso with a custom RequestHandler. My RecycerView list item has 1 ImageView in it and I tell Picasso to fetch the image in onBindViewHolder of my RecyclerView.Adapter. When coming to rest from a fling, my RecyclerView often (not always) attempts to scroll so that instead of a list item being partially visible, it scrolls down until that list item is fully visible.

**Comment by JakeWharton** [comment]
Provide a sample app or send a PR with a demonstration in our sample. We don't have time to guess at your code and try to reproduce your issue.

**Comment by chimuu** [comment]
AOrbator, I'm facing exactly same issue, have you got the solution ?

**Comment by AOrobator** [comment]
No, I ended up reverting back to a ListView. I think it also might've had to do with the fact that I was trying to implement a quick scroller.
