### ISSUE TITLE
Airplane mode warning seen in logcat

### ISSUE THREAD

**Issue by meisteg** [square/picasso#957]
Not a major issue, but when I use Picasso to load an image, I'm seeing this warning in logcat:
```
W/Settings( 9157): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
```

I'm using Picasso 2.5.2 (the latest release as of this writing).

**Comment by JakeWharton** [comment]
We can't link against the newer API, and it's not harmful. We'll fix it eventually.

**Comment by dnkoutso** [comment]
When this ever lands: #https://github.com/square/picasso/pull/876

**Comment by JakeWharton** [comment]
This is unblocked if someone wants a crack at it.
