### ISSUE TITLE
How to figure out the time cost and download size?

### ISSUE THREAD

**Issue by edwardaa** [square/picasso#959]
I want to figure out the quality of the current internet connection, so need to know the time cost and download size per network request, I found maybe the Target is a choice, any suggestion?

**Comment by JakeWharton** [comment]
Your best bet is a custom or subclass of a `Downloader` which has access to the raw HTTP stream and content length. Even better would really be an [OkHttp network interceptor][1] which is inside the HTTP client and would avoid seeing requests from the local disk cache.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by edwardaa** [comment]
thanks :)

**Comment by edwardaa** [comment]
I am using Picasso with OkHttp,  OkHttp Interceptors seem a good way to count network latency rather than downstream bandwidth.
