### ISSUE TITLE
Load part of image 

### ISSUE THREAD

**Issue by wojciechstaniewski** [square/picasso#960]
Hi 
It's possible to load a part (region) of source image using Picasso ? In standard android we have BitmapRegionDecoder and we can use decoder.decodeRegion(new Rect(...)) to create bitmap which is a part of source image.
Thanks for answer

**Comment by JakeWharton** [comment]
Not currently, no.

**Comment by dnkoutso** [comment]
Write a custom request handler or transformation to perform this.
