### ISSUE TITLE
Resize the image i can't change 

### ISSUE THREAD

**Issue by GabrielLiz** [square/picasso#962]
i testing it in Moto G.  i saw the solution  to folk the project and change the MARKER from NetworkBitmapHunter but i dont see that file anymore.. ideas? thanks..

Picasso.with(this) .load(photoUri)  .centerCrop() .resize(photoSize, photoSize) .into(ivPhoto, new Callback() {  @Override
                    public void onSuccess() {
                    }
                    @Override
                    public void onError() {
                  }
                });

 Cannot reset
com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
 com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by JakeWharton** [comment]
The value moved to [here][1]. There's already plenty of issues for this problem and we're going to address it soon so I'm closing this one.

 [1]: https://github.com/square/picasso/blob/601edbba23d7ddaf594770dd1cfeecdf9d903926/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java#L117

**Comment by GabrielLiz** [comment]
Sure thanks i saw a lot of this problem..  i'll solved with that number,  thanks again
