### ISSUE TITLE
OkHttpDownloader: can't customise request anymore?

### ISSUE THREAD

**Issue by farfromrefug** [square/picasso#963]
It seems that we lost the ability to customise the request in OkHttpDownloader since 2.5.0.
In 2.4.0 i am doing something like this
```
picasso = new Picasso.Builder(context).downloader(
            new OkHttpDownloader(context) {
                @Override
                protected HttpURLConnection openConnection(
                        Uri uri) throws IOException {
                    HttpURLConnection connection = super
                            .openConnection(uri);
                    if (mUserAgent != null) {
                        connection.addRequestProperty("User-Agent", mUserAgent);
                    }
                    
                    return connection;
                }
            }).build();
```
Which allows to set specific headers, timeout .... for the image request.
Now it seems that we can't do it anymore?
This could be done by allowing to override a new method ``` buildRequest``` which would return the OkHttp Request

**Comment by JakeWharton** [comment]
Now that we use OkHttpClient natively, there's no need to do that.

```java
OkHttpClient client = new OkHttpClient();
client.setConnectTimeout(15, SECONDS);
client.setReadTimeout(15, SECONDS);
client.setWriteTimeout(15, SECONDS);
client.interceptors().add(new Interceptor() {
  @Override public Response intercept(Chain chain) throws IOException {
    return chain.proceed(chain.request().builder()
        .addHeader("User-Agent", "whatever")
        .build());
  }
});
Picasso picasso = new Picasso.Builder(context)
    .downloader(new OkHttpDownloader(client))
    .build();
```

**Comment by farfromrefug** [comment]
@JakeWharton thanks a lot for the example! I see how to do it now.

Thanks

**Comment by farfromrefug** [comment]
@JakeWharton i just wanted to thank you again. I have implemented as you proposed and it works perfectly!
Thanks again

**Comment by moallemi** [comment]
@JakeWharton does your implementation have conflicts with disc cache?

**Comment by vnd-ranga** [comment]
how can we use okhttp3 client ?

**Comment by NightlyNexus** [comment]
@vnd-ranga The Picasso 3 snapshots use OkHttp 3.

If you need to use Picasso 2, use a custom Downloader like this one: https://github.com/JakeWharton/picasso2-okhttp3-downloader
