### ISSUE TITLE
Uneven scaling

### ISSUE THREAD

**Issue by DariusL** [square/picasso#969]
Picasso.with(getContext())
        .load(url)
        .resize(size, size)
        .centerCrop()
        .into(this);

Where size is 190 produces a bitmap with dimensions 190x191.

**Comment by JakeWharton** [comment]
What version?

**Comment by DariusL** [comment]
2.5.2 I believe. I'll try to reproduce the issue later.

**Comment by dnkoutso** [comment]
Any updates? Closing for now, if you do get concrete info please re-open. Its too little information to work with.
