### ISSUE TITLE
picasso just load first image in gridview

### ISSUE THREAD

**Issue by d7coders** [square/picasso#970]
Hi, I'm trying load image in gridview but just the first image loaded ,  and when I click on the image it's not showing in next activity (for the first image it's showing)

Here is my code:

      public View getView(final int position, View view, ViewGroup parent) {

				ImageView cover;
				if (view == null){
					view = mInflater.inflate(R.layout.photo_item, null);
					cover = new ImageView(getApplicationContext());
				}else{
					 cover = (ImageView) view.findViewById(R.id.cover);
				}
				cover.setScaleType(ImageView.ScaleType.CENTER_CROP);
				cover.setLayoutParams(mImageViewLayoutParams);

				// Check the height matches our calculated column width
				if (cover.getLayoutParams().height != mItemHeight) {
					cover.setLayoutParams(mImageViewLayoutParams);
				}

				Picasso.with(getApplicationContext())
		               .load(imgs[position])
		               .error(R.drawable.error)
		               .into(cover) ;
				
				return view;
			}

**Comment by JakeWharton** [comment]
What version? What do the debug logs say? Did you try attaching a failure listener? Your code is find, so there's nothing else to go on.

**Comment by mattprecious** [comment]
I see two issues with the code you provided that may or may not solve your problem.

First, when you're inflating your view you should pass the container it's going to be attached to:
```java
view = mInflater.inflate(R.layout.photo_item, parent, false);
```

Second, you're creating a new `ImageView` and never attaching it to anything:
```java
cover = new ImageView(getApplicationContext());
```
That line should be deleted and you should move the other one out of your `else` block:

```java
if (view == null){
  view = mInflater.inflate(R.layout.photo_item, parent, false);
}

ImageView cover = (ImageView) view.findViewById(R.id.cover);
```

**Comment by d7coders** [comment]
@mattprecious 
my code was like this before
     if (view == null){
  view = mInflater.inflate(R.layout.photo_item, parent, false);
}

ImageView cover = (ImageView) view.findViewById(R.id.cover);

then I saw a tutorial in some where then I decided to try if it will work or not
but nothing happen, so this not fixing any thing , Thanks :)

**Comment by d7coders** [comment]
@JakeWharton the last version, I just downloaded today ( 2.5.2)

**Comment by JakeWharton** [comment]
What do the debug logs say? Did you try attaching a failure listener? Your code is fine, so there's nothing else to go on.

**Comment by d7coders** [comment]
how can I enable the debugger I tried to add .setDebugging(true); but I got error then I make this changes 

    Picasso pic = Picasso.with(getApplicationContext());
			pic.setDebugging(true);
		        pic.load(imgs[position])
		        .error(R.drawable.error)
		        .into(cover); 


I have warning now and the debugger not showing anything,
and unfortunately I don't know what is the failure listener , sorry

**Comment by d7coders** [comment]
the URL is Just fine , the first image is showing and by clicking on it it's showing in the next activity,
but the other images showing the error icon and even by clicking in it , in the next activity even not showing , the interesting thing is that the next activity image url is different

**Comment by d7coders** [comment]
I just made some links manually it's showing the images , but not working with imgs[position], the imgs[position] Strings is fine I checked it with log.d , I don't know why this happen ,I guess I must solve it my self , thanks guys

**Comment by JakeWharton** [comment]
Great. Good luck, glad it wasn't Picasso's bug.
