### ISSUE TITLE
setIndicatorsEnabled() returns void instead of Picasso

### ISSUE THREAD

**Issue by oliverhausler** [square/picasso#973]
Is it on purpose that setIndicatorsEnabled returns void instead of Picasso?

  @SuppressWarnings("UnusedDeclaration") public void setIndicatorsEnabled(boolean enabled) {
    indicatorsEnabled = enabled;
  }

I know I can use indicatorsEnabled() on the builder, but returning void prevents me from using it inline like this:

Picasso.with(getContext()).setIndicatorsEnabled(true).load(url)

Means: I always need to rewrite my one-liner to quickly test something.

**Comment by JakeWharton** [comment]
It applies and persists to the `Picasso` instance, and has nothing to do with a request. Your code has incorrect implications, your one liner is a two liner:
```
Picasso.with(getContext()).setIndicatorsEnabled(true);
Picasso.with(getContext()).load(url)...
```
