### ISSUE TITLE
Does Picasso download Image as a file ?

### ISSUE THREAD

**Issue by leelei** [square/picasso#975]
I have different size of image, when click thumb image, it will show large image (like 440*7000), 
So i just need download (not encode image), get Image Path, use SubsamplingScaleImageView to show

**Comment by JakeWharton** [comment]
No. The HTTP client is downloads the image and we stream it directly to the decoder. Not only do we not want Picasso to be in the business of managing the storage of photos on disk, but this would make normal use much, much slower.

If you want a one-off download directly to a File (not to an image), we have a request for that already as #506.
