### ISSUE TITLE
Transparent part of the images become black

### ISSUE THREAD

**Issue by MachoProgrammer** [square/picasso#978]
Hello everyone,
 I have a problem using the Picasso library, I need to retrieve from some urls some images, in particularly gif images.  When I'm using it on Android 4.2.2 every transparent part of the gif stays transparent, but when I'm on lollipop it becames black. 
How can I solve the problem? 
I found a solution here http://stackoverflow.com/questions/20396307/transparent-part-of-image-in-imageview-become-black but it introduces another problem, it transforms ALL the black pixels in transparent pixels and some of the images become ruined.

Thanks

**Comment by JakeWharton** [comment]
All of the image decoding happens inside of Android code. Picasso is just responsible for figuring out how to download the data. The problem would be present whether or not you use Picasso and unfortunately we have no control over it, sorry!

**Comment by MachoProgrammer** [comment]
Ok thanks for your reply! Do you have any suggestion?
