### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mylesbennett** [square/picasso#979]
I posted this on stackoverflow before thinking of trying here - sorry about that:
http://stackoverflow.com/questions/29675573/possible-memory-leak-in-square-picasso-for-android

We're currently using 2.4.0 but I tried 2.5.2 with much the same result (quick look at the stack had the same jni stuff, etc.)

**Comment by JakeWharton** [comment]
This is not actionable. Without a test case that clearly shows allocations consistently going up that we can use for analysis, the best we can do is make blind guesses and that's not an effective way to evolve the library.

If you can create a sample app that demonstrates the same we will look. If you have the means to run allocation tracker and maybe do heap dumps and analyze them yourself we will fix any leaks you find.

From the description and log, my guess would be you're just blowing the heap by allocating massive things and consistently beating the garbage collector from reclaiming the memory. I'm sorry I can't offer you anything better, but without actually seeing it happen, there's no information to go on.
