### ISSUE TITLE
Rotation issue on upload :(

### ISSUE THREAD

**Issue by mpjbay** [square/picasso#980]
When we upload photos to our database profile photos are rotated 90 degrees counter clockwise. This is obviously a massive defect. 

Does anyone have a solution to this problem? 

Thanks in advanced!

**Comment by JakeWharton** [comment]
This is not a forum for discussion and help. Please try StackOverflow with the 'picasso' tag instead. If there is a concrete, reproducible bug or specific feature request then an issue is the correct medium.

**Comment by mpjbay** [comment]
A lot of people are having this issue but I have not found a solution. This is a major bug. Is StackOverflow my only option?

**Comment by JakeWharton** [comment]
> A lot of people are having this issue

Do you have proof of this?

> This is a major bug.

You have not described a concrete bug, but only abstract terms related to behavior. If you want something to be fixed, please provide example images, code, or even a full-fledged sample which unambiguously demonstrates the problem so that we can fix it without having to guess what's happening.

**Comment by mpjbay** [comment]
Do a Google search and you will find many posts from people having this issue but no one seems to have a resolution. 

Here is an image after photos were imported. All profile photo were rotated. All landscape photos are fine. 

![rotate](https://cloud.githubusercontent.com/assets/11984554/7193859/0bc3b3ca-e45b-11e4-897f-ac96f6590fb4.png)

**Comment by dnkoutso** [comment]
where do you load this images from? Network? disk? 

Why dont you also include a transformation to ensure the image is properly rotated, or perhaps it reads the EXIF information of the image.

If its a DocumentUri you are using then you can apply this.

https://gist.github.com/dnkoutso/9e34a1bba3d63034e863

Picasso is not here for a solve-everything type of problem. Its a pipeline for loading images which you can also customize if default functionality is not enough.

**Comment by JakeWharton** [comment]
An image of the purported problem is not useful to us. Unless there's
concrete, reproducible samples, images, and code we won't be looking into
this. It's not our job to speculate. In fact, it's not even our job to work
on this library and we simply don't have the time to do exploratory
investigation.

**Comment by mpjbay** [comment]
Thank you for a potential solution dnkoutsu. I will pass this post on to my developers and return with answers to your questions. Thank you :)
