### ISSUE TITLE
picasso image loading fail when trying to load info window google maps image

### ISSUE THREAD

**Issue by nvasilescu** [square/picasso#981]
W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
 W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)

picasso = new Picasso.Builder(getApplicationContext()).listener(new Picasso.Listener() {
            @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
                Log.d("map" , " image load failed");
            }
        }).build();

 private class CustomInfoWindowAdapter implements GoogleMap.InfoWindowAdapter {

        private View view;
        LayoutInflater inflater = null;

        public CustomInfoWindowAdapter(LayoutInflater inflater) {
            //Inflating the InfoWindow view.
            this.inflater = inflater;
            view = inflater.inflate(R.layout.map_info_window, null);
        }

        @Override
        public View getInfoContents(final Marker marker) {
            //Re-show InfoWindow if it already shown
            if ( currentlyClickedMarker != null && currentlyClickedMarker.isInfoWindowShown() ) {
                currentlyClickedMarker.hideInfoWindow();
                currentlyClickedMarker.showInfoWindow();
            }
            return null;
        }

        @Override
        public View getInfoWindow(final Marker marker) {
            currentlyClickedMarker = marker;
            TextView titleOfLocation = (TextView)view.findViewById(R.id.map_info_window_location_title);
            TextView distanceToLocation = (TextView)view.findViewById(R.id.map_info_window_location_distance);
            final ImageView locationImage = (ImageView)view.findViewById(R.id.map_info_window_image);
            //Get the Image from web using Picasso and update the info contents

            picasso.load(currentItem.getImage()).into(locationImage);
            titleOfLocation.setText(currentItem.getLocationTitle());

            if (currentLocation != null){
                distanceToLocation.setVisibility(View.VISIBLE);

                double distance = MathUtils.distanceBetweenTwoEarthPoints(currentLocation.latitude,currentLocation.longitude, currentItem.getPosition().latitude, currentItem.getPosition().longitude);
                String distToShow = MathUtils.convertDistanceToString(Math.round(distance) * 0.001);
                distanceToLocation.setText(distToShow.concat(" ").concat(getResources().getString(R.string.km_away)));

            }else{
                distanceToLocation.setVisibility(View.GONE);
            }

            return view;
        }
    }

googleMap.setInfoWindowAdapter(new CustomInfoWindowAdapter(getLayoutInflater()));

**Comment by JakeWharton** [comment]
Paste the full exception. What version?

**Comment by nvasilescu** [comment]
casso﹕ Main        created      [R216] Request{https://www.seniorprogramming.ro/clienti/lovelty/uploads/location/2/logo/2_20150410_144919.jpg}
04-17 17:29:23.763    2856-3331/ro.seniorprogramming.lovelty D/Picasso﹕ Hunter      executing    [R216]+5ms
04-17 17:29:23.893    2856-3288/ro.seniorprogramming.lovelty D/dalvikvm﹕ GC_FOR_ALLOC freed 1997K, 16% free 26484K/31328K, paused 126ms, total 126ms
04-17 17:29:23.893    2856-3288/ro.seniorprogramming.lovelty D/Picasso﹕ Dispatcher  enqueued     [R216]+4ms
04-17 17:29:24.348    2856-3283/ro.seniorprogramming.lovelty D/dalvikvm﹕ GC_FOR_ALLOC freed 1263K, 14% free 27171K/31328K, paused 73ms, total 73ms
04-17 17:29:24.448    2856-3288/ro.seniorprogramming.lovelty D/Picasso﹕ Dispatcher  batched      [R216]+689ms for error
04-17 17:29:24.648    2856-2856/ro.seniorprogramming.lovelty D/Picasso﹕ Main        errored      [R216]+891ms
04-17 17:29:24.648    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ com.squareup.picasso.Downloader$ResponseException: 404 Not Found
04-17 17:29:24.653    2856-3288/ro.seniorprogramming.lovelty D/Picasso﹕ Dispatcher  delivered    [R216]+893ms
04-17 17:29:24.653    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:121)
04-17 17:29:24.653    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
04-17 17:29:24.653    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
04-17 17:29:24.653    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
04-17 17:29:24.653    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
04-17 17:29:24.653    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
04-17 17:29:24.658    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
04-17 17:29:24.658    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
04-17 17:29:24.658    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
04-17 17:29:24.658    2856-2856/ro.seniorprogramming.lovelty W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
04-17 17:29:24.658    2856-2856/ro.seniorprogramming.lovelty D/map﹕ image load failed


Version : compile 'com.squareup.picasso:picasso:2.5.2'

**Comment by JakeWharton** [comment]
> 404 Not Found

The device gets a 404 when requesting that image. This is the problem with the server, not picasso.

**Comment by nvasilescu** [comment]
but the image works on click and i have like 300 images loaded from the same location that have no problem.

**Comment by JakeWharton** [comment]
It works for me too, but the error message clearly indicates that Picasso receives a 404 response from the server.

**Comment by nvasilescu** [comment]
Is there any way I can set up the request from picasso to server differently ? thx.

**Comment by dnkoutso** [comment]
![device-2015-05-09-114235](https://cloud.githubusercontent.com/assets/310370/7551529/830fbf40-f640-11e4-868b-5a7d87470ef6.png)


works fine in sample app. Something else is wrong. Check certificates and everything else around the connection handling.

**Comment by NaoufelBoumahdi** [comment]
Hi , got the same problem but only if i run my application in kitkat environment otherwise it works fine 
i get the famous 404 error 

08-12 07:46:54.310 1902-1902/com.sante W/System.err: com.squareup.picasso.Downloader$ResponseException: 404 Not Found
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:96)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at java.lang.Thread.run(Thread.java:841)
08-12 07:46:54.310 1902-1902/com.sante W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
