### ISSUE TITLE
picasso 2.5.2 unable display image from some file path in android 5.0

### ISSUE THREAD

**Issue by sd6352051** [square/picasso#984]
Unable display image from file path in android 5.0 when i use Lens Blur take photo and then to load this picture use Picasso.Other version works well.Only version 5.0
i use Camera or Panorama will  worked well

This‘s my code
``` java
File imageFile = new File(data.path);
Picasso.with(mContext)
      .load(imageFile)
      .placeholder(R.drawable.default_error)
      .error(R.drawable.default_error)
      .resize(mItemSize, mItemSize)
      .centerCrop()
      .into(image);
```

![Image][1]

[1]: http://imglf1.ph.126.net/iyZhhyx6oy2FAol1RGjv4A==/6630545497675926517.png

**Comment by JakeWharton** [comment]
What's the error? What version? You haven't provided any information for us to actually diagnose anything.

**Comment by sd6352051** [comment]
I use picasso 2.5.2 in android 5.0.1
everything is good .no any log error message .just unable display image when i use Lens Blur take photo and then to load this picture.other image file path is very normal .just Lens Blur not work.i use UIL worked well .but picasso can't .what information do i need to provide?please excuse me for my broken English.im a huge fan of the picasso.thanks

**Comment by dnkoutso** [comment]
Use a listener and paste stacktrace if there is an error. 

```java
new Builder(context).listener(new Listener() {
            @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
              exception.printStackTrace();;
            }
          }).build();
```

Are you accessing the files via document uri? See this gist https://gist.github.com/dnkoutso/9e34a1bba3d63034e863

**Comment by dnkoutso** [comment]
Re open issue when you have a stacktrace please.

**Comment by Miroslav10** [comment]
same problem. my logs 
07-06 16:49:50.477  19158-19158/com.inkly.android E/picasso_test﹕ java.io.IOException: Cannot reset
07-06 16:49:50.487  19158-19158/com.inkly.android W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
07-06 16:49:50.487  19158-19158/com.inkly.android W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
07-06 16:49:50.487  19158-19158/com.inkly.android W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
07-06 16:49:50.487  19158-19158/com.inkly.android W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
07-06 16:49:50.487  19158-19158/com.inkly.android W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
