### ISSUE TITLE
Content URI, album art & thumbnail

### ISSUE THREAD

**Issue by vbarthel-fr** [square/picasso#985]
*(Possible duplicate [issue #757](https://github.com/square/picasso/issues/757))*

Hi,

at some points in my code base, I want to load a local album cover art with its content URI, but Picasso doesn't  seem to load the proper image.

For want I understand: ```.fit()``` is used and the ```imageView``` is small so it falls into the ```MediaStoreRequestHandler.PicassoKind.MINI``` category leading to call ```Images.Thumbnails.getThumbnail(...)``` in [MediaStoreRequestHandler.java#L84
](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/MediaStoreRequestHandler.java#L84) and for a reason I don't understand it does not return a null bitmap but a bitmap of an other image.

Here is the code that reproduces the 'bug' on a 4.3 device:

```java
public class MainActivity extends ActionBarActivity {

    private static final Uri ALBUM_ART_URI = Uri.parse("content://media/external/audio/albumart/65");
    private static final Uri THUMBNAIL_URI = Uri.parse("content://media/external/images/thumbnails/65");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final ImageView imageView1 = (ImageView) findViewById(R.id.activity_main_image_view_1);
        final ImageView imageView2 = (ImageView) findViewById(R.id.activity_main_image_view_2);
        final ImageView imageView3 = (ImageView) findViewById(R.id.activity_main_image_view_3);

        findViewById(R.id.activity_main_btn_load).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                imageView1.setImageURI(ALBUM_ART_URI);
                imageView2.setImageURI(THUMBNAIL_URI);
                Picasso.with(v.getContext())
                        .load(ALBUM_ART_URI)
                        .fit()
                        .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
                        .into(imageView3);
            }
        });
    }

}
```

and a screenshot of the result:

![screenshot_2015-04-14-15-54-33](https://cloud.githubusercontent.com/assets/3321467/7141402/ac69cf52-e2d1-11e4-8e66-454f4353d823.png)

Hope it can help !

**Comment by dnkoutso** [comment]
The information provided is good enough but I am unable to repro the issue locally. If the bitmap is loaded from the content provider.

I recommend you debug that case and see. If you remove the check does it load the right image? I'd like to know the real problem here, but as a workaround you could write your own request handler to handle this.
