### ISSUE TITLE
Picasso 2.5.2 com.squareup.picasso.MarkableInputStream.reset(SourceFile:99)

### ISSUE THREAD

**Issue by AlexYXB** [square/picasso#986]
I got this issue in v2.4, and temp fixed with set BitmapHunter.MARKER to 1024x1024.

#907 issue said this was fixed in v.2.5.1, so  i upgrade to v2.5.2, but this still happen.

I find this line : long mark = markStream.savePosition(65535); // TODO fix this crap. 
in BitmapHunter.java

Need i change the 65535 to 1024x1024 again?

**Comment by AlexYXB** [comment]
ok, it worked by changed 65535 to 1024x1024

**Comment by AlexYXB** [comment]
why just close this issue? is this not an issue? @JakeWharton

**Comment by JakeWharton** [comment]
There are no less than 8 other open issues for this.
