### ISSUE TITLE
Reading from Disk (file://)

### ISSUE THREAD

**Issue by pollux-** [square/picasso#988]
If we load the images from the disk(file://), its looks like file operation and decoding is happening in main thread !!!
**Picasso.with(getActivity()).load("file://......").into(mThumb);**
Please let me know,  why it is happening if the decoding and file operation is on a worker thread ??

Getting the below log 

**04-22 14:53:30.609  17500-17500I/Choreographer﹕ Skipped 32 frames!  The application may be doing too much work on its main thread.**

**Comment by JakeWharton** [comment]
File loading definitely happens on a background thread. You can turn on StrictMode with a death penalty to prove this. The main thread blocking is coming from somewhere else. While a complicated tool, you can use traceview to figure out what code is being executed when the main thread is being blocked.

**Comment by pollux-** [comment]
Thanks a lot... I will try that
