### ISSUE TITLE
Picasso 2.5.2 not able to overlay image

### ISSUE THREAD

**Issue by moshlp** [square/picasso#991]
hi, i'm trying to display 2 overlain images on a gridView, but i'm not able to do this. On the layout xml I only have the gridview. I've tried many ways, browsing stackoverflow, with no results. shouldn't there be an easy way to perform this task? using .transform or other property. thanks

**Comment by JakeWharton** [comment]
Are both images remote? (As in, URLs)

**Comment by moshlp** [comment]
no, only the main one. the one that should appear overlaid is in drawable. if you need some code let me know...thanx for answering. this is what I aim to accomplish:
![overlay](https://cloud.githubusercontent.com/assets/12039298/7359765/d2b250e8-ed18-11e4-8638-02e8ac79fa31.jpg)

**Comment by dnkoutso** [comment]
Can you show code of the transformation you apply? This should be easy to add.

**Comment by moshlp** [comment]
of course, no transformation applied though:
Picasso picasso = Picasso.with(mContext);
FotoEntity foto = (FotoEntity) fotos.get(position);
picasso.load(foto.getURL())
.placeholder(R.raw.place_holder)
.error(R.raw.big_problem)
.resize(150, 150)
.centerCrop()
.into(imageView);

the idea is that depending on a boolean coming from "foto", I should render the overlaid image on top of main image.

**Comment by dnkoutso** [comment]
I dont see anywhere in the code where you apply a transformation to draw both bitmaps and the checkmark on top of the original one.

Either you need to add two image views one with the checkmark and the one that picasso loads and work with that or apply a transformation that draws both bitmaps and returns the final result.

**Comment by moshlp** [comment]
I apologize if I didn't myself clear, I couldn't find any solution for me online, that's why I'm only showing the code I have so far, without any way around my problem. 
I understand both of your approaches, but can you explain any of those? either loading two bitmaps or applying a transformation. thanks

**Comment by dnkoutso** [comment]
I am closing this and will update perhaps with a sample for you. This is not a Picasso problem.

**Comment by moshlp** [comment]
ok, I'll deeply appreciate a sample for any solution you proposed

**Comment by moshlp** [comment]
I'm sorry if I'm a burden, but can you please post the samples you mention? thanks

Date: Mon, 27 Apr 2015 17:06:20 -0700
