### ISSUE TITLE
How to get tag in Transformation

### ISSUE THREAD

**Issue by lichangadd** [square/picasso#996]
Hi,Is any way to get tag(set in request) in transformation?
In my customTransformation I need some value to do different thing,but I don't know how to do this.
I try to use target's callback,but I cannot recycle the bitmap parameter  
public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from)

**Comment by JakeWharton** [comment]
No. You can create a `Transformation` instance for every request that takes the required arguments into the constructor. A transformation might be called once for multiple requests which means there could be multiple tags.

**Comment by lichangadd** [comment]
OK,copy that!
